import type { TechnologyDefinition } from '../types';

export const animationTechnologyDefinitions = [
	{
		id: "animate-css",
		name: "Animate.css",
		website: "https://animate.style",
		description: "Animate.css is a ready-to-use library collection of CSS3 animation effects.",
		icon: "Animate.css.svg",
		categories: [
			"animation",
			"component-library",
		],
		rules: [
			{
				id: "animate-css:dom:0",
				kind: "dom",
				selector: ".animate__animated",
				description: "DOM selector matches a known technology marker.",
			},
			{
				id: "animate-css:dom:1",
				kind: "dom",
				selector: "link[href*='animate']",
				description: "DOM selector matches a known technology marker.",
			},
		],
		metadata: {
			oss: true,
		},
	},
	{
		id: "anime-js",
		name: "anime.js",
		website: "https://animejs.com/",
		description: "Anime.js (/ˈæn.ə.meɪ/) is a lightweight JavaScript animation library with a simple, yet powerful API.It works with CSS properties, SVG, DOM attributes and JavaScript Objects.",
		icon: "anime.js.svg",
		categories: [
			"animation",
			"graphics-visualization",
		],
		rules: [
			{
				id: "anime-js:jsGlobal:0",
				kind: "jsGlobal",
				property: "anime.version",
				valuePattern: new RegExp("^([\\d\\.]+)$"),
				version: {
					source: "match",
					group: 1,
				},
				description: "Page-owned global matches a known technology marker.",
			},
			{
				id: "anime-js:jsGlobal:1",
				kind: "jsGlobal",
				property: "AnimeJS",
				description: "Page-owned global matches a known technology marker.",
			},
			{
				id: "anime-js:header:2",
				kind: "header",
				key: "Access-Control-Allow-Origin",
				valuePattern: new RegExp("animejs\\.com", "i"),
				description: "Response header matches a known technology marker.",
			},
			{
				id: "anime-js:resourceUrl:modern:0",
				kind: "resourceUrl",
				pattern: new RegExp("animejs[.\\-@/]"),
				confidence: 75,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "anime-js:resourceUrl:modern:1",
				kind: "resourceUrl",
				pattern: new RegExp("anime\\.min\\.js"),
				confidence: 75,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "anime-js:resourceUrl:modern:2",
				kind: "resourceUrl",
				pattern: new RegExp("anime\\.es\\.js"),
				confidence: 75,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "anime-js:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("\"animejs\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
		metadata: {
			oss: true,
		},
	},
	{
		id: "aos",
		name: "AOS",
		website: "https://michalsnik.github.io/aos/",
		description: "JavaScript library to animate elements on your page as you scroll.",
		icon: "AOS.svg",
		categories: [
			"animation",
			"widgets-misc",
		],
		rules: [
			{
				id: "aos:scriptSrc:0",
				kind: "scriptSrc",
				pattern: new RegExp("unpkg\\.com\\/aos@([\\d\\.]+)\\/dist\\/aos\\.js"),
				version: {
					source: "match",
					group: 1,
				},
				description: "Script source URL matches a known technology marker.",
			},
			{
				id: "aos:scriptSrc:1",
				kind: "scriptSrc",
				pattern: new RegExp("\\/typo3conf\\/ext\\/udem_vendor\\/Resources\\/Public\\/aos-([\\d\\.]+)"),
				version: {
					source: "match",
					group: 1,
				},
				description: "Script source URL matches a known technology marker.",
			},
			{
				id: "aos:dom:2",
				kind: "dom",
				selector: " body[data-aos-easing]",
				description: "DOM selector matches a known technology marker.",
			},
			{
				id: "aos:jsGlobal:3",
				kind: "jsGlobal",
				property: "AOS.init",
				description: "Page-owned global matches a known technology marker.",
			},
			{
				id: "aos:jsGlobal:4",
				kind: "jsGlobal",
				property: "AOS.refresh",
				description: "Page-owned global matches a known technology marker.",
			},
			{
				id: "aos:jsGlobal:5",
				kind: "jsGlobal",
				property: "AOS.refreshHard",
				description: "Page-owned global matches a known technology marker.",
			},
			{
				id: "aos:header:6",
				kind: "header",
				key: "X-Powered-By",
				valuePattern: new RegExp("^AdministerAOS", "i"),
				description: "Response header matches a known technology marker.",
			},
			{
				id: "aos:scriptSrc:7",
				kind: "scriptSrc",
				pattern: new RegExp("\\/typo3conf\\/ext\\/udem_vendor\\/resources\\/public\\/aos-([\\d\\.]+)"),
				version: {
					source: "match",
					group: 1,
				},
				description: "Script source URL matches a known technology marker.",
			},
		],
		metadata: {
			oss: true,
		},
	},
	{
		id: "framer-motion",
		name: "Framer Motion",
		website: "https://motion.dev",
		description: "Framer Motion is a modern animation library for JavaScript, React, and Vue.",
		icon: "FramerMotion.svg",
		categories: [
			"animation",
			"widgets-misc",
		],
		rules: [
			{
				id: "framer-motion:jsGlobal:0",
				kind: "jsGlobal",
				property: "MotionIsMounted",
				description: "Page-owned global matches a known technology marker.",
			},
			{
				id: "framer-motion:resourceUrl:modern:0",
				kind: "resourceUrl",
				pattern: new RegExp("framer-motion[.\\-@/]"),
				confidence: 75,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "framer-motion:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("\"framer-motion\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "framer-motion:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("\"data-framer-portal-id\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "framer-motion:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("\"framerAppearId\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "framer-motion:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("\"motionComponentSymbol\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "framer-motion:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("\"projectionUpdate\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "framer-motion:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("\"projectionFrame\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
		metadata: {
			oss: true,
			pricing: [
				"freemium",
			],
		},
	},
	{
		id: "gsap",
		name: "GSAP",
		website: "https://greensock.com/gsap",
		description: "GSAP is an animation library that allows you to create animations with JavaScript.",
		icon: "TweenMax.png",
		categories: [
			"animation",
			"ui-library",
		],
		rules: [
			{
				id: "gsap:scriptSrc:0",
				kind: "scriptSrc",
				pattern: new RegExp("TweenMax(?:\\.min)?\\.js"),
				description: "Script source URL matches a known technology marker.",
			},
			{
				id: "gsap:jsGlobal:1",
				kind: "jsGlobal",
				property: "TweenLite.version",
				valuePattern: new RegExp("([\\d.]+)"),
				version: {
					source: "match",
					group: 1,
				},
				description: "Page-owned global matches a known technology marker.",
			},
			{
				id: "gsap:jsGlobal:2",
				kind: "jsGlobal",
				property: "TweenMax.version",
				valuePattern: new RegExp("([\\d.]+)"),
				version: {
					source: "match",
					group: 1,
				},
				description: "Page-owned global matches a known technology marker.",
			},
			{
				id: "gsap:jsGlobal:3",
				kind: "jsGlobal",
				property: "gsap.version",
				valuePattern: new RegExp("([\\d.]+)"),
				version: {
					source: "match",
					group: 1,
				},
				description: "Page-owned global matches a known technology marker.",
			},
			{
				id: "gsap:jsGlobal:4",
				kind: "jsGlobal",
				property: "gsapVersions",
				description: "Page-owned global matches a known technology marker.",
			},
			{
				id: "gsap:scriptSrc:5",
				kind: "scriptSrc",
				pattern: new RegExp("tweenmax(?:\\.min)?\\.js"),
				description: "Script source URL matches a known technology marker.",
			},
			{
				id: "gsap:resourceUrl:modern:0",
				kind: "resourceUrl",
				pattern: new RegExp("gsap[.\\-@/]"),
				confidence: 75,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "gsap:resourceUrl:modern:1",
				kind: "resourceUrl",
				pattern: new RegExp("greensock"),
				confidence: 75,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "gsap:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("GreenSock"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "gsap:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("GreenSockGlobals"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "gsap:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("registerPlugin"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "gsap:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("\"scrollTrigger\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "gsap:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("\"autoAlpha\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
		metadata: {
			pricing: [
				"freemium",
				"low",
				"recurring",
			],
		},
	},
	{
		id: "autoanimate",
		name: "AutoAnimate",
		website: "https://auto-animate.formkit.com/",
		description: "Add motion to your apps with a single line of code",
		categories: [
			"animation",
		],
		rules: [
			{
				id: "autoanimate:resourceUrl:modern:0",
				kind: "resourceUrl",
				pattern: new RegExp("@formkit\\/auto-animate[.\\-@/]"),
				confidence: 75,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "autoanimate:resourceUrl:modern:1",
				kind: "resourceUrl",
				pattern: new RegExp("auto-animate"),
				confidence: 75,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "autoanimate:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("\"@formkit\\/auto-animate\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "autoanimate:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("\"autoAnimate\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
	{
		id: "lottie",
		name: "Lottie",
		website: "https://airbnb.io/lottie/",
		description: "A library for rendering After Effects animations natively",
		categories: [
			"animation",
		],
		rules: [
			{
				id: "lottie:resourceUrl:modern:0",
				kind: "resourceUrl",
				pattern: new RegExp("lottie-web[.\\-@/]"),
				confidence: 75,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "lottie:resourceUrl:modern:1",
				kind: "resourceUrl",
				pattern: new RegExp("lottie-player[.\\-@/]"),
				confidence: 75,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "lottie:resourceUrl:modern:2",
				kind: "resourceUrl",
				pattern: new RegExp("@lottiefiles\\/"),
				confidence: 75,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "lottie:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("\"bodymovin\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "lottie:html:modern:4",
				kind: "html",
				pattern: new RegExp("<lottie-player"),
				confidence: 65,
				description: "Document HTML matches a modern tooling marker.",
			},
			{
				id: "lottie:html:modern:5",
				kind: "html",
				pattern: new RegExp("<dotlottie-player"),
				confidence: 65,
				description: "Document HTML matches a modern tooling marker.",
			},
		],
	},
	{
		id: "motion-one",
		name: "Motion One",
		website: "https://motion.dev/",
		description: "A new animation library built on the Web Animations API",
		categories: [
			"animation",
		],
		rules: [
			{
				id: "motion-one:resourceUrl:modern:0",
				kind: "resourceUrl",
				pattern: new RegExp("@motionone\\/"),
				confidence: 75,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "motion-one:resourceUrl:modern:1",
				kind: "resourceUrl",
				pattern: new RegExp("motion-one"),
				confidence: 75,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "motion-one:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("\"@motionone\\/dom\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "motion-one:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("\"@motionone\\/animation\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "motion-one:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("\"@motionone\\/utils\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
	{
		id: "react-spring",
		name: "React Spring",
		website: "https://www.react-spring.dev/",
		description: "A spring-physics based animation library for React",
		categories: [
			"animation",
		],
		rules: [
			{
				id: "react-spring:resourceUrl:modern:0",
				kind: "resourceUrl",
				pattern: new RegExp("react-spring[.\\-@/]"),
				confidence: 75,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "react-spring:resourceUrl:modern:1",
				kind: "resourceUrl",
				pattern: new RegExp("@react-spring\\/"),
				confidence: 75,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "react-spring:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("\"react-spring\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "react-spring:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("\"@react-spring\\/web\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "react-spring:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("\"@react-spring\\/core\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "react-spring:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("\"SpringValue\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "react-spring:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("\"SpringRef\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
] as const satisfies readonly TechnologyDefinition[];
