import type { TechnologyDefinition } from '../types';

export const datesTechnologyDefinitions = [
	{
		id: "day-js",
		name: "Day.js",
		website: "https://github.com/iamkun/dayjs",
		description: "Day.js is a lightweight JavaScript library for parsing, validating, and formatting dates.",
		icon: "Day.js.svg",
		categories: [
			"dates",
			"widgets-misc",
		],
		rules: [
			{
				id: "day-js:jsGlobal:0",
				kind: "jsGlobal",
				property: "dayjs",
				description: "Page-owned global matches a known technology marker.",
			},
			{
				id: "day-js:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("\\$isDayjsObject"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "day-js:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("\\[\"\\\\$isDayjsObject\"\\]"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "day-js:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("\\.\\$L.*\\.\\$d.*\\.\\$y.*\\.\\$M"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "day-js:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("\\.\\$y.*\\.\\$M.*\\.\\$D.*\\.\\$W.*\\.\\$H"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "day-js:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("dayjs\\.extend\\([^)]+\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "day-js:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("extend\\((?:customParseFormat|updateLocale|relativeTime|isoWeek)\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "day-js:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("\"Invalid Date\"===\\w+\\.\\$d\\.toString\\(\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "day-js:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("\"Invalid Date\"===\\w+\\.toString\\(\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "day-js:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("\"plugin conflict\"|\"plugin function is required\"|\"plugin name is required\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
	{
		id: "moment-timezone",
		name: "Moment Timezone",
		website: "https://momentjs.com/timezone/",
		description: "Moment Timezone is a library built upon Moment.js, extending its capabilities to handle time zones in JavaScript. It allows developers to parse, manipulate, and display dates and times in various time zones, providing comprehensive support for time zone conversions and adjustments in web applications.",
		icon: "Moment.js.svg",
		categories: [
			"dates",
			"widgets-misc",
		],
		rules: [
			{
				id: "moment-timezone:scriptSrc:0",
				kind: "scriptSrc",
				pattern: new RegExp("moment-timezone(?:-data)?(?:\\.min)?\\.js"),
				description: "Script source URL matches a known technology marker.",
			},
		],
		implies: [
			"moment-js",
		],
	},
	{
		id: "moment-js",
		name: "Moment.js",
		website: "https://momentjs.com",
		description: "Moment.js is a free and open-source JavaScript library that removes the need to use the native JavaScript Date object directly.",
		icon: "Moment.js.svg",
		categories: [
			"dates",
			"widgets-misc",
		],
		rules: [
			{
				id: "moment-js:scriptSrc:0",
				kind: "scriptSrc",
				pattern: new RegExp("moment(?:\\.min)?\\.js"),
				description: "Script source URL matches a known technology marker.",
			},
			{
				id: "moment-js:jsGlobal:1",
				kind: "jsGlobal",
				property: "moment",
				description: "Page-owned global matches a known technology marker.",
			},
			{
				id: "moment-js:jsGlobal:2",
				kind: "jsGlobal",
				property: "moment.version",
				valuePattern: new RegExp("^(.+)$"),
				version: {
					source: "match",
					group: 1,
				},
				description: "Page-owned global matches a known technology marker.",
			},
			{
				id: "moment-js:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("\\._isAMomentObject\\s*=\\s*source\\._isAMomentObject"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "moment-js:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("\\._isAMomentObject\\s*=\\s*true"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "moment-js:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("moment\\.updateOffset\\s*=\\s*function"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "moment-js:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("\\._pf\\.(?:empty|unusedTokens|unusedInput|overflow|charsLeftOver|nullInput|invalidEra|invalidMonth|invalidFormat|userInvalidated|iso|parsedDateParts|meridiem)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "moment-js:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("use moment\\.updateLocale\\(localeName, config\\) to change an existing locale\\. moment\\.defineLocale\\(localeName, config\\) should only be used for creating a new locale"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "moment-js:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("moment\\(\\)\\.lang\\(\\) is deprecated\\. Instead, use moment\\(\\)\\.localeData\\(\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "moment-js:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("moment construction falls back to js Date\\(\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "moment-js:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("\"Moment Timezone setDefault\\(\\) requires Moment\\.js >= [0-9.]+"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "moment-js:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("'Moment Timezone requires Moment\\.js\\. See https:\\/\\/momentjs\\.com\\/timezone\\/docs\\/#\\/use-it\\/browser\\/'"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "moment-js:scriptContent:modern:9",
				kind: "scriptContent",
				pattern: new RegExp("http:\\/\\/momentjs\\.com\\/guides\\/#\\/warnings\\/js-date\\/"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "moment-js:scriptContent:modern:10",
				kind: "scriptContent",
				pattern: new RegExp("http:\\/\\/momentjs\\.com\\/guides\\/#\\/warnings\\/define-locale\\/"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "moment-js:scriptContent:modern:11",
				kind: "scriptContent",
				pattern: new RegExp("http:\\/\\/momentjs\\.com\\/guides\\/#\\/warnings\\/min-max\\/"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "moment-js:scriptContent:modern:12",
				kind: "scriptContent",
				pattern: new RegExp("DATETIME_LOCAL:\"YYYY-MM-DDTHH:mm\",DATETIME_LOCAL_SECONDS:\"YYYY-MM-DDTHH:mm:ss\",DATETIME_LOCAL_MS:\"YYYY-MM-DDTHH:mm:ss\\.SSS\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "moment-js:scriptContent:modern:13",
				kind: "scriptContent",
				pattern: new RegExp("\\._invalidDate\\s*=\\s*['\"]Invalid date['\"]"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "moment-js:scriptContent:modern:14",
				kind: "scriptContent",
				pattern: new RegExp("\\._week\\s*=\\s*{\\s*dow:\\s*\\d+,\\s*doy:\\s*\\d+\\s*}"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "moment-js:scriptContent:modern:15",
				kind: "scriptContent",
				pattern: new RegExp("\\._locale\\._(?:abbr|config|ordinal|calendar|monthsParseExact)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "moment-js:scriptContent:modern:16",
				kind: "scriptContent",
				pattern: new RegExp("\\._isUTC\\s*=\\s*(?:true|false)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "moment-js:scriptContent:modern:17",
				kind: "scriptContent",
				pattern: new RegExp("\\._offset\\s*=\\s*(?:0|-?\\d+)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
		metadata: {
			cpe: "cpe:2.3:a:momentjs:moment:*:*:*:*:*:*:*:*",
		},
	},
	{
		id: "date-fns",
		name: "date-fns",
		website: "https://date-fns.org/",
		description: "Modern JavaScript date utility library",
		categories: [
			"dates",
		],
		rules: [
			{
				id: "date-fns:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("\"weekStartsOn must be between 0 and 6 inclusively\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "date-fns:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("firstWeekContainsDate must be between 1 and 7 inclusively"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "date-fns:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("\"startDate or endDate for interval cannot be Invalid Date\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "date-fns:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("\"The step must be a number between 0 and 7 inclusively\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "date-fns:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("\"useAdditionalDayPeriodTokens must be used with isProtectedDayPeriodToken\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "date-fns:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("firstWeekContainsDate"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "date-fns:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("[\"']abbreviated[\"'].*[\"']narrow[\"'].*[\"']short[\"'].*[\"']wide[\"']"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "date-fns:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("eachWeekendOfInterval\\([^)]+\\)|eachWeekendOfMonth\\([^)]+\\)|eachWeekendOfYear\\([^)]+\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "date-fns:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("differenceInBusinessDays\\([^)]+\\)|addBusinessDays\\([^)]+\\)|subBusinessDays\\([^)]+\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "date-fns:scriptContent:modern:9",
				kind: "scriptContent",
				pattern: new RegExp("differenceInCalendarISOWeeks\\([^)]+\\)|startOfISOWeek\\([^)]+\\)|lastDayOfISOWeek\\([^)]+\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "date-fns:scriptContent:modern:10",
				kind: "scriptContent",
				pattern: new RegExp("getQuarter\\([^)]+\\)|setQuarter\\([^)]+\\)|startOfQuarter\\([^)]+\\)|lastDayOfQuarter\\([^)]+\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "date-fns:scriptContent:modern:11",
				kind: "scriptContent",
				pattern: new RegExp("getISOWeekYear\\([^)]+\\)|startOfISOWeekYear\\([^)]+\\)|endOfISOWeekYear\\([^)]+\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "date-fns:scriptContent:modern:12",
				kind: "scriptContent",
				pattern: new RegExp("format\\([^,]+,\\s*[\"']PPPPp[\"']\\)"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "date-fns:scriptContent:modern:13",
				kind: "scriptContent",
				pattern: new RegExp("format\\([^,]+,\\s*[\"']RRRR[\"']\\)"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "date-fns:scriptContent:modern:14",
				kind: "scriptContent",
				pattern: new RegExp("formatISO9075\\([^)]+\\)"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "date-fns:scriptContent:modern:15",
				kind: "scriptContent",
				pattern: new RegExp("format\\([^,]+,\\s*[\"'][^\"']+[\"'],\\s*\\{locale:\\s*[^}]+\\}\\)"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "date-fns:scriptContent:modern:16",
				kind: "scriptContent",
				pattern: new RegExp("\"Wrong first weekday of week\""),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "date-fns:scriptContent:modern:17",
				kind: "scriptContent",
				pattern: new RegExp("\"ordinalNumber function is required\""),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "date-fns:scriptContent:modern:18",
				kind: "scriptContent",
				pattern: new RegExp("\"localizer function is required\""),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "date-fns:scriptContent:modern:19",
				kind: "scriptContent",
				pattern: new RegExp("eachDayOfInterval\\([^)]+\\)|eachHourOfInterval\\([^)]+\\)|eachMinuteOfInterval\\([^)]+\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "date-fns:scriptContent:modern:20",
				kind: "scriptContent",
				pattern: new RegExp("isWithinInterval\\([^,]+,\\s*\\{start:[^,]+,\\s*end:[^}]+\\}\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "date-fns:scriptContent:modern:21",
				kind: "scriptContent",
				pattern: new RegExp("areIntervalsOverlapping\\([^,]+,\\s*[^,]+(?:,\\s*\\{inclusive:\\s*(?:true|false)\\}\\s*)?\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "date-fns:scriptContent:modern:22",
				kind: "scriptContent",
				pattern: new RegExp("import\\s*\\{[^}]*\\}\\s*from\\s*[\"']date-fns\\/fp[\"']"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "date-fns:scriptContent:modern:23",
				kind: "scriptContent",
				pattern: new RegExp("pipe\\(\\s*(?:addDays|addMonths|addYears)\\s*\\(\\d+\\)\\s*,\\s*(?:format|formatDistance|formatRelative)"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
	{
		id: "js-joda",
		name: "JS-Joda",
		website: "https://js-joda.github.io/js-joda/",
		description: "Immutable date and time library for JavaScript",
		categories: [
			"dates",
		],
		rules: [
			{
				id: "js-joda:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("\"DateTimeException: TemporalField must not be null\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "js-joda:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("\"DateTimeException: ChronoField must not be null\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "js-joda:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("\"DateTimeException: ChronoUnit must not be null\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "js-joda:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("\"DateTimeException: Invalid value for YearOfEra\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "js-joda:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("\"DateTimeException: Invalid value for MonthOfYear\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "js-joda:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("\"UnsupportedTemporalTypeException: Unsupported field: FieldUnsupported\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "js-joda:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("@copyright.*js-joda.*contributors"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "js-joda:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("DateTimeFormatter.*ISO_LOCAL_DATE.*ISO_LOCAL_TIME"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "js-joda:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("MIN_SAFE_INTEGER.*MAX_SAFE_INTEGER.*safeToInt"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "js-joda:scriptContent:modern:9",
				kind: "scriptContent",
				pattern: new RegExp("Pattern using \\(localized\\) text not implemented, use @js-joda\\/locale plugin!"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "js-joda:scriptContent:modern:10",
				kind: "scriptContent",
				pattern: new RegExp("time must be an instance of LocalTime or OffsetTime"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "js-joda:scriptContent:modern:11",
				kind: "scriptContent",
				pattern: new RegExp("Pattern using (localized) text not implemented yet"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "js-joda:scriptContent:modern:12",
				kind: "scriptContent",
				pattern: new RegExp("t === v\\.MONTHS \\|\\| t === v\\.YEARS \\|\\| t === v\\.DECADES \\|\\| t === v\\.CENTURIES \\|\\| t === v\\.MILLENNIA \\|\\| t === v\\.ERAS "),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "js-joda:scriptContent:modern:13",
				kind: "scriptContent",
				pattern: new RegExp("ChronoField\\.ALIGNED_WEEK_OF_MONTH|ChronoField\\.ALIGNED_DAY_OF_WEEK_IN_MONTH"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "js-joda:scriptContent:modern:14",
				kind: "scriptContent",
				pattern: new RegExp("ChronoUnit\\.HALF_DAYS|ChronoUnit\\.FOREVER"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "js-joda:scriptContent:modern:15",
				kind: "scriptContent",
				pattern: new RegExp("IsoChronology\\.INSTANCE"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "js-joda:scriptContent:modern:16",
				kind: "scriptContent",
				pattern: new RegExp("Period\\.parse\\(\"P\\d+Y\\d+M\\d+D\"\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "js-joda:scriptContent:modern:17",
				kind: "scriptContent",
				pattern: new RegExp("ZoneRegion\\.of\\(\"[^\"]+\"\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "js-joda:scriptContent:modern:18",
				kind: "scriptContent",
				pattern: new RegExp("Clock\\.system\\(ZoneId\\.of\\([^)]+\\)\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "js-joda:scriptContent:modern:19",
				kind: "scriptContent",
				pattern: new RegExp("ALIGNED_DAY_OF_WEEK_IN_MONTH"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "js-joda:scriptContent:modern:20",
				kind: "scriptContent",
				pattern: new RegExp("ALIGNED_DAY_OF_WEEK_IN_YEAR"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
	{
		id: "luxon",
		name: "Luxon",
		website: "https://moment.github.io/luxon/",
		description: "Modern JavaScript date utility library",
		categories: [
			"dates",
		],
		rules: [
			{
				id: "luxon:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("\"Zone required with IANA name\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "luxon:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("\"Unique zone required\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "luxon:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("\"Can't subtract an invalid DateTime\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "luxon:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("\"Missing locale data for \""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "luxon:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("\"Could not create DateTime from invalid JSON\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "luxon:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("\"Numbers in toRelative\\(\\) are required to be Integers\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "luxon:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("isLuxonDateTime:\\s*true"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "luxon:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("\"Zone is an abstract class\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "luxon:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("formatToParts\\([^)]*\\).*?timeZoneName.*?offsetName"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "luxon:scriptContent:modern:9",
				kind: "scriptContent",
				pattern: new RegExp("type\\s*===\\s*\"timeZoneName\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "luxon:scriptContent:modern:10",
				kind: "scriptContent",
				pattern: new RegExp("LuxonError\\s*=.*?function.*?_Error\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "luxon:scriptContent:modern:11",
				kind: "scriptContent",
				pattern: new RegExp("inheritsLoose\\([^,]+,\\s*_Error\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "luxon:scriptContent:modern:12",
				kind: "scriptContent",
				pattern: new RegExp("Info\\.features\\(\\)\\.zones"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "luxon:scriptContent:modern:13",
				kind: "scriptContent",
				pattern: new RegExp("Info\\.features\\(\\)\\.intl"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "luxon:scriptContent:modern:14",
				kind: "scriptContent",
				pattern: new RegExp("Info\\.features\\(\\)\\.relative"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "luxon:scriptContent:modern:15",
				kind: "scriptContent",
				pattern: new RegExp("Info\\.meridiems\\("),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "luxon:scriptContent:modern:16",
				kind: "scriptContent",
				pattern: new RegExp("\\{numberingSystem:\\s*[\"'][^\"']+[\"'],\\s*outputCalendar:\\s*[\"'][^\"']+[\"']\\}"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "luxon:scriptContent:modern:17",
				kind: "scriptContent",
				pattern: new RegExp("\\{conversionAccuracy:\\s*[\"']casual[\"']\\}"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "luxon:scriptContent:modern:18",
				kind: "scriptContent",
				pattern: new RegExp("Settings\\.throwOnInvalid\\s*=\\s*true"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "luxon:scriptContent:modern:19",
				kind: "scriptContent",
				pattern: new RegExp("Settings\\.defaultZone\\s*="),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
] as const satisfies readonly TechnologyDefinition[];
