import type { TechnologyDefinition } from '../types';

export const formSchemaLibraryTechnologyDefinitions = [
	{
		id: "formalize-css",
		name: "Formalize CSS",
		website: "https://formalize.me",
		description: "Formalize CSS is a stylesheet that standardizes the appearance and behavior of HTML form elements across browsers to ensure consistent rendering.",
		icon: "Formalize.svg",
		categories: [
			"form-schema-library",
			"component-library",
			"styling-library",
		],
		rules: [
			{
				id: "formalize-css:scriptSrc:0",
				kind: "scriptSrc",
				pattern: new RegExp("\\/js\\/jquery\\.formalize\\.js"),
				description: "Script source URL matches a known technology marker.",
			},
			{
				id: "formalize-css:jsGlobal:1",
				kind: "jsGlobal",
				property: "FORMALIZE.init",
				description: "Page-owned global matches a known technology marker.",
			},
		],
		metadata: {
			saas: true,
			oss: false,
		},
	},
	{
		id: "final-form",
		name: "Final Form",
		website: "https://final-form.org/",
		description: "Framework agnostic, high performance, subscription-based form state management",
		categories: [
			"form-schema-library",
		],
		rules: [
			{
				id: "final-form:resourceUrl:modern:0",
				kind: "resourceUrl",
				pattern: new RegExp("final-form[.\\-@/]"),
				confidence: 75,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "final-form:resourceUrl:modern:1",
				kind: "resourceUrl",
				pattern: new RegExp("react-final-form[.\\-@/]"),
				confidence: 75,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "final-form:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("\"final-form\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "final-form:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("\"react-final-form\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "final-form:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("\"FORM_ERROR\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
	{
		id: "formik",
		name: "Formik",
		website: "https://formik.org/",
		description: "Build forms in React without the tears",
		categories: [
			"form-schema-library",
		],
		rules: [
			{
				id: "formik:resourceUrl:modern:0",
				kind: "resourceUrl",
				pattern: new RegExp("formik[.\\-@/]"),
				confidence: 75,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "formik:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("exports\\.Formik\\b"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "formik:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("exports\\.FormikProvider\\b"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "formik:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("exports\\.FormikContext\\b"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "formik:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("exports\\.FormikConsumer\\b"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "formik:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("exports\\.useFormik\\b"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "formik:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("exports\\.useField\\b"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "formik:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("exports\\.withFormik\\b"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "formik:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("exports\\.FastField\\b"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "formik:scriptContent:modern:9",
				kind: "scriptContent",
				pattern: new RegExp("exports\\.FieldArray\\b"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "formik:scriptContent:modern:10",
				kind: "scriptContent",
				pattern: new RegExp("exports\\.ErrorMessage\\b"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "formik:scriptContent:modern:11",
				kind: "scriptContent",
				pattern: new RegExp("exports\\.validateYupSchema\\b"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "formik:scriptContent:modern:12",
				kind: "scriptContent",
				pattern: new RegExp("exports\\.yupToFormErrors\\b"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
	{
		id: "react-hook-form",
		name: "React Hook Form",
		website: "https://react-hook-form.com/",
		description: "Performant, flexible and extensible forms with easy-to-use validation",
		categories: [
			"form-schema-library",
		],
		rules: [
			{
				id: "react-hook-form:resourceUrl:modern:0",
				kind: "resourceUrl",
				pattern: new RegExp("react-hook-form[.\\-@/]"),
				confidence: 75,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "react-hook-form:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("exports\\.FormProvider"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "react-hook-form:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("exports\\.useForm\\b"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "react-hook-form:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("exports\\.useController\\b"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "react-hook-form:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("exports\\.useFieldArray\\b"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "react-hook-form:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("exports\\.useFormContext\\b"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "react-hook-form:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("exports\\.Controller\\b"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "react-hook-form:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("\\bflexRender\\b.*\\buseReactTable\\b|\\buseReactTable\\b.*\\bflexRender\\b"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "react-hook-form:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("\\bFormProvider\\b.*\\buseForm\\b"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
	{
		id: "valibot",
		name: "Valibot",
		website: "https://valibot.dev/",
		description: "The modular and type safe schema library",
		categories: [
			"form-schema-library",
		],
		rules: [
			{
				id: "valibot:resourceUrl:modern:0",
				kind: "resourceUrl",
				pattern: new RegExp("valibot[.\\-@/]"),
				confidence: 75,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "valibot:resourceUrl:modern:1",
				kind: "resourceUrl",
				pattern: new RegExp("node_modules\\/valibot"),
				confidence: 75,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "valibot:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("\"ValiError\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "valibot:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("\"valibot\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "valibot:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("\"valibotResolver\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "valibot:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("valibotResolver"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "valibot:resourceUrl:modern:6",
				kind: "resourceUrl",
				pattern: new RegExp("hookform.*resolvers.*valibot"),
				confidence: 65,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "valibot:resourceUrl:modern:7",
				kind: "resourceUrl",
				pattern: new RegExp("resolvers\\/valibot"),
				confidence: 65,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
		],
	},
	{
		id: "yup",
		name: "Yup",
		website: "https://github.com/jquense/yup",
		description: "Schema builder for runtime value parsing and validation",
		categories: [
			"form-schema-library",
		],
		rules: [
			{
				id: "yup:resourceUrl:modern:0",
				kind: "resourceUrl",
				pattern: new RegExp("\\/yup[.\\-@/]"),
				confidence: 75,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "yup:resourceUrl:modern:1",
				kind: "resourceUrl",
				pattern: new RegExp("node_modules\\/yup"),
				confidence: 75,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "yup:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("exports\\.validateYupSchema\\b"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "yup:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("exports\\.yupToFormErrors\\b"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
	{
		id: "zod",
		name: "Zod",
		website: "https://zod.dev/",
		description: "TypeScript-first schema validation with static type inference",
		categories: [
			"form-schema-library",
		],
		rules: [
			{
				id: "zod:resourceUrl:modern:0",
				kind: "resourceUrl",
				pattern: new RegExp("zod[.\\-@/]"),
				confidence: 75,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "zod:resourceUrl:modern:1",
				kind: "resourceUrl",
				pattern: new RegExp("node_modules\\/zod"),
				confidence: 75,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "zod:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("\"ZodObject\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "zod:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("\"ZodString\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "zod:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("\"ZodNumber\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "zod:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("\"ZodArray\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "zod:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("\"ZodEnum\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "zod:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("\"ZodError\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "zod:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("\"ZodUnion\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "zod:scriptContent:modern:9",
				kind: "scriptContent",
				pattern: new RegExp("\"ZodBoolean\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "zod:scriptContent:modern:10",
				kind: "scriptContent",
				pattern: new RegExp("\"invalid_type\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "zod:scriptContent:modern:11",
				kind: "scriptContent",
				pattern: new RegExp("\"invalid_enum_value\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "zod:scriptContent:modern:12",
				kind: "scriptContent",
				pattern: new RegExp("\"invalid_union\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "zod:scriptContent:modern:13",
				kind: "scriptContent",
				pattern: new RegExp("\"invalid_string\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "zod:scriptContent:modern:14",
				kind: "scriptContent",
				pattern: new RegExp("\"too_small\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "zod:scriptContent:modern:15",
				kind: "scriptContent",
				pattern: new RegExp("\"too_big\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "zod:scriptContent:modern:16",
				kind: "scriptContent",
				pattern: new RegExp("\"unrecognized_keys\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "zod:scriptContent:modern:17",
				kind: "scriptContent",
				pattern: new RegExp("\"not_multiple_of\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "zod:scriptContent:modern:18",
				kind: "scriptContent",
				pattern: new RegExp("\"not_finite\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
] as const satisfies readonly TechnologyDefinition[];
