import type { TechnologyDefinition } from '../types';

export const httpClientTechnologyDefinitions = [
	{
		id: "axios",
		name: "Axios",
		website: "https://github.com/axios/axios",
		description: "Promise based HTTP client for the browser and node.js.",
		icon: "Axios.svg",
		categories: [
			"http-client",
			"widgets-misc",
		],
		rules: [
			{
				id: "axios:scriptSrc:0",
				kind: "scriptSrc",
				pattern: new RegExp("\\/axios(@|\\/)([\\d.]+)(?:\\/[a-z]+)?\\/axios(?:.min)?\\.js"),
				version: {
					source: "match",
					group: 2,
				},
				description: "Script source URL matches a known technology marker.",
			},
			{
				id: "axios:jsGlobal:1",
				kind: "jsGlobal",
				property: "axios.get",
				description: "Page-owned global matches a known technology marker.",
			},
			{
				id: "axios:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("\"transitional option built-in validator\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "axios:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("\"Don't know how to serialize '[^']+'\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "axios:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("\"maxBodyLength size of -1 is not supported\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "axios:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("\\.isAxiosError\\("),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "axios:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("instanceof\\s+AxiosError"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "axios:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("CancelToken\\.source\\(\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "axios:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("\\.CancelToken\\s*\\.\\s*source\\s*\\(\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "axios:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("\\.interceptors\\.(request|response)\\.(use|eject)\\([^)]*\\)"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "axios:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("\\.interceptors\\.(request|response)\\.handlers"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "axios:scriptContent:modern:9",
				kind: "scriptContent",
				pattern: new RegExp("AxiosRequestConfig(?![a-zA-Z])"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "axios:scriptContent:modern:10",
				kind: "scriptContent",
				pattern: new RegExp("AxiosResponse(?![a-zA-Z])"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "axios:scriptContent:modern:11",
				kind: "scriptContent",
				pattern: new RegExp("AxiosInstance(?![a-zA-Z])"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "axios:scriptContent:modern:12",
				kind: "scriptContent",
				pattern: new RegExp("AxiosError(?![a-zA-Z])"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "axios:header:modern:13",
				kind: "header",
				key: "x-requested-with",
				valuePattern: new RegExp("XMLHttpRequest", "i"),
				confidence: 55,
				description: "HTTP response header matches a modern tooling marker.",
			},
		],
		metadata: {
			cpe: "cpe:2.3:a:axios:axios:*:*:*:*:*:node.js:*:*",
		},
	},
	{
		id: "fetch-api",
		name: "Fetch API",
		website: "https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API",
		description: "Modern interface for fetching resources across the network.",
		categories: [
			"http-client",
		],
		rules: [
			{
				id: "fetch-api:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("(?:^|[^.a-zA-Z])fetch\\s*\\([^,)]+,\\s*\\{[^}]*(?:method|body|mode|credentials|keepalive|headers):", "i"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "fetch-api:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("(?:^|[^.a-zA-Z])fetch\\s*\\([^)]+\\)"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "fetch-api:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("new\\s+AbortController\\(\\)[^}]*fetch\\s*\\([^)]+signal:"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "fetch-api:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("\\.clone\\(\\)\\.(?:json|text|blob)\\(\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "fetch-api:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("\\.body\\.getReader\\(\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "fetch-api:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("Response\\.redirect\\([^)]+\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
	{
		id: "got",
		name: "got",
		website: "https://github.com/sindresorhus/got",
		description: "Simplified HTTP requests",
		categories: [
			"http-client",
		],
		rules: [
			{
				id: "got:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("\\.paginate\\.all\\(\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "got:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("\\.paginate\\.each\\(\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "got:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("'beforeRequest'\\s*,\\s*function"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "got:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("'beforeRedirect'\\s*,\\s*function"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "got:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("'beforeRetry'\\s*,\\s*function"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "got:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("'beforeError'\\s*,\\s*function"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "got:header:modern:6",
				kind: "header",
				key: "x-got-retry-count",
				valuePattern: new RegExp("^\\d+$"),
				confidence: 55,
				description: "HTTP response header matches a modern tooling marker.",
			},
			{
				id: "got:resourceUrl:modern:7",
				kind: "resourceUrl",
				pattern: new RegExp("got(?:\\.min)?\\.js$", "i"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "got:resourceUrl:modern:8",
				kind: "resourceUrl",
				pattern: new RegExp("got\\.[a-f0-9]{8,}\\.js$", "i"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
		],
	},
	{
		id: "ky",
		name: "ky",
		website: "https://github.com/sindresorhus/ky?tab=readme-ov-file",
		description: "Tiny and elegant HTTP client based on the Fetch API",
		categories: [
			"http-client",
		],
		rules: [
			{
				id: "ky:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("\"Failed to parse URL from "),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "ky:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("\"The `prefixUrl` option must start with"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "ky:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("new\\s+\\w+\\.Request\\([\"']https:\\/\\/empty\\.invalid[\"']"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "ky:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("\"Response code [0-9]+ \\([^)]+\\)\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "ky:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("\"Failed to execute request hook\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "ky:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("throw\\s+new\\s+Error\\([\"']retry\\.methods\\s+must\\s+be\\s+an\\s+array[\"']\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "ky:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("throw\\s+new\\s+Error\\([\"']retry\\.statusCodes\\s+must\\s+be\\s+an\\s+array[\"']\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "ky:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("throw\\s+new\\s+Error\\s*\\(\\s*[\"']Streams are not supported in your environment\\.\\s+`ReadableStream`\\s+is\\s+missing\\.[\"']\\s*\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "ky:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("throw\\s+new\\s+Error\\s*\\(\\s*[\"']`input`\\s+must\\s+not\\s+begin\\s+with\\s+a\\s+slash\\s+when\\s+using\\s+`prefixUrl`[\"']\\s*\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "ky:scriptContent:modern:9",
				kind: "scriptContent",
				pattern: new RegExp("throw\\s+new\\s+TypeError\\s*\\(\\s*[\"']The\\s+`onDownloadProgress`\\s+option\\s+must\\s+be\\s+a\\s+function[\"']\\s*\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "ky:scriptContent:modern:10",
				kind: "scriptContent",
				pattern: new RegExp("\"The `onDownloadProgress` option must be a function\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "ky:scriptContent:modern:11",
				kind: "scriptContent",
				pattern: new RegExp("\\b\\w+\\._options\\.retry\\.backoffLimit\\b"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "ky:scriptContent:modern:12",
				kind: "scriptContent",
				pattern: new RegExp("\\w+\\._options\\.throwHttpErrors"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "ky:scriptContent:modern:13",
				kind: "scriptContent",
				pattern: new RegExp("\\{(?:[^}]*retry:[^}]+prefixUrl:[^}]+throwHttpErrors:[^}]*|[^}]*prefixUrl:[^}]+throwHttpErrors:[^}]+retry:[^}]*)\\}"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "ky:scriptContent:modern:14",
				kind: "scriptContent",
				pattern: new RegExp("retry:\\s*\\{\\s*limit:\\s*\\d+,\\s*statusCodes:\\s*\\[\\d+(?:,\\s*\\d+)*\\],\\s*methods:\\s*\\[[\"'](?:GET|POST|PUT|DELETE)[\"']"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "ky:scriptContent:modern:15",
				kind: "scriptContent",
				pattern: new RegExp("\\{\\s*status,\\s*statusText,\\s*response\\s*\\}\\s*=\\s*error"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
	{
		id: "server-actions",
		name: "Server Actions",
		website: "https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations",
		description: "Asynchronous functions that are executed on the server. They can be called in Server and Client Components to handle form submissions and data mutations in Next.js applications.",
		categories: [
			"http-client",
		],
		rules: [
			{
				id: "server-actions:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("headers:\\s*\\{[^}]*(?:\"Accept\":\\s*[^,}]*RSC_CONTENT_TYPE_HEADER|\\[ACTION\\]:|\\[NEXT_ROUTER_STATE_TREE\\]:)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "server-actions:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("\"x-action-redirect\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "server-actions:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("\"x-action-revalidated\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "server-actions:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("JSON\\.parse\\([^)]*\\.get\\(\"x-action-revalidated\"\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "server-actions:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("\"__next_form_action__\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "server-actions:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("\"Server Actions must be bound to a server component\""),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "server-actions:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("\"Cannot pass a Server Action to a Client Component\""),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "server-actions:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("\"Server Action failed with\""),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "server-actions:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("\"Server Action application state update failed\""),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "server-actions:scriptContent:modern:9",
				kind: "scriptContent",
				pattern: new RegExp("\\{paths:\\s*(?:\\[\\]|e\\[0\\]),\\s*tag:\\s*!!e\\[1\\],\\s*cookie:\\s*(?:e\\[2\\]|false)\\}"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "server-actions:header:modern:10",
				kind: "header",
				key: "x-action-redirect",
				valuePattern: new RegExp(".*"),
				confidence: 65,
				description: "HTTP response header matches a modern tooling marker.",
			},
			{
				id: "server-actions:header:modern:11",
				kind: "header",
				key: "x-action-revalidated",
				valuePattern: new RegExp("\\[\\[.*\\],\\d+,\\d+\\]"),
				confidence: 65,
				description: "HTTP response header matches a modern tooling marker.",
			},
		],
	},
	{
		id: "relay-graphql",
		name: "Relay GraphQL",
		website: "https://relay.dev/",
		description: "A JavaScript framework for building data-driven React applications",
		categories: [
			"http-client",
		],
		rules: [
			{
				id: "relay-graphql:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("\"RelayRequiredFields\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "relay-graphql:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("\"RelayLiveResolvers\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "relay-graphql:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("\"RelayDefaultMask\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "relay-graphql:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("\"RelayConnectionHandler\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "relay-graphql:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("\"getRootField: Expected id"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "relay-graphql:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("\"getLinkedRecords: Expected array of records\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "relay-graphql:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("\"Expected id for record .* missing field"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "relay-graphql:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("\"Expected record .* to have a .* selection"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "relay-graphql:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("\"Relay: Expected .* to be registered before cleaning up\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "relay-graphql:scriptContent:modern:9",
				kind: "scriptContent",
				pattern: new RegExp("\"RelayModernStore: Mutation\",\\s*\"RetainQuery\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "relay-graphql:scriptContent:modern:10",
				kind: "scriptContent",
				pattern: new RegExp("\"RelayModernStore: Operation\",\\s*\"CommitPayload\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "relay-graphql:scriptContent:modern:11",
				kind: "scriptContent",
				pattern: new RegExp("\"__id\",\\s*\"__typename\",\\s*\"__isNode\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "relay-graphql:scriptContent:modern:12",
				kind: "scriptContent",
				pattern: new RegExp("\"RelayReader: Expected .* to be a scalar\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "relay-graphql:scriptContent:modern:13",
				kind: "scriptContent",
				pattern: new RegExp("\"connection:.*\\$.*\\$.*connections\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "relay-graphql:scriptContent:modern:14",
				kind: "scriptContent",
				pattern: new RegExp("\"__connection_next_edge_index\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "relay-graphql:scriptContent:modern:15",
				kind: "scriptContent",
				pattern: new RegExp("\"Connection handler .* cannot handle undefined\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "relay-graphql:scriptContent:modern:16",
				kind: "scriptContent",
				pattern: new RegExp("\"RelayConcreteNode\\.(?:LinkedField|ScalarField|Fragment)\""),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "relay-graphql:scriptContent:modern:17",
				kind: "scriptContent",
				pattern: new RegExp("\"RelayModernEnvironment: Operation\",\\s*\".*\"\\s*already exists\""),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "relay-graphql:scriptContent:modern:18",
				kind: "scriptContent",
				pattern: new RegExp("\"RelayValidator: Fragment spread .* unused\""),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
	{
		id: "superagent",
		name: "Superagent",
		website: "https://ladjs.github.io/superagent",
		description: "Ajax with less suck - (and node.js HTTP client to match)",
		categories: [
			"http-client",
		],
		rules: [
			{
				id: "superagent:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("\"no appendQueryString\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "superagent:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("\"no Request#pipe\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "superagent:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("Warning: superagent request was sent twice, because both \\.end\\(\\) and \\.then\\(\\) were called\\. Never call \\.end\\(\\) if you use promises"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "superagent:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("Using browser-only version of superagent in non-browser environment"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "superagent:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("superagent can't mix \\.send\\(\\) and \\.attach\\(\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "superagent:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("This is not supported in browser version of superagent"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "superagent:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("Warning: \\.end\\(\\) was called twice\\. This is not supported in superagent"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "superagent:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("Request has been terminated\\nPossible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc\\."),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "superagent:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("\"superagent first\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "superagent:scriptContent:modern:9",
				kind: "scriptContent",
				pattern: new RegExp("\"no superagent serializer\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "superagent:scriptContent:modern:10",
				kind: "scriptContent",
				pattern: new RegExp("\"multiple content-types\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "superagent:scriptContent:modern:11",
				kind: "scriptContent",
				pattern: new RegExp("\"please use Buffer\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "superagent:scriptContent:modern:12",
				kind: "scriptContent",
				pattern: new RegExp("\"should be a blob\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "superagent:scriptContent:modern:13",
				kind: "scriptContent",
				pattern: new RegExp("\"unexpected form field\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "superagent:scriptContent:modern:14",
				kind: "scriptContent",
				pattern: new RegExp("\"retries exceeded\""),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "superagent:scriptContent:modern:15",
				kind: "scriptContent",
				pattern: new RegExp("\"retry: gave up\""),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "superagent:scriptContent:modern:16",
				kind: "scriptContent",
				pattern: new RegExp("\"retry: too many redirects\""),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "superagent:scriptContent:modern:17",
				kind: "scriptContent",
				pattern: new RegExp("\"retry count exceeds\""),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "superagent:header:modern:18",
				kind: "header",
				key: "x-superagent-retry-count",
				valuePattern: new RegExp("^\\d+$"),
				confidence: 55,
				description: "HTTP response header matches a modern tooling marker.",
			},
			{
				id: "superagent:scriptContent:modern:19",
				kind: "scriptContent",
				pattern: new RegExp("\\.(?:accept|query|field|attach|set)\\([^)]*\\)\\.(?:accept|query|field|attach|set)\\([^)]*\\)\\.retry\\("),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "superagent:scriptContent:modern:20",
				kind: "scriptContent",
				pattern: new RegExp("\\.accept\\(['\"]application\\/json['\"]\\)\\.type\\(['\"]application\\/json['\"]\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "superagent:scriptContent:modern:21",
				kind: "scriptContent",
				pattern: new RegExp("\\.field\\([^)]+\\)\\.attach\\([^)]+\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "superagent:scriptContent:modern:22",
				kind: "scriptContent",
				pattern: new RegExp("\\.attach\\(['\"]file['\"],[^,]+,\\{filename:"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "superagent:scriptContent:modern:23",
				kind: "scriptContent",
				pattern: new RegExp("\\.attach\\(['\"]file['\"],[^,]+,\\{contentType:"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "superagent:scriptContent:modern:24",
				kind: "scriptContent",
				pattern: new RegExp("\\.field\\(['\"]name['\"],[^)]+\\)\\.field\\(['\"]key['\"],[^)]+\\)\\.attach\\("),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
	{
		id: "swr",
		name: "SWR",
		website: "https://swr.vercel.app/",
		description: "React Hooks library for remote data fetching",
		categories: [
			"http-client",
		],
		rules: [
			{
				id: "swr:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("\\[\\[\"finite\",1],\\[\"revalidateOnFocus\",1],\\[\"revalidateOnReconnect\",1],\\[\"refreshInterval\",0]]"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "swr:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("\"No fetcher function matched"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "swr:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("\"broadcast\\([^)]*\\):\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "swr:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("\"serialized key: \""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "swr:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("\"focus\",\"visibilitychange\",\"online\",\"offline\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "swr:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("\\$swr\\$.*?\\$cache\\$"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "swr:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("\\$cache\\$\\/.*?\\$swr\\$"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "swr:resourceUrl:modern:7",
				kind: "resourceUrl",
				pattern: new RegExp("swr(?:\\.min)?\\.js$", "i"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "swr:resourceUrl:modern:8",
				kind: "resourceUrl",
				pattern: new RegExp("swr\\.[a-f0-9]{8,}\\.js$", "i"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "swr:resourceUrl:modern:9",
				kind: "resourceUrl",
				pattern: new RegExp("use-swr\\.[a-f0-9]{8,}\\.js$", "i"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
		],
	},
] as const satisfies readonly TechnologyDefinition[];
