import type { TechnologyDefinition } from '../types';

export const minifierTechnologyDefinitions = [
	{
		id: "babel-minify",
		name: "Babel Minify",
		website: "https://babeljs.io/docs/en/babel-minify",
		description: "Minify JavaScript using Babel",
		categories: [
			"minifier",
		],
		rules: [
			{
				id: "babel-minify:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("\\([$_a-z]=\\d+,[$_a-z]=\\d+,[$_a-z][+\\-*/][$_a-z]\\)"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "babel-minify:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("\\|\\s*0(?!\\d)"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "babel-minify:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("[\"']production[\"']===[\"']production[\"']\\&\\&"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "babel-minify:resourceUrl:modern:3",
				kind: "resourceUrl",
				pattern: new RegExp("\\.babel\\.min\\.js$"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "babel-minify:resourceUrl:modern:4",
				kind: "resourceUrl",
				pattern: new RegExp("\\.min\\.babel\\.js$"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
		],
	},
	{
		id: "closure",
		name: "Closure",
		website: "https://developers.google.com/closure/compiler",
		description: "JavaScript minifier and optimizer",
		categories: [
			"minifier",
		],
		rules: [
			{
				id: "closure:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("var [$_a-z]_=function\\([$_a-z]_,[$_a-z]_\\)\\{return [$_a-z]_[+\\-*/][$_a-z]_\\}"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "closure:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("this\\.[$_a-z]_=\\d+(?:,this\\.[$_a-z]_=\\d+){1,}"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "closure:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("[\"']undefined[\"']==typeof [$_a-z]\\b"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "closure:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("[=!]=(?:=)?!(?:0|1)(?!\\d)(?:&&|\\|\\||\\}|\\))"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "closure:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("\\{[$_a-z]:(?:\\d+|!0|!1)(?:,[$_a-z]:(?:\\d+|!0|!1))*\\}"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "closure:resourceUrl:modern:5",
				kind: "resourceUrl",
				pattern: new RegExp("\\.closure\\.min\\.js$"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "closure:resourceUrl:modern:6",
				kind: "resourceUrl",
				pattern: new RegExp("\\.cc\\.min\\.js$"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "closure:resourceUrl:modern:7",
				kind: "resourceUrl",
				pattern: new RegExp("\\.[a-f0-9]{8}\\.closure\\.js$"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
		],
	},
	{
		id: "prepack",
		name: "Prepack",
		website: "https://prepack.io/",
		description: "Partial evaluator for JavaScript",
		categories: [
			"minifier",
		],
		rules: [
			{
				id: "prepack:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("(?:\\b\\d+(?:\\.\\d+)?\\b[+\\-*/]){3,}\\b\\d+(?:\\.\\d+)?\\b"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "prepack:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("if\\(!0\\)\\{(?:[^{}]|{[^{}]*})*\\}"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "prepack:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("[\"'][a-zA-Z0-9_$]{10,}[\"']"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "prepack:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("(?:[$_a-z]+=\\d+;){3,}"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "prepack:resourceUrl:modern:4",
				kind: "resourceUrl",
				pattern: new RegExp("\\.prepack\\.min\\.js$"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "prepack:resourceUrl:modern:5",
				kind: "resourceUrl",
				pattern: new RegExp("\\.pp\\.min\\.js$"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "prepack:resourceUrl:modern:6",
				kind: "resourceUrl",
				pattern: new RegExp("\\.[a-f0-9]{8}\\.prepack\\.js$"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
		],
	},
	{
		id: "swc",
		name: "SWC",
		website: "https://swc.rs",
		description: "SWC is a fast compiler and minifier for JavaScript and TypeScript.",
		categories: [
			"minifier",
			"transpiler",
		],
		rules: [
			{
				id: "swc:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("_createClass\\([A-Z],\\[\\{key:\"[a-z]\",value:function\\(\\)\\{\\}\\}\\]\\)"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "swc:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("var [$_a-z]=\\d+(?:,[$_a-z]=\\d+){2,}"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "swc:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("async function\\(\\)\\{try\\{await [$_a-z]\\(\\)\\}catch\\([a-z]\\)\\{\\}\\}"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "swc:resourceUrl:modern:3",
				kind: "resourceUrl",
				pattern: new RegExp("\\.swc\\.min\\.js$"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "swc:resourceUrl:modern:4",
				kind: "resourceUrl",
				pattern: new RegExp("\\.min\\.swc\\.js$"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "swc:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("\"use strict\";(?:\\s*var\\s+__create\\s*=\\s*Object\\.create;\\s*var\\s+__defProp\\s*=\\s*Object\\.defineProperty;\\s*var\\s+__getOwnPropDesc\\s*=\\s*Object\\.getOwnPropertyDescriptor;)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "swc:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("var\\s+__defNormalProp\\s*=\\s*\\(\\w+,\\s*\\w+,\\s*\\w+\\)\\s*=>\\s*\\w+\\s+in\\s+\\w+\\s*\\?\\s*__defProp"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "swc:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("var\\s+_\\w+\\s*=\\s*\\/\\*#__PURE__\\*\\/\\s*new\\s+WeakMap\\(\\);"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "swc:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("var\\s+__decorateClass\\s*=\\s*\\(\\[\\s*decorators,\\s*target,\\s*key,\\s*kind\\s*\\]\\)\\s*=>"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "swc:scriptContent:modern:9",
				kind: "scriptContent",
				pattern: new RegExp("var\\s+__metadata\\s*=\\s*\\(\\[\\s*metadataKey,\\s*metadataValue\\s*\\]\\)\\s*=>"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "swc:scriptContent:modern:10",
				kind: "scriptContent",
				pattern: new RegExp("return\\s*\\(\\w+\\s*=\\s*class\\s+extends\\s*\\w+\\s*\\{\\}\\s*,\\s*__decorateClass\\(\\[\\w+\\],\\s*\\w+\\.prototype,\\s*[\"']\\w+[\"']"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "swc:scriptContent:modern:11",
				kind: "scriptContent",
				pattern: new RegExp("var\\s+__async\\s*=\\s*\\(__this,\\s*__arguments,\\s*generator\\)\\s*=>\\s*\\{"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "swc:scriptContent:modern:12",
				kind: "scriptContent",
				pattern: new RegExp("(?:var|let)\\s+(_\\w+)\\s*=\\s*class\\s+extends\\s+\\w+\\s*\\{\\s*constructor\\(\\)\\s*\\{\\s*super\\(\\);\\s*_\\w+\\.set\\(this,\\s*void\\s*0\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "swc:scriptContent:modern:13",
				kind: "scriptContent",
				pattern: new RegExp("\\(\\s*function\\s*\\(\\w+\\)\\s*\\{\\s*\\w+\\[\\w+\\[\"[^\"]+\"\\]\\s*=\\s*\\d+\\]\\s*=\\s*\"[^\"]+\";\\s*\\}\\)\\(\\w+\\s*\\|\\|\\s*\\(\\w+\\s*=\\s*\\{\\}\\)\\);"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "swc:scriptContent:modern:14",
				kind: "scriptContent",
				pattern: new RegExp("var\\s+__toESM\\s*=\\s*\\(\\w+,\\s*\\w+\\)\\s*=>\\s*\\{\\s*return\\s+__reExport\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "swc:scriptContent:modern:15",
				kind: "scriptContent",
				pattern: new RegExp("var\\s+__reExport\\s*=\\s*\\(\\w+,\\s*\\w+,\\s*\\w+\\)\\s*=>\\s*Object\\.keys\\(\\w+\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "swc:scriptContent:modern:16",
				kind: "scriptContent",
				pattern: new RegExp("Object\\.defineProperty\\(\\w+,\\s*\"__esModule\",\\s*\\{\\s*value:\\s*true\\s*\\}\\);\\s*__reExport\\(exports,"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
	{
		id: "terser",
		name: "Terser",
		website: "https://terser.org/",
		description: "JavaScript parser, mangler, compressor, and beautifier toolkit",
		categories: [
			"minifier",
		],
		rules: [
			{
				id: "terser:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("^\\(\\(\\)\\s*=>\\s*\\{\"use strict\";(?:var|let|const)\\s+[a-zA-Z$_]\\s*=\\s*\\{"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "terser:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("(?:return|[=!]=)\\s*void\\s*0\\b"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "terser:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("(?:\\(|function\\s*)[a-zA-Z$_][a-zA-Z0-9$_]*,\\s*\\.\\.\\.[$_a-z]\\)\\s*[={]"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "terser:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp(",([a-zA-Z$_][a-zA-Z0-9$_]*)\\s*:\\s*\\1(?=\\}|,)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "terser:resourceUrl:modern:4",
				kind: "resourceUrl",
				pattern: new RegExp("\\.terser\\.(?:min\\.)?js$"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "terser:resourceUrl:modern:5",
				kind: "resourceUrl",
				pattern: new RegExp("\\.min\\.[a-f0-9]{8}\\.terser\\.js$"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
		],
	},
	{
		id: "uglify",
		name: "Uglify",
		website: "https://lisperator.net/uglifyjs/",
		description: "JavaScript parser, mangler, compressor, and beautifier toolkit",
		categories: [
			"minifier",
		],
		rules: [
			{
				id: "uglify:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("^!function\\([a-z],\\s*[a-z]\\)\\{.{0,50}?\\}\\((?:window|this)\\)"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "uglify:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("function [a-z]\\([a-z],\\s*[a-z]\\)\\{return [a-z][+\\-*/][a-z]\\}"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "uglify:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("(?:[=!]=)!(?:0|1)(?!\\d)"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "uglify:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("\\((?:[a-z]=(?:[a-z]\\.(?:length|id|name)),?){2,}\\s*[a-z]\\)"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "uglify:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("\\[[\"'](?:[gs]et|on|handle)[^\"']+[\"']\\+[a-z]\\]"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "uglify:resourceUrl:modern:5",
				kind: "resourceUrl",
				pattern: new RegExp("\\.uglify(?:js)?\\.(?:min\\.)?js$"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "uglify:resourceUrl:modern:6",
				kind: "resourceUrl",
				pattern: new RegExp("\\.min\\.[a-f0-9]{8}\\.ugly\\.js$"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
		],
	},
] as const satisfies readonly TechnologyDefinition[];
