import type { TechnologyDefinition } from '../types';

export const moduleFormatTechnologyDefinitions = [
	{
		id: "amd",
		name: "AMD",
		website: "https://en.wikipedia.org/wiki/Asynchronous_module_definition",
		description: "Asynchronous Module Definition (AMD) is a JavaScript API for defining modules such that the module and its dependencies can be asynchronously loaded.",
		categories: [
			"module-format",
		],
		rules: [
			{
				id: "amd:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("define\\s*\\(\\s*[\"'][^\"']+[\"']\\s*,\\s*\\["),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "amd:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("define\\s*\\(\\s*\\[[^\\]]*\\]\\s*,\\s*function"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "amd:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("define\\s*\\(\\s*function\\s*\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "amd:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("define\\s*\\(\\s*\\[\\s*[\"']require[\"']\\s*,\\s*[\"']exports[\"']\\s*,\\s*[\"']module[\"']\\s*\\]"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "amd:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("define\\s*\\(\\s*\\[\\s*[\"']exports[\"']\\s*\\]"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "amd:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("define\\([\"'][^\"']+[\"'],\\["),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "amd:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("define\\(\\[[^\\]]*\\],function"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "amd:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("define\\(function\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "amd:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("return\\s*\\{\\s*[^}]*\\}"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "amd:scriptContent:modern:9",
				kind: "scriptContent",
				pattern: new RegExp("return\\s*\\(\\s*\\{\\s*[^}]*\\}\\s*\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "amd:scriptContent:modern:10",
				kind: "scriptContent",
				pattern: new RegExp("exports\\.\\w+\\s*="),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "amd:scriptContent:modern:11",
				kind: "scriptContent",
				pattern: new RegExp("exports\\[[\"']\\w+[\"']\\]\\s*="),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "amd:scriptContent:modern:12",
				kind: "scriptContent",
				pattern: new RegExp("return\\s+function\\s*\\w*\\s*\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "amd:scriptContent:modern:13",
				kind: "scriptContent",
				pattern: new RegExp("return\\s+class\\s*\\w*\\s*\\{"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "amd:scriptContent:modern:14",
				kind: "scriptContent",
				pattern: new RegExp("module\\.exports\\s*="),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "amd:scriptContent:modern:15",
				kind: "scriptContent",
				pattern: new RegExp("exports\\s*=\\s*[^;]+"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "amd:scriptContent:modern:16",
				kind: "scriptContent",
				pattern: new RegExp("return{"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "amd:scriptContent:modern:17",
				kind: "scriptContent",
				pattern: new RegExp("exports\\.\\w+="),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "amd:scriptContent:modern:18",
				kind: "scriptContent",
				pattern: new RegExp("return function\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "amd:scriptContent:modern:19",
				kind: "scriptContent",
				pattern: new RegExp("return class\\{"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "amd:scriptContent:modern:20",
				kind: "scriptContent",
				pattern: new RegExp("Object\\.defineProperty\\s*\\(\\s*exports\\s*,"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "amd:scriptContent:modern:21",
				kind: "scriptContent",
				pattern: new RegExp("Object\\.defineProperties\\s*\\(\\s*exports\\s*,"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "amd:scriptContent:modern:22",
				kind: "scriptContent",
				pattern: new RegExp("factory\\s*\\(\\s*(?:require\\s*,\\s*)?exports\\s*,\\s*module\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "amd:scriptContent:modern:23",
				kind: "scriptContent",
				pattern: new RegExp("factory\\.call\\s*\\(\\s*this\\s*,\\s*(?:require\\s*,\\s*)?exports\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "amd:scriptContent:modern:24",
				kind: "scriptContent",
				pattern: new RegExp("typeof\\s+exports\\s*===?\\s*[\"']object[\"']"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "amd:scriptContent:modern:25",
				kind: "scriptContent",
				pattern: new RegExp("typeof\\s+define\\s*===?\\s*[\"']function[\"']"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "amd:scriptContent:modern:26",
				kind: "scriptContent",
				pattern: new RegExp("\\w+\\.define\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "amd:scriptContent:modern:27",
				kind: "scriptContent",
				pattern: new RegExp("\\w+\\.exports\\."),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
	{
		id: "commonjs",
		name: "CommonJS",
		website: "https://en.wikipedia.org/wiki/CommonJS#:~:text=CommonJS%20is%20a%20project%20to,js.",
		description: "Project to standardize the module ecosystem for JavaScript outside of web browsers.",
		categories: [
			"module-format",
		],
		rules: [
			{
				id: "commonjs:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("require\\s*\\(\\s*[\"'][^\"']+[\"']\\s*\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "commonjs:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("require\\s*\\(\\s*`[^`]+`\\s*\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "commonjs:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("(?:const|let|var)\\s*\\{[^}]+\\}\\s*=\\s*require\\s*\\([^)]+\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "commonjs:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("(?:const|let|var)\\s+\\w+\\s*=\\s*require\\s*\\([^)]+\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "commonjs:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("=require\\([\"'][^\"']+[\"']\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "commonjs:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("=require\\([^)]+\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "commonjs:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("require\\([\"'][^\"']+[\"']\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "commonjs:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("require\\s*\\(\\s*\\w+\\s*\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "commonjs:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("require\\s*\\(\\s*\\w+\\s*\\+\\s*[\"'][^\"']*[\"']\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "commonjs:scriptContent:modern:9",
				kind: "scriptContent",
				pattern: new RegExp("require\\s*\\(\\s*`[^`]*\\$\\{[^}]+\\}[^`]*`\\s*\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "commonjs:scriptContent:modern:10",
				kind: "scriptContent",
				pattern: new RegExp("require\\.resolve\\s*\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "commonjs:scriptContent:modern:11",
				kind: "scriptContent",
				pattern: new RegExp("require\\.cache\\b"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "commonjs:scriptContent:modern:12",
				kind: "scriptContent",
				pattern: new RegExp("require\\.main\\b"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "commonjs:scriptContent:modern:13",
				kind: "scriptContent",
				pattern: new RegExp("module\\.exports\\s*=\\s*[^;]+"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "commonjs:scriptContent:modern:14",
				kind: "scriptContent",
				pattern: new RegExp("module\\s*\\[\\s*[\"']exports[\"']\\s*\\]\\s*="),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "commonjs:scriptContent:modern:15",
				kind: "scriptContent",
				pattern: new RegExp("module\\.exports\\s*=\\s*\\{"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "commonjs:scriptContent:modern:16",
				kind: "scriptContent",
				pattern: new RegExp("exports\\.\\w+\\s*="),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "commonjs:scriptContent:modern:17",
				kind: "scriptContent",
				pattern: new RegExp("exports\\[[\"']\\w+[\"']\\]\\s*="),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "commonjs:scriptContent:modern:18",
				kind: "scriptContent",
				pattern: new RegExp("Object\\.defineProperty\\s*\\(\\s*exports\\s*,\\s*[\"']\\w+[\"']\\s*,"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "commonjs:scriptContent:modern:19",
				kind: "scriptContent",
				pattern: new RegExp("Object\\.defineProperties\\s*\\(\\s*exports\\s*,"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "commonjs:scriptContent:modern:20",
				kind: "scriptContent",
				pattern: new RegExp("exports\\s*=\\s*module\\.exports\\s*="),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "commonjs:scriptContent:modern:21",
				kind: "scriptContent",
				pattern: new RegExp("module\\.exports\\s*=\\s*exports\\s*="),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "commonjs:scriptContent:modern:22",
				kind: "scriptContent",
				pattern: new RegExp("exports\\.\\w+="),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "commonjs:scriptContent:modern:23",
				kind: "scriptContent",
				pattern: new RegExp("exports=module\\.exports="),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "commonjs:scriptContent:modern:24",
				kind: "scriptContent",
				pattern: new RegExp("module\\.exports=\\{"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "commonjs:scriptContent:modern:25",
				kind: "scriptContent",
				pattern: new RegExp("exports\\s*\\[\\s*[\"']default[\"']\\s*\\]\\s*="),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "commonjs:scriptContent:modern:26",
				kind: "scriptContent",
				pattern: new RegExp("module\\.exports\\s*\\[\\s*[\"']default[\"']\\s*\\]\\s*="),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
	{
		id: "es-modules",
		name: "ES Modules",
		website: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules",
		description: "A way to structure your JavaScript code in separate files that can be imported where needed.",
		categories: [
			"module-format",
		],
		rules: [
			{
				id: "es-modules:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("import\\s+\\{[^}]+\\}\\s*from"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "es-modules:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("import\\s+\\w+\\s*,\\s*\\{[^}]+\\}\\s*from"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "es-modules:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("import\\s+\\*\\s+as\\s+\\w+\\s+from"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "es-modules:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("import\\s+\\w+\\s+from"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "es-modules:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("import\\s+[\"'][^\"']+[\"']"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "es-modules:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("import{[^}]+}from"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "es-modules:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("import\\{"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "es-modules:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("import\\*"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "es-modules:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("from[\"'][^\"']+[\"']"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "es-modules:scriptContent:modern:9",
				kind: "scriptContent",
				pattern: new RegExp("import\\s*\\([^)]+\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "es-modules:scriptContent:modern:10",
				kind: "scriptContent",
				pattern: new RegExp("import\\s*\\([\"'][^\"']+[\"']\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "es-modules:scriptContent:modern:11",
				kind: "scriptContent",
				pattern: new RegExp("\\(\\s*\\)\\s*=>\\s*import\\s*\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "es-modules:scriptContent:modern:12",
				kind: "scriptContent",
				pattern: new RegExp("await\\s+import\\s*\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "es-modules:scriptContent:modern:13",
				kind: "scriptContent",
				pattern: new RegExp("Promise\\s*\\.\\s*all\\s*\\(\\s*\\[?\\s*import\\s*\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "es-modules:scriptContent:modern:14",
				kind: "scriptContent",
				pattern: new RegExp("import\\([\"'][^\"']+[\"']\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "es-modules:scriptContent:modern:15",
				kind: "scriptContent",
				pattern: new RegExp("\\(\\)?=>import\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "es-modules:scriptContent:modern:16",
				kind: "scriptContent",
				pattern: new RegExp("await import\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "es-modules:scriptContent:modern:17",
				kind: "scriptContent",
				pattern: new RegExp("export\\s+(?:const|let|var|class|function|interface|type)\\s+\\w+"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "es-modules:scriptContent:modern:18",
				kind: "scriptContent",
				pattern: new RegExp("export\\s+\\{[^}]+\\}"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "es-modules:scriptContent:modern:19",
				kind: "scriptContent",
				pattern: new RegExp("export\\s+\\{[^}]+\\}\\s+from"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "es-modules:scriptContent:modern:20",
				kind: "scriptContent",
				pattern: new RegExp("export\\s+default\\s+"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "es-modules:scriptContent:modern:21",
				kind: "scriptContent",
				pattern: new RegExp("export\\s+default\\s+function\\s*\\w*\\s*\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "es-modules:scriptContent:modern:22",
				kind: "scriptContent",
				pattern: new RegExp("export\\s+default\\s+class\\s*\\w*\\s*\\{"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "es-modules:scriptContent:modern:23",
				kind: "scriptContent",
				pattern: new RegExp("export\\s+\\*\\s+from"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "es-modules:scriptContent:modern:24",
				kind: "scriptContent",
				pattern: new RegExp("export\\s+\\*\\s+as\\s+\\w+\\s+from"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "es-modules:scriptContent:modern:25",
				kind: "scriptContent",
				pattern: new RegExp("export{[^}]+}"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "es-modules:scriptContent:modern:26",
				kind: "scriptContent",
				pattern: new RegExp("export{[^}]+}from"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "es-modules:scriptContent:modern:27",
				kind: "scriptContent",
				pattern: new RegExp("export default"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "es-modules:scriptContent:modern:28",
				kind: "scriptContent",
				pattern: new RegExp("export\\*"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "es-modules:scriptContent:modern:29",
				kind: "scriptContent",
				pattern: new RegExp("Object\\.defineProperty\\s*\\(\\s*exports\\s*,\\s*['\"]__esModule['\"]\\s*,\\s*\\{\\s*value:\\s*true\\s*\\}\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
	{
		id: "umd",
		name: "UMD",
		website: "https://github.com/umdjs/umd",
		description: "Universal Module Definition (UMD) is a way to define modules that work in both CommonJS and AMD environments.",
		categories: [
			"module-format",
		],
		rules: [
			{
				id: "umd:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("typeof\\s+define\\s*===?\\s*[\"']function[\"']\\s*&&\\s*define\\.amd"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "umd:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("typeof\\s+exports\\s*===?\\s*[\"']object[\"']"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "umd:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("typeof\\s+module\\s*!==?\\s*[\"']undefined[\"']"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "umd:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("typeof\\s+root\\s*!==?\\s*[\"']undefined[\"']"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "umd:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("\\(\\s*function\\s*\\(\\s*(?:root,\\s*)?factory\\s*\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "umd:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("\\(\\s*function\\s*\\(\\s*global\\s*,\\s*factory\\s*\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "umd:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("function\\(\\w+,\\w+\\){"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "umd:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("\\btypeof exports\\b.*\\btypeof module\\b"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "umd:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("\\btypeof define\\b.*\\bdefine\\.amd\\b"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "umd:scriptContent:modern:9",
				kind: "scriptContent",
				pattern: new RegExp("define\\s*\\(\\s*[\"'][^\"']+[\"']\\s*,\\s*\\["),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "umd:scriptContent:modern:10",
				kind: "scriptContent",
				pattern: new RegExp("define\\s*\\(\\s*\\[[^\\]]*\\]\\s*,\\s*function"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "umd:scriptContent:modern:11",
				kind: "scriptContent",
				pattern: new RegExp("define\\s*\\(\\s*function\\s*\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "umd:scriptContent:modern:12",
				kind: "scriptContent",
				pattern: new RegExp("root\\[\\s*[\"'][^\"']+[\"']\\s*\\]\\s*="),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "umd:scriptContent:modern:13",
				kind: "scriptContent",
				pattern: new RegExp("this\\[\\s*[\"'][^\"']+[\"']\\s*\\]\\s*="),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "umd:scriptContent:modern:14",
				kind: "scriptContent",
				pattern: new RegExp("global\\[\\s*[\"'][^\"']+[\"']\\s*\\]\\s*="),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "umd:scriptContent:modern:15",
				kind: "scriptContent",
				pattern: new RegExp("module\\.exports\\s*=\\s*factory"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "umd:scriptContent:modern:16",
				kind: "scriptContent",
				pattern: new RegExp("exports\\s*=\\s*factory"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "umd:scriptContent:modern:17",
				kind: "scriptContent",
				pattern: new RegExp("define\\.amd\\s*="),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "umd:scriptContent:modern:18",
				kind: "scriptContent",
				pattern: new RegExp("factory\\s*\\(\\s*(?:root|global|this|window)\\s*\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "umd:scriptContent:modern:19",
				kind: "scriptContent",
				pattern: new RegExp("factory\\s*\\(\\s*(?:exports|module)?\\s*,\\s*(?:exports|module)?\\s*\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "umd:scriptContent:modern:20",
				kind: "scriptContent",
				pattern: new RegExp("\\[\\s*[\"']require[\"']\\s*,\\s*[\"']exports[\"']\\s*,\\s*[\"']module[\"']\\s*\\]"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "umd:scriptContent:modern:21",
				kind: "scriptContent",
				pattern: new RegExp("\\[\\s*[\"']exports[\"']\\s*,\\s*[\"']module[\"']\\s*\\]"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "umd:scriptContent:modern:22",
				kind: "scriptContent",
				pattern: new RegExp("factory\\(\\w+(?:,\\w+)*\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "umd:scriptContent:modern:23",
				kind: "scriptContent",
				pattern: new RegExp("\\[[\"']require[\"'],[\"']exports[\"']\\]"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
] as const satisfies readonly TechnologyDefinition[];
