import type { TechnologyDefinition } from '../types';

export const routerTechnologyDefinitions = [
	{
		id: "page-js",
		name: "Page.js",
		website: "https://github.com/visionmedia/page.js",
		description: "Page.js is a micro client-side router designed to handle client-side routing within web applications.",
		categories: [
			"router",
			"developer-tooling",
		],
		rules: [
			{
				id: "page-js:jsGlobal:0",
				kind: "jsGlobal",
				property: "page.Route",
				description: "Page-owned global matches a known technology marker.",
			},
		],
		metadata: {
			saas: false,
			oss: true,
		},
	},
	{
		id: "tanstack",
		name: "TanStack",
		website: "https://tanstack.com",
		description: "TanStack is a set of headless JavaScript libraries for building web application features such as data fetching, tables, routing, virtualization, and state management.",
		icon: "TanStack.svg",
		categories: [
			"router",
			"developer-tooling",
		],
		rules: [
			{
				id: "tanstack:scriptSrc:0",
				kind: "scriptSrc",
				pattern: new RegExp("\\/static\\/.*npm\\.tanstack.*\\.js"),
				description: "Script source URL matches a known technology marker.",
			},
			{
				id: "tanstack:scriptContent:1",
				kind: "scriptContent",
				pattern: new RegExp("(?:https?:)?\\/\\/(?:www\\.)?tanstack\\.com(?:\\/[^\"'>]*)?"),
				description: "Script content contains a bounded technology signature.",
			},
			{
				id: "tanstack:dom:2",
				kind: "dom",
				selector: "link[href*='@tanstack']",
				description: "DOM selector matches a known technology marker.",
			},
		],
		metadata: {
			saas: false,
			oss: true,
		},
	},
	{
		id: "umijs",
		name: "UmiJs",
		website: "https://umijs.org",
		description: "UmiJs is a scalable, enterprise-class frontend application framework that supports both configuration and conventional routing while maintaining functional completeness, such as dynamic routing, nested routing, and permission routing.",
		icon: "UmiJs.svg",
		categories: [
			"router",
			"ui-library",
			"framework",
		],
		rules: [
			{
				id: "umijs:scriptSrc:0",
				kind: "scriptSrc",
				pattern: new RegExp("\\/umi(\\.[\\w\\d]{8})?\\.js"),
				description: "Script source URL matches a known technology marker.",
			},
			{
				id: "umijs:jsGlobal:1",
				kind: "jsGlobal",
				property: "g_umi.version",
				valuePattern: new RegExp("([\\d\\.]+)"),
				version: {
					source: "match",
					group: 1,
				},
				description: "Page-owned global matches a known technology marker.",
			},
		],
		metadata: {
			saas: false,
			oss: true,
		},
		implies: [
			"node-js",
		],
	},
	{
		id: "angular-router",
		name: "Angular Router",
		website: "https://angular.io/guide/router",
		description: "Powerful JavaScript router built and maintained by the Angular team that allows developers to build single-page applications with multiple views and share data between views.",
		categories: [
			"router",
		],
		rules: [
			{
				id: "angular-router:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("InjectionToken\\([\"'](?:ROUTER_CONFIG|ROUTER_INITIALIZER|ROUTER_FORROOT_GUARD)[\"']\\)"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "angular-router:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("\\[Symbol\\.for\\([\"'](?:NgRouter|RouterState|RouteParams)[\"']\\)\\]"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "angular-router:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("__NG_ROUTER_[A-Z_]+__"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "angular-router:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("\\w+\\.ɵfac\\s*=\\s*function\\s*\\(t\\)\\s*\\{\\s*return\\s*new\\s*\\(t\\s*\\|\\|\\s*\\w+Router\\)"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "angular-router:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("\\w+\\.ɵprov\\s*=\\s*\\/\\*@__PURE__\\*\\/\\s*[ɵ\\w]+\\([\"']Router[\"']\\)"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "angular-router:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("ɵɵdefineInjectable\\(\\{factory:\\s*function\\s*\\w+Router_Factory"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "angular-router:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("ɵɵdefineNgModule\\(\\{.*?declarations:\\s*\\[RouterOutlet\\]"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "angular-router:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("routerNgProbeToken"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "angular-router:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("emptyRouterOutlet"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "angular-router:scriptContent:modern:9",
				kind: "scriptContent",
				pattern: new RegExp("router-outlet"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "angular-router:scriptContent:modern:10",
				kind: "scriptContent",
				pattern: new RegExp("registerNonRouterCurrentEntryChangeListener"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "angular-router:scriptContent:modern:11",
				kind: "scriptContent",
				pattern: new RegExp("\\.generateNgRouterState"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "angular-router:scriptContent:modern:12",
				kind: "scriptContent",
				pattern: new RegExp("\\.nonRouterCurrentEntryChangeSubscription"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "angular-router:scriptContent:modern:13",
				kind: "scriptContent",
				pattern: new RegExp("\\b[a-zA-Z_$][\\w$]*\\.\\$broadcast\\(\\s*[\"']\\$routeChangeStart[\"']\\s*,\\s*[a-zA-Z_$][\\w$]*\\s*,\\s*[a-zA-Z_$][\\w$]*\\s*\\)"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "angular-router:scriptContent:modern:14",
				kind: "scriptContent",
				pattern: new RegExp("\\b[a-zA-Z_$][\\w$]*\\.\\$broadcast\\(\\s*[\"']\\$routeChangeSuccess[\"']\\s*,\\s*[a-zA-Z_$][\\w$]*\\s*,\\s*[a-zA-Z_$][\\w$]*\\s*\\)"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "angular-router:scriptContent:modern:15",
				kind: "scriptContent",
				pattern: new RegExp("\\b[a-zA-Z_$][\\w$]*\\.\\$broadcast\\(\\s*[\"']\\$routeChangeError[\"']\\s*,\\s*[a-zA-Z_$][\\w$]*\\s*,\\s*[a-zA-Z_$][\\w$]*\\s*,\\s*[a-zA-Z_$][\\w$]*\\s*\\)"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "angular-router:scriptContent:modern:16",
				kind: "scriptContent",
				pattern: new RegExp("RouterModule\\.(?:forRoot|forChild)\\(\\s*(?:\\[|routes)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "angular-router:scriptContent:modern:17",
				kind: "scriptContent",
				pattern: new RegExp("provideRouter\\(\\s*withRouterConfig\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "angular-router:scriptContent:modern:18",
				kind: "scriptContent",
				pattern: new RegExp("withPreloading\\(\\s*(?:NoPreloading|PreloadAllModules)\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "angular-router:scriptContent:modern:19",
				kind: "scriptContent",
				pattern: new RegExp("withRouterConfig\\(\\{malformedUriErrorHandler:"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "angular-router:scriptContent:modern:20",
				kind: "scriptContent",
				pattern: new RegExp("NG_ROUTER_PROVIDERS"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "angular-router:scriptContent:modern:21",
				kind: "scriptContent",
				pattern: new RegExp("ROUTER_CONFIGURATION"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "angular-router:scriptContent:modern:22",
				kind: "scriptContent",
				pattern: new RegExp("ROUTER_FORROOT_GUARD"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "angular-router:scriptContent:modern:23",
				kind: "scriptContent",
				pattern: new RegExp("RouterOutlet\\.ngComponentOutlet"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "angular-router:scriptContent:modern:24",
				kind: "scriptContent",
				pattern: new RegExp("new\\s+NavigationCancelingError\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "angular-router:scriptContent:modern:25",
				kind: "scriptContent",
				pattern: new RegExp("EmptyOutletComponent"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
	{
		id: "ember-router",
		name: "Ember Router",
		website: "https://api.emberjs.com/ember/release/classes/emberrouter/",
		description: "Ember Router provides a declarative, component-based way to navigate between views in your Ember application.",
		categories: [
			"router",
		],
		rules: [
			{
				id: "ember-router:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("@ember\\/routing\\/[a-zA-Z-]+"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "ember-router:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("\\._routerMicrolib\\.activeTransition"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "ember-router:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("\\._routerMicrolib\\.recognize"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "ember-router:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("['\"]TransitionAborted['\"].*activeTransition"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
	{
		id: "next-js-router",
		name: "Next.js Router",
		website: "https://nextjs.org/docs/routing/introduction",
		description: "Next.js has a file-system based router built on the concept of pages.",
		categories: [
			"router",
		],
		rules: [
			{
				id: "next-js-router:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("\\.isNextRouterError\\)\\("),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "next-js-router:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("\\[[\\w.]*NEXT_ROUTER_STATE_TREE_HEADER"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "next-js-router:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("GlobalLayoutRouterContext"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "next-js-router:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("extractPathFromFlightRouterState"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "next-js-router:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("useDynamicRouteParams\\)\\([\"']useParams\\(\\)[\"']"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "next-js-router:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("Object\\.defineProperty\\(Error\\([\"']invariant global layout router not mounted[\"']\\),\\s*[\"']__NEXT_ERROR_CODE[\"']"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "next-js-router:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("Object\\.defineProperty\\([^,]+,\\s*[\"']createInitialRouterState[\"']"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "next-js-router:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("[\"'](?:next\\/(?:navigation|router|link|dist\\/client\\/router)|n\\/r)[\"']"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "next-js-router:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("__NEXT_(?:DATA|P|C|HAS_REWRITE|ROUTER|HISTORY|OPTIMISTIC)__"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "next-js-router:scriptContent:modern:9",
				kind: "scriptContent",
				pattern: new RegExp("AppRouterContext"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "next-js-router:scriptContent:modern:10",
				kind: "scriptContent",
				pattern: new RegExp("[A-Za-z]\\.__N(?:=|ext)|__N_SSG|__N_SSP"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "next-js-router:scriptContent:modern:11",
				kind: "scriptContent",
				pattern: new RegExp("window\\.__N(?:_STATE|EXT_P|_CROSS)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "next-js-router:scriptContent:modern:12",
				kind: "scriptContent",
				pattern: new RegExp("err\\.digest.*NEXT_NOT_FOUND"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "next-js-router:scriptContent:modern:13",
				kind: "scriptContent",
				pattern: new RegExp("NEXT_REDIRECT.*permanent"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
	{
		id: "qwik-router",
		name: "Qwik Router",
		website: "https://qwik.dev/docs/routing/",
		description: "Qwik has a file-system based router built on the concept of pages.",
		categories: [
			"router",
		],
		rules: [
			{
				id: "qwik-router:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("q:container=\"[\\w-]+\""),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "qwik-router:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("q:version=\"[\\w.-]+\""),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "qwik-router:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("q:base=\"[\\w-]+\""),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "qwik-router:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("q:slot=\"[\\w-]+\""),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "qwik-router:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("on:qvisible="),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "qwik-router:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("preventdefault:submit"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "qwik-router:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("q:key=\"[\\w-]+\""),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "qwik-router:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("bindge:click="),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "qwik-router:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("\\[Symbol\\.for\\(\"qk-city\"\\)\\]"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "qwik-router:scriptContent:modern:9",
				kind: "scriptContent",
				pattern: new RegExp("QwikCityMockProvider\\$_"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "qwik-router:scriptContent:modern:10",
				kind: "scriptContent",
				pattern: new RegExp("QwikCityProvider\\$_"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "qwik-router:scriptContent:modern:11",
				kind: "scriptContent",
				pattern: new RegExp("RouterOutlet\\$_"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "qwik-router:scriptContent:modern:12",
				kind: "scriptContent",
				pattern: new RegExp("\\$\\w+\\$_use[A-Z]\\w+__\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "qwik-router:scriptContent:modern:13",
				kind: "scriptContent",
				pattern: new RegExp("_\\$use[A-Z]\\w+\\$_\\([^)]*\\)\\[Q-\\w+\\]"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "qwik-router:scriptContent:modern:14",
				kind: "scriptContent",
				pattern: new RegExp("\\$\\w+\\$_use\\w+\\$_\\[Symbol\\.for\\(\"qHook\"\\)\\]"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "qwik-router:scriptContent:modern:15",
				kind: "scriptContent",
				pattern: new RegExp("qrl\\((?:[\"']\\w+_\\w+[\"'],\\s*)?[\"']\\$\\w+\\$_use\\w+\\$_[\"']\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "qwik-router:scriptContent:modern:16",
				kind: "scriptContent",
				pattern: new RegExp("endQwikCity\\$"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "qwik-router:scriptContent:modern:17",
				kind: "scriptContent",
				pattern: new RegExp("qwikCity\\.json"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "qwik-router:scriptContent:modern:18",
				kind: "scriptContent",
				pattern: new RegExp("qwikSerializer\\$"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "qwik-router:scriptContent:modern:19",
				kind: "scriptContent",
				pattern: new RegExp("qwikBrowser\\$"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "qwik-router:scriptContent:modern:20",
				kind: "scriptContent",
				pattern: new RegExp("new QwikCityPageError\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "qwik-router:scriptContent:modern:21",
				kind: "scriptContent",
				pattern: new RegExp("new QwikError\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "qwik-router:scriptContent:modern:22",
				kind: "scriptContent",
				pattern: new RegExp("getErrorHtml\\$"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "qwik-router:scriptContent:modern:23",
				kind: "scriptContent",
				pattern: new RegExp("qwikLoadPage\\$"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "qwik-router:scriptContent:modern:24",
				kind: "scriptContent",
				pattern: new RegExp("QWIK_VERSION"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "qwik-router:scriptContent:modern:25",
				kind: "scriptContent",
				pattern: new RegExp("QWIK_BUILD"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "qwik-router:scriptContent:modern:26",
				kind: "scriptContent",
				pattern: new RegExp("QWIK_DEVTOOLS"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "qwik-router:scriptContent:modern:27",
				kind: "scriptContent",
				pattern: new RegExp("QWIK_MODULES"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "qwik-router:resourceUrl:modern:28",
				kind: "resourceUrl",
				pattern: new RegExp("qwik-city-plan\\.js$", "i"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "qwik-router:resourceUrl:modern:29",
				kind: "resourceUrl",
				pattern: new RegExp("qwik-city-middleware\\.js$", "i"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "qwik-router:resourceUrl:modern:30",
				kind: "resourceUrl",
				pattern: new RegExp("qwik-city-static\\.js$", "i"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "qwik-router:resourceUrl:modern:31",
				kind: "resourceUrl",
				pattern: new RegExp("qwik-city-not-found\\.js$", "i"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "qwik-router:resourceUrl:modern:32",
				kind: "resourceUrl",
				pattern: new RegExp("entry\\.qwik\\.[a-f0-9]+\\.js$", "i"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "qwik-router:resourceUrl:modern:33",
				kind: "resourceUrl",
				pattern: new RegExp("q-[\\w-]+\\.qwik\\.js$", "i"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "qwik-router:resourceUrl:modern:34",
				kind: "resourceUrl",
				pattern: new RegExp("qwik\\.[\\w-]+\\.js$", "i"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "qwik-router:resourceUrl:modern:35",
				kind: "resourceUrl",
				pattern: new RegExp("qkc\\.[\\w-]+\\.js$", "i"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
		],
	},
	{
		id: "react-router",
		name: "React Router",
		website: "https://reactrouter.com/",
		description: "Declarative routing for React applications that allows developers to build single-page applications with multiple views and share data between views.",
		categories: [
			"router",
		],
		rules: [
			{
				id: "react-router:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("\"remix-router-transitions\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "react-router:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("\"react-router-scroll-positions\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "react-router:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("@remix-run\\/router error"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "react-router:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("createHashRouter.*manually changes the URL"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "react-router:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("blocker on a POP navigation"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "react-router:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("router only supports one blocker at a time"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "react-router:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("💿 Hey developer 👋.*Check out https:\\/\\/remix\\.run\\/guides\\/errors"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "react-router:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("(?:from\\s+[\"']|\\b)react-router(?:\\/dom)?[\"']"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "react-router:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("\\.hasOwnProperty\\(\"remix-router-transitions\"\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "react-router:scriptContent:modern:9",
				kind: "scriptContent",
				pattern: new RegExp("\\[\"react-router-scroll-positions\"\\]"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "react-router:scriptContent:modern:10",
				kind: "scriptContent",
				pattern: new RegExp("@remix-run\\/router.*silently in production"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "react-router:scriptContent:modern:11",
				kind: "scriptContent",
				pattern: new RegExp("([a-zA-Z0-9_$]+)\\._pendingLocation\\s*&&\\s*\\1\\.setState\\(\\s*\\{\\s*location:\\s*\\1\\._pendingLocation"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "react-router:scriptContent:modern:12",
				kind: "scriptContent",
				pattern: new RegExp("([a-zA-Z0-9_$]+)\\.props\\.(?:staticContext|[a-zA-Z0-9_$]+)\\s*\\|\\|\\s*\\(\\1\\.(?:unlisten|[a-zA-Z0-9_$]+)\\s*=\\s*\\1\\.props\\.history\\.listen\\(function\\(([a-zA-Z0-9_$]+)\\)\\s*\\{\\s*([a-zA-Z0-9_$]+)\\._isMounted\\s*&&\\s*\\3\\.setState\\(\\s*\\{\\s*location:\\s*\\2"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "react-router:scriptContent:modern:13",
				kind: "scriptContent",
				pattern: new RegExp("match:\\s*([a-zA-Z0-9_$]+)\\.computeRootMatch\\(([a-zA-Z0-9_$]+)\\.state\\.location\\.pathname\\)"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "react-router:scriptContent:modern:14",
				kind: "scriptContent",
				pattern: new RegExp("(?:create|use)[BHM]?\\w*Router\\s*\\(\\s*\\["),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "react-router:scriptContent:modern:15",
				kind: "scriptContent",
				pattern: new RegExp("RouterProvider\\s*\\{\\s*router:"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "react-router:scriptContent:modern:16",
				kind: "scriptContent",
				pattern: new RegExp("\\[UNSAFE_NavigationContext\\]"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "react-router:scriptContent:modern:17",
				kind: "scriptContent",
				pattern: new RegExp("\\[DataRouterContext\\]"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "react-router:scriptContent:modern:18",
				kind: "scriptContent",
				pattern: new RegExp("\\[DataRouterStateContext\\]"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
	{
		id: "remix-router",
		name: "Remix Router",
		website: "https://remix.run/docs/en/main/guides/accessibility#routing",
		description: "Remix has a file-system based router built on the concept of pages.",
		categories: [
			"router",
		],
		rules: [
			{
				id: "remix-router:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("[\"']@remix-run\\/router[\"']"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "remix-router:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("[\"']@remix-run\\/router\\/history[\"']"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "remix-router:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("[\"']@remix-run\\/router\\/data[\"']"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "remix-router:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("__remixRouter"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "remix-router:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("__remixManifest"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "remix-router:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("__remixContext"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "remix-router:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("__remixRouteModules"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "remix-router:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("\\[Symbol\\.for\\([\"']remix-router-state[\"']\\)\\]"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "remix-router:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("createPath\\(\\{pathname:"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "remix-router:scriptContent:modern:9",
				kind: "scriptContent",
				pattern: new RegExp("getStateKeyForLocation\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "remix-router:scriptContent:modern:10",
				kind: "scriptContent",
				pattern: new RegExp("createClientSideRemixRouter\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "remix-router:scriptContent:modern:11",
				kind: "scriptContent",
				pattern: new RegExp("createRemixStub\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "remix-router:scriptContent:modern:12",
				kind: "scriptContent",
				pattern: new RegExp("createActionData\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "remix-router:scriptContent:modern:13",
				kind: "scriptContent",
				pattern: new RegExp("createLoaderData\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "remix-router:scriptContent:modern:14",
				kind: "scriptContent",
				pattern: new RegExp("createRouteData\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "remix-router:scriptContent:modern:15",
				kind: "scriptContent",
				pattern: new RegExp("createTransitionManager\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "remix-router:scriptContent:modern:16",
				kind: "scriptContent",
				pattern: new RegExp("createClientRoute\\(\\{id:"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "remix-router:scriptContent:modern:17",
				kind: "scriptContent",
				pattern: new RegExp("createClientResolver\\(\\{routes:"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "remix-router:scriptContent:modern:18",
				kind: "scriptContent",
				pattern: new RegExp("UNSAFE_DEFERRED_SYMBOL"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "remix-router:scriptContent:modern:19",
				kind: "scriptContent",
				pattern: new RegExp("UNSAFE_ERROR_BOUNDARY_SYMBOL"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "remix-router:scriptContent:modern:20",
				kind: "scriptContent",
				pattern: new RegExp("getLoadingNavigation\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "remix-router:scriptContent:modern:21",
				kind: "scriptContent",
				pattern: new RegExp("getSubmissionNavigation\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "remix-router:scriptContent:modern:22",
				kind: "scriptContent",
				pattern: new RegExp("getRedirectNavigation\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "remix-router:scriptContent:modern:23",
				kind: "scriptContent",
				pattern: new RegExp("createTransitionRedirect\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "remix-router:scriptContent:modern:24",
				kind: "scriptContent",
				pattern: new RegExp("ErrorResponseImpl\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "remix-router:scriptContent:modern:25",
				kind: "scriptContent",
				pattern: new RegExp("isRouteErrorResponse\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "remix-router:scriptContent:modern:26",
				kind: "scriptContent",
				pattern: new RegExp("createClientError\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "remix-router:scriptContent:modern:27",
				kind: "scriptContent",
				pattern: new RegExp("getInternalRouterError\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "remix-router:scriptContent:modern:28",
				kind: "scriptContent",
				pattern: new RegExp("createClientSideRoute\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "remix-router:scriptContent:modern:29",
				kind: "scriptContent",
				pattern: new RegExp("createClientRouteLoader\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "remix-router:scriptContent:modern:30",
				kind: "scriptContent",
				pattern: new RegExp("createClientLoaderFunction\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "remix-router:scriptContent:modern:31",
				kind: "scriptContent",
				pattern: new RegExp("createDeferredReadable\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "remix-router:resourceUrl:modern:32",
				kind: "resourceUrl",
				pattern: new RegExp("@remix-run[\\\\/]router[\\\\/]dist[\\\\/]router\\.js$"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "remix-router:resourceUrl:modern:33",
				kind: "resourceUrl",
				pattern: new RegExp("@remix-run[\\\\/]router[\\\\/]dist[\\\\/]data\\.js$"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "remix-router:resourceUrl:modern:34",
				kind: "resourceUrl",
				pattern: new RegExp("@remix-run[\\\\/]router[\\\\/]dist[\\\\/]history\\.js$"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "remix-router:resourceUrl:modern:35",
				kind: "resourceUrl",
				pattern: new RegExp("remix-router-[a-f0-9]+\\.js$", "i"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "remix-router:resourceUrl:modern:36",
				kind: "resourceUrl",
				pattern: new RegExp("remix-client-[a-f0-9]+\\.js$", "i"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "remix-router:resourceUrl:modern:37",
				kind: "resourceUrl",
				pattern: new RegExp("remix-routes-[a-f0-9]+\\.js$", "i"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "remix-router:resourceUrl:modern:38",
				kind: "resourceUrl",
				pattern: new RegExp("remix-route-loader\\.[a-f0-9]+\\.js$", "i"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "remix-router:resourceUrl:modern:39",
				kind: "resourceUrl",
				pattern: new RegExp("remix-action-handler\\.[a-f0-9]+\\.js$", "i"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "remix-router:resourceUrl:modern:40",
				kind: "resourceUrl",
				pattern: new RegExp("remix-transition-manager\\.[a-f0-9]+\\.js$", "i"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
		],
	},
	{
		id: "solid-router",
		name: "Solid Router",
		website: "https://solidjs.com/docs/latest/concepts/router",
		description: "Solid has a file-system based router built on the concept of pages.",
		categories: [
			"router",
		],
		rules: [
			{
				id: "solid-router:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("[\"']@solidjs\\/router(?:\\/dist\\/|\\/)?[^\"']*[\"']"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "solid-router:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("\\$?\\w+\\.__propertyCheck"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "solid-router:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("\\$?\\w+\\.__intercepted"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "solid-router:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("\\$?\\w+\\.__propertyCache"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "solid-router:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("\\[Symbol\\.for\\([\"']solid-router-context[\"']\\)\\]"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "solid-router:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("\\[Symbol\\.for\\([\"']solid-root[\"']\\)\\]"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "solid-router:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("\\[Symbol\\.for\\([\"']solid-track[\"']\\)\\]"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "solid-router:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("\\[Symbol\\.for\\([\"']solid-dev[\"']\\)\\]"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "solid-router:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("\"undefined\"!=typeof window&&window\\.\\$PROXY"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "solid-router:scriptContent:modern:9",
				kind: "scriptContent",
				pattern: new RegExp("DEV_EXPRESSION"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "solid-router:scriptContent:modern:10",
				kind: "scriptContent",
				pattern: new RegExp("DEVCOMP"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "solid-router:scriptContent:modern:11",
				kind: "scriptContent",
				pattern: new RegExp("\\w+\\.__propertyCheck&&\\w+\\.__propertyCheck\\([^)]+\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "solid-router:scriptContent:modern:12",
				kind: "scriptContent",
				pattern: new RegExp("WeakMap\\.prototype\\.get\\.call\\(\\w+\\.__propertyCache"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "solid-router:scriptContent:modern:13",
				kind: "scriptContent",
				pattern: new RegExp("\\w+\\.__interceptor\\(\\w+,\\w+\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "solid-router:scriptContent:modern:14",
				kind: "scriptContent",
				pattern: new RegExp("createResource\\(\\{source:"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "solid-router:scriptContent:modern:15",
				kind: "scriptContent",
				pattern: new RegExp("createMemo\\(\\{equals:!1\\}"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "solid-router:scriptContent:modern:16",
				kind: "scriptContent",
				pattern: new RegExp("getOwner\\(\\)\\.owner"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "solid-router:scriptContent:modern:17",
				kind: "scriptContent",
				pattern: new RegExp("throw new Error\\(\"@solidjs\\/router: "),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "solid-router:scriptContent:modern:18",
				kind: "scriptContent",
				pattern: new RegExp("SolidRouteError\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "solid-router:scriptContent:modern:19",
				kind: "scriptContent",
				pattern: new RegExp("handleRouterError\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "solid-router:resourceUrl:modern:20",
				kind: "resourceUrl",
				pattern: new RegExp("@solidjs[\\\\/]router[\\\\/]dist[\\\\/][^/]+\\.(?:cjs|mjs|js)$"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "solid-router:resourceUrl:modern:21",
				kind: "resourceUrl",
				pattern: new RegExp("solid-router\\.[\\w-]+\\.js$", "i"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "solid-router:resourceUrl:modern:22",
				kind: "resourceUrl",
				pattern: new RegExp("router\\.[\\w-]+\\.solidjs\\.js$", "i"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "solid-router:resourceUrl:modern:23",
				kind: "resourceUrl",
				pattern: new RegExp("solid\\.[\\w-]+\\.proxy\\.js$", "i"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "solid-router:resourceUrl:modern:24",
				kind: "resourceUrl",
				pattern: new RegExp("proxy\\.[\\w-]+\\.solid\\.js$", "i"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
			{
				id: "solid-router:resourceUrl:modern:25",
				kind: "resourceUrl",
				pattern: new RegExp("router\\.[\\w-]+\\.solid\\.js$", "i"),
				confidence: 45,
				description: "Resource filename or URL matches a modern tooling marker.",
			},
		],
	},
	{
		id: "svelte-router",
		name: "Svelte Router",
		website: "https://svelte.dev/docs#svelte_router",
		description: "A declarative Svelte router with a small footprint.",
		categories: [
			"router",
		],
		rules: [
			{
				id: "svelte-router:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("[a-zA-Z0-9_$]+\\s*=\\s*[\"']sveltekit:navigation[\"']"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "svelte-router:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("a\\s+load\\s+function\\s+related\\s+to\\s+route\\s+['\"`]\\$\\{[\\w.]+\\}['\"`]\\s+returned"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "svelte-router:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("history\\.(?:pushState|replaceState).*?conflict with SvelteKit['\"]s router"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "svelte-router:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("__SVELTEKIT_CLIENT_ROUTING__"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "svelte-router:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("throw\\s+new\\s+Error\\([^)]*Page\\s+options\\s+are\\s+ignored\\s+when[^)]*router\\.type\\s+===\\s+['\"]hash['\"][^)]*\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "svelte-router:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("\\.reject\\(new Error\\(\"navigation cancelled\"\\)\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "svelte-router:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("\\.reject\\(new Error\\(\"navigation aborted\"\\)\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "svelte-router:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("[\"']@sveltejs\\/kit(?:\\/navigation|\\/routing|\\/runtime\\/client)[\"']"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "svelte-router:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("[\"']sveltejs\\/kit(?:\\/package\\.json|\\/client\\.js)[\"']"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "svelte-router:scriptContent:modern:9",
				kind: "scriptContent",
				pattern: new RegExp("\\[Symbol\\.for\\([\"']sveltekit-routing[\"']\\)\\]"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "svelte-router:scriptContent:modern:10",
				kind: "scriptContent",
				pattern: new RegExp("load\\s*\\(\\s*\\{\\s*(?:params|url|route|depends)\\s*\\}"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "svelte-router:scriptContent:modern:11",
				kind: "scriptContent",
				pattern: new RegExp("handle\\s*\\(\\s*\\{\\s*event\\s*,\\s*resolve\\s*\\}\\s*\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "svelte-router:scriptContent:modern:12",
				kind: "scriptContent",
				pattern: new RegExp("handleError\\s*\\(\\s*\\{\\s*error\\s*,\\s*event\\s*\\}\\s*\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "svelte-router:scriptContent:modern:13",
				kind: "scriptContent",
				pattern: new RegExp("setupLoadContext\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "svelte-router:scriptContent:modern:14",
				kind: "scriptContent",
				pattern: new RegExp("goto\\(\\s*(?:url|delta):"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "svelte-router:scriptContent:modern:15",
				kind: "scriptContent",
				pattern: new RegExp("pushState\\(\\s*\\{\\s*[^}]*sveltekit:"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "svelte-router:scriptContent:modern:16",
				kind: "scriptContent",
				pattern: new RegExp("invalidateAll\\(\\s*\\{\\s*soft:\\s*true\\s*\\}\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "svelte-router:scriptContent:modern:17",
				kind: "scriptContent",
				pattern: new RegExp("preloadData\\(\\s*\\{\\s*type:\\s*[\"']link[\"']"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "svelte-router:scriptContent:modern:18",
				kind: "scriptContent",
				pattern: new RegExp("handleMissingId\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "svelte-router:scriptContent:modern:19",
				kind: "scriptContent",
				pattern: new RegExp("handleDataError\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "svelte-router:scriptContent:modern:20",
				kind: "scriptContent",
				pattern: new RegExp("redirect\\((?:\\d{3}|\\w+\\.status)\\s*,\\s*(?:url|location):"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
	{
		id: "tanstack-router",
		name: "TanStack Router",
		website: "https://tanstack.com/router",
		description: "Tanstack has a file-system based router built on the concept of pages.",
		categories: [
			"router",
		],
		rules: [
			{
				id: "tanstack-router:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("[\"']@t(?:anstack)?[/\\\\-]router(?:-(?:core|devtools))?[\"']"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "tanstack-router:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("__TANSTACK_ROUTER_(?:STATE|HISTORY|DEVTOOLS)__"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "tanstack-router:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("\\$TSR_ROUTER\\$"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "tanstack-router:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("\\$TS_ROUTER\\$"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "tanstack-router:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("routeMasks.*find.*No.*basepath.*pathname.*caseSensitive:"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "tanstack-router:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("notFoundRoute.*tanstack\\.com\\/router\\/v1\\/docs\\/framework\\/react\\/guide\\/not-found-errors"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "tanstack-router:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("createFileRoute\\s*\\(\\s*['\"][/\\w]+['\"]\\s*,?\\s*\\{"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "tanstack-router:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("createLazyFileRoute\\s*\\(\\s*['\"][/\\w]+['\"]\\s*,?\\s*\\{"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
	{
		id: "vitepress-router",
		name: "VitePress Router",
		website: "https://vitepress.dev/guide/routing",
		description: "VitePress has a file-system based router built on the concept of pages.",
		categories: [
			"router",
		],
		rules: [
			{
				id: "vitepress-router:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("\\.md\\.js\"\\},\"(\\w+)\":{\"importName"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "vitepress-router:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("\\.replace\\(\\/(?:\\(\\^|\\\\\\/)index(?:\\.html\\)\\$|\\\\\\/)\\/,\\s*[\"']\\$1[\"']\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
	{
		id: "vue-router",
		name: "Vue Router",
		website: "https://router.vuejs.org/",
		description: "The official router for Vue.js. It deeply integrates with Vue.js core.",
		categories: [
			"router",
		],
		rules: [
			{
				id: "vue-router:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("\\{name:[\"']RouterLink[\"']"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "vue-router:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("\\{name:[\"']RouterView[\"']"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "vue-router:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("component\\([\"']RouterLink[\"'],[^)]+\\).*component\\([\"']RouterView[\"']"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "vue-router:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("\\{path:[^}]+component:[^}]+name:"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "vue-router:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("\\{currentRoute:[^}]+resolve:[^}]+beforeEach:"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "vue-router:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("beforeRouteLeave[^}]+beforeRouteEnter"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "vue-router:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("createWebHistory|createWebHashHistory|createMemoryHistory"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "vue-router:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("[\"']vue-router[\"']"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "vue-router:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("[\"']@vue\\/router[\"']"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "vue-router:scriptContent:modern:9",
				kind: "scriptContent",
				pattern: new RegExp("__VUE_ROUTER__"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "vue-router:scriptContent:modern:10",
				kind: "scriptContent",
				pattern: new RegExp("__VUE_ROUTER_BASE__"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "vue-router:scriptContent:modern:11",
				kind: "scriptContent",
				pattern: new RegExp("defineComponent\\(\\{name:[\"']RouterView[\"']"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "vue-router:scriptContent:modern:12",
				kind: "scriptContent",
				pattern: new RegExp("defineComponent\\(\\{name:[\"']RouterLink[\"']"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "vue-router:scriptContent:modern:13",
				kind: "scriptContent",
				pattern: new RegExp("\\{name:[\"']router-link[\"']"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "vue-router:scriptContent:modern:14",
				kind: "scriptContent",
				pattern: new RegExp("\\{name:[\"']router-view[\"']"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "vue-router:scriptContent:modern:15",
				kind: "scriptContent",
				pattern: new RegExp("\\[routerViewLocationKey\\]"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "vue-router:scriptContent:modern:16",
				kind: "scriptContent",
				pattern: new RegExp("\\{beforeEnter:[^}]+meta:"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "vue-router:scriptContent:modern:17",
				kind: "scriptContent",
				pattern: new RegExp("\\{path:[^}]+component:[^}]+children:"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "vue-router:scriptContent:modern:18",
				kind: "scriptContent",
				pattern: new RegExp("\\{name:[^}]+path:[^}]+component:"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "vue-router:scriptContent:modern:19",
				kind: "scriptContent",
				pattern: new RegExp("globalProperties\\.\\$router"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "vue-router:scriptContent:modern:20",
				kind: "scriptContent",
				pattern: new RegExp("globalProperties\\.\\$route"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "vue-router:scriptContent:modern:21",
				kind: "scriptContent",
				pattern: new RegExp("matched\\.length[^}]+params[^}]+query[^}]+hash"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
	{
		id: "vuepress-router",
		name: "VuePress Router",
		website: "https://vuepress.vuejs.org/guide/page.html#routing",
		description: "VuePress has a file-system based router built on the concept of pages.",
		categories: [
			"router",
		],
		rules: [
			{
				id: "vuepress-router:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("@vuepress\\/(?:core|theme-default)"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "vuepress-router:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("__VUEPRESS_ROUTER_BASE__"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "vuepress-router:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("\\[vuepress\\] No matching page found for sidebar item"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "vuepress-router:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("\\[\\s*vuepress\\s*\\]\\s*page\\s*not\\s*found:"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "vuepress-router:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("\\.hasOwnProperty\\(\"internal_routes\"\\)"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "vuepress-router:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("RouterLink\\s*name=[\"'](?:vuepress)-"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "vuepress-router:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("resolveMatchingRoute|resolvePageComponent"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "vuepress-router:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("@vuepress\\/markdown|markdown-it"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "vuepress-router:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("resolveThemeLayout|resolveLayoutComponent"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
] as const satisfies readonly TechnologyDefinition[];
