import type { TechnologyDefinition } from '../types';

export const stateManagementTechnologyDefinitions = [
	{
		id: "mobx",
		name: "MobX",
		website: "https://mobx.js.org",
		description: "Simple, scalable state management.",
		icon: "MobX.svg",
		categories: [
			"state-management",
			"widgets-misc",
		],
		rules: [
			{
				id: "mobx:scriptSrc:0",
				kind: "scriptSrc",
				pattern: new RegExp("(?:\\/([\\d\\.]+))?\\/mobx(?:\\.[a-z]+){0,2}\\.js(?:$|\\?)"),
				version: {
					source: "match",
					group: 1,
				},
				description: "Script source URL matches a known technology marker.",
			},
			{
				id: "mobx:jsGlobal:1",
				kind: "jsGlobal",
				property: "__mobxGlobal",
				description: "Page-owned global matches a known technology marker.",
			},
			{
				id: "mobx:jsGlobal:2",
				kind: "jsGlobal",
				property: "__mobxGlobals",
				description: "Page-owned global matches a known technology marker.",
			},
			{
				id: "mobx:jsGlobal:3",
				kind: "jsGlobal",
				property: "__mobxInstanceCount",
				description: "Page-owned global matches a known technology marker.",
			},
			{
				id: "mobx:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("Symbol\\.for\\([\"']mobx-stored-annotations[\"']\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "mobx:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("\"Since strict-mode is enabled, changing observed observable values outside actions is not allowed\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "mobx:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("\"[ComputedValue] It is not allowed to create or access other observables or computeds while computing a computed value\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "mobx:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("Symbol\\([\"']mobx administration[\"']\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "mobx:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("mobx stored-annotations"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "mobx:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("\\.__mobxInstanceCount"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "mobx:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("\\.__mobxGlobals"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "mobx:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("mobxGuid"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "mobx:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("\\[MobX\\] minified error nr:"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "mobx:scriptContent:modern:9",
				kind: "scriptContent",
				pattern: new RegExp("https:\\/\\/github\\.com\\/mobxjs\\/mobx\\/blob\\/main\\/packages\\/mobx\\/src\\/errors\\.ts"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "mobx:scriptContent:modern:10",
				kind: "scriptContent",
				pattern: new RegExp("\\.isMobxAction\\s*=\\s*true"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "mobx:scriptContent:modern:11",
				kind: "scriptContent",
				pattern: new RegExp("\\.isMobXFlow\\s*=\\s*true"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "mobx:scriptContent:modern:12",
				kind: "scriptContent",
				pattern: new RegExp("\\{allowStateChanges:\\s*false,\\s*allowStateReads:\\s*true\\}"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "mobx:scriptContent:modern:13",
				kind: "scriptContent",
				pattern: new RegExp("enforceActions:\\s*true"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "mobx:scriptContent:modern:14",
				kind: "scriptContent",
				pattern: new RegExp("\\[\"?__mobxDecorators\"?\\]"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "mobx:scriptContent:modern:15",
				kind: "scriptContent",
				pattern: new RegExp("\\[\"?__mobxInstanceAdmin\"?\\]"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "mobx:scriptContent:modern:16",
				kind: "scriptContent",
				pattern: new RegExp("\\[\"?__mobxDidRunLazyInitializers\"?\\]"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "mobx:scriptContent:modern:17",
				kind: "scriptContent",
				pattern: new RegExp("\"Since strict-mode is enabled, changing (observed )?observable values outside actions is not allowed\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "mobx:scriptContent:modern:18",
				kind: "scriptContent",
				pattern: new RegExp("\"[mobx] Since strict-mode is enabled, changing observed observable values outside actions is not allowed\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
	{
		id: "pinia",
		name: "Pinia",
		website: "https://pinia.vuejs.org",
		description: "Pinia is a state management library for Vue.js.",
		icon: "Pinia.svg",
		categories: [
			"state-management",
			"widgets-misc",
		],
		rules: [
			{
				id: "pinia:scriptSrc:0",
				kind: "scriptSrc",
				pattern: new RegExp("\\/pinia\\/.+\\.js"),
				description: "Script source URL matches a known technology marker.",
			},
			{
				id: "pinia:html:1",
				kind: "html",
				pattern: new RegExp("\\bpinia\\b", "i"),
				confidence: 80,
				description: "Document HTML contains a Pinia package/runtime marker.",
			},
			{
				id: "pinia:text:2",
				kind: "text",
				pattern: new RegExp("\"pinia\""),
				description: "Page text contains a known technology marker.",
			},
			{
				id: "pinia:jsGlobal:3",
				kind: "jsGlobal",
				property: "Pinia.createPinia",
				description: "Page-owned global matches a known technology marker.",
			},
			{
				id: "pinia:jsGlobal:4",
				kind: "jsGlobal",
				property: "__NUXT__.pinia",
				description: "Page-owned global matches a known technology marker.",
			},
			{
				id: "pinia:jsGlobal:5",
				kind: "jsGlobal",
				property: "mount_pinia",
				description: "Page-owned global matches a known technology marker.",
			},
			{
				id: "pinia:jsGlobal:6",
				kind: "jsGlobal",
				property: "pinia.state",
				description: "Page-owned global matches a known technology marker.",
			},
			{
				id: "pinia:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("Symbol\\([\"']pinia[\"']\\)"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "pinia:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("\"🍍 Pinia \\(root\\)\""),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "pinia:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("\"🍍 \""),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "pinia:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("const\\s+\\w+\\s*=\\s*Symbol\\(\\s*(?:'pinia'|\"pinia\")\\s*\\)"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "pinia:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("\\w+\\.config\\.globalProperties\\.\\$pinia\\s*=\\s*\\w+"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "pinia:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("\\/\\*!\\s*\\n\\s*\\*\\s*pinia\\s+v\\d+\\.\\d+\\.\\d+"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "pinia:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("\"\\[Pinia\\]: skipping hmr because store doesn't exist yet\""),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "pinia:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("\"pinia:mutations\""),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "pinia:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("MutationType\\.direct"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "pinia:scriptContent:modern:9",
				kind: "scriptContent",
				pattern: new RegExp("MutationType\\.patchFunction"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "pinia:scriptContent:modern:10",
				kind: "scriptContent",
				pattern: new RegExp("MutationType\\.patchObject"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "pinia:scriptContent:modern:11",
				kind: "scriptContent",
				pattern: new RegExp("\"https:\\/\\/pinia\\.vuejs\\.org\\/logo\\.svg\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "pinia:scriptContent:modern:12",
				kind: "scriptContent",
				pattern: new RegExp("\"__PINIA__\""),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "pinia:scriptContent:modern:13",
				kind: "scriptContent",
				pattern: new RegExp("\"__PINIA_DEVTOOLS_GLOBAL_HOOK__\""),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
		metadata: {
			oss: true,
		},
		requires: [
			"vue-js",
		],
	},
	{
		id: "redux",
		name: "Redux",
		website: "https://redux.js.org",
		description: "Redux is a predictable state container for JavaScript applications.",
		icon: "Redux.svg",
		categories: [
			"state-management",
			"ui-library",
		],
		rules: [
			{
				id: "redux:scriptSrc:0",
				kind: "scriptSrc",
				pattern: new RegExp("\\/redux(@|\\/)([\\d.]+)(?:\\/[a-z]+)?\\/redux(?:.min)?\\.js"),
				version: {
					source: "match",
					group: 2,
				},
				description: "Script source URL matches a known technology marker.",
			},
			{
				id: "redux:dom:1",
				kind: "dom",
				selector: "link[href*='//redux.js.org']",
				description: "DOM selector matches a known technology marker.",
			},
			{
				id: "redux:jsGlobal:2",
				kind: "jsGlobal",
				property: "ReactRedux",
				description: "Page-owned global matches a known technology marker.",
			},
			{
				id: "redux:jsGlobal:3",
				kind: "jsGlobal",
				property: "Redux.applyMiddleware",
				description: "Page-owned global matches a known technology marker.",
			},
			{
				id: "redux:jsGlobal:4",
				kind: "jsGlobal",
				property: "__REDUX_DEVTOOLS_EXTENSION__",
				description: "Page-owned global matches a known technology marker.",
			},
			{
				id: "redux:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("\"@@redux\\/INIT[^\"]+\""),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "redux:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("\"@@redux\\/REPLACE[^\"]+\""),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "redux:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("\"@@redux\\/PROBE_UNKNOWN_ACTION[^\"]+\""),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "redux:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("redux-toolkit\\.js\\.org\\/Errors\\?code="),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "redux:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("Symbol\\.for\\([\"']rtk-state-proxy-original[\"']\\)"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "redux:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("Symbol\\.for\\([\"']react-redux-context[\"']\\)"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "redux:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("throw Error\\(['\"]You may not call store\\.getState\\(\\) while the reducer is executing\\. The reducer has already received the state as an argument\\. Pass it down from the top reducer instead of reading it from the store\\.['\"][\\)];"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "redux:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("See https:\\/\\/redux\\.js\\.org\\/api\\/store#subscribelistener"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "redux:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("throw Error\\(['\"]It looks like you are passing several store enhancers to createStore\\(\\)\\. This is not supported\\. Instead, compose them together to a single function\\. See https:\\/\\/redux\\.js\\.org\\/tutorials\\/fundamentals\\/part-4-store#creating-a-store-with-enhancers for an example\\.['\"][\\)];"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "redux:scriptContent:modern:9",
				kind: "scriptContent",
				pattern: new RegExp("throw Error\\(['\"]Actions may not have an undefined \"type\" property\\. You may have misspelled an action type string constant\\.['\"][\\)];"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "redux:scriptContent:modern:10",
				kind: "scriptContent",
				pattern: new RegExp("throw Error\\(['\"]Reducers may not dispatch actions\\.['\"][\\)];"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "redux:scriptContent:modern:11",
				kind: "scriptContent",
				pattern: new RegExp("visit https:\\/\\/redux\\.js\\.org\\/Errors\\?code="),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "redux:scriptContent:modern:12",
				kind: "scriptContent",
				pattern: new RegExp("You may need to add middleware to your store setup to handle dispatching other values, such as ['\"]redux-thunk['\"] to handle dispatching functions"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "redux:scriptContent:modern:13",
				kind: "scriptContent",
				pattern: new RegExp("function\\s+createStore\\s*\\([^)]*\\)\\s*\\{\\s*(?:var|let|const)\\s+currentReducer\\s*=\\s*reducer(?:\\s*;)?\\s*(?:var|let|const)\\s+currentState\\s*=\\s*preloadedState"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "redux:scriptContent:modern:14",
				kind: "scriptContent",
				pattern: new RegExp("function\\s+isPlainObject\\s*\\(obj\\)\\s*\\{\\s*if\\s*\\(typeof\\s+obj\\s*!==\\s*['\"]object['\"]\\s*\\|\\|\\s*obj\\s*===\\s*null\\)\\s*return\\s*false"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "redux:scriptContent:modern:15",
				kind: "scriptContent",
				pattern: new RegExp("if\\s*\\(typeof\\s+enhancer\\s*!==\\s*['\"]undefined['\"]\\)\\s*\\{\\s*if\\s*\\(typeof\\s+enhancer\\s*!==\\s*['\"]function['\"]\\)\\s*\\{\\s*throw"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "redux:scriptContent:modern:16",
				kind: "scriptContent",
				pattern: new RegExp("\"Actions must be plain objects\\. Instead, the actual type was: '[^']+'\\. You may need to add middleware\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "redux:scriptContent:modern:17",
				kind: "scriptContent",
				pattern: new RegExp("'Actions may not have an undefined \"type\" property'"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "redux:scriptContent:modern:18",
				kind: "scriptContent",
				pattern: new RegExp("\"Action \\\\\"type\\\\\" property must be a string\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "redux:scriptContent:modern:19",
				kind: "scriptContent",
				pattern: new RegExp("\"You may not call store\\.subscribe\\(\\) while the reducer is executing\""),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "redux:scriptContent:modern:20",
				kind: "scriptContent",
				pattern: new RegExp("\"Reducers may not dispatch actions\""),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "redux:scriptContent:modern:21",
				kind: "scriptContent",
				pattern: new RegExp("\"The slice reducer for key [^\"]+ returned undefined during initialization\""),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "redux:scriptContent:modern:22",
				kind: "scriptContent",
				pattern: new RegExp("\"Invalid value of type .* for mapDispatchToProps argument when connecting component"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "redux:scriptContent:modern:23",
				kind: "scriptContent",
				pattern: new RegExp("Connect\\([^)]+\\).*reactReduxForwardedRef"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "redux:scriptContent:modern:24",
				kind: "scriptContent",
				pattern: new RegExp("\\[\"__reactRedux\"\\]"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "redux:scriptContent:modern:25",
				kind: "scriptContent",
				pattern: new RegExp("notifyNestedSubs"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "redux:scriptContent:modern:26",
				kind: "scriptContent",
				pattern: new RegExp("\\{reactReduxForwardedRef:.*getServerState:.*\\}"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
		metadata: {
			oss: true,
		},
	},
	{
		id: "redux-framework",
		name: "Redux Framework",
		website: "https://redux.io",
		description: "Redux Framework is a modular PHP library that allows developers to create customisable settings panels and controls for WordPress projects, providing a consistent user interface for managing options and settings.",
		icon: "Redux Framework.svg",
		categories: [
			"state-management",
			"wordpress-ecosystem",
		],
		rules: [
			{
				id: "redux-framework:meta:0",
				kind: "meta",
				key: "framework",
				valuePattern: new RegExp("Redux\\s([\\d\\.]+)", "i"),
				version: {
					source: "match",
					group: 1,
				},
				description: "Meta tag matches a known technology marker.",
			},
			{
				id: "redux-framework:meta:1",
				kind: "meta",
				key: "generator",
				valuePattern: new RegExp("Redux\\s([\\d\\.]+)", "i"),
				version: {
					source: "match",
					group: 1,
				},
				description: "Meta tag matches a known technology marker.",
			},
			{
				id: "redux-framework:meta:2",
				kind: "meta",
				key: "framework",
				valuePattern: new RegExp("redux\\s([\\d\\.]+)", "i"),
				version: {
					source: "match",
					group: 1,
				},
				description: "Meta tag matches a known technology marker.",
			},
			{
				id: "redux-framework:meta:3",
				kind: "meta",
				key: "generator",
				valuePattern: new RegExp("redux\\s([\\d\\.]+)", "i"),
				version: {
					source: "match",
					group: 1,
				},
				description: "Meta tag matches a known technology marker.",
			},
		],
		metadata: {
			oss: true,
		},
		requires: [
			"wordpress",
		],
	},
	{
		id: "effector",
		name: "Effector",
		website: "https://effector.dev/",
		description: "The state manager that helps to create fast and reliable applications.",
		categories: [
			"state-management",
		],
		rules: [
			{
				id: "effector:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("\"Handlers map can contain only effects as keys\""),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "effector:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("\"Values map can contain only writable stores as keys\""),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "effector:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("['\"](family|graphite)[\"']\\s+in\\s+e"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "effector:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("\\.graphite\\s*\\|\\|\\s*e"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "effector:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("\\.family\\.owner"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "effector:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("\\{store:\\s*t\\.stateRef,\\s*to:\\s*['\"]stack[\"']\\}"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "effector:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("\\{store:\\s*[^,]+,\\s*to:\\s*['\"](?:stack|a|b)[\"']"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "effector:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("priority:\\s*['\"](?:barrier|read)[\"']"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "effector:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("\\.sidMap\\[O\\([^,]+,\\s*['\"]sid[\"']\\)\\]"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
	{
		id: "jotai",
		name: "Jotai",
		website: "https://jotai.org",
		description: "Primitive and flexible state management for React.",
		categories: [
			"state-management",
		],
		rules: [
			{
				id: "jotai:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("\"setSelf function cannot be used with read-only atom\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "jotai:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("\"setSelf function cannot be called in sync\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "jotai:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("\"atom not writable\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "jotai:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("\"no atom init\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "jotai:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("\"atom\\d+\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "jotai:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("atomStateMap\\s*=\\s*new\\s*WeakMap"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "jotai:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("mountedMap\\s*=\\s*new\\s*WeakMap"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "jotai:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("cancelPromiseMap\\s*=\\s*new\\s*WeakMap"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "jotai:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("from\\s+[\"']jotai\\/vanilla[\"']"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "jotai:scriptContent:modern:9",
				kind: "scriptContent",
				pattern: new RegExp("from\\s+[\"']jotai\\/devtools[\"']"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "jotai:scriptContent:modern:10",
				kind: "scriptContent",
				pattern: new RegExp("require\\([\"']jotai\\/vanilla[\"']\\)"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "jotai:scriptContent:modern:11",
				kind: "scriptContent",
				pattern: new RegExp("require\\([\"']jotai\\/devtools[\"']\\)"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
	{
		id: "ngrx",
		name: "NgRx",
		website: "https://ngrx.io/",
		description: "A set of reactive libraries for Angular.",
		categories: [
			"state-management",
		],
		rules: [
			{
				id: "ngrx:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("@ngrx\\/store\\/init"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "ngrx:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("new\\s+[a-zA-Z.]*nKC\\(\\s*[\"']@ngrx\\/[^\"']+[\"']\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "ngrx:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("\"@ngrx\\/store\\s+Internal[^\"]+\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "ngrx:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("https:\\/\\/ngrx\\.io\\/guide\\/store\\/configuration\\/runtime-checks"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "ngrx:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("\"@ngrx\\/store Internal Root Guard\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "ngrx:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("\"@ngrx\\/store Internal Initial State\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "ngrx:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("\"@ngrx\\/store Initial State\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "ngrx:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("\"@ngrx\\/store\\/update-reducers\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "ngrx:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("\\[\"\\$\\$isNgrxMockEnvironment\"\\]"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "ngrx:scriptContent:modern:9",
				kind: "scriptContent",
				pattern: new RegExp("\\[\"\\$ngrxMockState\"\\]"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "ngrx:scriptContent:modern:10",
				kind: "scriptContent",
				pattern: new RegExp("\"The root Store has been provided more than once. Feature modules should provide feature states instead.\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "ngrx:scriptContent:modern:11",
				kind: "scriptContent",
				pattern: new RegExp("\"@ngrx\\/store Store Features\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "ngrx:scriptContent:modern:12",
				kind: "scriptContent",
				pattern: new RegExp("\"@ngrx\\/store Internal Store Features\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "ngrx:scriptContent:modern:13",
				kind: "scriptContent",
				pattern: new RegExp("\"@ngrx\\/store Feature Reducers\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "ngrx:scriptContent:modern:14",
				kind: "scriptContent",
				pattern: new RegExp("\"@ngrx\\/store\\/metaReducers\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "ngrx:scriptContent:modern:15",
				kind: "scriptContent",
				pattern: new RegExp("\"@ngrx\\/store\\/reducers\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "ngrx:scriptContent:modern:16",
				kind: "scriptContent",
				pattern: new RegExp("[\"']\\@ngrx\\/store[\"']"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "ngrx:scriptContent:modern:17",
				kind: "scriptContent",
				pattern: new RegExp("[\"']\\@ngrx\\/effects[\"']"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "ngrx:scriptContent:modern:18",
				kind: "scriptContent",
				pattern: new RegExp("[\"']\\@ngrx\\/entity[\"']"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "ngrx:scriptContent:modern:19",
				kind: "scriptContent",
				pattern: new RegExp("[\"']\\@ngrx\\/store-devtools[\"']"),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
	{
		id: "recoil",
		name: "Recoil",
		website: "https://recoiljs.org/",
		description: "A state management library for React that provides several capabilities that are difficult to achieve with React alone, while being compatible with the newest features of React.",
		categories: [
			"state-management",
		],
		rules: [
			{
				id: "recoil:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("\\$\\$isRecoilValue"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "recoil:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("\\[\"ROOT_QUERY\"\\]|\\[\"ROOT_MUTATION\"\\]"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "recoil:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("Recoil selector has circular dependencies:"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "recoil:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("\"RECOIL_GKS_ENABLED\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "recoil:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("\"Cannot use server actions in pages\\/api\\/\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "recoil:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("function\\s+atomFamily\\s*\\(\\s*\\{\\s*key\\s*:[^,]+,\\s*default\\s*:"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "recoil:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("function\\s+RecoilRoot\\s*\\(\\s*\\{\\s*(?:initializeState|override)\\s*:"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "recoil:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("\"Duplicate atom key \\\\\"[^\"]+\\\\\". This is a FATAL ERROR\""),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "recoil:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("\"Missing definition for RecoilValue: \\\\\"[^\"]+\\\\\"\""),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "recoil:scriptContent:modern:9",
				kind: "scriptContent",
				pattern: new RegExp("\"Multiple Content-Length\".*\"both multipart and urlencoded\""),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
	{
		id: "tanstack-query",
		name: "TanStack Query",
		website: "https://tanstack.com/query",
		description: "Query-based state management.",
		categories: [
			"state-management",
		],
		rules: [
			{
				id: "tanstack-query:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("ensureInfiniteQueryData\\s*\\("),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "tanstack-query:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("prefetchInfiniteQuery\\s*\\("),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "tanstack-query:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("fetchInfiniteQuery\\s*\\("),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "tanstack-query:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("observers\\.find\\([^)]+\\.shouldFetchOnReconnect\\(\\)\\)"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "tanstack-query:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("\\w+\\.defaultMutationOptions\\s*\\("),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "tanstack-query:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("\\w+\\.options\\.refetchIntervalInBackground"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "tanstack-query:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("_experimental_beforeQuery"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "tanstack-query:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("_experimental_afterQuery"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "tanstack-query:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("experimental_prefetchInRender"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "tanstack-query:scriptContent:modern:9",
				kind: "scriptContent",
				pattern: new RegExp("[Nn]o\\s*QueryClient\\s*set,\\s*use\\s*QueryClientProvider"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
	{
		id: "valtio",
		name: "valtio",
		website: "https://valtio.dev/",
		description: "Reactive global state for React.",
		categories: [
			"state-management",
		],
		rules: [
			{
				id: "valtio:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("unstable_getDeriveSubscriptions"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "valtio:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("proxyCompare\\.markToTrack"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "valtio:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("'Please use proxy object'"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "valtio:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("\\[\\$valtioRef\\]"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "valtio:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("\\[valtio_listeners\\]"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "valtio:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("\\[valtio_source\\]"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "valtio:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("markToTrack\\(snapshot,\\s*true\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "valtio:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("snapshot\\[PROMISE_SYMBOL\\]"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "valtio:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("addPromiseListener"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "valtio:scriptContent:modern:9",
				kind: "scriptContent",
				pattern: new RegExp("import\\s+.*from\\s+[\"']valtio\\/vanilla[\"']"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "valtio:scriptContent:modern:10",
				kind: "scriptContent",
				pattern: new RegExp("import\\s+.*from\\s+[\"']valtio\\/utils[\"']"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "valtio:scriptContent:modern:11",
				kind: "scriptContent",
				pattern: new RegExp("require\\([\"']valtio\\/vanilla[\"']\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "valtio:scriptContent:modern:12",
				kind: "scriptContent",
				pattern: new RegExp("require\\([\"']valtio\\/utils[\"']\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "valtio:scriptContent:modern:13",
				kind: "scriptContent",
				pattern: new RegExp("import\\([\"']valtio\\/vanilla[\"']\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "valtio:scriptContent:modern:14",
				kind: "scriptContent",
				pattern: new RegExp("import\\([\"']valtio\\/utils[\"']\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "valtio:scriptContent:modern:15",
				kind: "scriptContent",
				pattern: new RegExp("\"__valtio_devtools_value__\""),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "valtio:scriptContent:modern:16",
				kind: "scriptContent",
				pattern: new RegExp("\"__valtio_devtools_undefined__\""),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "valtio:scriptContent:modern:17",
				kind: "scriptContent",
				pattern: new RegExp("\"__valtio_devtools_pending__\""),
				confidence: 55,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
	{
		id: "xstate",
		name: "XState",
		website: "https://xstate.js.org/",
		description: "XState is a state management and orchestration solution for JavaScript and TypeScript apps.",
		categories: [
			"state-management",
		],
		rules: [
			{
				id: "xstate:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("\"@xstate\\.snapshot\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "xstate:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("\"@xstate\\.event\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "xstate:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("\"@xstate\\.microstep\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "xstate:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("\"xstate\\.init\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "xstate:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("\"xstate\\.stop\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "xstate:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("\"xstate\\.spawnChild\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "xstate:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("xstate\\$\\$type:\\s*1"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "xstate:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("xstate\\.done\\.actor\\.\\${[^}]+}"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "xstate:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("xstate\\.done\\.state\\.\\${[^}]+}"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "xstate:scriptContent:modern:9",
				kind: "scriptContent",
				pattern: new RegExp("xstate\\.error\\.actor"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "xstate:scriptContent:modern:10",
				kind: "scriptContent",
				pattern: new RegExp("xstate\\.invoke\\.\\${[^}]+}"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "xstate:scriptContent:modern:11",
				kind: "scriptContent",
				pattern: new RegExp("\"xstate\\.observable\\.next\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "xstate:scriptContent:modern:12",
				kind: "scriptContent",
				pattern: new RegExp("\"xstate\\.observable\\.error\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "xstate:scriptContent:modern:13",
				kind: "scriptContent",
				pattern: new RegExp("\"xstate\\.observable\\.complete\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "xstate:scriptContent:modern:14",
				kind: "scriptContent",
				pattern: new RegExp("\"xstate\\.promise\\.resolve\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "xstate:scriptContent:modern:15",
				kind: "scriptContent",
				pattern: new RegExp("\"xstate\\.promise\\.reject\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "xstate:scriptContent:modern:16",
				kind: "scriptContent",
				pattern: new RegExp("\"xstate\\.enqueueActions\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "xstate:scriptContent:modern:17",
				kind: "scriptContent",
				pattern: new RegExp("\\.type=\"xstate\\.log\""),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
	{
		id: "zustand",
		name: "Zustand",
		website: "https://zustand-demo.pmnd.rs",
		description: "A small, fast and scalable bearbones state-management solution using simplified flux principles.",
		categories: [
			"state-management",
		],
		rules: [
			{
				id: "zustand:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("zustandVanilla"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "zustand:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("zustandShallow"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "zustand:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("zustandContext"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "zustand:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("\\{\\s*getInitialState\\s*:[^,}]*,\\s*getState\\s*:[^,}]*,\\s*setState\\s*:[^,}]*,\\s*subscribe\\s*:[^,}]*\\s*\\}", "m"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "zustand:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("\\[zustand devtools middleware\\] Unsupported action format"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "zustand:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("\\[DEPRECATED\\] Passing a vanilla store will be unsupported in a future version\\. Instead use import \\{ useStore \\} from 'zustand'\\."),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "zustand:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("\\[zustand devtools middleware\\] Unsupported __setState action format"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "zustand:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("When using 'store' option in devtools\\(\\), the 'state' should have only one key"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "zustand:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("\\[DEPRECATED\\].*['\"]zustand\\/traditional['\"]"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "zustand:scriptContent:modern:9",
				kind: "scriptContent",
				pattern: new RegExp("github\\.com\\/pmndrs\\/zustand\\/discussions\\/1937"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "zustand:scriptContent:modern:10",
				kind: "scriptContent",
				pattern: new RegExp("\"Seems like you have not used zustand provider as an ancestor\\.\""),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "zustand:scriptContent:modern:11",
				kind: "scriptContent",
				pattern: new RegExp("createWithEqualityFn.*instead of.*create.*useStoreWithEqualityFn.*instead of.*useStore"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "zustand:scriptContent:modern:12",
				kind: "scriptContent",
				pattern: new RegExp("import\\s+.*from\\s+[\"']zustand\\/vanilla[\"']"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "zustand:scriptContent:modern:13",
				kind: "scriptContent",
				pattern: new RegExp("import\\s+.*from\\s+[\"']zustand\\/react[\"']"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "zustand:scriptContent:modern:14",
				kind: "scriptContent",
				pattern: new RegExp("import\\s+.*from\\s+[\"']zustand\\/shallow[\"']"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "zustand:scriptContent:modern:15",
				kind: "scriptContent",
				pattern: new RegExp("require\\([\"']zustand\\/vanilla[\"']\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "zustand:scriptContent:modern:16",
				kind: "scriptContent",
				pattern: new RegExp("require\\([\"']zustand\\/react[\"']\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "zustand:scriptContent:modern:17",
				kind: "scriptContent",
				pattern: new RegExp("require\\([\"']zustand\\/shallow[\"']\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "zustand:scriptContent:modern:18",
				kind: "scriptContent",
				pattern: new RegExp("import\\([\"']zustand\\/vanilla[\"']\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "zustand:scriptContent:modern:19",
				kind: "scriptContent",
				pattern: new RegExp("import\\([\"']zustand\\/react[\"']\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "zustand:scriptContent:modern:20",
				kind: "scriptContent",
				pattern: new RegExp("import\\([\"']zustand\\/shallow[\"']\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "zustand:scriptContent:modern:21",
				kind: "scriptContent",
				pattern: new RegExp("define\\(\\[[\"']zustand\\/vanilla[\"']\\]|define\\(\\[[\"']zustand\\/react[\"']\\]|define\\(\\[[\"']zustand\\/shallow[\"']\\]"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
] as const satisfies readonly TechnologyDefinition[];
