import type { TechnologyDefinition } from '../types';

export const stylingProcessorTechnologyDefinitions = [
	{
		id: "emotion",
		name: "Emotion",
		website: "https://emotion.sh",
		description: "Emotion is a library designed for writing CSS styles with JavaScript.",
		icon: "Emotion.png",
		categories: [
			"styling-processor",
			"ui-library",
			"developer-tooling",
		],
		rules: [
			{
				id: "emotion:dom:0",
				kind: "dom",
				selector: "style[data-emotion], style[data-emotion-css]",
				description: "DOM selector matches a known technology marker.",
			},
			{
				id: "emotion:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("\\.getAttribute\\([\"']data-emotion[\"']\\)"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "emotion:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("\\w+\\.setAttribute\\([\"']data-emotion[\"']\\s*,\\s*\\w+(?:\\.\\w+)?(?:\\s*\\+\\s*[^\\)]+)?\\)"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "emotion:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("\\.querySelectorAll\\([\"']style\\[data-emotion\\]:not\\(\\[data-s\\]\\)[\"']\\)"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "emotion:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("\\{\"key\":\"[\\w-]+\",\"nonce\":\"[\\w-]*\",\"insertionPoint\":[\\w\\s\\.\"]+\\}"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "emotion:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("\\w+\\.__emotion_styles\\b"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "emotion:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("\\w+\\.__emotion_real\\b"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "emotion:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("\\w+\\.__emotion_forwardProp\\b"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "emotion:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("\\.withComponent=function\\([\\w$]+\\)\\{return[\\w$]+\\([\\w$]+,\\{target:[\\w$]+\\.target\\}\\)\\}"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "emotion:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("Symbol\\.for\\([\"']emotion-[\\w-]+[\"']\\)"),
				confidence: 75,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "emotion:stylesheetContent:modern:9",
				kind: "stylesheetContent",
				pattern: new RegExp("\\.css-[\\w-]+-EmotionCSS-[\\w-]+\\[data-emotion-[\\w-]+\\]"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "emotion:stylesheetContent:modern:10",
				kind: "stylesheetContent",
				pattern: new RegExp("@keyframes\\s+emotion-[\\w-]+-[\\w-]+"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "emotion:stylesheetContent:modern:11",
				kind: "stylesheetContent",
				pattern: new RegExp("\\[data-emotion-global-[\\w-]+\\]"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "emotion:scriptContent:modern:12",
				kind: "scriptContent",
				pattern: new RegExp("\\[@emotion\\/styled\\]"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "emotion:scriptContent:modern:13",
				kind: "scriptContent",
				pattern: new RegExp("\\[@emotion\\/react\\]"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "emotion:scriptContent:modern:14",
				kind: "scriptContent",
				pattern: new RegExp("\\[@emotion\\/css\\]"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "emotion:scriptContent:modern:15",
				kind: "scriptContent",
				pattern: new RegExp("import\\s*\\{\\s*css\\s*\\}\\s*from\\s*[\"']@emotion\\/react[\"']"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
		metadata: {
			oss: true,
		},
	},
	{
		id: "less",
		name: "Less",
		website: "https://lesscss.org",
		description: "Less is a CSS preprocessor, providing a set of extensions and features to traditional Cascading Style Sheets (CSS) for improved maintainability and ease of styling in web development.",
		icon: "Less.png",
		categories: [
			"styling-processor",
			"widgets-misc",
		],
		rules: [
			{
				id: "less:html:0",
				kind: "html",
				pattern: new RegExp("<link[^>]+ rel=\"stylesheet\\/less\""),
				description: "HTML contains a known technology signature.",
			},
			{
				id: "less:dom:1",
				kind: "dom",
				selector: "link[rel='stylesheet/less']",
				description: "DOM selector matches a known technology marker.",
			},
			{
				id: "less:stylesheetContent:modern:0",
				kind: "stylesheetContent",
				pattern: new RegExp("\\.-?[_a-zA-Z][\\w-]*\\[default\\]\\{"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "less:stylesheetContent:modern:1",
				kind: "stylesheetContent",
				pattern: new RegExp("\\.-?[_a-zA-Z][\\w-]*\\[[\\w\\s><=!]+\\]\\{"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "less:stylesheetContent:modern:2",
				kind: "stylesheetContent",
				pattern: new RegExp("when\\(iscolor\\([@\\w-]+\\)\\)"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "less:stylesheetContent:modern:3",
				kind: "stylesheetContent",
				pattern: new RegExp("\\[data-less-[\\da-f]{8}\\]"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "less:stylesheetContent:modern:4",
				kind: "stylesheetContent",
				pattern: new RegExp("less-[\\da-f]{8}-extend"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "less:stylesheetContent:modern:5",
				kind: "stylesheetContent",
				pattern: new RegExp("\\.-?[_a-zA-Z][\\w-]*e\\[[\\da-f]{8}\\]"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "less:stylesheetContent:modern:6",
				kind: "stylesheetContent",
				pattern: new RegExp("\\+\\s*_[\\da-f]{8}(?!\\w)"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "less:stylesheetContent:modern:7",
				kind: "stylesheetContent",
				pattern: new RegExp("@plugin\\s+\"less-plugin-[\\w-]+\";"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "less:stylesheetContent:modern:8",
				kind: "stylesheetContent",
				pattern: new RegExp("--less-[\\da-f]{8}-prop"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
		],
		metadata: {
			oss: true,
		},
	},
	{
		id: "sass",
		name: "Sass",
		website: "https://sass-lang.com",
		description: "Sass is an extension of CSS that enables you to use things like variables, nested rules, inline imports and more.",
		icon: "Sass.svg",
		categories: [
			"styling-processor",
			"developer-tooling",
		],
		rules: [
			{
				id: "sass:dom:0",
				kind: "dom",
				selector: "link[href*='/index.scss']",
				description: "DOM selector matches a known technology marker.",
			},
			{
				id: "sass:stylesheetContent:modern:0",
				kind: "stylesheetContent",
				pattern: new RegExp("\\[data-v-s-[\\da-f]{8,}\\]"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "sass:stylesheetContent:modern:1",
				kind: "stylesheetContent",
				pattern: new RegExp("\\._[\\da-f]{6,}(?:[\\w-]+)?__[\\da-f]{6,}"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "sass:stylesheetContent:modern:2",
				kind: "stylesheetContent",
				pattern: new RegExp("\\[data-v-[\\da-f]{8,}\\]"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "sass:stylesheetContent:modern:3",
				kind: "stylesheetContent",
				pattern: new RegExp("\\$--[\\da-f]{6,}-interpolation"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "sass:stylesheetContent:modern:4",
				kind: "stylesheetContent",
				pattern: new RegExp("--sass-interpolate-[\\da-f]{6,}"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "sass:stylesheetContent:modern:5",
				kind: "stylesheetContent",
				pattern: new RegExp("\\.sass-module-[\\da-f]{8,}"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "sass:stylesheetContent:modern:6",
				kind: "stylesheetContent",
				pattern: new RegExp("\\$--color-[\\da-f]{6,}-adjust"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "sass:stylesheetContent:modern:7",
				kind: "stylesheetContent",
				pattern: new RegExp("--sass-color-[\\da-f]{6,}"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "sass:stylesheetContent:modern:8",
				kind: "stylesheetContent",
				pattern: new RegExp("color:rgba\\(var\\(--sass-rgba-[\\da-f]{6,}\\)\\)"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
		],
	},
	{
		id: "stitches",
		name: "Stitches",
		website: "https://stitches.dev",
		description: "Stitches is an is a CSS-in-JS styling framework with near-zero runtime, SSR, and multi-variant support.",
		icon: "Stitches.svg",
		categories: [
			"styling-processor",
			"ui-library",
			"developer-tooling",
		],
		rules: [
			{
				id: "stitches:dom:0",
				kind: "dom",
				selector: "style#stitches",
				description: "DOM selector matches a known technology marker.",
			},
			{
				id: "stitches:meta:1",
				kind: "meta",
				key: "generator",
				valuePattern: new RegExp("^c-[A-Za-z]{5}$", "i"),
				description: "Meta tag matches a known technology marker.",
			},
			{
				id: "stitches:meta:2",
				kind: "meta",
				key: "generator",
				valuePattern: new RegExp("^c-[a-za-z]{5}$", "i"),
				description: "Meta tag matches a known technology marker.",
			},
			{
				id: "stitches:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("__stitches=\\{prefix:\"[\\w-]+\",insertionMethod:[\\d]+"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "stitches:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("insertionMethod:[\\d]+,[\\w]+:\"[\\w-]+-(?:keyframes|global|themed)\""),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "stitches:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("createTheme\\([\"'](?:light|dark|[\\w-]+)_theme[\"']\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "stitches:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("\\{media:\\{[^}]+\\},theme:\\{[^}]+\\},utils:\\{[^}]+\\},prefix:[\"'][\\w-]+[\"']\\}"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "stitches:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("styled\\([^)]+,\\{variants:\\{[\\w-]+:\\{[\\w-]+:\\{transform:"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "stitches:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("compoundVariants:\\[\\{variants:\\{[\\w-]+:[\"'][\\w-]+[\"']\\}"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "stitches:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("type\\s+\\w+Props=ComponentProps<typeof\\s+\\w+>&\\{variants:\\{"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "stitches:stylesheetContent:modern:7",
				kind: "stylesheetContent",
				pattern: new RegExp("\\.sxtchs[\\w-]*[\\da-f]{4,8}"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "stitches:stylesheetContent:modern:8",
				kind: "stylesheetContent",
				pattern: new RegExp("@keyframes\\s+sxtchs-[\\da-f]{4,8}-anim"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "stitches:stylesheetContent:modern:9",
				kind: "stylesheetContent",
				pattern: new RegExp("\\.sxtchs[\\w-]*[\\da-f]{4,8}-variant"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "stitches:stylesheetContent:modern:10",
				kind: "stylesheetContent",
				pattern: new RegExp("--sxtchs-[\\da-f]{4,8}-[\\w-]+"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "stitches:stylesheetContent:modern:11",
				kind: "stylesheetContent",
				pattern: new RegExp("var\\(--sxtchs-[\\da-f]{4,8}-themed-[\\w-]+\\)"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "stitches:stylesheetContent:modern:12",
				kind: "stylesheetContent",
				pattern: new RegExp("calc\\(var\\(--sxtchs-[\\da-f]{4,8}-[\\w-]+\\)[^)]*\\)"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
		],
		metadata: {
			oss: true,
		},
	},
	{
		id: "styled-components",
		name: "styled-components",
		website: "https://styled-components.com",
		description: "Styled components is a CSS-in-JS styling framework that uses tagged template literals in JavaScript.",
		icon: "styled-components.svg",
		categories: [
			"styling-processor",
			"ui-library",
			"developer-tooling",
		],
		rules: [
			{
				id: "styled-components:dom:0",
				kind: "dom",
				selector: "[sc-component-id]",
				description: "DOM selector matches a known technology marker.",
			},
			{
				id: "styled-components:dom:1",
				kind: "dom",
				selector: "style[data-styled-version]",
				description: "DOM selector matches a known technology marker.",
			},
			{
				id: "styled-components:dom:2",
				kind: "dom",
				selector: "style[data-styled], style[data-styled-components], [sc-component-id]",
				description: "DOM selector matches a known technology marker.",
			},
			{
				id: "styled-components:jsGlobal:3",
				kind: "jsGlobal",
				property: "styled",
				description: "Page-owned global matches a known technology marker.",
			},
			{
				id: "styled-components:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("\\[\\$\\$typeof\\]=Symbol\\.for\\([\"']sc_element[\"']\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "styled-components:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("\\.__sc-[\\da-zA-Z]{8}-[\\da-zA-Z]{4}={"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "styled-components:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("\\.styledComponentId=[\"']sc-[\\da-zA-Z]{8}-[\\da-zA-Z]{4}[\"']"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "styled-components:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("\\.withConfig\\(\\{\"componentId\":[\"']sc-[\\da-zA-Z]{8}-[\\da-zA-Z]{4}[\"']\\}\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "styled-components:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("\\.attrs\\(\\{[\"']data-sc-[\\da-zA-Z]{8}[\"']:"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "styled-components:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("sc_createGlobalStyle\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "styled-components:stylesheetContent:modern:6",
				kind: "stylesheetContent",
				pattern: new RegExp("\\.sc-[\\da-zA-Z]{8}-[\\da-zA-Z]{4}\\[data-sc-[\\da-zA-Z]{8}\\]"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "styled-components:stylesheetContent:modern:7",
				kind: "stylesheetContent",
				pattern: new RegExp("@keyframes\\s+sc-keyframes-[\\da-zA-Z]{8}"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "styled-components:stylesheetContent:modern:8",
				kind: "stylesheetContent",
				pattern: new RegExp("sc-global-[\\da-zA-Z]{8}"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "styled-components:stylesheetContent:modern:9",
				kind: "stylesheetContent",
				pattern: new RegExp("\\[data-sc-[\\da-zA-Z]{8}\\]{"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "styled-components:stylesheetContent:modern:10",
				kind: "stylesheetContent",
				pattern: new RegExp("--sc-[\\da-zA-Z]{8}-[\\da-zA-Z]{4}"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "styled-components:stylesheetContent:modern:11",
				kind: "stylesheetContent",
				pattern: new RegExp("content:var\\(--sc-[\\da-zA-Z]{8}-[\\da-zA-Z]{4}\\)"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
		],
		implies: [
			"react",
		],
	},
	{
		id: "jss",
		name: "JSS",
		website: "https://emotion.sh/docs/introduction",
		description: "Emotion is a performant and flexible CSS-in-JS library. Building on many other CSS-in-JS libraries, it allows you to style apps quickly with string or object styles. It has predictable composition to avoid specificity issues with CSS.",
		categories: [
			"styling-processor",
		],
		rules: [
			{
				id: "jss:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("jss-[\\da-f]{4,8}-[\\da-f]{4}"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "jss:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("createRule\\([\"']@(?:media|keyframes)[\"'],\\{"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "jss:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("\\.[\\w-]+-[\\da-f]{4,8}-[\\da-f]{4}\\s*{"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "jss:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("\\{registry:\\[\\],plugins:\\[\\],index:0,sheet:[\\w$]+,rules:\\{"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "jss:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("\\{generateId:[\\w$]+,jss:[\\w$]+,Renderer:[\\w$]+,insertionPoint:"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "jss:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("\\.use\\(\\{onCreateRule:[\\w$]+,onProcessRule:[\\w$]+\\}\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "jss:stylesheetContent:modern:6",
				kind: "stylesheetContent",
				pattern: new RegExp("\\.jss[\\da-f]{4,8}-[\\da-f]{4}"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "jss:stylesheetContent:modern:7",
				kind: "stylesheetContent",
				pattern: new RegExp("--jss-[\\da-f]{4,8}-[\\da-f]{4}:"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "jss:stylesheetContent:modern:8",
				kind: "stylesheetContent",
				pattern: new RegExp("@keyframes jss-keyframe-[\\da-f]{4,8}"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "jss:scriptContent:modern:9",
				kind: "scriptContent",
				pattern: new RegExp("jss-plugin-[\\w-]+"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "jss:scriptContent:modern:10",
				kind: "scriptContent",
				pattern: new RegExp("onProcessStyle:\\s*function\\([\\w$]+,[\\w$]+,[\\w$]+\\)\\{"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "jss:scriptContent:modern:11",
				kind: "scriptContent",
				pattern: new RegExp("onCreateRule:\\s*function\\([\\w$]+,[\\w$]+,[\\w$]+\\)\\{"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
	{
		id: "postcss",
		name: "PostCSS",
		website: "https://postcss.org",
		description: "PostCSS is a tool for transforming CSS with JavaScript plugins. These plugins can lint your CSS, support variables and mixins, transpile future CSS syntax, inline images, and more.",
		categories: [
			"styling-processor",
		],
		rules: [
			{
				id: "postcss:stylesheetContent:modern:0",
				kind: "stylesheetContent",
				pattern: new RegExp("@property\\s+--[\\w-]+\\s*{[^}]*syntax:"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "postcss:stylesheetContent:modern:1",
				kind: "stylesheetContent",
				pattern: new RegExp("@custom-media\\s+--[\\w-]+\\s*\\([^)]+\\)"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "postcss:stylesheetContent:modern:2",
				kind: "stylesheetContent",
				pattern: new RegExp("@custom-selector\\s*:--[\\w-]+"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "postcss:stylesheetContent:modern:3",
				kind: "stylesheetContent",
				pattern: new RegExp("@nest\\s*&"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "postcss:stylesheetContent:modern:4",
				kind: "stylesheetContent",
				pattern: new RegExp("@nest\\s+[^&]+&[^{]+{"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "postcss:stylesheetContent:modern:5",
				kind: "stylesheetContent",
				pattern: new RegExp("&:matches\\([^)]+\\)"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "postcss:stylesheetContent:modern:6",
				kind: "stylesheetContent",
				pattern: new RegExp("color\\([^)]+(?:tint|shade|modify|adjust)\\s+[\\d.]+%?\\)"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "postcss:stylesheetContent:modern:7",
				kind: "stylesheetContent",
				pattern: new RegExp("color-mod\\([^)]+\\)"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "postcss:stylesheetContent:modern:8",
				kind: "stylesheetContent",
				pattern: new RegExp("lab\\([^)]+\\/\\s*[\\d.]+%?\\)"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "postcss:stylesheetContent:modern:9",
				kind: "stylesheetContent",
				pattern: new RegExp("@custom-media[^{]+{"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "postcss:stylesheetContent:modern:10",
				kind: "stylesheetContent",
				pattern: new RegExp("@custom-selector[^{]+{"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "postcss:stylesheetContent:modern:11",
				kind: "stylesheetContent",
				pattern: new RegExp("@custom-property[^{]+{"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
		],
	},
	{
		id: "stylus",
		name: "Stylus",
		website: "http://stylus-lang.com",
		description: "Stylus is a preprocessor that allows you to write CSS with a syntax that is more concise and easier to read. It supports variables, nesting, and mixins.",
		categories: [
			"styling-processor",
		],
		rules: [
			{
				id: "stylus:stylesheetContent:modern:0",
				kind: "stylesheetContent",
				pattern: new RegExp("^[\\w-]+\\s+[\\w-]+\\s+[\\w-]+$", "m"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "stylus:stylesheetContent:modern:1",
				kind: "stylesheetContent",
				pattern: new RegExp("^&:[\\w-]+\\s+[\\w-]+$", "m"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "stylus:stylesheetContent:modern:2",
				kind: "stylesheetContent",
				pattern: new RegExp("\\^[0-9]+\\s*\\{"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "stylus:stylesheetContent:modern:3",
				kind: "stylesheetContent",
				pattern: new RegExp("@[\\w-]+\\[[0-9]+\\]"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "stylus:stylesheetContent:modern:4",
				kind: "stylesheetContent",
				pattern: new RegExp("[\\w-]+\\s*\\?=\\s*[^;{]+"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "stylus:stylesheetContent:modern:5",
				kind: "stylesheetContent",
				pattern: new RegExp("is\\s+a\\s+['\"](?:unit|color|string|ident|boolean)[\"']"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "stylus:stylesheetContent:modern:6",
				kind: "stylesheetContent",
				pattern: new RegExp("\\@[\\w-]+\\[[\\w\\d]+\\]"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "stylus:stylesheetContent:modern:7",
				kind: "stylesheetContent",
				pattern: new RegExp("for\\s+[\\w-]+\\s+in\\s+\\(1\\.\\.\\d+\\)"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "stylus:stylesheetContent:modern:8",
				kind: "stylesheetContent",
				pattern: new RegExp("\\/\\/\\s*@stylus"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "stylus:stylesheetContent:modern:9",
				kind: "stylesheetContent",
				pattern: new RegExp("\\/\\*\\s*@stylus-compiled\\s*\\*\\/"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "stylus:stylesheetContent:modern:10",
				kind: "stylesheetContent",
				pattern: new RegExp("\\/\\*\\s*@stylus-generated\\s*\\*\\/"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "stylus:stylesheetContent:modern:11",
				kind: "stylesheetContent",
				pattern: new RegExp("\\b(?:push|unshift|lookup|define|operate)\\s*\\([^)]*\\)"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "stylus:stylesheetContent:modern:12",
				kind: "stylesheetContent",
				pattern: new RegExp("\\b(?:lightness|desaturate|invert)\\s*\\([^)]*\\)\\s*\\+\\s*\\d+%"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
			{
				id: "stylus:stylesheetContent:modern:13",
				kind: "stylesheetContent",
				pattern: new RegExp("unit\\s*\\([^)]+,\\s*(['\"])?[a-z%]+\\1\\s*\\)"),
				confidence: 45,
				description: "Stylesheet content matches a modern styling marker.",
			},
		],
	},
] as const satisfies readonly TechnologyDefinition[];
