import type { TechnologyDefinition } from '../types';

export const transpilerTechnologyDefinitions = [
	{
		id: "canyon",
		name: "Canyon",
		website: "https://docs.canyonjs.io",
		description: "Canyon is a tool that enables JavaScript coverage collection and real-time report generation through Babel configuration, addressing coverage-gathering challenges in end-to-end testing.",
		icon: "Canyon.svg",
		categories: [
			"transpiler",
			"developer-tooling",
		],
		rules: [
			{
				id: "canyon:jsGlobal:0",
				kind: "jsGlobal",
				property: "__coverage__",
				description: "Page-owned global matches a known technology marker.",
			},
			{
				id: "canyon:jsGlobal:1",
				kind: "jsGlobal",
				property: "canyonShowDecorations",
				description: "Page-owned global matches a known technology marker.",
			},
		],
		metadata: {
			saas: false,
			oss: true,
		},
	},
	{
		id: "wijmo",
		name: "Wijmo",
		website: "https://developer.mescius.com/wijmo",
		description: "Wijmo is a JavaScript UI component library built in TypeScript, ideal for developing lightweight, high-speed HTML5/JavaScript applications with no dependencies, and designed for enterprise use.",
		icon: "Wijmo.svg",
		categories: [
			"transpiler",
			"developer-tooling",
		],
		rules: [
			{
				id: "wijmo:scriptSrc:0",
				kind: "scriptSrc",
				pattern: new RegExp("\\/Scripts\\/Acts\\/Wijmo\\/wijmo\\.min\\.js\\?v=([\\d]+\\.\\d+)"),
				version: {
					source: "match",
					group: 1,
				},
				description: "Script source URL matches a known technology marker.",
			},
			{
				id: "wijmo:jsGlobal:1",
				kind: "jsGlobal",
				property: "wijmo",
				description: "Page-owned global matches a known technology marker.",
			},
		],
		metadata: {
			saas: true,
			oss: false,
			pricing: [
				"low",
				"recurring",
			],
		},
	},
	{
		id: "babel",
		name: "Babel",
		website: "https://babel.dev/",
		description: "A JavaScript compiler that allows developers to use next-generation JavaScript, today.",
		categories: [
			"transpiler",
		],
		rules: [
			{
				id: "babel:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("function\\s+_typeof\\s*\\(\\w+\\)\\s*\\{(?:[^{}]|\\{[^{}]*\\})*typeof\\s+Symbol[^}]+\\}"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "babel:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("function\\s+_classCallCheck\\s*\\(\\w+\\s*,\\s*\\w+\\)\\s*\\{"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "babel:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("function\\s+_defineProperties\\s*\\(\\w+\\s*,\\s*\\w+\\)\\s*\\{"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "babel:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("function\\s+_createClass\\s*\\(\\w+\\s*,\\s*\\w+(?:\\s*,\\s*\\w+)?\\)\\s*\\{"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "babel:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("function\\s+_inherits\\s*\\(\\w+\\s*,\\s*\\w+\\)\\s*\\{[^}]*_setPrototypeOf\\s*\\([^}]+\\}"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "babel:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("@babel\\/runtime\\/helpers\\/"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "babel:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("function\\s+_extends\\(\\)\\s*\\{\\s*_extends\\s*=\\s*Object\\.assign\\s*\\|\\|"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "babel:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("function\\s+_objectSpread\\s*\\(\\w+\\)\\s*\\{"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "babel:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("var\\s+\\w+\\s*=\\s*function\\s*\\(\\)\\s*\\{\\s*function\\s+\\w+\\([^)]*\\)\\s*\\{[^}]*_classCallCheck\\(this,\\s*\\w+\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "babel:scriptContent:modern:9",
				kind: "scriptContent",
				pattern: new RegExp("function\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\s*\\(\\)\\s*{\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\s*=\\s*function\\s*\\(\\)\\s*{\\s*return\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\s*}\\s*;"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "babel:scriptContent:modern:10",
				kind: "scriptContent",
				pattern: new RegExp("_decorate\\(\\[\\s*\\w+(?:\\s*,\\s*\\w+)*\\s*\\],\\s*\\w+\\.prototype,\\s*[\"'][^\"']+[\"']"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "babel:scriptContent:modern:11",
				kind: "scriptContent",
				pattern: new RegExp("[a-zA-Z$_][a-zA-Z$_0-9]*\\._invoke\\s*=\\s*{\\s*value\\s*:\\s*function\\s*\\([a-zA-Z$_][a-zA-Z$_0-9]*,\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "babel:scriptContent:modern:12",
				kind: "scriptContent",
				pattern: new RegExp("[a-zA-Z$_][a-zA-Z$_0-9]*\\(\\)\\s*\\.\\s*mark\\s*\\(\\s*function\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\s*\\(.*?\\)\\s*{\\s*return\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\(\\)\\s*\\.\\s*wrap"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "babel:scriptContent:modern:13",
				kind: "scriptContent",
				pattern: new RegExp("function\\s+_asyncToGenerator\\s*\\(\\s*fn\\s*\\)\\s*\\{"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "babel:scriptContent:modern:14",
				kind: "scriptContent",
				pattern: new RegExp("regeneratorRuntime\\.mark\\(function\\s+_callee\\("),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "babel:scriptContent:modern:15",
				kind: "scriptContent",
				pattern: new RegExp("function\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\s*\\([a-zA-Z$_][a-zA-Z$_0-9]*,\\s*[a-zA-Z$_][a-zA-Z$_0-9]*,\\s*[a-zA-Z$_][a-zA-Z$_0-9]*,\\s*[a-zA-Z$_][a-zA-Z$_0-9]*,\\s*[a-zA-Z$_][a-zA-Z$_0-9]*,\\s*[a-zA-Z$_][a-zA-Z$_0-9]*,\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\)\\s*{\\s*try\\s*{\\s*var\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\s*=\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\[[a-zA-Z$_][a-zA-Z$_0-9]*\\]\\([a-zA-Z$_][a-zA-Z$_0-9]*\\)"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "babel:scriptContent:modern:16",
				kind: "scriptContent",
				pattern: new RegExp("\\[\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\s*\\|\\|\\s*\"@@iterator\"\\s*\\]"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "babel:scriptContent:modern:17",
				kind: "scriptContent",
				pattern: new RegExp("function\\s+_objectWithoutProperties\\s*\\([^)]+\\)\\s*\\{"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "babel:scriptContent:modern:18",
				kind: "scriptContent",
				pattern: new RegExp("function\\s+_objectWithoutPropertiesLoose\\s*\\([^)]+\\)\\s*\\{"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "babel:scriptContent:modern:19",
				kind: "scriptContent",
				pattern: new RegExp("\\w+===(?:void\\s*0|null)\\?\\s*void\\s*0:\\w+\\.\\w+"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "babel:scriptContent:modern:20",
				kind: "scriptContent",
				pattern: new RegExp("\\w+!==(?:void\\s*0|null)&&\\w+!==void\\s*0\\?\\w+:"),
				confidence: 65,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "babel:scriptContent:modern:21",
				kind: "scriptContent",
				pattern: new RegExp("var\\s+\\w+\\s*=\\s*\\w+\\s*==\\s*null\\s*\\?\\s*void\\s*0\\s*:\\s*\\w+(?:\\[|\\.)(?:[^;]|;(?=[^;]))*;"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "babel:scriptContent:modern:22",
				kind: "scriptContent",
				pattern: new RegExp("var\\s+\\w+\\s*=\\s*\\w+\\s*===?\\s*null\\s*\\|\\|\\s*\\w+\\s*===?\\s*void\\s*0\\s*\\?\\s*\\w+\\s*:\\s*\\w+"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "babel:scriptContent:modern:23",
				kind: "scriptContent",
				pattern: new RegExp("\\w+\\s*!==\\s*null\\s*&&\\s*\\w+\\s*!==\\s*void\\s*0\\s*\\?\\s*\\w+\\s*:"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "babel:scriptContent:modern:24",
				kind: "scriptContent",
				pattern: new RegExp("\\w+\\s*===\\s*null\\s*\\|\\|\\s*\\w+\\s*===\\s*void\\s*0\\s*\\?\\s*void\\s*0\\s*:\\s*\\w+\\.\\w+"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "babel:scriptContent:modern:25",
				kind: "scriptContent",
				pattern: new RegExp("var\\s+\\w+\\s*=\\s*new\\s+WeakMap\\(\\);\\s*var\\s+\\w+\\s*=\\s*function\\s*\\w+\\s*\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "babel:scriptContent:modern:26",
				kind: "scriptContent",
				pattern: new RegExp("Object\\.defineProperty\\(\\w+\\.prototype,\\s*[\"'][^\"']+[\"'],\\s*\\{\\s*configurable:\\s*true,\\s*writable:\\s*true,\\s*value:"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "babel:scriptContent:modern:27",
				kind: "scriptContent",
				pattern: new RegExp("Object\\.defineProperty\\(exports,\\s*[\"']__esModule[\"'],\\s*\\{\\s*value:\\s*true\\s*\\}\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "babel:scriptContent:modern:28",
				kind: "scriptContent",
				pattern: new RegExp("exports\\.(?:default|[\\w$]+)\\s*=\\s*void\\s*0"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "babel:scriptContent:modern:29",
				kind: "scriptContent",
				pattern: new RegExp("exports\\[[\"']default[\"']\\]\\s*=\\s*\\w+"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "babel:scriptContent:modern:30",
				kind: "scriptContent",
				pattern: new RegExp("Promise\\.resolve\\(\\)\\.\\s*then\\(function\\s*\\(\\)\\s*\\{\\s*return\\s*require\\("),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
	{
		id: "sucrase",
		name: "Sucrase",
		website: "https://sucrase.io/",
		description: "A JavaScript compiler that allows developers to use next-generation JavaScript, today.",
		categories: [
			"transpiler",
		],
		rules: [
			{
				id: "sucrase:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("exports\\.__esModule\\s*=\\s*true;\\s*exports\\.\\w+\\s*=\\s*void\\s*0"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "sucrase:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("exports\\.default\\s*=\\s*\\w+;\\s*module\\.exports\\s*=\\s*exports\\.default"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "sucrase:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("exports\\.\\{[^}]+\\}\\s*=\\s*\\w+[;,]\\s*exports\\."),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "sucrase:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("React\\.createElement\\(\\s*[\\w$]+,\\s*(?:\\{[^}]*\\}|null),\\s*(?:[^;,]+)\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "sucrase:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("React\\.createElement\\(React\\.Fragment,\\s*null,\\s*(?:[^;,]+)\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "sucrase:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("Object\\.defineProperty\\(\\w+,\\s*[\"']\\w+[\"'],\\s*\\{\\s*enumerable:\\s*true,\\s*value:\\s*(?:[^}]+)\\}\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "sucrase:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("var\\s+(\\w+)\\s*=\\s*(?:require\\([\"'][^\"']+[\"']\\)|\\w+)(?:\\s*,\\s*\\w+\\s*=\\s*(?:require\\([\"'][^\"']+[\"']\\)|\\w+))*;"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "sucrase:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("var\\s*\\{\\s*(?:\\w+\\s*(?::\\s*\\w+)?\\s*(?:,\\s*\\w+\\s*(?::\\s*\\w+)?)*\\s*)\\}\\s*=\\s*\\w+;"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
	{
		id: "typescript",
		name: "TypeScript",
		website: "https://www.typescriptlang.org/",
		description: "Typed superset of JavaScript that compiles to plain JavaScript.",
		categories: [
			"transpiler",
		],
		rules: [
			{
				id: "typescript:scriptContent:modern:0",
				kind: "scriptContent",
				pattern: new RegExp("var\\s+__decorate\\s*=\\s*\\(this\\s*&&\\s*this\\.__decorate\\)\\s*\\|\\|\\s*function\\s*\\(decorators,\\s*target[^)]*\\)\\s*\\{"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "typescript:scriptContent:modern:1",
				kind: "scriptContent",
				pattern: new RegExp("var\\s+__metadata\\s*=\\s*\\(this\\s*&&\\s*this\\.__metadata\\)\\s*\\|\\|\\s*function\\s*\\(k,\\s*v\\)\\s*\\{"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "typescript:scriptContent:modern:2",
				kind: "scriptContent",
				pattern: new RegExp("var\\s+__param\\s*=\\s*\\(this\\s*&&\\s*this\\.__param\\)\\s*\\|\\|\\s*function\\s*\\(paramIndex,\\s*decorator\\)\\s*\\{"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "typescript:scriptContent:modern:3",
				kind: "scriptContent",
				pattern: new RegExp("__decorate\\(\\[\\s*\\w+(?:\\([^)]*\\))?\\s*\\],\\s*\\w+\\.prototype,\\s*[\"'][^\"']+[\"']"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "typescript:scriptContent:modern:4",
				kind: "scriptContent",
				pattern: new RegExp("__param\\(\\d+,\\s*\\w+(?:\\([^)]*\\))?\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "typescript:scriptContent:modern:5",
				kind: "scriptContent",
				pattern: new RegExp("var\\s+__awaiter\\s*=\\s*\\(this\\s*&&\\s*this\\.__awaiter\\)\\s*\\|\\|\\s*function"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "typescript:scriptContent:modern:6",
				kind: "scriptContent",
				pattern: new RegExp("var\\s+__generator\\s*=\\s*\\(this\\s*&&\\s*this\\.__generator\\)\\s*\\|\\|\\s*function"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "typescript:scriptContent:modern:7",
				kind: "scriptContent",
				pattern: new RegExp("var\\s+__spreadArray\\s*=\\s*\\(this\\s*&&\\s*this\\.__spreadArray\\)\\s*\\|\\|\\s*function"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "typescript:scriptContent:modern:8",
				kind: "scriptContent",
				pattern: new RegExp("var\\s+__extends\\s*=\\s*\\(this\\s*&&\\s*this\\.__extends\\)\\s*\\|\\|\\s*function"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "typescript:scriptContent:modern:9",
				kind: "scriptContent",
				pattern: new RegExp("var\\s+__assign\\s*=\\s*\\(this\\s*&&\\s*this\\.__assign\\)\\s*\\|\\|\\s*function\\s*\\(\\)\\s*\\{\\s*__assign\\s*=\\s*Object\\.assign"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "typescript:scriptContent:modern:10",
				kind: "scriptContent",
				pattern: new RegExp("var\\s+__importDefault\\s*=\\s*\\(this\\s*&&\\s*this\\.__importDefault\\)\\s*\\|\\|\\s*function\\s*\\(mod\\)\\s*\\{"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "typescript:scriptContent:modern:11",
				kind: "scriptContent",
				pattern: new RegExp("var\\s+__importStar\\s*=\\s*\\(this\\s*&&\\s*this\\.__importStar\\)\\s*\\|\\|\\s*function\\s*\\(mod\\)\\s*\\{"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "typescript:scriptContent:modern:12",
				kind: "scriptContent",
				pattern: new RegExp("exports\\.\\w+\\s*=\\s*\\{\\s*__proto__:\\s*null\\s*\\};"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "typescript:scriptContent:modern:13",
				kind: "scriptContent",
				pattern: new RegExp("(?:\\(0,\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\.C6\\)|__extends)\\s*\\(\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\s*,\\s*_super\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "typescript:scriptContent:modern:14",
				kind: "scriptContent",
				pattern: new RegExp("Object\\.defineProperty\\s*\\([a-zA-Z$_][a-zA-Z$_0-9]*,\\s*[a-zA-Z$_][a-zA-Z$_0-9]*,\\s*\\{\\s*enumerable:\\s*(?:true|false),\\s*get:\\s*function"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "typescript:scriptContent:modern:15",
				kind: "scriptContent",
				pattern: new RegExp("r\\.d\\s*\\(\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\s*,\\s*\\{\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\s*:\\s*\\(\\)\\s*=>\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\s*\\}\\)"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "typescript:scriptContent:modern:16",
				kind: "scriptContent",
				pattern: new RegExp("if\\s*\\(\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\s*===\\s*void\\s+0\\s*\\)\\s*\\{\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\s*="),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "typescript:scriptContent:modern:17",
				kind: "scriptContent",
				pattern: new RegExp("=\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\s*===\\s*void\\s+0\\s*\\?\\s*[^:]+\\s*:\\s*[a-zA-Z$_][a-zA-Z$_0-9]*[,;)]"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "typescript:scriptContent:modern:18",
				kind: "scriptContent",
				pattern: new RegExp("^[\"']use strict[\"'];", "m"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "typescript:scriptContent:modern:19",
				kind: "scriptContent",
				pattern: new RegExp("(?:\\(0,\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\.Cl\\)|__assign)\\s*\\(\\s*\\{\\s*\\}"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "typescript:scriptContent:modern:20",
				kind: "scriptContent",
				pattern: new RegExp("var\\s+\\w+\\s*;\\s*\\(\\s*function\\s*\\(\\w+\\)\\s*\\{\\s*\\w+\\[\\w+\\[\"\\w+\"\\]\\s*=\\s*\\d+\\]\\s*=\\s*\"\\w+\""),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "typescript:scriptContent:modern:21",
				kind: "scriptContent",
				pattern: new RegExp("\\b\\d+\\s*\\/\\*\\s*\\w+\\.\\w+\\s*\\*\\/"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "typescript:scriptContent:modern:22",
				kind: "scriptContent",
				pattern: new RegExp("\\w+\\[\\w+\\[\"\\w+\"\\]\\s*=\\s*\"\\w+\"\\]\\s*=\\s*\"\\w+\""),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "typescript:scriptContent:modern:23",
				kind: "scriptContent",
				pattern: new RegExp("\\w+\\[\\w+\\[\\w+\\s*=\\s*\\w+\\.\\w+\\]\\s*=\\s*\\w+\\]"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
			{
				id: "typescript:scriptContent:modern:24",
				kind: "scriptContent",
				pattern: new RegExp("void\\s+0\\s*===\\s*[a-zA-Z$_][a-zA-Z$_0-9]*|[a-zA-Z$_][a-zA-Z$_0-9]*\\s*===\\s*void\\s+0"),
				confidence: 45,
				description: "Bundled script content matches a modern tooling marker.",
			},
		],
	},
] as const satisfies readonly TechnologyDefinition[];
