import type { DetectionRule, RuntimeDetectionKind, TechnologyDefinition } from '../detection/types';
import type { NormalizedObservationKind } from '../observations';

/** Current JSON registry asset schema version. */
export const PACKAGED_REGISTRY_ASSET_SCHEMA_VERSION = 1;

/** Literal JSON registry asset schema version used by runtime guards. */
export type PackagedRegistryAssetSchemaVersion = typeof PACKAGED_REGISTRY_ASSET_SCHEMA_VERSION;

/** Runtime observation kinds that can be matched by generated registry shards. */
export const PACKAGED_REGISTRY_OBSERVATION_KINDS = [
	'url',
	'htmlMatch',
	'meta',
	'dom',
	'header',
	'responseHeader',
	'link',
	'cookie',
	'storage',
	'jsGlobal',
	'scriptSrc',
	'stylesheetHref',
	'resourceUrl',
	'requestUrl',
	'requestHeader',
	'html',
	'text',
	'scriptContent',
	'stylesheetContent',
	'robots',
	'dns',
	'certIssuer',
	'probe',
] as const satisfies readonly NormalizedObservationKind[];

/** Observation kind represented by a packaged matcher shard. */
export type PackagedRegistryObservationKind = typeof PACKAGED_REGISTRY_OBSERVATION_KINDS[number];

/** Registry asset kinds copied into the extension output by the WXT module. */
export const PACKAGED_REGISTRY_ASSET_KINDS = ['bootstrap', 'enrichment', 'metadata', 'relationships', 'manifest', 'kind-shard'] as const;

/** Registry asset kind recorded in every generated JSON payload. */
export type PackagedRegistryAssetKind = typeof PACKAGED_REGISTRY_ASSET_KINDS[number];

/** Generated asset paths relative to the extension output root. */
export const PACKAGED_REGISTRY_ASSET_PATHS = Object.freeze({
	bootstrap: 'red-detector-registry/registry.bootstrap.json',
	enrichment: 'red-detector-registry/registry.enrichment.json',
	metadata: 'red-detector-registry/registry.metadata.json',
	relationships: 'red-detector-registry/registry.relationships.json',
	manifest: 'red-detector-registry/registry.manifest.json',
} satisfies Record<Exclude<PackagedRegistryAssetKind, 'kind-shard'>, string>);

/** Encoded regular expression marker used inside JSON registry assets. */
export interface PackagedRegistryRegExpRecord {
	/** Stable marker that distinguishes encoded regexes from ordinary rule objects. */
	readonly $redDetectorRegExp: true;
	/** Original regular expression source. */
	readonly source: string;
	/** Original regular expression flags. */
	readonly flags: string;
}

/** JSON registry asset containing technology definitions for runtime hydration. */
export interface PackagedTechnologyRegistryAsset {
	/** Asset schema version checked before hydration trusts the payload. */
	readonly schemaVersion: PackagedRegistryAssetSchemaVersion;
	/** Technology registry tier represented by the payload. */
	readonly kind: Extract<PackagedRegistryAssetKind, 'bootstrap' | 'enrichment'>;
	/** Ordered technology definitions with regular expressions encoded as JSON records. */
	readonly technologies: readonly unknown[];
	/** Number of rules represented before JSON encoding, used for asset diagnostics. */
	readonly ruleCount: number;
	/** Millisecond timestamp from the build that generated the asset. */
	readonly generatedAt: number;
}

/** Matcher shard containing only rules that can receive one observation kind. */
export interface PackagedTechnologyRegistryShardAsset {
	/** Asset schema version checked before hydration trusts the payload. */
	readonly schemaVersion: PackagedRegistryAssetSchemaVersion;
	/** Shard payload kind. */
	readonly kind: Extract<PackagedRegistryAssetKind, 'kind-shard'>;
	/** Observation kind routed to this shard. */
	readonly observationKind: PackagedRegistryObservationKind;
	/** Ordered technology definitions whose rules are narrowed for this observation kind. */
	readonly technologies: readonly unknown[];
	/** Number of rules represented before JSON encoding, used for diagnostics. */
	readonly ruleCount: number;
	/** Number of technologies that still own at least one rule in the shard. */
	readonly technologyCount: number;
	/** Scheduler priority assigned to this observation kind. */
	readonly priority: number;
	/** Millisecond timestamp from the build that generated the asset. */
	readonly generatedAt: number;
}

/** Manifest entry for one generated observation-kind shard. */
export interface PackagedRegistryShardManifestEntry {
	/** Observation kind routed to the shard. */
	readonly observationKind: PackagedRegistryObservationKind;
	/** Asset path relative to the extension root. */
	readonly path: string;
	/** Number of rules in the shard. */
	readonly ruleCount: number;
	/** Number of technologies represented in the shard. */
	readonly technologyCount: number;
	/** Scheduler priority assigned to this observation kind. */
	readonly priority: number;
}

/** Manifest describing every observation-kind shard generated by the compiler. */
export interface PackagedRegistryShardManifestAsset {
	/** Asset schema version checked before consumers trust the payload. */
	readonly schemaVersion: PackagedRegistryAssetSchemaVersion;
	/** Manifest asset kind. */
	readonly kind: Extract<PackagedRegistryAssetKind, 'manifest'>;
	/** Shard descriptors keyed by observation kind. */
	readonly shards: Readonly<Record<PackagedRegistryObservationKind, PackagedRegistryShardManifestEntry>>;
	/** Millisecond timestamp from the build that generated the asset. */
	readonly generatedAt: number;
}

/** Metadata asset used by tests, diagnostics, and future popup display loading. */
export interface PackagedRegistryMetadataAsset {
	/** Asset schema version checked before consumers trust the payload. */
	readonly schemaVersion: PackagedRegistryAssetSchemaVersion;
	/** Metadata asset kind. */
	readonly kind: Extract<PackagedRegistryAssetKind, 'metadata'>;
	/** Lightweight technology metadata in detector order. */
	readonly technologyMetadata: readonly unknown[];
	/** Rule-kind counts for diagnostics and benchmark setup. */
	readonly patternTables: Readonly<Record<string, number>>;
	/** Millisecond timestamp from the build that generated the asset. */
	readonly generatedAt: number;
}

/** Relationship asset used to inspect graph data without reading full rules. */
export interface PackagedRegistryRelationshipsAsset {
	/** Asset schema version checked before consumers trust the payload. */
	readonly schemaVersion: PackagedRegistryAssetSchemaVersion;
	/** Relationship asset kind. */
	readonly kind: Extract<PackagedRegistryAssetKind, 'relationships'>;
	/** Relationship edges in compiler order. */
	readonly relationshipEdges: readonly unknown[];
	/** Millisecond timestamp from the build that generated the asset. */
	readonly generatedAt: number;
}

/** Rule kinds safe for the small bootstrap registry asset kept for compatibility tests. */
const BOOTSTRAP_RULE_KINDS = Object.freeze({
	cookie: true,
	dom: true,
	jsGlobal: true,
	link: true,
	meta: true,
	storage: true,
	url: true,
} satisfies Partial<Record<TechnologyDefinition['rules'][number]['kind'], true>>);

/** Priority table shared by generated shard metadata and matcher scheduling docs. */
const OBSERVATION_KIND_PRIORITIES = Object.freeze({
	url: 1,
	htmlMatch: 1,
	meta: 1,
	dom: 1,
	header: 2,
	responseHeader: 2,
	link: 2,
	cookie: 2,
	storage: 2,
	jsGlobal: 2,
	scriptSrc: 3,
	stylesheetHref: 3,
	resourceUrl: 3,
	requestUrl: 3,
	requestHeader: 3,
	html: 4,
	text: 4,
	scriptContent: 4,
	stylesheetContent: 4,
	robots: 4,
	dns: 4,
	certIssuer: 4,
	probe: 4,
} satisfies Record<PackagedRegistryObservationKind, number>);

/** Return a registry whose rules are limited to cheap page-local startup evidence. */
export function createBootstrapTechnologyRegistry(
	technologies: readonly TechnologyDefinition[],
): readonly TechnologyDefinition[] {
	return technologies
		.map((technology) => ({
			...technology,
			rules: technology.rules.filter((rule) => hasRuleKind(BOOTSTRAP_RULE_KINDS, rule.kind)),
		}))
		.filter((technology) => technology.rules.length > 0);
}

/** Return the generated asset path for one matcher shard. */
export function getPackagedRegistryShardAssetPath(kind: PackagedRegistryObservationKind): string {
	return `red-detector-registry/registry.kind.${kind}.json`;
}

/** Return scheduler priority recorded in the shard manifest. */
export function getPackagedRegistryShardPriority(kind: PackagedRegistryObservationKind): number {
	return OBSERVATION_KIND_PRIORITIES[kind];
}

/** Convert runtime observation kinds to the generated shard key. */
export function normalizePackagedRegistryObservationKind(kind: NormalizedObservationKind): PackagedRegistryObservationKind {
	return kind === 'htmlMatch' ? 'htmlMatch' : kind;
}

/** Return a registry narrowed to rules that can match one observation kind. */
export function createObservationKindTechnologyRegistry(
	technologies: readonly TechnologyDefinition[],
	observationKind: NormalizedObservationKind,
): readonly TechnologyDefinition[] {
	const normalizedObservationKind = normalizePackagedRegistryObservationKind(observationKind);
	return technologies
		.map((technology) => ({
			...technology,
			rules: technology.rules
				.map((rule, ruleIndex) => ({ rule, ruleIndex }))
				.filter(({ rule }) => canRuleReceiveObservationKind(rule, normalizedObservationKind))
				.map(({ rule, ruleIndex }) => preserveSourceRuleIndex(rule, ruleIndex)),
		}))
		.filter((technology) => technology.rules.length > 0);
}


/** Preserve full-registry rule order after a shard drops unrelated rule kinds. */
function preserveSourceRuleIndex(rule: DetectionRule, sourceRuleIndex: number): DetectionRule {
	return Object.assign({}, rule, { sourceRuleIndex });
}

/** Count rules without walking encoded JSON after asset creation. */
export function countTechnologyRules(technologies: readonly TechnologyDefinition[]): number {
	let count = 0;
	for (const technology of technologies) {
		count += technology.rules.length;
	}
	return count;
}

/** Encode a value so `RegExp` rules survive JSON serialization. */
export function encodeRegistryJsonValue(value: unknown): unknown {
	if (value instanceof RegExp) {
		return {
			$redDetectorRegExp: true,
			source: value.source,
			flags: value.flags,
		} satisfies PackagedRegistryRegExpRecord;
	}

	if (Array.isArray(value)) {
		return value.map((entry) => encodeRegistryJsonValue(entry));
	}

	if (value && typeof value === 'object') {
		const encoded: Record<string, unknown> = Object.create(null) as Record<string, unknown>;
		for (const [key, entry] of Object.entries(value)) {
			if (entry !== undefined) {
				encoded[key] = encodeRegistryJsonValue(entry);
			}
		}
		return encoded;
	}

	return value;
}

/** Decode regular expression records after a packaged registry asset is parsed. */
export function decodeRegistryJsonValue(value: unknown): unknown {
	if (isPackagedRegistryRegExpRecord(value)) {
		return new RegExp(value.source, value.flags);
	}

	if (Array.isArray(value)) {
		return value.map((entry) => decodeRegistryJsonValue(entry));
	}

	if (value && typeof value === 'object') {
		const decoded: Record<string, unknown> = Object.create(null) as Record<string, unknown>;
		for (const [key, entry] of Object.entries(value)) {
			decoded[key] = decodeRegistryJsonValue(entry);
		}
		return decoded;
	}

	return value;
}

/** Guard the encoded regular expression record before constructing a runtime `RegExp`. */
export function isPackagedRegistryRegExpRecord(value: unknown): value is PackagedRegistryRegExpRecord {
	if (typeof value !== 'object' || value === null) {
		return false;
	}

	const candidate = value as Partial<PackagedRegistryRegExpRecord>;
	return (
		candidate.$redDetectorRegExp === true &&
		typeof candidate.source === 'string' &&
		typeof candidate.flags === 'string'
	);
}

/** Guard the registry source asset before runtime hydration walks a large payload. */
export function isPackagedTechnologyRegistryAsset(
	value: unknown,
	kind: Extract<PackagedRegistryAssetKind, 'bootstrap' | 'enrichment'>,
): value is PackagedTechnologyRegistryAsset {
	if (typeof value !== 'object' || value === null) {
		return false;
	}

	const candidate = value as Partial<PackagedTechnologyRegistryAsset>;
	return (
		candidate.schemaVersion === PACKAGED_REGISTRY_ASSET_SCHEMA_VERSION &&
		candidate.kind === kind &&
		Array.isArray(candidate.technologies) &&
		typeof candidate.ruleCount === 'number' &&
		typeof candidate.generatedAt === 'number'
	);
}

/** Guard a matcher shard asset before worker hydration uses its narrowed rules. */
export function isPackagedTechnologyRegistryShardAsset(
	value: unknown,
	observationKind: PackagedRegistryObservationKind,
): value is PackagedTechnologyRegistryShardAsset {
	if (typeof value !== 'object' || value === null) {
		return false;
	}

	const candidate = value as Partial<PackagedTechnologyRegistryShardAsset>;
	return (
		candidate.schemaVersion === PACKAGED_REGISTRY_ASSET_SCHEMA_VERSION &&
		candidate.kind === 'kind-shard' &&
		candidate.observationKind === observationKind &&
		Array.isArray(candidate.technologies) &&
		typeof candidate.ruleCount === 'number' &&
		typeof candidate.technologyCount === 'number' &&
		typeof candidate.priority === 'number' &&
		typeof candidate.generatedAt === 'number'
	);
}

/** Convert a parsed JSON asset into ordered technology definitions. */
export function hydratePackagedTechnologyRegistry(
	asset: PackagedTechnologyRegistryAsset | PackagedTechnologyRegistryShardAsset,
): readonly TechnologyDefinition[] {
	return decodeRegistryJsonValue(asset.technologies) as readonly TechnologyDefinition[];
}

/** Render JSON with stable indentation for reviewable generated artifacts. */
export function renderPackagedRegistryJson(value: unknown): string {
	return `${JSON.stringify(encodeRegistryJsonValue(value), null, 2)}\n`;
}

/** HTML probes reuse `html` rules even when the normalized observation kind is `htmlMatch`. */
function canRuleReceiveObservationKind(
	rule: DetectionRule,
	observationKind: PackagedRegistryObservationKind,
): boolean {
	switch (observationKind) {
		case 'htmlMatch':
			return rule.kind === 'html';
		case 'header':
			return rule.kind === 'header' || rule.kind === 'responseHeader';
		default:
			return rule.kind === observationKind;
	}
}

function hasRuleKind(
	lookup: Partial<Record<RuntimeDetectionKind, true>>,
	kind: DetectionRule['kind'],
): boolean {
	return Object.prototype.hasOwnProperty.call(lookup, kind);
}
