import type { CompiledTechnologyRegistryArtifact } from './compiler';
import type { IndexedObservationRuleBuckets, IndexedObservationKeyBuckets } from '../detection/observation-matcher-index';
import type { TechnologyDefinition } from '../detection/types';

/** Input needed to render a checked-in generated registry module. */
export interface RenderPrecompiledRegistryModuleInput {
	/** Artifact produced by the registry compiler during the WXT build. */
	readonly artifact: CompiledTechnologyRegistryArtifact;
	/** Path used in the generated header so reviewers know what produced the file. */
	readonly generatorPath: string;
}

/**
 * Render the compiled registry as TypeScript code that performs no registry walk.
 *
 * The matcher index is emitted as references into the generated technology array.
 * That keeps rule objects shared with the emitted registry while avoiding the
 * first-popup work of flattening rules, routing matcher buckets, and rebuilding
 * relationship tables inside the background service worker.
 */
export function renderPrecompiledRegistryModule(
	input: RenderPrecompiledRegistryModuleInput,
): string {
	const artifact = input.artifact;
	const technologyIndexById = new Map<string, number>();
	artifact.technologies.forEach((technology, index) => {
		technologyIndexById.set(technology.id, index);
	});

	return [
		'/**',
		` * Generated by ${input.generatorPath}.`,
		' * Do not edit by hand. Run WXT dev/build to refresh this artifact.',
		' */',
		"import type { CompiledTechnologyRegistryArtifact } from '../lib/registry';",
		'',
		`const technologies = ${renderValue(artifact.technologies)} as const satisfies CompiledTechnologyRegistryArtifact['technologies'];`,
		'',
		`const relationshipEdges = ${renderValue(artifact.relationshipGraph.relationshipEdges)} as const;`,
		'',
		'export const precompiledRegistryArtifact = {',
		`\tartifactVersion: ${renderValue(artifact.artifactVersion)},`,
		`\tsourceSchemaVersion: ${renderValue(artifact.sourceSchemaVersion)},`,
		'\ttechnologies,',
		`\ttechnologyMetadata: ${renderValue(artifact.technologyMetadata)},`,
		`\tpatternTables: ${renderValue(artifact.patternTables)},`,
		'\trelationshipGraph: {',
		'\t\ttechnologies: [...technologies],',
		'\t\tdefinitionsById: new Map(technologies.map((technology) => [technology.id, technology])),',
		'\t\tregistryOrderById: new Map(technologies.map((technology, index) => [technology.id, index])),',
		'\t\trelationshipEdges: [...relationshipEdges],',
		'\t},',
		'\tmatcherIndex: {',
		`\t\ttechnologyCount: ${artifact.matcherIndex.technologyCount},`,
		`\t\truleCount: ${artifact.matcherIndex.ruleCount},`,
		`\t\tfallbackRules: ${renderRuleBuckets(artifact.matcherIndex.fallbackRules, technologyIndexById, 2)},`,
		`\t\tkeyedRules: ${renderKeyBuckets(artifact.matcherIndex.keyedRules, technologyIndexById, 2)},`,
		'\t},',
		`\tcollectionPlan: ${renderValue(artifact.collectionPlan)},`,
		`\tsourceMap: ${renderValue(artifact.sourceMap)},`,
		`\tdiagnostics: ${renderValue(artifact.diagnostics)},`,
		"} as const satisfies CompiledTechnologyRegistryArtifact;",
		'',
	].join('\n');
}

function renderRuleBuckets(
	buckets: IndexedObservationRuleBuckets,
	technologyIndexById: ReadonlyMap<string, number>,
	indentLevel: number,
): string {
	const entries = Object.entries(buckets);
	if (entries.length === 0) {
		return '{}';
	}

	const indent = '\t'.repeat(indentLevel);
	const innerIndent = '\t'.repeat(indentLevel + 1);
	const lines = ['{'];
	for (const [kind, rules] of entries) {
		lines.push(`${innerIndent}${JSON.stringify(kind)}: ${renderIndexedRuleArray(rules, technologyIndexById, indentLevel + 1)},`);
	}
	lines.push(`${indent}}`);
	return lines.join('\n');
}

function renderKeyBuckets(
	buckets: IndexedObservationKeyBuckets,
	technologyIndexById: ReadonlyMap<string, number>,
	indentLevel: number,
): string {
	const entries = Object.entries(buckets);
	if (entries.length === 0) {
		return '{}';
	}

	const indent = '\t'.repeat(indentLevel);
	const kindIndent = '\t'.repeat(indentLevel + 1);
	const keyIndent = '\t'.repeat(indentLevel + 2);
	const lines = ['{'];
	for (const [kind, keyBuckets] of entries) {
		lines.push(`${kindIndent}${JSON.stringify(kind)}: {`);
		for (const [key, rules] of Object.entries(keyBuckets)) {
			lines.push(`${keyIndent}${JSON.stringify(key)}: ${renderIndexedRuleArray(rules, technologyIndexById, indentLevel + 2)},`);
		}
		lines.push(`${kindIndent}},`);
	}
	lines.push(`${indent}}`);
	return lines.join('\n');
}

function renderIndexedRuleArray(
	rules: readonly { readonly technology: TechnologyDefinition; readonly ruleIndex: number; readonly sequence: number }[],
	technologyIndexById: ReadonlyMap<string, number>,
	indentLevel: number,
): string {
	if (rules.length === 0) {
		return '[]';
	}

	const indent = '\t'.repeat(indentLevel);
	const itemIndent = '\t'.repeat(indentLevel + 1);
	const lines = ['['];
	for (const rule of rules) {
		const technologyIndex = technologyIndexById.get(rule.technology.id);
		if (technologyIndex === undefined) {
			throw new Error(`Cannot render matcher rule for unknown technology ${rule.technology.id}`);
		}

		lines.push(
			`${itemIndent}{ technology: technologies[${technologyIndex}]!, rule: technologies[${technologyIndex}]!.rules[${rule.ruleIndex}]!, ruleIndex: ${rule.ruleIndex}, sequence: ${rule.sequence} },`,
		);
	}
	lines.push(`${indent}]`);
	return lines.join('\n');
}

function renderValue(value: unknown): string {
	if (value instanceof RegExp) {
		return `new RegExp(${JSON.stringify(value.source)}, ${JSON.stringify(value.flags)})`;
	}
	if (Array.isArray(value)) {
		return `[${value.map((entry) => renderValue(entry)).join(', ')}]`;
	}
	if (value && typeof value === 'object') {
		const entries = Object.entries(value as Record<string, unknown>)
			.filter(([, entry]) => entry !== undefined)
			.map(([key, entry]) => `${JSON.stringify(key)}: ${renderValue(entry)}`);
		return `{ ${entries.join(', ')} }`;
	}
	if (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean' || value === null) {
		return JSON.stringify(value);
	}
	if (value === undefined) {
		return 'undefined';
	}

	throw new Error(`Cannot render registry artifact value of type ${typeof value}`);
}
