import type { TechnologyDefinition } from '../../types';

export const emotionTechnologyDefinition = {
	id: "emotion",
	name: "Emotion",
	website: "https://emotion.sh",
	description: "Emotion is a library designed for writing CSS styles with JavaScript.",
	icon: "Emotion.png",
	categories: [
		"styling-processor",
		"ui-library",
		"developer-tooling",
	],
	rules: [
		{
			id: "emotion:dom:0",
			kind: "dom",
			selector: "style[data-emotion], style[data-emotion-css]",
			description: "DOM selector matches a known technology marker.",
		},
		{
			id: "emotion:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("\\.getAttribute\\([\"']data-emotion[\"']\\)"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "emotion:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("\\w+\\.setAttribute\\([\"']data-emotion[\"']\\s*,\\s*\\w+(?:\\.\\w+)?(?:\\s*\\+\\s*[^\\)]+)?\\)"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "emotion:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("\\.querySelectorAll\\([\"']style\\[data-emotion\\]:not\\(\\[data-s\\]\\)[\"']\\)"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "emotion:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("\\{\"key\":\"[\\w-]+\",\"nonce\":\"[\\w-]*\",\"insertionPoint\":[\\w\\s\\.\"]+\\}"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "emotion:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("\\w+\\.__emotion_styles\\b"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "emotion:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("\\w+\\.__emotion_real\\b"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "emotion:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("\\w+\\.__emotion_forwardProp\\b"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "emotion:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("\\.withComponent=function\\([\\w$]+\\)\\{return[\\w$]+\\([\\w$]+,\\{target:[\\w$]+\\.target\\}\\)\\}"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "emotion:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("Symbol\\.for\\([\"']emotion-[\\w-]+[\"']\\)"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "emotion:stylesheetContent:modern:9",
			kind: "stylesheetContent",
			pattern: new RegExp("\\.css-[\\w-]+-EmotionCSS-[\\w-]+\\[data-emotion-[\\w-]+\\]"),
			confidence: 45,
			description: "Stylesheet content matches a modern styling marker.",
		},
		{
			id: "emotion:stylesheetContent:modern:10",
			kind: "stylesheetContent",
			pattern: new RegExp("@keyframes\\s+emotion-[\\w-]+-[\\w-]+"),
			confidence: 45,
			description: "Stylesheet content matches a modern styling marker.",
		},
		{
			id: "emotion:stylesheetContent:modern:11",
			kind: "stylesheetContent",
			pattern: new RegExp("\\[data-emotion-global-[\\w-]+\\]"),
			confidence: 45,
			description: "Stylesheet content matches a modern styling marker.",
		},
		{
			id: "emotion:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("\\[@emotion\\/styled\\]"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "emotion:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("\\[@emotion\\/react\\]"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "emotion:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("\\[@emotion\\/css\\]"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "emotion:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("import\\s*\\{\\s*css\\s*\\}\\s*from\\s*[\"']@emotion\\/react[\"']"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
	metadata: {
		oss: true,
	},
} as const satisfies TechnologyDefinition;
