import type { TechnologyDefinition } from '../../types';

export const styledComponentsTechnologyDefinition = {
	id: "styled-components",
	name: "styled-components",
	website: "https://styled-components.com",
	description: "Styled components is a CSS-in-JS styling framework that uses tagged template literals in JavaScript.",
	icon: "styled-components.svg",
	categories: [
		"styling-processor",
		"ui-library",
		"developer-tooling",
	],
	rules: [
		{
			id: "styled-components:dom:0",
			kind: "dom",
			selector: "[sc-component-id]",
			description: "DOM selector matches a known technology marker.",
		},
		{
			id: "styled-components:dom:1",
			kind: "dom",
			selector: "style[data-styled-version]",
			description: "DOM selector matches a known technology marker.",
		},
		{
			id: "styled-components:dom:2",
			kind: "dom",
			selector: "style[data-styled], style[data-styled-components], [sc-component-id]",
			description: "DOM selector matches a known technology marker.",
		},
		{
			id: "styled-components:jsGlobal:3",
			kind: "jsGlobal",
			property: "styled",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "styled-components:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("\\[\\$\\$typeof\\]=Symbol\\.for\\([\"']sc_element[\"']\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "styled-components:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("\\.__sc-[\\da-zA-Z]{8}-[\\da-zA-Z]{4}={"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "styled-components:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("\\.styledComponentId=[\"']sc-[\\da-zA-Z]{8}-[\\da-zA-Z]{4}[\"']"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "styled-components:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("\\.withConfig\\(\\{\"componentId\":[\"']sc-[\\da-zA-Z]{8}-[\\da-zA-Z]{4}[\"']\\}\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "styled-components:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("\\.attrs\\(\\{[\"']data-sc-[\\da-zA-Z]{8}[\"']:"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "styled-components:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("sc_createGlobalStyle\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "styled-components:stylesheetContent:modern:6",
			kind: "stylesheetContent",
			pattern: new RegExp("\\.sc-[\\da-zA-Z]{8}-[\\da-zA-Z]{4}\\[data-sc-[\\da-zA-Z]{8}\\]"),
			confidence: 45,
			description: "Stylesheet content matches a modern styling marker.",
		},
		{
			id: "styled-components:stylesheetContent:modern:7",
			kind: "stylesheetContent",
			pattern: new RegExp("@keyframes\\s+sc-keyframes-[\\da-zA-Z]{8}"),
			confidence: 45,
			description: "Stylesheet content matches a modern styling marker.",
		},
		{
			id: "styled-components:stylesheetContent:modern:8",
			kind: "stylesheetContent",
			pattern: new RegExp("sc-global-[\\da-zA-Z]{8}"),
			confidence: 45,
			description: "Stylesheet content matches a modern styling marker.",
		},
		{
			id: "styled-components:stylesheetContent:modern:9",
			kind: "stylesheetContent",
			pattern: new RegExp("\\[data-sc-[\\da-zA-Z]{8}\\]{"),
			confidence: 45,
			description: "Stylesheet content matches a modern styling marker.",
		},
		{
			id: "styled-components:stylesheetContent:modern:10",
			kind: "stylesheetContent",
			pattern: new RegExp("--sc-[\\da-zA-Z]{8}-[\\da-zA-Z]{4}"),
			confidence: 45,
			description: "Stylesheet content matches a modern styling marker.",
		},
		{
			id: "styled-components:stylesheetContent:modern:11",
			kind: "stylesheetContent",
			pattern: new RegExp("content:var\\(--sc-[\\da-zA-Z]{8}-[\\da-zA-Z]{4}\\)"),
			confidence: 45,
			description: "Stylesheet content matches a modern styling marker.",
		},
	],
	implies: [
		"react",
	],
} as const satisfies TechnologyDefinition;
