import type { TechnologyDefinition } from '../../types';

export const apolloGraphqlTechnologyDefinition = {
	id: "apollo-graphql",
	name: "Apollo GraphQL",
	website: "https://www.apollographql.com/",
	description: "A comprehensive state management library for JavaScript with GraphQL",
	categories: [
		"api-pattern",
		"http-client",
	],
	rules: [
		{
			id: "apollo-graphql:resourceUrl:modern:0",
			kind: "resourceUrl",
			pattern: new RegExp("@apollo\\/client[.\\-@/]"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "apollo-graphql:resourceUrl:modern:1",
			kind: "resourceUrl",
			pattern: new RegExp("apollo-client[.\\-@/]"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "apollo-graphql:resourceUrl:modern:2",
			kind: "resourceUrl",
			pattern: new RegExp("apollo-boost[.\\-@/]"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "apollo-graphql:html:modern:3",
			kind: "html",
			pattern: new RegExp("__APOLLO_STATE__"),
			confidence: 75,
			description: "Document HTML matches a modern tooling marker.",
		},
		{
			id: "apollo-graphql:html:modern:4",
			kind: "html",
			pattern: new RegExp("__APOLLO_CLIENT__"),
			confidence: 75,
			description: "Document HTML matches a modern tooling marker.",
		},
		{
			id: "apollo-graphql:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("\"Cache data may be lost when replacing the \\w+ field of a Query object\\."),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "apollo-graphql:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("\"Missing selection set for object of type [^\"]+ returned for query field [^\"]+\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "apollo-graphql:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("\"keyArgs\":\\[\"sort\",\"limit\"\\],\"merge\":function"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "apollo-graphql:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("https:\\/\\/go\\.apollo\\.dev\\/c\\/err#"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "apollo-graphql:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("Symbol\\.for\\(\"ApolloErrorMessageHandler_[^\"]+\"\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "apollo-graphql:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("Symbol\\.for\\(\"apollo\\.dataMasking\"\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "apollo-graphql:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("http:\\/\\/dev\\.apollodata\\.com\\/core\\/fragments\\.html"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "apollo-graphql:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("Warning: fragment with name .+ already exists\\.[^\"]+unique-names"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "apollo-graphql:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("\\[\"ROOT_QUERY\"\\]|\\[\"ROOT_MUTATION\"\\]"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "apollo-graphql:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("\"__ref\":\"[^\"]+:\\{\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "apollo-graphql:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("\"storeFactory\",\"cacheKeyRoot\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "apollo-graphql:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("\"__APOLLO_CLIENT__\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "apollo-graphql:header:modern:17",
			kind: "header",
			key: "apollo-operation-name",
			valuePattern: new RegExp(".*"),
			confidence: 55,
			description: "HTTP response header matches a modern tooling marker.",
		},
		{
			id: "apollo-graphql:header:modern:18",
			kind: "header",
			key: "apollo-preflight",
			valuePattern: new RegExp("true"),
			confidence: 55,
			description: "HTTP response header matches a modern tooling marker.",
		},
		{
			id: "apollo-graphql:header:modern:19",
			kind: "header",
			key: "apollo-federation-include-trace",
			valuePattern: new RegExp(".*"),
			confidence: 55,
			description: "HTTP response header matches a modern tooling marker.",
		},
		{
			id: "apollo-graphql:header:modern:20",
			kind: "header",
			key: "apollo-require-preflight",
			valuePattern: new RegExp("true"),
			confidence: 55,
			description: "HTTP response header matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
