import type { TechnologyDefinition } from '../../types';

export const urqlTechnologyDefinition = {
	id: "urql",
	name: "urql",
	website: "https://formidable.com/open-source/urql/",
	description: "A highly customizable and versatile GraphQL client",
	categories: [
		"api-pattern",
		"http-client",
	],
	rules: [
		{
			id: "urql:resourceUrl:modern:0",
			kind: "resourceUrl",
			pattern: new RegExp("urql[.\\-@/]"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "urql:resourceUrl:modern:1",
			kind: "resourceUrl",
			pattern: new RegExp("@urql\\/"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "urql:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("\"urql\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "urql:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("\"@urql\\/core\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "urql:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("\"@urql\\/exchange-graphcache\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "urql:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("\"urqlClient\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "urql:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("\"@urql\\/core: "),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "urql:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("\"No exchange has handled this operation\""),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "urql:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("\"The exchanges have been set up incorrectly\""),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "urql:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("\"No more operations can be spawned\""),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "urql:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("\"fetchExchange: Network request failed\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "urql:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("\"cacheExchange: Invalid undefined value\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "urql:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("\"subscriptionExchange: Failed to connect\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "urql:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("\\{(?:[^}]*exchanges:\\s*\\[[^]]+\\],[^}]*url:|url:[^,]+,exchanges:\\s*\\[[^]]+\\])"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "urql:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("\\{query:[^,]+,variables:[^,]+,pause:"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "urql:header:modern:15",
			kind: "header",
			key: "x-graphql-event-stream",
			valuePattern: new RegExp("true"),
			confidence: 55,
			description: "HTTP response header matches a modern tooling marker.",
		},
		{
			id: "urql:header:modern:16",
			kind: "header",
			key: "x-graphql-transport-ws",
			valuePattern: new RegExp("true"),
			confidence: 55,
			description: "HTTP response header matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
