import type { TechnologyDefinition } from '../../types';

export const babelTechnologyDefinition = {
	id: "babel",
	name: "Babel",
	website: "https://babel.dev/",
	description: "A JavaScript compiler that allows developers to use next-generation JavaScript, today.",
	categories: [
		"transpiler",
	],
	rules: [
		{
			id: "babel:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("function\\s+_typeof\\s*\\(\\w+\\)\\s*\\{(?:[^{}]|\\{[^{}]*\\})*typeof\\s+Symbol[^}]+\\}"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "babel:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("function\\s+_classCallCheck\\s*\\(\\w+\\s*,\\s*\\w+\\)\\s*\\{"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "babel:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("function\\s+_defineProperties\\s*\\(\\w+\\s*,\\s*\\w+\\)\\s*\\{"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "babel:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("function\\s+_createClass\\s*\\(\\w+\\s*,\\s*\\w+(?:\\s*,\\s*\\w+)?\\)\\s*\\{"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "babel:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("function\\s+_inherits\\s*\\(\\w+\\s*,\\s*\\w+\\)\\s*\\{[^}]*_setPrototypeOf\\s*\\([^}]+\\}"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "babel:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("@babel\\/runtime\\/helpers\\/"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "babel:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("function\\s+_extends\\(\\)\\s*\\{\\s*_extends\\s*=\\s*Object\\.assign\\s*\\|\\|"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "babel:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("function\\s+_objectSpread\\s*\\(\\w+\\)\\s*\\{"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "babel:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("var\\s+\\w+\\s*=\\s*function\\s*\\(\\)\\s*\\{\\s*function\\s+\\w+\\([^)]*\\)\\s*\\{[^}]*_classCallCheck\\(this,\\s*\\w+\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "babel:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("function\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\s*\\(\\)\\s*{\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\s*=\\s*function\\s*\\(\\)\\s*{\\s*return\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\s*}\\s*;"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "babel:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("_decorate\\(\\[\\s*\\w+(?:\\s*,\\s*\\w+)*\\s*\\],\\s*\\w+\\.prototype,\\s*[\"'][^\"']+[\"']"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "babel:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("[a-zA-Z$_][a-zA-Z$_0-9]*\\._invoke\\s*=\\s*{\\s*value\\s*:\\s*function\\s*\\([a-zA-Z$_][a-zA-Z$_0-9]*,\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "babel:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("[a-zA-Z$_][a-zA-Z$_0-9]*\\(\\)\\s*\\.\\s*mark\\s*\\(\\s*function\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\s*\\(.*?\\)\\s*{\\s*return\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\(\\)\\s*\\.\\s*wrap"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "babel:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("function\\s+_asyncToGenerator\\s*\\(\\s*fn\\s*\\)\\s*\\{"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "babel:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("regeneratorRuntime\\.mark\\(function\\s+_callee\\("),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "babel:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("function\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\s*\\([a-zA-Z$_][a-zA-Z$_0-9]*,\\s*[a-zA-Z$_][a-zA-Z$_0-9]*,\\s*[a-zA-Z$_][a-zA-Z$_0-9]*,\\s*[a-zA-Z$_][a-zA-Z$_0-9]*,\\s*[a-zA-Z$_][a-zA-Z$_0-9]*,\\s*[a-zA-Z$_][a-zA-Z$_0-9]*,\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\)\\s*{\\s*try\\s*{\\s*var\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\s*=\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\[[a-zA-Z$_][a-zA-Z$_0-9]*\\]\\([a-zA-Z$_][a-zA-Z$_0-9]*\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "babel:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("\\[\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\s*\\|\\|\\s*\"@@iterator\"\\s*\\]"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "babel:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("function\\s+_objectWithoutProperties\\s*\\([^)]+\\)\\s*\\{"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "babel:scriptContent:modern:18",
			kind: "scriptContent",
			pattern: new RegExp("function\\s+_objectWithoutPropertiesLoose\\s*\\([^)]+\\)\\s*\\{"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "babel:scriptContent:modern:19",
			kind: "scriptContent",
			pattern: new RegExp("\\w+===(?:void\\s*0|null)\\?\\s*void\\s*0:\\w+\\.\\w+"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "babel:scriptContent:modern:20",
			kind: "scriptContent",
			pattern: new RegExp("\\w+!==(?:void\\s*0|null)&&\\w+!==void\\s*0\\?\\w+:"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "babel:scriptContent:modern:21",
			kind: "scriptContent",
			pattern: new RegExp("var\\s+\\w+\\s*=\\s*\\w+\\s*==\\s*null\\s*\\?\\s*void\\s*0\\s*:\\s*\\w+(?:\\[|\\.)(?:[^;]|;(?=[^;]))*;"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "babel:scriptContent:modern:22",
			kind: "scriptContent",
			pattern: new RegExp("var\\s+\\w+\\s*=\\s*\\w+\\s*===?\\s*null\\s*\\|\\|\\s*\\w+\\s*===?\\s*void\\s*0\\s*\\?\\s*\\w+\\s*:\\s*\\w+"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "babel:scriptContent:modern:23",
			kind: "scriptContent",
			pattern: new RegExp("\\w+\\s*!==\\s*null\\s*&&\\s*\\w+\\s*!==\\s*void\\s*0\\s*\\?\\s*\\w+\\s*:"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "babel:scriptContent:modern:24",
			kind: "scriptContent",
			pattern: new RegExp("\\w+\\s*===\\s*null\\s*\\|\\|\\s*\\w+\\s*===\\s*void\\s*0\\s*\\?\\s*void\\s*0\\s*:\\s*\\w+\\.\\w+"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "babel:scriptContent:modern:25",
			kind: "scriptContent",
			pattern: new RegExp("var\\s+\\w+\\s*=\\s*new\\s+WeakMap\\(\\);\\s*var\\s+\\w+\\s*=\\s*function\\s*\\w+\\s*\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "babel:scriptContent:modern:26",
			kind: "scriptContent",
			pattern: new RegExp("Object\\.defineProperty\\(\\w+\\.prototype,\\s*[\"'][^\"']+[\"'],\\s*\\{\\s*configurable:\\s*true,\\s*writable:\\s*true,\\s*value:"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "babel:scriptContent:modern:27",
			kind: "scriptContent",
			pattern: new RegExp("Object\\.defineProperty\\(exports,\\s*[\"']__esModule[\"'],\\s*\\{\\s*value:\\s*true\\s*\\}\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "babel:scriptContent:modern:28",
			kind: "scriptContent",
			pattern: new RegExp("exports\\.(?:default|[\\w$]+)\\s*=\\s*void\\s*0"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "babel:scriptContent:modern:29",
			kind: "scriptContent",
			pattern: new RegExp("exports\\[[\"']default[\"']\\]\\s*=\\s*\\w+"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "babel:scriptContent:modern:30",
			kind: "scriptContent",
			pattern: new RegExp("Promise\\.resolve\\(\\)\\.\\s*then\\(function\\s*\\(\\)\\s*\\{\\s*return\\s*require\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
