import type { TechnologyDefinition } from '../../types';

export const typescriptTechnologyDefinition = {
	id: "typescript",
	name: "TypeScript",
	website: "https://www.typescriptlang.org/",
	description: "Typed superset of JavaScript that compiles to plain JavaScript.",
	categories: [
		"transpiler",
	],
	rules: [
		{
			id: "typescript:resourceUrl:runtime:0",
			kind: "resourceUrl",
			pattern: new RegExp("(?:^|/)tslib(?:[./@-]|$)", "i"),
			confidence: 90,
			description: "Resource URL references tslib, TypeScript's runtime helper library.",
		},
		{
			id: "typescript:scriptContent:helper:0",
			kind: "scriptContent",
			pattern: new RegExp("var\\s+__decorate\\s*=\\s*\\(this\\s*&&\\s*this\\.__decorate\\)\\s*\\|\\|\\s*function\\s*\\(decorators,\\s*target[^)]*\\)\\s*\\{"),
			confidence: 45,
			description: "Bundled script content contains a TypeScript emitted helper.",
		},
		{
			id: "typescript:scriptContent:helper:1",
			kind: "scriptContent",
			pattern: new RegExp("var\\s+__metadata\\s*=\\s*\\(this\\s*&&\\s*this\\.__metadata\\)\\s*\\|\\|\\s*function\\s*\\(k,\\s*v\\)\\s*\\{"),
			confidence: 45,
			description: "Bundled script content contains a TypeScript emitted helper.",
		},
		{
			id: "typescript:scriptContent:helper:2",
			kind: "scriptContent",
			pattern: new RegExp("var\\s+__param\\s*=\\s*\\(this\\s*&&\\s*this\\.__param\\)\\s*\\|\\|\\s*function\\s*\\(paramIndex,\\s*decorator\\)\\s*\\{"),
			confidence: 45,
			description: "Bundled script content contains a TypeScript emitted helper.",
		},
		{
			id: "typescript:scriptContent:helper:3",
			kind: "scriptContent",
			pattern: new RegExp("__decorate\\(\\[\\s*\\w+(?:\\([^)]*\\))?\\s*\\],\\s*\\w+\\.prototype,\\s*[\"'][^\"']+[\"']"),
			confidence: 45,
			description: "Bundled script content contains TypeScript decorator output.",
		},
		{
			id: "typescript:scriptContent:helper:4",
			kind: "scriptContent",
			pattern: new RegExp("__param\\(\\d+,\\s*\\w+(?:\\([^)]*\\))?\\)"),
			confidence: 45,
			description: "Bundled script content contains TypeScript decorator output.",
		},
		{
			id: "typescript:scriptContent:helper:5",
			kind: "scriptContent",
			pattern: new RegExp("var\\s+__awaiter\\s*=\\s*\\(this\\s*&&\\s*this\\.__awaiter\\)\\s*\\|\\|\\s*function"),
			confidence: 45,
			description: "Bundled script content contains a TypeScript emitted helper.",
		},
		{
			id: "typescript:scriptContent:helper:6",
			kind: "scriptContent",
			pattern: new RegExp("var\\s+__generator\\s*=\\s*\\(this\\s*&&\\s*this\\.__generator\\)\\s*\\|\\|\\s*function"),
			confidence: 45,
			description: "Bundled script content contains a TypeScript emitted helper.",
		},
		{
			id: "typescript:scriptContent:helper:7",
			kind: "scriptContent",
			pattern: new RegExp("var\\s+__spreadArray\\s*=\\s*\\(this\\s*&&\\s*this\\.__spreadArray\\)\\s*\\|\\|\\s*function"),
			confidence: 45,
			description: "Bundled script content contains a TypeScript emitted helper.",
		},
		{
			id: "typescript:scriptContent:helper:8",
			kind: "scriptContent",
			pattern: new RegExp("var\\s+__extends\\s*=\\s*\\(this\\s*&&\\s*this\\.__extends\\)\\s*\\|\\|\\s*function"),
			confidence: 45,
			description: "Bundled script content contains a TypeScript emitted helper.",
		},
		{
			id: "typescript:scriptContent:helper:9",
			kind: "scriptContent",
			pattern: new RegExp("var\\s+__assign\\s*=\\s*\\(this\\s*&&\\s*this\\.__assign\\)\\s*\\|\\|\\s*function\\s*\\(\\)\\s*\\{\\s*__assign\\s*=\\s*Object\\.assign"),
			confidence: 45,
			description: "Bundled script content contains a TypeScript emitted helper.",
		},
		{
			id: "typescript:scriptContent:helper:10",
			kind: "scriptContent",
			pattern: new RegExp("var\\s+__importDefault\\s*=\\s*\\(this\\s*&&\\s*this\\.__importDefault\\)\\s*\\|\\|\\s*function\\s*\\(mod\\)\\s*\\{"),
			confidence: 45,
			description: "Bundled script content contains a TypeScript emitted helper.",
		},
		{
			id: "typescript:scriptContent:helper:11",
			kind: "scriptContent",
			pattern: new RegExp("var\\s+__importStar\\s*=\\s*\\(this\\s*&&\\s*this\\.__importStar\\)\\s*\\|\\|\\s*function\\s*\\(mod\\)\\s*\\{"),
			confidence: 45,
			description: "Bundled script content contains a TypeScript emitted helper.",
		},
	],
} as const satisfies TechnologyDefinition;
