import type { TechnologyDefinition } from '../../types';

export const typescriptTechnologyDefinition = {
	id: "typescript",
	name: "TypeScript",
	website: "https://www.typescriptlang.org/",
	description: "Typed superset of JavaScript that compiles to plain JavaScript.",
	categories: [
		"transpiler",
	],
	rules: [
		{
			id: "typescript:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("var\\s+__decorate\\s*=\\s*\\(this\\s*&&\\s*this\\.__decorate\\)\\s*\\|\\|\\s*function\\s*\\(decorators,\\s*target[^)]*\\)\\s*\\{"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "typescript:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("var\\s+__metadata\\s*=\\s*\\(this\\s*&&\\s*this\\.__metadata\\)\\s*\\|\\|\\s*function\\s*\\(k,\\s*v\\)\\s*\\{"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "typescript:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("var\\s+__param\\s*=\\s*\\(this\\s*&&\\s*this\\.__param\\)\\s*\\|\\|\\s*function\\s*\\(paramIndex,\\s*decorator\\)\\s*\\{"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "typescript:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("__decorate\\(\\[\\s*\\w+(?:\\([^)]*\\))?\\s*\\],\\s*\\w+\\.prototype,\\s*[\"'][^\"']+[\"']"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "typescript:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("__param\\(\\d+,\\s*\\w+(?:\\([^)]*\\))?\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "typescript:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("var\\s+__awaiter\\s*=\\s*\\(this\\s*&&\\s*this\\.__awaiter\\)\\s*\\|\\|\\s*function"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "typescript:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("var\\s+__generator\\s*=\\s*\\(this\\s*&&\\s*this\\.__generator\\)\\s*\\|\\|\\s*function"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "typescript:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("var\\s+__spreadArray\\s*=\\s*\\(this\\s*&&\\s*this\\.__spreadArray\\)\\s*\\|\\|\\s*function"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "typescript:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("var\\s+__extends\\s*=\\s*\\(this\\s*&&\\s*this\\.__extends\\)\\s*\\|\\|\\s*function"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "typescript:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("var\\s+__assign\\s*=\\s*\\(this\\s*&&\\s*this\\.__assign\\)\\s*\\|\\|\\s*function\\s*\\(\\)\\s*\\{\\s*__assign\\s*=\\s*Object\\.assign"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "typescript:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("var\\s+__importDefault\\s*=\\s*\\(this\\s*&&\\s*this\\.__importDefault\\)\\s*\\|\\|\\s*function\\s*\\(mod\\)\\s*\\{"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "typescript:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("var\\s+__importStar\\s*=\\s*\\(this\\s*&&\\s*this\\.__importStar\\)\\s*\\|\\|\\s*function\\s*\\(mod\\)\\s*\\{"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "typescript:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("exports\\.\\w+\\s*=\\s*\\{\\s*__proto__:\\s*null\\s*\\};"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "typescript:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("(?:\\(0,\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\.C6\\)|__extends)\\s*\\(\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\s*,\\s*_super\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "typescript:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("Object\\.defineProperty\\s*\\([a-zA-Z$_][a-zA-Z$_0-9]*,\\s*[a-zA-Z$_][a-zA-Z$_0-9]*,\\s*\\{\\s*enumerable:\\s*(?:true|false),\\s*get:\\s*function"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "typescript:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("r\\.d\\s*\\(\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\s*,\\s*\\{\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\s*:\\s*\\(\\)\\s*=>\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\s*\\}\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "typescript:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("if\\s*\\(\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\s*===\\s*void\\s+0\\s*\\)\\s*\\{\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\s*="),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "typescript:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("=\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\s*===\\s*void\\s+0\\s*\\?\\s*[^:]+\\s*:\\s*[a-zA-Z$_][a-zA-Z$_0-9]*[,;)]"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "typescript:scriptContent:modern:18",
			kind: "scriptContent",
			pattern: new RegExp("^[\"']use strict[\"'];", "m"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "typescript:scriptContent:modern:19",
			kind: "scriptContent",
			pattern: new RegExp("(?:\\(0,\\s*[a-zA-Z$_][a-zA-Z$_0-9]*\\.Cl\\)|__assign)\\s*\\(\\s*\\{\\s*\\}"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "typescript:scriptContent:modern:20",
			kind: "scriptContent",
			pattern: new RegExp("var\\s+\\w+\\s*;\\s*\\(\\s*function\\s*\\(\\w+\\)\\s*\\{\\s*\\w+\\[\\w+\\[\"\\w+\"\\]\\s*=\\s*\\d+\\]\\s*=\\s*\"\\w+\""),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "typescript:scriptContent:modern:21",
			kind: "scriptContent",
			pattern: new RegExp("\\b\\d+\\s*\\/\\*\\s*\\w+\\.\\w+\\s*\\*\\/"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "typescript:scriptContent:modern:22",
			kind: "scriptContent",
			pattern: new RegExp("\\w+\\[\\w+\\[\"\\w+\"\\]\\s*=\\s*\"\\w+\"\\]\\s*=\\s*\"\\w+\""),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "typescript:scriptContent:modern:23",
			kind: "scriptContent",
			pattern: new RegExp("\\w+\\[\\w+\\[\\w+\\s*=\\s*\\w+\\.\\w+\\]\\s*=\\s*\\w+\\]"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "typescript:scriptContent:modern:24",
			kind: "scriptContent",
			pattern: new RegExp("void\\s+0\\s*===\\s*[a-zA-Z$_][a-zA-Z$_0-9]*|[a-zA-Z$_][a-zA-Z$_0-9]*\\s*===\\s*void\\s+0"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
