import type { TechnologyDefinition } from '../../types';

export const modxTechnologyDefinition = {
	id: "modx",
	name: "MODX",
	website: "https://modx.com/content-management-framework",
	description: "MODX (originally MODx) is an open source content management system and web application framework for publishing content on the World Wide Web and intranets.",
	icon: "MODX.svg",
	categories: [
		"platform-cms-builder",
	],
	rules: [
		{
			id: "modx:scriptSrc:0",
			kind: "scriptSrc",
			pattern: new RegExp("\\/assets\\/components\\/templates\\/"),
			confidence: 50,
			description: "Script source URL matches a known technology marker.",
		},
		{
			id: "modx:html:1",
			kind: "html",
			pattern: new RegExp("<a[^>]+>Powered by MODX<\\/a>"),
			description: "HTML contains a known technology signature.",
		},
		{
			id: "modx:html:2",
			kind: "html",
			pattern: new RegExp("<!-- Modx process time debug info -->"),
			description: "HTML contains a known technology signature.",
		},
		{
			id: "modx:html:3",
			kind: "html",
			pattern: new RegExp("<(?:link|script)[^>]+assets\\/snippets\\/"),
			confidence: 20,
			description: "HTML contains a known technology signature.",
		},
		{
			id: "modx:html:4",
			kind: "html",
			pattern: new RegExp("<form[^>]+id=\"ajaxSearch_form"),
			confidence: 20,
			description: "HTML contains a known technology signature.",
		},
		{
			id: "modx:html:5",
			kind: "html",
			pattern: new RegExp("<input[^>]+id=\"ajaxSearch_input"),
			confidence: 20,
			description: "HTML contains a known technology signature.",
		},
		{
			id: "modx:jsGlobal:6",
			kind: "jsGlobal",
			property: "MODX",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "modx:jsGlobal:7",
			kind: "jsGlobal",
			property: "MODX_MEDIA_PATH",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "modx:header:8",
			kind: "header",
			key: "X-Powered-By",
			valuePattern: new RegExp("^MODX", "i"),
			description: "Response header matches a known technology marker.",
		},
		{
			id: "modx:meta:9",
			kind: "meta",
			key: "generator",
			valuePattern: new RegExp("MODX[^\\d.]*([\\d.]+)?", "i"),
			version: {
				source: "match",
				group: 1,
			},
			description: "Meta tag matches a known technology marker.",
		},
		{
			id: "modx:dom:10",
			kind: "dom",
			selector: "form[id*='ajaxSearch_form']",
			description: "DOM selector matches a known technology marker.",
		},
		{
			id: "modx:dom:11",
			kind: "dom",
			selector: "input[id*='ajaxSearch_input']",
			description: "DOM selector matches a known technology marker.",
		},
		{
			id: "modx:jsGlobal:12",
			kind: "jsGlobal",
			property: "miniShop2Config.actionUrl",
			valuePattern: new RegExp("\\/assets\\/components\\/minishop2\\/"),
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "modx:html:13",
			kind: "html",
			pattern: new RegExp("<!-- modx process time debug info -->"),
			description: "HTML contains a known technology signature.",
		},
		{
			id: "modx:html:14",
			kind: "html",
			pattern: new RegExp("<a[^>]+>powered by modx<\\/a>"),
			description: "HTML contains a known technology signature.",
		},
		{
			id: "modx:html:15",
			kind: "html",
			pattern: new RegExp("<form[^>]+id=\"ajaxsearch_form"),
			confidence: 20,
			description: "HTML contains a known technology signature.",
		},
		{
			id: "modx:html:16",
			kind: "html",
			pattern: new RegExp("<input[^>]+id=\"ajaxsearch_input"),
			confidence: 20,
			description: "HTML contains a known technology signature.",
		},
		{
			id: "modx:header:17",
			kind: "header",
			key: "x-powered-by",
			valuePattern: new RegExp("^modx", "i"),
			description: "Response header matches a known technology marker.",
		},
		{
			id: "modx:meta:18",
			kind: "meta",
			key: "generator",
			valuePattern: new RegExp("modx[^\\d.]*([\\d.]+)?", "i"),
			version: {
				source: "match",
				group: 1,
			},
			description: "Meta tag matches a known technology marker.",
		},
		{
			id: "modx:dom:19",
			kind: "dom",
			selector: "form[id*='ajaxSearch_form'], input[id*='ajaxSearch_input']",
			description: "DOM selector matches a known technology marker.",
		},
	],
	metadata: {
		saas: true,
		oss: true,
		pricing: [
			"low",
		],
		cpe: "cpe:2.3:a:modx:modx_revolution:*:*:*:*:*:*:*:*",
	},
	implies: [
		"php",
	],
} as const satisfies TechnologyDefinition;
