import type { TechnologyDefinition } from '../../types';

export const shopifyTechnologyDefinition = {
	id: "shopify",
	name: "Shopify",
	website: "https://shopify.com",
	description: "Shopify is a subscription-based software that allows anyone to set up an online store and sell their products. Shopify store owners can also sell in physical locations using Shopify POS, a point-of-sale app and accompanying hardware.",
	icon: "Shopify.svg",
	categories: [
		"platform-cms-builder",
	],
	rules: [
		{
			id: "shopify:scriptSrc:0",
			kind: "scriptSrc",
			pattern: new RegExp("sdks\\.shopifycdn\\.com"),
			description: "Script source URL matches a known technology marker.",
		},
		{
			id: "shopify:scriptSrc:1",
			kind: "scriptSrc",
			pattern: new RegExp("cdn\\.shopify\\.com"),
			description: "Script source URL matches a known technology marker.",
		},
		{
			id: "shopify:scriptContent:2",
			kind: "scriptContent",
			pattern: new RegExp("shopifyTag"),
			description: "Script content contains a bounded technology signature.",
		},
		{
			id: "shopify:url:3",
			kind: "url",
			pattern: new RegExp("^https?\\/\\/.+\\.myshopify\\.com"),
			description: "Page URL matches a known technology marker.",
		},
		{
			id: "shopify:requestUrl:4",
			kind: "requestUrl",
			pattern: new RegExp("\\.myshopify\\.com"),
			description: "Observed request URL matches a known technology marker.",
		},
		{
			id: "shopify:jsGlobal:6",
			kind: "jsGlobal",
			property: "SHOPIFY_API_BASE_URL",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "shopify:jsGlobal:8",
			kind: "jsGlobal",
			property: "ShopifyAPI",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "shopify:jsGlobal:9",
			kind: "jsGlobal",
			property: "ShopifyCustomer",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "shopify:cookie:10",
			kind: "cookie",
			keyPattern: new RegExp("^_shopify_s$", "i"),
			description: "Cookie name matches a known technology marker.",
		},
		{
			id: "shopify:cookie:11",
			kind: "cookie",
			keyPattern: new RegExp("^_shopify_y$", "i"),
			description: "Cookie name matches a known technology marker.",
		},
		{
			id: "shopify:jsGlobal:12",
			kind: "jsGlobal",
			property: "ShopifyAnalytics",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "shopify:jsGlobal:13",
			kind: "jsGlobal",
			property: "goaffproShopifyStVariableFix",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "shopify:jsGlobal:14",
			kind: "jsGlobal",
			property: "shopifyAccessUrl",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "shopify:cookie:15",
			kind: "cookie",
			keyPattern: new RegExp("^_shopify_essential_$", "i"),
			description: "Cookie name matches a known technology marker.",
		},
		{
			id: "shopify:cookie:16",
			kind: "cookie",
			keyPattern: new RegExp("^_shopify_sa_p$", "i"),
			description: "Cookie name matches a known technology marker.",
		},
		{
			id: "shopify:cookie:17",
			kind: "cookie",
			keyPattern: new RegExp("^_shopify_sa_t$", "i"),
			description: "Cookie name matches a known technology marker.",
		},
		{
			id: "shopify:header:18",
			kind: "header",
			key: "powered-by",
			valuePattern: new RegExp("Shopify", "i"),
			description: "Response header matches a known technology marker.",
		},
		{
			id: "shopify:scriptContent:19",
			kind: "scriptContent",
			pattern: new RegExp("shopifytag"),
			description: "Script content contains a bounded technology signature.",
		},
		{
			id: "shopify:header:20",
			kind: "header",
			key: "powered-by",
			valuePattern: new RegExp("shopify", "i"),
			description: "Response header matches a known technology marker.",
		},
		{
			id: "shopify:scriptContent:21",
			kind: "scriptContent",
			pattern: new RegExp("shopify\\.content_for_header"),
			confidence: 50,
			description: "Script content contains a bounded technology signature.",
		},
		{
			id: "shopify:scriptContent:22",
			kind: "scriptContent",
			pattern: new RegExp("cdn\\.shopify\\.com"),
			confidence: 50,
			description: "Script content contains a bounded technology signature.",
		},
		{
			id: "shopify:jsGlobal:23",
			kind: "jsGlobal",
			property: "ShopifyStorefrontAPIClient.createStorefrontApiClient",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "shopify:header:24",
			kind: "header",
			key: "Powered-By",
			valuePattern: new RegExp("^Shopify", "i"),
			description: "Response header matches a known technology marker.",
		},
		{
			id: "shopify:resourceUrl:modern:0",
			kind: "resourceUrl",
			pattern: new RegExp("\\.myshopify\\.com\\/"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "shopify:resourceUrl:modern:2",
			kind: "resourceUrl",
			pattern: new RegExp("cdn\\.shopify\\.com\\/"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "shopify:resourceUrl:modern:3",
			kind: "resourceUrl",
			pattern: new RegExp("shopifycdn\\.com\\/"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "shopify:header:modern:4",
			kind: "header",
			key: "x-shopify-stage",
			valuePattern: new RegExp(".+"),
			confidence: 45,
			description: "HTTP response header matches a modern tooling marker.",
		},
		{
			id: "shopify:header:modern:5",
			kind: "header",
			key: "x-shopify-shop-api-call-limit",
			valuePattern: new RegExp(".+"),
			confidence: 45,
			description: "HTTP response header matches a modern tooling marker.",
		},
	],
	metadata: {
		saas: true,
		pricing: [
			"low",
			"recurring",
		],
	},
} as const satisfies TechnologyDefinition;
