import type { TechnologyDefinition } from '../../types';

export const squarespaceTechnologyDefinition = {
	id: "squarespace",
	name: "Squarespace",
	website: "https://www.squarespace.com",
	description: "Squarespace provides Software-as-a-Service (SaaS) for website building and hosting, and allows users to use pre-built website templates.",
	icon: "Squarespace.svg",
	categories: [
		"platform-cms-builder",
	],
	rules: [
		{
			id: "squarespace:jsGlobal:0",
			kind: "jsGlobal",
			property: "Squarespace",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "squarespace:jsGlobal:1",
			kind: "jsGlobal",
			property: "Static.SQUARESPACE_CONTEXT.templateVersion",
			valuePattern: new RegExp("^(\\d(?:\\.\\d)?)$"),
			version: {
				source: "match",
				group: 1,
			},
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "squarespace:header:2",
			kind: "header",
			key: "server",
			valuePattern: new RegExp("Squarespace", "i"),
			description: "Response header matches a known technology marker.",
		},
		{
			id: "squarespace:header:3",
			kind: "header",
			key: "server",
			valuePattern: new RegExp("squarespace", "i"),
			description: "Response header matches a known technology marker.",
		},
		{
			id: "squarespace:meta:generator",
			kind: "meta",
			key: "generator",
			valuePattern: new RegExp("Squarespace", "i"),
			confidence: 65,
			description: "Document generator metadata references Squarespace.",
		},
		{
			id: "squarespace:dom:page-section",
			kind: "dom",
			selector: "[data-type='page-section']",
			confidence: 65,
			description: "DOM uses Squarespace page-section structure.",
		},
		{
			id: "squarespace:dom:site-loader",
			kind: "dom",
			selector: "[data-controller*='SiteLoader']",
			confidence: 65,
			description: "DOM uses Squarespace SiteLoader controller markup.",
		},
		{
			id: "squarespace:dom:sqs-block",
			kind: "dom",
			selector: ".sqs-block, [class*='sqs-block']",
			confidence: 65,
			description: "DOM uses Squarespace block markup.",
		},
		{
			id: "squarespace:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("sqsp\\.net\\/"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "squarespace:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("Squarespace\\.afterBodyLoad"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "squarespace:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("Squarespace\\.globalInit"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "squarespace:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("Universal\\.premiumInit"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "squarespace:resourceUrl:modern:8",
			kind: "resourceUrl",
			pattern: new RegExp("\\.squarespace\\.com\\/"),
			confidence: 55,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "squarespace:resourceUrl:modern:9",
			kind: "resourceUrl",
			pattern: new RegExp("\\.sqsp\\.net\\/"),
			confidence: 55,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "squarespace:resourceUrl:modern:10",
			kind: "resourceUrl",
			pattern: new RegExp("static1\\.squarespace\\.com\\/"),
			confidence: 55,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "squarespace:resourceUrl:modern:11",
			kind: "resourceUrl",
			pattern: new RegExp("assets\\.squarespace\\.com\\/"),
			confidence: 55,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "squarespace:header:modern:12",
			kind: "header",
			key: "x-sq-version",
			valuePattern: new RegExp(".+"),
			confidence: 55,
			description: "HTTP response header matches a modern tooling marker.",
		},
		{
			id: "squarespace:header:modern:13",
			kind: "header",
			key: "x-sqs-page-id",
			valuePattern: new RegExp(".+"),
			confidence: 55,
			description: "HTTP response header matches a modern tooling marker.",
		},
	],
	metadata: {
		saas: true,
		pricing: [
			"low",
			"recurring",
		],
	},
} as const satisfies TechnologyDefinition;
