import type { TechnologyDefinition } from '../../types';

export const wordpressTechnologyDefinition = {
	id: "wordpress",
	name: "WordPress",
	website: "https://wordpress.org",
	description: "WordPress is a free and open-source content management system written in PHP and paired with a MySQL or MariaDB database. Features include a plugin architecture and a template system.",
	icon: "WordPress.svg",
	categories: [
		"platform-cms-builder",
		"content-publishing",
	],
	rules: [
		{
			id: "wordpress:meta:wordpress-com-generator",
			kind: "meta",
			key: "generator",
			valuePattern: new RegExp("^WordPress\\.com$", "i"),
			confidence: 95,
			description: "WordPress.com generator meta tag implies WordPress.",
		},
		{
			id: "wordpress:scriptSrc:0",
			kind: "scriptSrc",
			pattern: new RegExp("\\/wp-(?:content|includes)\\/"),
			description: "Script source URL matches a known technology marker.",
		},
		{
			id: "wordpress:scriptSrc:1",
			kind: "scriptSrc",
			pattern: new RegExp("wp-embed\\.min\\.js"),
			description: "Script source URL matches a known technology marker.",
		},
		{
			id: "wordpress:stylesheetHref:2",
			kind: "stylesheetHref",
			pattern: new RegExp("\\/wp-(?:content|includes)\\/", "i"),
			description: "Stylesheet URL is served from a WordPress content or includes path.",
		},
		{
			id: "wordpress:stylesheetHref:3",
			kind: "stylesheetHref",
			pattern: new RegExp("https?://s\\d+\\.wp\\.com/", "i"),
			description: "Stylesheet URL is served from WordPress.com static asset hosts.",
		},
		{
			id: "wordpress:jsGlobal:4",
			kind: "jsGlobal",
			property: "wp_username",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "wordpress:header:5",
			kind: "header",
			key: "X-Pingback",
			valuePattern: new RegExp("\\/xmlrpc\\.php$", "i"),
			description: "Response header matches a known technology marker.",
		},
		{
			id: "wordpress:header:6",
			kind: "header",
			key: "link",
			valuePattern: new RegExp("rel=\"https:\\/\\/api\\.w\\.org\\/\"", "i"),
			description: "Response header matches a known technology marker.",
		},
		{
			id: "wordpress:meta:7",
			kind: "meta",
			key: "generator",
			valuePattern: new RegExp("^WordPress(?: ([\\d.]+))?", "i"),
			version: {
				source: "match",
				group: 1,
			},
			description: "Meta tag matches a known technology marker.",
		},
		{
			id: "wordpress:scriptSrc:8",
			kind: "scriptSrc",
			pattern: new RegExp("wp-static\\.assets\\.sh\\/"),
			description: "Script source URL matches a known technology marker.",
		},
		{
			id: "wordpress:scriptContent:9",
			kind: "scriptContent",
			pattern: new RegExp("\\/wp-content"),
			description: "Script content contains a bounded technology signature.",
		},
		{
			id: "wordpress:dom:10",
			kind: "dom",
			selector: "div[class*='wp-block-group'] > div[class*='wp-block-']",
			description: "DOM selector matches a known technology marker.",
		},
		{
			id: "wordpress:dom:11",
			kind: "dom",
			selector: "link[rel=stylesheet][href*='/wp-content/']",
			description: "DOM selector matches a known technology marker.",
		},
		{
			id: "wordpress:dom:12",
			kind: "dom",
			selector: "link[rel=stylesheet][href*='/wp-includes/']",
			description: "DOM selector matches a known technology marker.",
		},
		{
			id: "wordpress:dom:13",
			kind: "dom",
			selector: "link[href*='.wp.com']",
			description: "DOM selector matches a known technology marker.",
		},
		{
			id: "wordpress:jsGlobal:14",
			kind: "jsGlobal",
			property: "wp.ajax",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "wordpress:jsGlobal:15",
			kind: "jsGlobal",
			property: "wp.receiveEmbedMessage",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "wordpress:jsGlobal:16",
			kind: "jsGlobal",
			property: "wpb_prepare_tab_content",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "wordpress:resourceUrl:17",
			kind: "resourceUrl",
			pattern: new RegExp("\\/wp-(?:content|includes)\\/", "i"),
			confidence: 85,
			description: "Loaded resource URL is served from a WordPress content or includes path.",
		},
		{
			id: "wordpress:header:19",
			kind: "header",
			key: "x-pingback",
			valuePattern: new RegExp("\\/xmlrpc\\.php$", "i"),
			description: "Response header matches a known technology marker.",
		},
		{
			id: "wordpress:meta:20",
			kind: "meta",
			key: "generator",
			valuePattern: new RegExp("^wordpress(?:\\s*([\\d.]+))?", "i"),
			version: {
				source: "match",
				group: 1,
			},
			description: "Meta tag matches a known technology marker.",
		},
		{
			id: "wordpress:scriptSrc:21",
			kind: "scriptSrc",
			pattern: new RegExp("\\/(?:wp-(?:content|includes)|wp-embed\\.min\\.js|wp-static\\.assets\\.sh)\\/"),
			description: "Script source URL matches a known technology marker.",
		},
		{
			id: "wordpress:dom:22",
			kind: "dom",
			selector: "div[class*='wp-block-group'] > div[class*='wp-block-'], link[rel=stylesheet][href*='/wp-content/'], link[rel=stylesheet][href*='/wp-includes/'], link[href*='.wp.com']",
			description: "DOM selector matches a known technology marker.",
		},
		{
			id: "wordpress:header:23",
			kind: "header",
			key: "X-Redirect-By",
			valuePattern: new RegExp("WordPress", "i"),
			description: "Response header matches a known technology marker.",
		},
		{
			id: "wordpress:html:modern:3",
			kind: "html",
			pattern: new RegExp("class=[\"'][^\"']*\\b(?:wp-site-blocks|wp-block-[\\w-]+|wordpress-(?:logged-in|admin-bar))\\b", "i"),
			confidence: 45,
			description: "Document HTML contains WordPress-specific block or runtime classes.",
		},
		{
			id: "wordpress:dom:modern:4",
			kind: "dom",
			selector: ".wp-site-blocks, .wordpress-logged-in, .wordpress-admin-bar",
			confidence: 65,
			description: "DOM contains WordPress-specific site or runtime classes.",
		},
		{
			id: "wordpress:stylesheetContent:modern:5",
			kind: "stylesheetContent",
			pattern: new RegExp("--wp--preset--"),
			confidence: 45,
			description: "Stylesheet content contains WordPress preset custom properties.",
		},
		{
			id: "wordpress:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("wp-content\\/themes\\/"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "wordpress:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("wp-includes\\/js\\/"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "wordpress:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("wp-content\\/plugins\\/"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "wordpress:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("wp-emoji-release\\.min\\.js"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "wordpress:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("wp-embed\\.min\\.js"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "wordpress:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("jquery\\/jquery-migrate\\."),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "wordpress:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("wp-admin\\/js\\/"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "wordpress:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("woocommerce\\/assets"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "wordpress:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("wc-cart-fragments"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "wordpress:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("wc-add-to-cart"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "wordpress:resourceUrl:modern:16",
			kind: "resourceUrl",
			pattern: new RegExp("\\.wordpress\\.com\\/"),
			confidence: 55,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "wordpress:resourceUrl:modern:17",
			kind: "resourceUrl",
			pattern: new RegExp("wp-content\\/"),
			confidence: 55,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "wordpress:resourceUrl:modern:18",
			kind: "resourceUrl",
			pattern: new RegExp("wp-includes\\/"),
			confidence: 55,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "wordpress:resourceUrl:modern:19",
			kind: "resourceUrl",
			pattern: new RegExp("wp-json\\/"),
			confidence: 55,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "wordpress:header:modern:20",
			kind: "header",
			key: "x-pingback",
			valuePattern: new RegExp("xmlrpc\\.php"),
			confidence: 55,
			description: "HTTP response header matches a modern tooling marker.",
		},
		{
			id: "wordpress:header:modern:21",
			kind: "header",
			key: "x-powered-by",
			valuePattern: new RegExp("^WordPress(?:\\b|/)", "i"),
			confidence: 55,
			description: "HTTP response header matches a modern tooling marker.",
		},
		{
			id: "wordpress:meta:22",
			kind: "meta",
			key: "shareaholic:wp_version",
			description: "Meta tag matches a known technology marker."
		},
      {
			id: "wordpress:cookie:23",
        kind: "cookie",
        key: "wordpress_test_cookie",
        description: "WordPress test cookie exists.",
      }
	],
	metadata: {
		saas: true,
		oss: true,
		pricing: [
			"freemium",
			"low",
			"recurring",
		],
		cpe: "cpe:2.3:a:wordpress:wordpress:*:*:*:*:*:*:*:*",
	},
	implies: [
		"mysql",
		"php",
	],
} as const satisfies TechnologyDefinition;

export const wordpressBlockEditorTechnologyDefinition = {
	id: "wordpress-block-editor",
	name: "WordPress Block Editor",
	website: "https://wordpress.org/gutenberg/",
	description: "Sites using the WordPress Block Editor, also known as Gutenberg.",
	icon: "WordPress.svg",
	categories: [
		"platform-cms-builder",
	],
	rules: [
		{
			id: "wordpress-block-editor:html:0",
			kind: "html",
			pattern: /<[^>]+class=["'][^"']*\bwp-block-/i,
			confidence: 100,
			description: "Document HTML contains WordPress block editor classes.",
		},
		{
			id: "wordpress-block-editor:stylesheetHref:1",
			kind: "stylesheetHref",
			pattern: new RegExp("/wp-content/plugins/gutenberg-core/v([0-9][^/]+)/build/styles/block-library/", "i"),
			version: {
				source: "match",
				group: 1,
			},
			confidence: 100,
			description: "Gutenberg block-library stylesheet is declared.",
		},
		{
			id: "wordpress-block-editor:resourceUrl:2",
			kind: "resourceUrl",
			pattern: new RegExp("/wp-content/plugins/gutenberg-core/v([0-9][^/]+)/", "i"),
			version: {
				source: "match",
				group: 1,
			},
			confidence: 100,
			description: "Loaded resource URL references Gutenberg core plugin assets.",
		},
		{
			id: "wordpress-block-editor:scriptSrc:3",
			kind: "scriptSrc",
			pattern: new RegExp("/wp-includes/js/dist/block-library/|/wp-includes/blocks/|/wp-content/plugins/gutenberg-core/", "i"),
			confidence: 95,
			description: "Script URL references WordPress block editor packages.",
		},
	],
	implies: [
		"react",
	],
	requires: [
		"wordpress",
	],
} as const satisfies TechnologyDefinition;

export const wordpressSiteEditorTechnologyDefinition = {
	id: "wordpress-site-editor",
	name: "WordPress Site Editor",
	website: "https://wordpress.org/documentation/article/site-editor/",
	description: "Full Site Editing enables users to design and customize their entire WordPress website with a block-based editor.",
	icon: "WordPress.svg",
	categories: [
		"platform-cms-builder",
	],
	rules: [
		{
			id: "wordpress-site-editor:html:0",
			kind: "html",
			pattern: new RegExp("<div class=\"wp-site-blocks\">"),
			description: "HTML contains a known technology signature.",
		},
	],
	requires: [
		"wordpress",
	],
	excludes: [
		"wordpress-block-editor",
	],
} as const satisfies TechnologyDefinition;
