import type { DomSelectorPlan } from '../collectors/planning';

/** Offscreen-host channel used for DOM selector matching. */
export const DOM_SELECTOR_OFFSCREEN_CHANNEL = 'red-detector.dom-selector-offscreen.v1';

/** Request payload for matching DOM selectors against serialized HTML. */
export interface MatchDomSelectorsOffscreenRequest {
	/** Serialized document or subtree HTML produced by the content script. */
	readonly html: string;
	/** Parsed selector plan from the compiled registry. */
	readonly plan: DomSelectorPlan;
	/** Selectors whose boolean presence should be reported. */
	readonly selectorProbeList: readonly string[];
}

/** Message asking the offscreen host to match DOM selectors. */
export interface MatchDomSelectorsOffscreenMessage {
	/** Private channel discriminator so unrelated runtime messages are ignored. */
	readonly channel: typeof DOM_SELECTOR_OFFSCREEN_CHANNEL;
	/** Command name handled by the offscreen host. */
	readonly type: 'dom-selector.match';
	/** Request payload generated by the content script. */
	readonly request: MatchDomSelectorsOffscreenRequest;
}

/** Runtime messages accepted by the offscreen DOM selector host. */
export type DomSelectorOffscreenRequestMessage = MatchDomSelectorsOffscreenMessage;

/** Response returned by offscreen DOM selector matching. */
export type DomSelectorOffscreenResponse =
	| { readonly ok: true; readonly selectors: Record<string, boolean> }
	| { readonly ok: false; readonly message: string };
