import type { TechnologyDefinition } from '../../types';

export const doxygenTechnologyDefinition = {
	id: "doxygen",
	name: "Doxygen",
	website: "https://www.doxygen.nl/",
	description: "Doxygen is a documentation generator, a tool for writing software reference documentation.",
	icon: "Doxygen.png",
	categories: [
		"content-publishing",
	],
	rules: [
		{
			id: "doxygen:html:0",
			kind: "html",
			pattern: new RegExp("(?:<!-- Generated by Doxygen ([\\d.]+)|<link[^>]+doxygen\\.css)"),
			version: {
				source: "match",
				group: 1,
			},
			description: "HTML contains a known technology signature.",
		},
		{
			id: "doxygen:meta:1",
			kind: "meta",
			key: "generator",
			valuePattern: new RegExp("Doxygen ([\\d.]+)", "i"),
			version: {
				source: "match",
				group: 1,
			},
			description: "Meta tag matches a known technology marker.",
		},
		{
			id: "doxygen:dom:2",
			kind: "dom",
			selector: "link[href*='doxygen.css']",
			description: "DOM selector matches a known technology marker.",
		},
		{
			id: "doxygen:html:3",
			kind: "html",
			pattern: new RegExp("(?:<!-- generated by doxygen ([\\d.]+)|<link[^>]+doxygen\\.css)"),
			version: {
				source: "match",
				group: 1,
			},
			description: "HTML contains a known technology signature.",
		},
		{
			id: "doxygen:meta:4",
			kind: "meta",
			key: "generator",
			valuePattern: new RegExp("doxygen ([\\d.]+)", "i"),
			version: {
				source: "match",
				group: 1,
			},
			description: "Meta tag matches a known technology marker.",
		},
	],
	metadata: {
		oss: true,
		pricing: [
			"freemium",
		],
		cpe: "cpe:2.3:a:doxygen:doxygen:*:*:*:*:*:*:*:*",
	},
} as const satisfies TechnologyDefinition;
