import type { TechnologyDefinition } from '../../types';

export const javadocTechnologyDefinition = {
	id: "javadoc",
	name: "Javadoc",
	website: "https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html",
	description: "Javadoc is a tool used for generating Java code documentation in HTML format from Java source code.",
	icon: "Java.svg",
	categories: [
		"content-publishing",
	],
	rules: [
		{
			id: "javadoc:html:0",
			kind: "html",
			pattern: new RegExp("<!-- Generated by javadoc -->"),
			description: "HTML contains a known technology signature.",
		},
		{
			id: "javadoc:html:1",
			kind: "html",
			pattern: new RegExp("<!-- generated by javadoc -->"),
			description: "HTML contains a known technology signature.",
		},
	],
} as const satisfies TechnologyDefinition;
