import type { TechnologyDefinition } from '../../types';

export const phpdocumentorTechnologyDefinition = {
	id: "phpdocumentor",
	name: "phpDocumentor",
	website: "https://www.phpdoc.org",
	description: "phpDocumentor is an open-source documentation generator written in PHP.",
	icon: "phpDocumentor.png",
	categories: [
		"content-publishing",
	],
	rules: [
		{
			id: "phpdocumentor:html:0",
			kind: "html",
			pattern: new RegExp("<!-- Generated by phpDocumentor"),
			description: "HTML contains a known technology signature.",
		},
		{
			id: "phpdocumentor:html:1",
			kind: "html",
			pattern: new RegExp("<!-- generated by phpdocumentor"),
			description: "HTML contains a known technology signature.",
		},
		{
			id: "phpdocumentor:dom:2",
			kind: "dom",
			selector: "header.phpdocumentor-header, nav.phpdocumentor-topnav",
			description: "DOM selector matches a known technology marker.",
		},
	],
	implies: [
		"php",
	],
} as const satisfies TechnologyDefinition;
