import type { TechnologyDefinition } from '../../types';

export const rdocTechnologyDefinition = {
	id: "rdoc",
	name: "RDoc",
	website: "https://github.com/ruby/rdoc",
	description: "RDoc produces HTML and command-line documentation for Ruby projects.",
	icon: "RDoc.png",
	categories: [
		"content-publishing",
	],
	rules: [
		{
			id: "rdoc:html:0",
			kind: "html",
			pattern: new RegExp("<link[^>]+href=\"[^\"]*rdoc-style\\.css"),
			description: "HTML contains a known technology signature.",
		},
		{
			id: "rdoc:html:1",
			kind: "html",
			pattern: new RegExp("Generated by <a[^>]+href=\"https?:\\/\\/rdoc\\.rubyforge\\.org[^>]+>RDoc<\\/a> ([\\d.]*\\d)"),
			version: {
				source: "match",
				group: 1,
			},
			description: "HTML contains a known technology signature.",
		},
		{
			id: "rdoc:html:2",
			kind: "html",
			pattern: new RegExp("Generated by <a href=\"https:\\/\\/ruby\\.github\\.io\\/rdoc\\/\">RDoc<\\/a> ([\\d.]*\\d)"),
			version: {
				source: "match",
				group: 1,
			},
			description: "HTML contains a known technology signature.",
		},
		{
			id: "rdoc:jsGlobal:3",
			kind: "jsGlobal",
			property: "rdoc_rel_prefix",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "rdoc:dom:4",
			kind: "dom",
			selector: "link[href*='rdoc-style.css']",
			description: "DOM selector matches a known technology marker.",
		},
		{
			id: "rdoc:html:5",
			kind: "html",
			pattern: new RegExp("generated by <a href=\"https:\\/\\/ruby\\.github\\.io\\/rdoc\\/\">rdoc<\\/a> ([\\d.]*\\d)"),
			version: {
				source: "match",
				group: 1,
			},
			description: "HTML contains a known technology signature.",
		},
		{
			id: "rdoc:html:6",
			kind: "html",
			pattern: new RegExp("generated by <a[^>]+href=\"https?:\\/\\/rdoc\\.rubyforge\\.org[^>]+>rdoc<\\/a> ([\\d.]*\\d)"),
			version: {
				source: "match",
				group: 1,
			},
			description: "HTML contains a known technology signature.",
		},
	],
	metadata: {
		cpe: "cpe:2.3:a:dave_thomas:rdoc:*:*:*:*:*:*:*:*",
	},
	implies: [
		"ruby",
	],
} as const satisfies TechnologyDefinition;
