import type { TechnologyDefinition } from '../../types';

export const formikTechnologyDefinition = {
	id: "formik",
	name: "Formik",
	website: "https://formik.org/",
	description: "Build forms in React without the tears",
	categories: [
		"form-schema-library",
	],
	rules: [
		{
			id: "formik:resourceUrl:modern:0",
			kind: "resourceUrl",
			pattern: new RegExp("formik[.\\-@/]"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "formik:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("exports\\.Formik\\b"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "formik:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("exports\\.FormikProvider\\b"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "formik:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("exports\\.FormikContext\\b"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "formik:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("exports\\.FormikConsumer\\b"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "formik:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("exports\\.useFormik\\b"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "formik:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("exports\\.useField\\b"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "formik:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("exports\\.withFormik\\b"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "formik:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("exports\\.FastField\\b"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "formik:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("exports\\.FieldArray\\b"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "formik:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("exports\\.ErrorMessage\\b"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "formik:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("exports\\.validateYupSchema\\b"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "formik:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("exports\\.yupToFormErrors\\b"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
