import type { TechnologyDefinition } from '../../types';

export const zodTechnologyDefinition = {
	id: "zod",
	name: "Zod",
	website: "https://zod.dev/",
	description: "TypeScript-first schema validation with static type inference",
	categories: [
		"form-schema-library",
	],
	rules: [
		{
			id: "zod:resourceUrl:modern:0",
			kind: "resourceUrl",
			pattern: new RegExp("zod[.\\-@/]"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "zod:resourceUrl:modern:1",
			kind: "resourceUrl",
			pattern: new RegExp("node_modules\\/zod"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "zod:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("\"ZodObject\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "zod:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("\"ZodString\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "zod:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("\"ZodNumber\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "zod:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("\"ZodArray\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "zod:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("\"ZodEnum\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "zod:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("\"ZodError\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "zod:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("\"ZodUnion\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "zod:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("\"ZodBoolean\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "zod:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("\"invalid_type\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "zod:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("\"invalid_enum_value\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "zod:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("\"invalid_union\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "zod:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("\"invalid_string\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "zod:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("\"too_small\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "zod:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("\"too_big\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "zod:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("\"unrecognized_keys\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "zod:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("\"not_multiple_of\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "zod:scriptContent:modern:18",
			kind: "scriptContent",
			pattern: new RegExp("\"not_finite\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
