import type { TechnologyDefinition } from '../../types';

export const airbrakeTechnologyDefinition = {
	id: "airbrake",
	name: "Airbrake",
	website: "https://www.airbrake.io/",
	description: "Frictionless error monitoring and performance insights for your entire app stack.",
	categories: [
		"monitoring-error-tracking",
	],
	rules: [
		{
			id: "airbrake:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("console\\.error\\(['\"']airbrake: span=%s does not exist"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "airbrake:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("new Error\\(['\"']airbrake: unauthorized: project id or key are wrong['\"']\\)"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "airbrake:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("new Error\\(['\"']airbrake: IP is rate limited['\"']\\)"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "airbrake:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("throw new Error\\(['\"']airbrake: fetch: unexpected response: code="),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "airbrake:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("new Error\\(['\"']airbrake: request: response statusCode is"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "airbrake:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("['\"']airbrake-js\\/browser['\"']"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "airbrake:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("\\{\\s*name:\\s*[a-zA-Z_$][a-zA-Z0-9_$]*\\s*,\\s*version:\\s*[a-zA-Z_$][a-zA-Z0-9_$]*\\s*,\\s*url:\\s*['\"']https:\\/\\/github\\.com\\/airbrake\\/airbrake-js\\/tree\\/master\\/packages\\/browser['\"']\\s*\\},"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "airbrake:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("new Error\\(['\"']airbrake: not sending this error, errorNotifications is disabled err="),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "airbrake:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("new Error\\(['\"']airbrake: error is filtered['\"']\\)"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "airbrake:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("new Error\\(['\"']airbrake: notice exceeds max length and can't be truncated['\"']\\)"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "airbrake:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("console\\.warn\\(['\"']airbrake: options\\.reporter must be a function['\"']\\)"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "airbrake:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("[a-zA-Z_$][a-zA-Z0-9_$]*\\._airbrake\\s*="),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "airbrake:resourceUrl:modern:12",
			kind: "resourceUrl",
			pattern: new RegExp("api\\.airbrake\\.io"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "airbrake:resourceUrl:modern:13",
			kind: "resourceUrl",
			pattern: new RegExp("notifier\\-configs\\.airbrake\\.io"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
