import type { TechnologyDefinition } from '../../types';

export const datadogTechnologyDefinition = {
	id: "datadog",
	name: "Datadog",
	website: "https://www.datadoghq.com",
	description: "Datadog is a SaaS-based monitoring and analytics platform for large-scale applications and infrastructure.",
	icon: "Datadog.svg",
	categories: [
		"monitoring-error-tracking",
		"analytics",
	],
	rules: [
		{
			id: "datadog:scriptSrc:0",
			kind: "scriptSrc",
			pattern: new RegExp("www\\.datadoghq-browser-agent\\.com"),
			description: "Script source URL matches a known technology marker.",
		},
		{
			id: "datadog:jsGlobal:1",
			kind: "jsGlobal",
			property: "DD_LOGS",
			confidence: 1,
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "datadog:jsGlobal:2",
			kind: "jsGlobal",
			property: "DD_RUM",
			confidence: 99,
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "datadog:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("['\"']\\/real_user_monitoring\\/browser\\/troubleshooting['\"']"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "datadog:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("['\"']Datadog Browser SDK:['\"']"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "datadog:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("[a-zA-Z_$][a-zA-Z0-9_$]*\\(\\)\\.DatadogEventBridge"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "datadog:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("String\\([a-zA-Z_$][a-zA-Z0-9_$]*\\.dd_fingerprint\\)"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "datadog:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("[a-zA-Z_$][a-zA-Z0-9_$]*\\.warn\\(['\"']PCI compliance for Logs is only available for Datadog organizations in the US1 site\\. Default intake will be used\\.['\"']\\)"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "datadog:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("[a-zA-Z_$][a-zA-Z0-9_$]*\\(['\"']DD_RUM['\"'], [a-zA-Z_$][a-zA-Z0-9_$]*\\);"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "datadog:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("['\"']x-datadog-origin['\"']\\s*:\\s*['\"']rum['\"']"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "datadog:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("[a-zA-Z_$][a-zA-Z0-9_$]*\\([a-zA-Z_$][a-zA-Z0-9_$]*, ['\"']Datadog Session Replay"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "datadog:resourceUrl:modern:8",
			kind: "resourceUrl",
			pattern: new RegExp("datad0g\\.com"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "datadog:resourceUrl:modern:9",
			kind: "resourceUrl",
			pattern: new RegExp("dd0g-gov\\.com"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "datadog:resourceUrl:modern:10",
			kind: "resourceUrl",
			pattern: new RegExp("datadoghq\\.com"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "datadog:resourceUrl:modern:11",
			kind: "resourceUrl",
			pattern: new RegExp("browser-intake-datadoghq\\.com"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
	],
	metadata: {
		saas: true,
		pricing: [
			"freemium",
			"low",
			"payg",
			"recurring",
		],
	},
} as const satisfies TechnologyDefinition;
