import type { TechnologyDefinition } from '../../types';

export const logrocketTechnologyDefinition = {
	id: "logrocket",
	name: "LogRocket",
	website: "https://logrocket.com/",
	description: "LogRocket is a logging and session replay platform that helps developers identify and troubleshoot issues in web applications by recording and replaying user sessions, along with capturing logs and user interactions in real-time.",
	icon: "LogRocket.svg",
	categories: [
		"monitoring-error-tracking",
		"analytics",
	],
	rules: [
		{
			id: "logrocket:scriptSrc:0",
			kind: "scriptSrc",
			pattern: new RegExp("cdn\\.logrocket\\.(com|io)"),
			description: "Script source URL matches a known technology marker.",
		},
		{
			id: "logrocket:scriptSrc:1",
			kind: "scriptSrc",
			pattern: new RegExp("cdn\\.lr-ingest\\.io"),
			description: "Script source URL matches a known technology marker.",
		},
		{
			id: "logrocket:scriptSrc:2",
			kind: "scriptSrc",
			pattern: new RegExp("cdn\\.(?:lr-ingest|logrocket)\\.(?:com|io)"),
			description: "Script source URL matches a known technology marker.",
		},
		{
			id: "logrocket:jsGlobal:3",
			kind: "jsGlobal",
			property: "LogRocket._buffer",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "logrocket:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("\\bLogrocket\\b|\\blogRocket\\b|\\bLR\\b", "i"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "logrocket:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("LogRocket truncating to first 1000 characters"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "logrocket:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("LogRocket skipped consuming an event-stream body"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "logrocket:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("LogRocket error reading body"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "logrocket:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("LogRocket: Error accessing response"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "logrocket:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("Keep data under 4MB to prevent truncation"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "logrocket:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("https:\\/\\/docs\\.logrocket\\.com\\/reference\\/network"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "logrocket:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("LogRocket\\.init\\("),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "logrocket:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("LogRocket\\.identify\\("),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "logrocket:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("_LRLogger"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "logrocket:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("\\[['\"]LogRocket['\"]\\]"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "logrocket:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("registerLogger\\(['\"]logrocket['\"]", "i"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "logrocket:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("LogRocket\\.min\\.js", "i"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "logrocket:resourceUrl:modern:13",
			kind: "resourceUrl",
			pattern: new RegExp("cdn\\.logrocket\\.(?:com|io)"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
	],
	metadata: {
		saas: true,
		pricing: [
			"freemium",
			"mid",
			"recurring",
		],
	},
} as const satisfies TechnologyDefinition;
