import type { TechnologyDefinition } from '../../types';

export const newRelicTechnologyDefinition = {
	id: "new-relic",
	name: "New Relic",
	website: "https://newrelic.com",
	description: "New Relic is a SaaS offering that focuses on performance and availability monitoring.",
	icon: "New Relic.svg",
	categories: [
		"monitoring-error-tracking",
	],
	rules: [
		{
			id: "new-relic:dom:0",
			kind: "dom",
			selector: "link[href*='.newrelic.com']",
			description: "DOM selector matches a known technology marker.",
		},
		{
			id: "new-relic:jsGlobal:1",
			kind: "jsGlobal",
			property: "NREUM",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "new-relic:jsGlobal:2",
			kind: "jsGlobal",
			property: "newrelic",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "new-relic:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("require\\(\"\\.\\/lib\\/agent\"\\)"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "new-relic:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("newrelic\\/security-agent"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "new-relic:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("require\\.cache\\.__NR_cache"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "new-relic:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("\\b[a-zA-Z_$][\\w$]*.recordSupportability"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "new-relic:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("New\\s+Relic\\s+for\\s+Node\\.js"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "new-relic:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("\\b[a-zA-Z_$][\\w$]*.recordFeatureFlagMetrics"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "new-relic:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("\\b[a-zA-Z_$][\\w$]*.recordSourceMapMetric"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "new-relic:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("set\\s+app_name\\s+in\\s+your\\s+newrelic"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "new-relic:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("newrelic\\.com\\/.*\\/agent"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "new-relic:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("newrelic.*agent.*\\.js"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "new-relic:resourceUrl:modern:10",
			kind: "resourceUrl",
			pattern: new RegExp("js\\.agent\\.newrelic\\.com"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "new-relic:resourceUrl:modern:11",
			kind: "resourceUrl",
			pattern: new RegExp("bam\\.nr-data\\.net"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "new-relic:resourceUrl:modern:12",
			kind: "resourceUrl",
			pattern: new RegExp("js-agent\\.newrelic\\.com\\/nr-.+\\.js"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "new-relic:resourceUrl:modern:13",
			kind: "resourceUrl",
			pattern: new RegExp("cdn\\.newrelic\\.com"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "new-relic:resourceUrl:modern:14",
			kind: "resourceUrl",
			pattern: new RegExp("newrelic\\/browser-agent"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "new-relic:resourceUrl:modern:15",
			kind: "resourceUrl",
			pattern: new RegExp("newrelic.*\\.js"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
	],
	metadata: {
		saas: true,
		pricing: [
			"freemium",
			"low",
			"mid",
			"payg",
			"recurring",
		],
	},
} as const satisfies TechnologyDefinition;
