import type { TechnologyDefinition } from '../../types';

export const opentelemetryTechnologyDefinition = {
	id: "opentelemetry",
	name: "opentelemetry",
	website: "https://opentelemetry.io",
	description: "OpenTelemetry is a framework for observability, providing standardized APIs, libraries, and agents to collect telemetry data.",
	icon: "opentelemetry.svg",
	categories: [
		"monitoring-error-tracking",
		"analytics",
	],
	rules: [
		{
			id: "opentelemetry:scriptSrc:0",
			kind: "scriptSrc",
			pattern: new RegExp("opentelemetry.*\\.js"),
			description: "Script source URL matches a known technology marker.",
		},
		{
			id: "opentelemetry:jsGlobal:1",
			kind: "jsGlobal",
			property: "otel",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "opentelemetry:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("OTEL_EXPORTER_OTLP_(?:TRACES_|METRICS_|LOGS_)?ENDPOINT:\\s*['\"']([^'\"']*)['\"']"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "opentelemetry:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("OTEL_SERVICE_NAME:"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "opentelemetry:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("OTEL_PROPAGATORS:"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "opentelemetry:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("OTEL_EXPORTER_OTLP_"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "opentelemetry:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("OTEL_EXPORTER_ZIPKIN_ENDPOINT:"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "opentelemetry:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("OTEL_EXPORTER_JAEGER_"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "opentelemetry:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("OTEL_(?:BSP|BLRP)_SCHEDULE_DELAY:"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "opentelemetry:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("Error\\(['\"']@opentelemetry\\/api: Attempted duplicate registration of API: ['\"']\\s*\\+\\s*[a-zA-Z_$][a-zA-Z0-9_$]*\\)"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "opentelemetry:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("Error\\(['\"']@opentelemetry\\/api: Registration of version v"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "opentelemetry:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("['\"']@opentelemetry\\/api: Registered a global for"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "opentelemetry:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("['\"']@opentelemetry\\/api: Unregistering a global for"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "opentelemetry:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("Error\\(['\"']Cannot use diag as the logger for itself\\. Please use a DiagLogger implementation like ConsoleDiagLogger or a custom implementation['\"']\\)"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "opentelemetry:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("Symbol\\.for\\(['\"']OpenTelemetry Context Key SPAN['\"']\\)"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "opentelemetry:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("this\\._provider\\.getDelegateTracer\\(this\\.name, this\\.version, this\\.options\\)"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "opentelemetry:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("\\[ATTR_TELEMETRY_SDK_NAME\\]:\\s*['\"']opentelemetry['\"']"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "opentelemetry:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("this\\._meterSharedState\\.observableRegistry"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "opentelemetry:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("this\\._meterSharedState\\.registerAsyncMetricStorage"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "opentelemetry:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("this\\._meterSharedState\\.observableRegistry\\.addBatchCallback"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "opentelemetry:scriptContent:modern:18",
			kind: "scriptContent",
			pattern: new RegExp("INT value type cannot accept a floating-point value for"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "opentelemetry:scriptContent:modern:19",
			kind: "scriptContent",
			pattern: new RegExp("this\\.metricStorageRegistry\\.findOrUpdateCompatibleCollectorStorage"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "opentelemetry:scriptContent:modern:20",
			kind: "scriptContent",
			pattern: new RegExp("Reflect\\.apply\\([a-zA-Z_$][a-zA-Z0-9_$]*\\.startActiveSpan, [a-zA-Z_$][a-zA-Z0-9_$]*, arguments\\)"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "opentelemetry:resourceUrl:modern:21",
			kind: "resourceUrl",
			pattern: new RegExp("opentelemetry\\.js\\.api"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "opentelemetry:requestUrl:modern:22",
			kind: "requestUrl",
			pattern: new RegExp("/\\.well-known/otel/(?:metrics|traces|logs)(?:\\?|$)", "i"),
			confidence: 85,
			description: "Observed request URL targets the OpenTelemetry well-known collection endpoint.",
		},
	],
	metadata: {
		oss: true,
	},
} as const satisfies TechnologyDefinition;
