import type { TechnologyDefinition } from '../../types';

export const rollbarTechnologyDefinition = {
	id: "rollbar",
	name: "Rollbar",
	website: "https://rollbar.com/",
	description: "Real-time error monitoring and debugging tool with detailed error reporting.",
	icon: "Rollbar.svg",
	categories: [
		"monitoring-error-tracking",
		"developer-tooling",
	],
	rules: [
		{
			id: "rollbar:scriptSrc:0",
			kind: "scriptSrc",
			pattern: new RegExp("rollbar\\.js\\/([0-9.]+)"),
			version: {
				source: "match",
				group: 1,
			},
			description: "Script source URL matches a known technology marker.",
		},
		{
			id: "rollbar:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("rollbar\\.min\\.js"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollbar:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("rollbar\\.js"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollbar:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("window\\._rollbarConfig"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollbar:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("\\bRollbar\\.error\\("),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollbar:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("\\bRollbar\\.warning\\("),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollbar:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("\\bRollbar\\.info\\("),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollbar:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("\\bRollbar\\.debug\\("),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollbar:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("\\bRollbar\\.critical\\("),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollbar:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("\\bRollbar\\.configure\\("),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollbar:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("\\bRollbar\\.log\\("),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollbar:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("\\bnew\\s+Rollbar\\("),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollbar:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("rollbar\\.com\\/api\\/1\\/item"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollbar:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("rollbar\\.com\\/api\\/1\\/occurrences"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollbar:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("_rollbarConfig="),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollbar:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("_rollbarShims"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollbar:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("_rollbarOldOnError"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollbar:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("_rollbarWrappedError"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollbar:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("window\\._rollbarDidLoad"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollbar:scriptContent:modern:18",
			kind: "scriptContent",
			pattern: new RegExp("setupShim\\(window,_rollbarConfig"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollbar:scriptContent:modern:19",
			kind: "scriptContent",
			pattern: new RegExp("rollbarJsUrl"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollbar:scriptContent:modern:20",
			kind: "scriptContent",
			pattern: new RegExp("r\\._rollbarWrappedError"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollbar:scriptContent:modern:21",
			kind: "scriptContent",
			pattern: new RegExp("r\\._rollbarOldOnError"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollbar:resourceUrl:modern:22",
			kind: "resourceUrl",
			pattern: new RegExp("cdnjs\\.cloudflare\\.com\\/ajax\\/libs\\/rollbar"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "rollbar:resourceUrl:modern:23",
			kind: "resourceUrl",
			pattern: new RegExp("rollbar\\.com\\/api\\/"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "rollbar:resourceUrl:modern:24",
			kind: "resourceUrl",
			pattern: new RegExp("cdn\\.rollbar\\.com\\/rollbarjs"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "rollbar:resourceUrl:modern:25",
			kind: "resourceUrl",
			pattern: new RegExp("js\\.sentry-cdn\\.com\\/.*\\/rollbar"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "rollbar:resourceUrl:modern:26",
			kind: "resourceUrl",
			pattern: new RegExp("rollbarjs\\/refs\\/tags\\/v[\\d\\.]+\\/rollbar(\\.min)?\\.js"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "rollbar:resourceUrl:modern:27",
			kind: "resourceUrl",
			pattern: new RegExp("rollbar\\.com\\/rollbarjs\\/"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
