import type { TechnologyDefinition } from '../../types';

export const sentryTechnologyDefinition = {
	id: "sentry",
	name: "Sentry",
	website: "https://sentry.io/",
	description: "Sentry is an open-source platform for workflow productivity, aggregating errors from across the stack in real time.",
	icon: "Sentry.svg",
	categories: [
		"monitoring-error-tracking",
		"developer-tooling",
	],
	rules: [
		{
			id: "sentry:scriptSrc:0",
			kind: "scriptSrc",
			pattern: new RegExp("browser\\.sentry\\-cdn\\.com\\/([0-9.]+)\\/bundle(?:\\.tracing)?(?:\\.min)?\\.js"),
			version: {
				source: "match",
				group: 1,
			},
			description: "Script source URL matches a known technology marker.",
		},
		{
			id: "sentry:html:1",
			kind: "html",
			pattern: new RegExp("<script[^>]*>\\s*Raven\\.config\\('[^']*', \\{\\s+release: '([0-9\\.]+)'"),
			version: {
				source: "match",
				group: 1,
			},
			description: "HTML contains a known technology signature.",
		},
		{
			id: "sentry:html:2",
			kind: "html",
			pattern: new RegExp("<script[^>]*src=\"[^\"]*browser\\.sentry\\-cdn\\.com\\/([0-9.]+)\\/bundle(?:\\.tracing)?(?:\\.min)?\\.js"),
			version: {
				source: "match",
				group: 1,
			},
			description: "HTML contains a known technology signature.",
		},
		{
			id: "sentry:jsGlobal:3",
			kind: "jsGlobal",
			property: "Raven.config",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "sentry:jsGlobal:4",
			kind: "jsGlobal",
			property: "Sentry",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "sentry:jsGlobal:5",
			kind: "jsGlobal",
			property: "Sentry.SDK_VERSION",
			valuePattern: new RegExp("(.+)"),
			version: {
				source: "match",
				group: 1,
			},
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "sentry:jsGlobal:6",
			kind: "jsGlobal",
			property: "__SENTRY__",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "sentry:jsGlobal:7",
			kind: "jsGlobal",
			property: "ravenOptions.whitelistUrls",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "sentry:scriptSrc:8",
			kind: "scriptSrc",
			pattern: new RegExp("\\.sentry-cdn\\.com\\/"),
			description: "Script source URL matches a known technology marker.",
		},
		{
			id: "sentry:jsGlobal:9",
			kind: "jsGlobal",
			property: "SENTRY_SDK_SOURCE",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "sentry:html:10",
			kind: "html",
			pattern: new RegExp("<script[^>]*>\\s*raven\\.config\\('[^']*', \\{\\s+release: '([0-9\\.]+)'"),
			version: {
				source: "match",
				group: 1,
			},
			description: "HTML contains a known technology signature.",
		},
		{
			id: "sentry:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("Sentry responded with status code "),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "sentry:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("\\[[\"']x-sentry-rate-limits[\"']\\]"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "sentry:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("\\b[a-zA-Z_$][\\w$]*\\.headers\\.get\\([\"']X-Sentry-Rate-Limits[\"']\\)"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "sentry:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("\\b[a-zA-Z_$][\\w$]*\\.setAttribute\\([\"']sentry\\.idle_span_discarded_spans[\"'],\\s*[a-zA-Z_$][\\w$]*\\)"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "sentry:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("warn\\([\"']Invalid sentry-trace data\\. Cannot generate trace data[\"']\\)"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "sentry:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("\\b[a-zA-Z_$][\\w$]*\\[[\"']sentry\\.browser\\.measure_start_time[\"']\\]"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "sentry:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("\\b[a-zA-Z_$][\\w$]*\\.setAttribute\\([\"']sentry\\.cancellation_reason[\"'],\\s*[\"']document\\.hidden[\"']\\)"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "sentry:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("\\b[a-zA-Z_$][\\w$]*\\.__sentry_own_request__"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "sentry:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("\\b[a-zA-Z_$][\\w$]*\\.__sentry_xhr_span_id__"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "sentry:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("\\b[a-zA-Z_$][\\w$]*\\.__SENTRY_INSTRUMENTED__"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "sentry:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("\\b[a-zA-Z_$][\\w$]*\\.__SENTRY_LOADER__"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "sentry:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("Error\\(['\"']Sentry syntheticException['\"']\\)"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "sentry:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("\\b[a-zA-Z_$][\\w$]*\\._sentryRewriteFramesAssetPrefixPath\\b"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "sentry:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("new\\s+Error\\([\"']Raven send failed \\(no additional details provided\\)[\"']\\)"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "sentry:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("[\"']Raven dropped repeat event: [\"']"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "sentry:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("sentry_client:[\"']raven-js\\/[\"']"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "sentry:resourceUrl:modern:16",
			kind: "resourceUrl",
			pattern: new RegExp("browser\\.sentry-cdn\\.com"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "sentry:resourceUrl:modern:17",
			kind: "resourceUrl",
			pattern: new RegExp("js\\.sentry-cdn\\.com"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "sentry:resourceUrl:modern:18",
			kind: "resourceUrl",
			pattern: new RegExp("cdn\\.ravenjs\\.com"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
	],
	metadata: {
		cpe: "cpe:2.3:a:sentry:sentry:*:*:*:*:*:*:*:*",
	},
} as const satisfies TechnologyDefinition;
