import type { TechnologyDefinition } from '../../types';

export const bunTechnologyDefinition = {
	id: "bun",
	name: "Bun",
	website: "https://bun.sh",
	description: "Bun is a JavaScript runtime, bundler, test runner, and package manager.",
	categories: [
		"bundler",
		"transpiler",
	],
	rules: [
		{
			id: "bun:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("\\$b\\$_import\\$\\([\"'][^\"']+[\"']\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("\\bBun\\.appdir\\s*="),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("\\bBun\\.main\\s*=\\s*import\\.meta\\.path"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("\\$b\\$_registry\\s*=\\s*new\\s+Map"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("\\$b\\$_modules\\s*=\\s*new\\s+Map"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("\\$b\\$_entry\\s*\\(\\s*[\"'][^\"']+[\"']\\s*\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("\\$b\\$_load\\(\\s*\\{\\s*id:\\s*[\"'][^\"']+[\"']"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("\\$b\\$_hmr\\$\\w+"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("\\$b\\$_interop\\$default"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("\\$b\\$_require\\s*\\(\\s*[\"'][^\"']+[\"']\\s*\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("\\$b\\$_asset\\$url\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("\\$b\\$_asset\\$inline\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("\\/\\*\\s*@bun-plugin\\s*\\*\\/"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("\\/\\*\\s*@bun-chunk\\s*\\*\\/"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("\\/\\*\\s*@bun-pure\\s*\\*\\/"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("\\$b\\$_css\\$optimize"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("\\$b\\$_js\\$optimize"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("\\$b\\$_macro\\$env\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:18",
			kind: "scriptContent",
			pattern: new RegExp("\\$b\\$_macro\\$path\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:19",
			kind: "scriptContent",
			pattern: new RegExp("\\$b\\$_macro\\$dirname\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:20",
			kind: "scriptContent",
			pattern: new RegExp("\\$b\\$_macro\\$import\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:21",
			kind: "scriptContent",
			pattern: new RegExp("\\$b\\$_macro\\$require\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:22",
			kind: "scriptContent",
			pattern: new RegExp("\\$b\\$_hmr\\$accept\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:23",
			kind: "scriptContent",
			pattern: new RegExp("\\$b\\$_hmr\\$self\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:24",
			kind: "scriptContent",
			pattern: new RegExp("\\$b\\$_hmr\\$data\\s*="),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:25",
			kind: "scriptContent",
			pattern: new RegExp("\\$b\\$_hmr\\$runtime\\s*="),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:26",
			kind: "scriptContent",
			pattern: new RegExp("\\$b\\$_hmr\\$update\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:27",
			kind: "scriptContent",
			pattern: new RegExp("\\[\"bun:wrap\"\\]"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:28",
			kind: "scriptContent",
			pattern: new RegExp("Bun\\.(?:consume|resolveSync|resolve|fileURLToPath)\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:29",
			kind: "scriptContent",
			pattern: new RegExp("\\bBun\\.(?:env|main|file|which)\\b"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:30",
			kind: "scriptContent",
			pattern: new RegExp("\\$blazepack\\$__(?:require|import)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:31",
			kind: "scriptContent",
			pattern: new RegExp("Bun\\.(?:error|sleep)\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:32",
			kind: "scriptContent",
			pattern: new RegExp("\\bBunPlugin\\b"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:33",
			kind: "scriptContent",
			pattern: new RegExp("async\\s+function\\s*\\w*\\s*\\(\\)\\s*\\{\\s*return\\s+await\\s+Bun\\."),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:34",
			kind: "scriptContent",
			pattern: new RegExp("import\\s*\\.\\s*meta\\s*\\.\\s*(?:path|url)\\s*=\\s*Bun\\."),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:35",
			kind: "scriptContent",
			pattern: new RegExp("class\\s+\\w+\\s*extends\\s+Bun\\."),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:36",
			kind: "scriptContent",
			pattern: new RegExp("__toBun\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:37",
			kind: "scriptContent",
			pattern: new RegExp("Bun\\.unwrap\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:38",
			kind: "scriptContent",
			pattern: new RegExp("__FastRefreshRuntime__\\.register\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:39",
			kind: "scriptContent",
			pattern: new RegExp("__FastRefreshRuntime__\\.performReactRefresh\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:40",
			kind: "scriptContent",
			pattern: new RegExp("\\$RefreshReg\\$\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:41",
			kind: "scriptContent",
			pattern: new RegExp("\\$RefreshSig\\$\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:42",
			kind: "scriptContent",
			pattern: new RegExp("\\/\\*\\s*@bun-safe\\s*\\*\\/"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:43",
			kind: "scriptContent",
			pattern: new RegExp("\\/\\*\\s*@bun-types\\s*\\*\\/"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:44",
			kind: "scriptContent",
			pattern: new RegExp("\\/\\*\\s*@bun-runtime\\s*\\*\\/"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:45",
			kind: "scriptContent",
			pattern: new RegExp("\\/\\*\\s*@pure\\s*\\*\\/\\s*Bun\\."),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "bun:scriptContent:modern:46",
			kind: "scriptContent",
			pattern: new RegExp("\\/\\*\\s*@__PURE__\\s*\\*\\/\\s*Bun\\."),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
