import type { TechnologyDefinition } from '../../types';

export const rollupTechnologyDefinition = {
	id: "rollup",
	name: "rollup",
	website: "https://rollupjs.org/",
	description: "A module bundler for JavaScript which compiles small pieces of code into something larger and more complex",
	categories: [
		"bundler",
	],
	rules: [
		{
			id: "rollup:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("var\\s*\\w+\\s*=\\s*\\(function\\s*\\(exports\\)\\s*\\{\\s*['\"]use strict['\"]\\s*;\\s*\\/\\*\\s*Rollup\\s*[^*]*\\*\\/", "i"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollup:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("createCommonjsModule\\s*\\(\\s*function\\s*\\(module,\\s*exports\\)\\s*\\{\\s*\\/\\*\\s*@rollup\\/\\w+\\s*\\*\\/"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollup:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("\\/\\*\\s*rollup-plugin-\\w+\\s*version:\\s*['\"][0-9.]+['\"]\\s*\\*\\/"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollup:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("Object\\.defineProperty\\s*\\(\\s*exports,\\s*['\"]__esModule['\"],\\s*\\{\\s*value:\\s*true\\s*\\}\\s*\\);\\s*\\/\\*\\s*Rollup\\s*"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollup:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("\\/\\*![^*]+\\*\\/"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollup:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("import\\s*{\\s*[a-zA-Z$_][a-zA-Z0-9$_]*\\s+as\\s+[a-zA-Z$_][a-zA-Z0-9$_]*\\s*(?:,\\s*[a-zA-Z$_][a-zA-Z0-9$_]*\\s+as\\s+[a-zA-Z$_][a-zA-Z0-9$_]*\\s*)*}\\s*from\\s*[\"'][^\"']+[\"']"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollup:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("__import__\\s*\\(\\s*[\"']\\.\\/chunk"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollup:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("from\\s*[\"']\\.\\/chunk-[A-Z0-9]{8}\\.js[\"']"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollup:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("from\\s*[\"']\\.\\/chunk-[a-z0-9]{8}\\.js[\"']"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollup:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("export\\s*{\\s*[a-zA-Z$_][a-zA-Z0-9$_]*\\s+as\\s+[a-z]\\s*}"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollup:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("export\\s*{\\s*[a-zA-Z$_][a-zA-Z0-9$_]*\\s+(?:as\\s+[a-zA-Z$_][a-zA-Z0-9$_]*)?\\s*(?:,\\s*[a-zA-Z$_][a-zA-Z0-9$_]*\\s+(?:as\\s+[a-zA-Z$_][a-zA-Z0-9$_]*)?\\s*)*}\\s*(?:from\\s*[\"'][^\"']+[\"'])?"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollup:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("function\\s*loadBundle\\s*\\(\\s*bundle\\s*\\)\\s*\\{\\s*return\\s*Promise\\.all\\(Object\\.keys\\(bundle\\)\\.map\\(\\(\\s*key\\s*\\)\\s*=>\\s*\\{"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollup:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("function\\s*register\\s*\\(\\s*modules\\s*\\)\\s*\\{\\s*modules\\.forEach\\(\\s*function\\s*\\(\\s*module\\s*\\)\\s*\\{\\s*registry\\[module\\.id\\]\\s*=\\s*module"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollup:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("function\\s*instantiate\\s*\\(\\s*id\\s*\\)\\s*\\{\\s*var\\s*module\\s*=\\s*registry\\[id\\];\\s*if\\s*\\(module\\.instance\\)\\s*return\\s*module\\.instance;"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollup:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("function\\s*_interopNamespace\\s*\\(\\s*e\\s*\\)\\s*\\{\\s*if\\s*\\(e\\s*&&\\s*e\\.__esModule\\)\\s*return\\s*e;\\s*var\\s*n\\s*=\\s*Object\\.create\\s*\\(null\\);\\s*if\\s*\\(e\\)\\s*\\{\\s*Object\\.keys\\s*\\(e\\)\\.forEach\\s*\\("),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollup:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("return\\s*Promise\\.resolve\\s*\\(\\s*\\)\\s*\\.then\\s*\\(\\s*function\\s*\\(\\s*\\)\\s*\\{\\s*return\\s*__module__\\s*\\}\\s*\\)\\.catch\\s*\\(\\s*function\\s*\\(e\\)\\s*\\{\\s*deleted\\[id\\]\\s*=\\s*true;"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollup:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("var\\s*registry\\s*=\\s*\\{\\};\\s*var\\s*deleted\\s*=\\s*\\{\\};\\s*function\\s*register\\s*\\(\\s*id,\\s*exports\\s*\\)\\s*\\{\\s*deleted\\[id\\]\\s*=\\s*false;"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "rollup:resourceUrl:modern:17",
			kind: "resourceUrl",
			pattern: new RegExp("chunk-[A-Z0-9]{8}\\.js$"),
			confidence: 65,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "rollup:resourceUrl:modern:18",
			kind: "resourceUrl",
			pattern: new RegExp("chunk-[a-z0-9]{8}\\.js$"),
			confidence: 65,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "rollup:resourceUrl:modern:19",
			kind: "resourceUrl",
			pattern: new RegExp("chunk-[A-Z0-9]{6,12}\\.js$"),
			confidence: 65,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
