import type { TechnologyDefinition } from '../../types';

export const turbopackTechnologyDefinition = {
	id: "turbopack",
	name: "Turbopack",
	website: "https://nextjs.org/docs/app/api-reference/turbopack",
	description: "Turbopack is an incremental bundler for JavaScript and TypeScript, written in Rust and integrated into the Next.js framework for optimized build performance.",
	icon: "Turbopack.svg",
	categories: [
		"bundler",
		"transpiler",
		"developer-tooling",
	],
	rules: [
		{
			id: "turbopack:jsGlobal:0",
			kind: "jsGlobal",
			property: "TURBOPACK.push",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "turbopack:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("TURBOPACK"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "turbopack:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("\\[\\[SSR\\]\\]"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "turbopack:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("(__turbopack_require__)[\\s\\n]*="),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "turbopack:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("(__turbopack_external_require__)[\\s\\n]*="),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "turbopack:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("(__turbopack_cache__)[\\s\\n]*="),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "turbopack:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("(__turbopack_export__)[\\s\\n]*="),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "turbopack:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("(__turbopack_import__)[\\s\\n]*="),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "turbopack:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("(turbopack_modules|_tm)[\\s\\n]*="),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "turbopack:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("(turbopack\\/runtime)"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "turbopack:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("chunk_global_id"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "turbopack:resourceUrl:modern:10",
			kind: "resourceUrl",
			pattern: new RegExp("\\[\\d+\\]\\.entry\\.[a-f0-9]{16}\\.js$"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "turbopack:resourceUrl:modern:11",
			kind: "resourceUrl",
			pattern: new RegExp("chunks\\/\\[\\d+\\]\\.[a-f0-9]{16}\\.js$"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "turbopack:resourceUrl:modern:12",
			kind: "resourceUrl",
			pattern: new RegExp("chunks\\/[a-zA-Z0-9_-]+\\.[a-f0-9]{16}\\.js$"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "turbopack:resourceUrl:modern:13",
			kind: "resourceUrl",
			pattern: new RegExp("static\\/chunks\\/[^/]+\\.js$"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "turbopack:resourceUrl:modern:14",
			kind: "resourceUrl",
			pattern: new RegExp("static\\/chunks\\/app\\/[^/]+\\.js$"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "turbopack:resourceUrl:modern:15",
			kind: "resourceUrl",
			pattern: new RegExp("app-pages-browser\\.js$"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
	],
	metadata: {
		saas: false,
		oss: true,
	},
	requires: [
		"next-js",
	],
} as const satisfies TechnologyDefinition;
