import type { TechnologyDefinition } from '../../types';

export const viteTechnologyDefinition = {
	id: "vite",
	name: "vite",
	website: "https://vitejs.dev/",
	description: "A build tool that aims to provide a faster and leaner development experience for modern web projects",
	categories: [
		"bundler",
	],
	rules: [
		{
			id: "vite:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("const\\s+\\w+=document\\.createElement\\(\"link\"\\)\\.relList;if\\(\\w+&&\\w+\\.supports&&\\w+\\.supports\\(\"modulepreload\"\\)\\)return;"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("if\\(\\w+\\.ep\\)return;\\w+\\.ep=!0"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("import\\.meta\\.env\\.VITE_"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("\\/@vite\\/client"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("vite\\/dist\\/client"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("vite\\/modulepreload-polyfill"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("\\[vite\\]"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("__vite__bundler"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("__vite__xhr"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("__vite__log"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("__vite__cjsImport"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("__vite__baseUrl"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("__vite_ws"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("__vite__loadChunk"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("__vite__moveToHead"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("__vite__injectRef"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("__vite__mapDeps"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("\\b\\w+\\.vitePluginDetected\\b"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:18",
			kind: "scriptContent",
			pattern: new RegExp("\\[vite\\]\\s+Failed\\s+to\\s+load", "i"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:19",
			kind: "scriptContent",
			pattern: new RegExp("new\\s+Event\\(\\s*[\"']vite:preloadError[\"']"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:stylesheetContent:modern:20",
			kind: "stylesheetContent",
			pattern: new RegExp("\\.vite-error-overlay"),
			confidence: 45,
			description: "Stylesheet content matches a modern styling marker.",
		},
		{
			id: "vite:stylesheetContent:modern:21",
			kind: "stylesheetContent",
			pattern: new RegExp("\\[vite-hmr-indicator\\]"),
			confidence: 45,
			description: "Stylesheet content matches a modern styling marker.",
		},
		{
			id: "vite:scriptContent:modern:22",
			kind: "scriptContent",
			pattern: new RegExp("import\\s*{\\s*[a-zA-Z]+\\s+as\\s+[a-zA-Z]+\\s*}\\s*from"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:23",
			kind: "scriptContent",
			pattern: new RegExp("import\\s*{\\s*[a-zA-Z$_][a-zA-Z0-9$_]*\\s+as\\s+[a-z]\\s*}"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:24",
			kind: "scriptContent",
			pattern: new RegExp("import\\s*{\\s*[a-zA-Z$_][a-zA-Z0-9$_]*\\s+as\\s+[a-zA-Z$_][a-zA-Z0-9$_]*\\s*(?:,\\s*[a-zA-Z$_][a-zA-Z0-9$_]*\\s+as\\s+[a-zA-Z$_][a-zA-Z0-9$_]*\\s*)*}\\s*from\\s*[\"'][^\"']+[\"']"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:25",
			kind: "scriptContent",
			pattern: new RegExp("__import__\\s*\\(\\s*[\"']\\.\\/chunk"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:26",
			kind: "scriptContent",
			pattern: new RegExp("from\\s*[\"']\\.\\/chunk-[A-Z0-9]{8}\\.js[\"']"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:27",
			kind: "scriptContent",
			pattern: new RegExp("from\\s*[\"']\\.\\/chunk-[a-z0-9]{8}\\.js[\"']"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:28",
			kind: "scriptContent",
			pattern: new RegExp("export\\s*{\\s*[a-zA-Z$_][a-zA-Z0-9$_]*\\s+as\\s+[a-z]\\s*}"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:29",
			kind: "scriptContent",
			pattern: new RegExp("export\\s*{\\s*[a-zA-Z$_][a-zA-Z0-9$_]*\\s+(?:as\\s+[a-zA-Z$_][a-zA-Z0-9$_]*)?\\s*(?:,\\s*[a-zA-Z$_][a-zA-Z0-9$_]*\\s+(?:as\\s+[a-zA-Z$_][a-zA-Z0-9$_]*)?\\s*)*}\\s*(?:from\\s*[\"'][^\"']+[\"'])?"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:30",
			kind: "scriptContent",
			pattern: new RegExp("const\\s+\\w+\\s*=\\s*{\"VITE_[A-Z0-9_]+\":"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:31",
			kind: "scriptContent",
			pattern: new RegExp("process\\.env\\.VITE_"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:32",
			kind: "scriptContent",
			pattern: new RegExp("import\\.meta\\.env\\.VITE_[A-Z0-9_]+"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:33",
			kind: "scriptContent",
			pattern: new RegExp("import\\.meta\\.env\\.MODE"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:34",
			kind: "scriptContent",
			pattern: new RegExp("import\\.meta\\.env\\.PROD"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:35",
			kind: "scriptContent",
			pattern: new RegExp("import\\.meta\\.env\\.DEV"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:36",
			kind: "scriptContent",
			pattern: new RegExp("import\\.meta\\.env\\.SSR"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:37",
			kind: "scriptContent",
			pattern: new RegExp("\\.\\.\\.(import\\.meta\\.env)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:38",
			kind: "scriptContent",
			pattern: new RegExp("vite-hmr"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:39",
			kind: "scriptContent",
			pattern: new RegExp("vite-hot-data"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:40",
			kind: "scriptContent",
			pattern: new RegExp("@vite\\/env"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:41",
			kind: "scriptContent",
			pattern: new RegExp("\\/@fs\\/"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:42",
			kind: "scriptContent",
			pattern: new RegExp("\\/@id\\/"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:43",
			kind: "scriptContent",
			pattern: new RegExp("@modules\\/"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:44",
			kind: "scriptContent",
			pattern: new RegExp("resolveVirtualModule"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:45",
			kind: "scriptContent",
			pattern: new RegExp("virtual:\\/\\/"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:46",
			kind: "scriptContent",
			pattern: new RegExp("vite-error-overlay"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:47",
			kind: "scriptContent",
			pattern: new RegExp("__vite__error"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:48",
			kind: "scriptContent",
			pattern: new RegExp("vite-plugin-error"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:49",
			kind: "scriptContent",
			pattern: new RegExp("vite-plugin-"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:50",
			kind: "scriptContent",
			pattern: new RegExp("__vite_ssr_"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:51",
			kind: "scriptContent",
			pattern: new RegExp("__vite_ssr_dynamic_import__"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vite:scriptContent:modern:52",
			kind: "scriptContent",
			pattern: new RegExp("__vite_ssr_import__"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
