import type { TechnologyDefinition } from '../../types';

export const webpackTechnologyDefinition = {
	id: "webpack",
	name: "Webpack",
	website: "https://webpack.js.org/",
	description: "A static module bundler for modern JavaScript applications",
	categories: [
		"bundler",
	],
	rules: [
		{
			id: "webpack:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("__webpack_require__"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "webpack:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("__webpack_modules__"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "webpack:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("__webpack_module_cache__"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "webpack:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("__webpack_exports__"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "webpack:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("__webpack_public_path__"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "webpack:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("webpackJsonp"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "webpack:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("webpackChunk"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "webpack:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("__webpack_require__\\.e"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "webpack:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("(self|window)\\.webpackChunk_[\\w_]+="),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "webpack:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("installedChunks\\[chunkId\\]"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "webpack:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("__webpack_require__\\.[rdot]"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "webpack:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("__webpack_dynamic_require__"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "webpack:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("__non_webpack_require__"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "webpack:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("webpackHotUpdate"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "webpack:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("__webpack_require__\\.hmr"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "webpack:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("webpack\\/hot"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "webpack:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("webpackAsyncContext"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "webpack:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("\\/\\*\\s*webpackChunkName\\s*:"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "webpack:scriptContent:modern:18",
			kind: "scriptContent",
			pattern: new RegExp("webpack\\/runtime"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "webpack:scriptContent:modern:19",
			kind: "scriptContent",
			pattern: new RegExp("webpack\\/bootstrap"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "webpack:scriptContent:modern:20",
			kind: "scriptContent",
			pattern: new RegExp("webpack:\\/\\/"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "webpack:scriptContent:modern:21",
			kind: "scriptContent",
			pattern: new RegExp("__webpack_require__\\.p"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "webpack:scriptContent:modern:22",
			kind: "scriptContent",
			pattern: new RegExp("webpack-dev-server"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "webpack:scriptContent:modern:23",
			kind: "scriptContent",
			pattern: new RegExp("webpackDevServer"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "webpack:scriptContent:modern:24",
			kind: "scriptContent",
			pattern: new RegExp("\\/\\/# sourceURL=webpack"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
