import type { TechnologyDefinition } from '../../types';

export const swcTechnologyDefinition = {
	id: "swc",
	name: "SWC",
	website: "https://swc.rs",
	description: "SWC is a fast compiler and minifier for JavaScript and TypeScript.",
	categories: [
		"minifier",
		"transpiler",
	],
	rules: [
		{
			id: "swc:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("_createClass\\([A-Z],\\[\\{key:\"[a-z]\",value:function\\(\\)\\{\\}\\}\\]\\)"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "swc:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("var [$_a-z]=\\d+(?:,[$_a-z]=\\d+){2,}"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "swc:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("async function\\(\\)\\{try\\{await [$_a-z]\\(\\)\\}catch\\([a-z]\\)\\{\\}\\}"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "swc:resourceUrl:modern:3",
			kind: "resourceUrl",
			pattern: new RegExp("\\.swc\\.min\\.js$"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "swc:resourceUrl:modern:4",
			kind: "resourceUrl",
			pattern: new RegExp("\\.min\\.swc\\.js$"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "swc:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("\"use strict\";(?:\\s*var\\s+__create\\s*=\\s*Object\\.create;\\s*var\\s+__defProp\\s*=\\s*Object\\.defineProperty;\\s*var\\s+__getOwnPropDesc\\s*=\\s*Object\\.getOwnPropertyDescriptor;)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "swc:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("var\\s+__defNormalProp\\s*=\\s*\\(\\w+,\\s*\\w+,\\s*\\w+\\)\\s*=>\\s*\\w+\\s+in\\s+\\w+\\s*\\?\\s*__defProp"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "swc:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("var\\s+_\\w+\\s*=\\s*\\/\\*#__PURE__\\*\\/\\s*new\\s+WeakMap\\(\\);"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "swc:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("var\\s+__decorateClass\\s*=\\s*\\(\\[\\s*decorators,\\s*target,\\s*key,\\s*kind\\s*\\]\\)\\s*=>"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "swc:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("var\\s+__metadata\\s*=\\s*\\(\\[\\s*metadataKey,\\s*metadataValue\\s*\\]\\)\\s*=>"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "swc:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("return\\s*\\(\\w+\\s*=\\s*class\\s+extends\\s*\\w+\\s*\\{\\}\\s*,\\s*__decorateClass\\(\\[\\w+\\],\\s*\\w+\\.prototype,\\s*[\"']\\w+[\"']"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "swc:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("var\\s+__async\\s*=\\s*\\(__this,\\s*__arguments,\\s*generator\\)\\s*=>\\s*\\{"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "swc:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("(?:var|let)\\s+(_\\w+)\\s*=\\s*class\\s+extends\\s+\\w+\\s*\\{\\s*constructor\\(\\)\\s*\\{\\s*super\\(\\);\\s*_\\w+\\.set\\(this,\\s*void\\s*0\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "swc:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("\\(\\s*function\\s*\\(\\w+\\)\\s*\\{\\s*\\w+\\[\\w+\\[\"[^\"]+\"\\]\\s*=\\s*\\d+\\]\\s*=\\s*\"[^\"]+\";\\s*\\}\\)\\(\\w+\\s*\\|\\|\\s*\\(\\w+\\s*=\\s*\\{\\}\\)\\);"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "swc:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("var\\s+__toESM\\s*=\\s*\\(\\w+,\\s*\\w+\\)\\s*=>\\s*\\{\\s*return\\s+__reExport\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "swc:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("var\\s+__reExport\\s*=\\s*\\(\\w+,\\s*\\w+,\\s*\\w+\\)\\s*=>\\s*Object\\.keys\\(\\w+\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "swc:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("Object\\.defineProperty\\(\\w+,\\s*\"__esModule\",\\s*\\{\\s*value:\\s*true\\s*\\}\\);\\s*__reExport\\(exports,"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
