import type { DetectionRunOptions, SiteAnalysis, TechnologyDefinition } from '../detection/types';
import type { ObservationPatternMatch } from '../detection/observation-match-types';
import type { ObservationMatcherDiagnostics, ObservationMatcherIndex } from '../detection/observation-matcher-index';
import type { CompiledDetectionRegistry } from '../detection/registry-graph';
import type { DetectionPipelineRuntimeResult } from '../pipeline';
import type {
	NormalizedObservationKind,
	ObservationBatch,
	ObservationTarget,
} from '../observations';

/**
 * Priority assigned to matcher work before it enters the offscreen worker pool.
 *
 * Lower numbers run first. The popup needs cheap document facts before deep
 * source and asset scans, so scheduler priority replaces the older hard split
 * between an early detector and a later detector.
 */
export type MatcherPartitionPriority = 1 | 2 | 3 | 4;

/** Current lifecycle state for a durable matcher job. */
export type MatcherJobStatus =
	| 'queued'
	| 'dispatching'
	| 'running'
	| 'streaming'
	| 'completed'
	| 'stale'
	| 'canceled'
	| 'failed';

/** Why a matcher job can be deprioritized or rejected after it has started. */
export type MatcherJobTerminalReason =
	| 'completed'
	| 'manual-refresh'
	| 'navigation'
	| 'tab-closed'
	| 'tab-closed-cache-complete'
	| 'newer-job'
	| 'offscreen-unavailable'
	| 'worker-failed';

/** Scheduler mode for one matcher job. */
export type MatcherJobMode = 'complete' | 'evidence-pass';

/** Stable ids used by background, offscreen, and worker messages for one matcher run. */
export interface MatcherJobIdentity {
	/** Job id generated by the background before work is dispatched. */
	readonly jobId: string;
	/** Browser tab that requested or owns the job. */
	readonly tabId: number;
	/** Session id for popup observation, when the job belongs to a live popup session. */
	readonly sessionId?: string;
	/** Document URL captured before collection started. */
	readonly expectedUrl: string;
	/** Whether persistent writes are skipped for this job. */
	readonly incognito?: boolean;
}

/** Durable lifecycle record used by background scheduling and diagnostics. */
export interface MatcherJobRecord extends MatcherJobIdentity {
	/** Current state of the job. */
	readonly status: MatcherJobStatus;
	/** Scheduling mode selected for this run. */
	readonly mode: MatcherJobMode;
	/** Target document from the observation batch. */
	readonly target: ObservationTarget;
	/** Timestamp when the background created the job. */
	readonly createdAt: number;
	/** Timestamp when the job record last changed. */
	readonly updatedAt: number;
	/** Number of observations sent to offscreen or fallback matching. */
	readonly observationCount: number;
	/** Number of matcher partitions derived from the observation batch. */
	readonly partitionCount: number;
	/** Latest completed partition count seen by the background. */
	readonly completedPartitionCount: number;
	/** Optional terminal reason for stale, canceled, completed, or failed jobs. */
	readonly reason?: MatcherJobTerminalReason;
	/** Error message stored when a job fails before a usable result exists. */
	readonly errorMessage?: string;
}

/** Partition of observations that can be matched independently by kind. */
export interface MatcherPartitionTask {
	/** Job that owns this partition. */
	readonly job: MatcherJobIdentity;
	/** Unique id within the job, usually based on kind and ordinal. */
	readonly partitionId: string;
	/** Observation kind processed by this partition. */
	readonly kind: NormalizedObservationKind;
	/** Scheduler priority for this partition. */
	readonly priority: MatcherPartitionPriority;
	/** Observation batch containing only this partition's observations. */
	readonly batch: ObservationBatch;
	/** Original observation indexes from the unpartitioned batch. */
	readonly observationIndexes: readonly number[];
	/** Optional detector flags such as disabled kinds. */
	readonly options?: DetectionRunOptions;
}

/** Match event annotated with original batch order for deterministic merge. */
export interface MatcherPartitionMatch {
	/** Observation index in the unpartitioned batch. */
	readonly observationIndex: number;
	/** Match order inside that observation after registry sequence routing. */
	readonly matchIndex: number;
	/** Pattern match emitted by the semantic matcher. */
	readonly match: ObservationPatternMatch;
}

/** Worker result for one kind partition. */
export interface MatcherPartitionResult {
	/** Job that owns this result. */
	readonly job: MatcherJobIdentity;
	/** Partition id that produced the result. */
	readonly partitionId: string;
	/** Observation kind processed by the worker. */
	readonly kind: NormalizedObservationKind;
	/** Scheduler priority assigned before dispatch. */
	readonly priority: MatcherPartitionPriority;
	/** Original observation count processed by this partition. */
	readonly observationCount: number;
	/** Ordered matches with original observation indexes attached. */
	readonly matches: readonly MatcherPartitionMatch[];
	/** Indexed matcher diagnostics for this partition. */
	readonly diagnostics: ObservationMatcherDiagnostics;
	/** Timestamp recorded by the worker when the partition completed. */
	readonly completedAt: number;
}

/** Input sent from background to the offscreen matcher host. */
export interface RunMatcherJobRequest {
	/** Job identity and lifecycle metadata. */
	readonly job: MatcherJobIdentity;
	/** Scheduler mode selected by the background. */
	readonly mode: MatcherJobMode;
	/** Full or filtered observation batch to partition. */
	readonly batch: ObservationBatch;
	/** Registry used by offscreen workers and fallback matching. */
	readonly registry: readonly TechnologyDefinition[];
	/** Prebuilt matcher index shared with the executor for this job. */
	readonly index: ObservationMatcherIndex;
	/** Relationship graph used after worker partitions emit rule matches. */
	readonly relationshipGraph: CompiledDetectionRegistry;
	/** Optional detector compatibility flags. */
	readonly options?: DetectionRunOptions;
	/** Emitted analysis timestamp override used by deterministic tests. */
	readonly analyzedAt?: number;
	/** Source marker written to emitted analysis. */
	readonly source?: SiteAnalysis['source'];
	/** Maximum workers the offscreen pool may keep hot. */
	readonly maxWorkerCount?: number;
}

/** Executor path that produced a matcher job result. */
export type MatcherJobExecutor = 'offscreen-worker-pool' | 'background-fallback' | 'dev-fallback';

/** Completed matcher job returned to the background. */
export interface MatcherJobRunResult {
	/** Identity supplied by the background. */
	readonly job: MatcherJobIdentity;
	/** Job mode that produced the result. */
	readonly mode: MatcherJobMode;
	/** Final analysis and replay-safe pipeline events. */
	readonly result: DetectionPipelineRuntimeResult;
	/** Partitions completed by the offscreen worker pool. */
	readonly partitions: readonly MatcherPartitionResult[];
	/** Whether the offscreen worker path or background fallback produced the result. */
	readonly executor: MatcherJobExecutor;
	/** Timestamp when the executor completed the final merge. */
	readonly completedAt: number;
}

/** Offscreen-host message channel used by background and the hidden page. */
export const MATCHER_OFFSCREEN_CHANNEL = 'red-detector.matcher-offscreen.v1';

/** Message asking the offscreen host to run a matcher job. */
export interface RunMatcherJobMessage {
	/** Private channel discriminator so unrelated runtime messages are ignored. */
	readonly channel: typeof MATCHER_OFFSCREEN_CHANNEL;
	/** Command name handled by the offscreen host. */
	readonly type: 'matcher.run-job';
	/** Request payload generated by the background scheduler. */
	readonly request: RunMatcherJobRequest;
}

/** Message asking the offscreen host to cancel queued or running job work. */
export interface CancelMatcherJobMessage {
	/** Private channel discriminator so unrelated runtime messages are ignored. */
	readonly channel: typeof MATCHER_OFFSCREEN_CHANNEL;
	/** Command name handled by the offscreen host. */
	readonly type: 'matcher.cancel-job';
	/** Job id to remove from queues and mark canceled. */
	readonly jobId: string;
}

/** Message asking the offscreen host whether it is loaded and ready. */
export interface PingMatcherHostMessage {
	/** Private channel discriminator so unrelated runtime messages are ignored. */
	readonly channel: typeof MATCHER_OFFSCREEN_CHANNEL;
	/** Command name handled by the offscreen host. */
	readonly type: 'matcher.ping';
}

/** Runtime messages accepted by the offscreen matcher host. */
export type MatcherOffscreenRequestMessage =
	| RunMatcherJobMessage
	| CancelMatcherJobMessage
	| PingMatcherHostMessage;

/** Successful response from the offscreen matcher host. */
export type MatcherOffscreenResponse =
	| { readonly ok: true; readonly ready: true }
	| { readonly ok: true; readonly canceled: true; readonly jobId: string }
	| { readonly ok: true; readonly value: MatcherJobRunResult }
	| { readonly ok: false; readonly message: string };

/** Message emitted by offscreen when a partition completes before the full job. */
export interface MatcherPartitionProgressMessage {
	/** Private channel discriminator so background can ignore unrelated messages. */
	readonly channel: typeof MATCHER_OFFSCREEN_CHANNEL;
	/** Progress event name emitted from offscreen to background. */
	readonly type: 'matcher.partition-complete';
	/** Completed partition summary. */
	readonly partition: MatcherPartitionResult;
	/** Number of partitions completed so far for the job. */
	readonly completedPartitionCount: number;
	/** Total partition count for the job. */
	readonly partitionCount: number;
}

/** Worker message asking one dedicated worker to process a partition. */
export interface MatcherWorkerRunMessage {
	/** Worker command name. */
	readonly type: 'matcher-worker.run-partition';
	/** Partition to process. */
	readonly task: MatcherPartitionTask;
}


/** Worker response for a completed or failed partition. */
export type MatcherWorkerResponseMessage =
	| { readonly type: 'matcher-worker.partition-complete'; readonly result: MatcherPartitionResult }
	| { readonly type: 'matcher-worker.partition-failed'; readonly jobId: string; readonly partitionId: string; readonly message: string };
