import type { TechnologyDefinition } from '../../types';

export const astroTechnologyDefinition = {
	id: "astro",
	name: "Astro",
	website: "https://astro.build",
	description: "Astro is a web framework for content-driven sites that uses islands architecture and static generation.",
	icon: "Astro.svg",
	categories: [
		"framework",
		"ui-library",
	],
	rules: [
		{
			id: "astro:dom:0",
			kind: "dom",
			selector: "[class^='astro-']",
			description: "DOM selector matches a known technology marker.",
		},
		{
			id: "astro:dom:1",
			kind: "dom",
			selector: "astro-root",
			description: "DOM selector matches a known technology marker.",
		},
		{
			id: "astro:dom:2",
			kind: "dom",
			selector: "link[href*='/_astro/']",
			description: "DOM selector matches a known technology marker.",
		},
		{
			id: "astro:jsGlobal:3",
			kind: "jsGlobal",
			property: "Astro",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "astro:meta:4",
			kind: "meta",
			key: "generator",
			valuePattern: new RegExp("^Astro\\sv([\\d\\.]+)$", "i"),
			version: {
				source: "match",
				group: 1,
			},
			description: "Meta tag matches a known technology marker.",
		},
		{
			id: "astro:dom:5",
			kind: "dom",
			selector: "link[href*='/_astro/'][href$='.css']",
			description: "DOM selector matches a known technology marker.",
		},
		{
			id: "astro:meta:6",
			kind: "meta",
			key: "generator",
			valuePattern: new RegExp("^Astro(?:\\sv([\\d\\.]+))?$", "i"),
			version: {
				source: "match",
				group: 1,
			},
			description: "Meta tag matches a known technology marker.",
		},
		{
			id: "astro:meta:7",
			kind: "meta",
			key: "generator",
			valuePattern: new RegExp("^astro\\sv([\\d\\.]+)$", "i"),
			version: {
				source: "match",
				group: 1,
			},
			description: "Meta tag matches a known technology marker.",
		},
		{
			id: "astro:scriptSrc:8",
			kind: "scriptSrc",
			pattern: new RegExp("\\/_astro\\/.+\\.js"),
			description: "Script source URL matches a known technology marker.",
		},
		{
			id: "astro:dom:9",
			kind: "dom",
			selector: "script[data-sdkn='@vercel/speed-insights/astro']",
			description: "DOM selector matches a known technology marker.",
		},
		{
			id: "astro:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("Astro\\.self"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "astro:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("astro:js"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "astro:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("astro:html"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "astro:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("astro:page"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "astro:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("\\/client\\/.*?astro\\."),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "astro:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("astro:scripts"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "astro:html:modern:6",
			kind: "html",
			pattern: new RegExp("astro-island"),
			confidence: 75,
			description: "Document HTML matches a modern tooling marker.",
		},
		{
			id: "astro:html:modern:7",
			kind: "html",
			pattern: new RegExp("data-astro-cid-"),
			confidence: 75,
			description: "Document HTML matches a modern tooling marker.",
		},
		{
			id: "astro:html:modern:8",
			kind: "html",
			pattern: new RegExp("astro-client-only"),
			confidence: 75,
			description: "Document HTML matches a modern tooling marker.",
		},
		{
			id: "astro:html:modern:9",
			kind: "html",
			pattern: new RegExp("data-astro-transition-"),
			confidence: 75,
			description: "Document HTML matches a modern tooling marker.",
		},
		{
			id: "astro:html:modern:10",
			kind: "html",
			pattern: new RegExp("class=\"astro-."),
			confidence: 75,
			description: "Document HTML matches a modern tooling marker.",
		},
		{
			id: "astro:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("astro:after-hydration"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "astro:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("astro:before-hydration"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "astro:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("props\\.hydrate"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "astro:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("astro:hydration"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "astro:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("data-astro-hydrate"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "astro:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("astro:only"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "astro:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("data-astro-source"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "astro:scriptContent:modern:18",
			kind: "scriptContent",
			pattern: new RegExp("astro-static-slot"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
	metadata: {
		oss: true,
		cpe: "cpe:2.3:a:astro:astro:*:*:*:*:*:node.js:*:*",
	},
} as const satisfies TechnologyDefinition;
