import type { TechnologyDefinition } from '../../types';

export const docusaurusTechnologyDefinition = {
	id: "docusaurus",
	name: "Docusaurus",
	website: "docusaurus.io",
	description: "A modern static site generator that makes it easy to build documentation websites.",
	categories: [
		"framework",
	],
	rules: [
		{
			id: "docusaurus:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("window\\.__docusaurus"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "docusaurus:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("__DOCUSAURUS_CHUNK_LOADING_MANIFEST"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "docusaurus:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("__DOCUSAURUS_ASYNC_LOADER__"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "docusaurus:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("__DOCUSAURUS_SSR__"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "docusaurus:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("window\\.__DOCUSAURUS_CONTEXT__"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "docusaurus:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("div\\[class\\*=\"docusaurus\"\\]"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "docusaurus:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("div\\[class\\*=\"navbar--fixed-top\"\\]"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "docusaurus:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("div\\[class\\*=\"main-wrapper\"\\]"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "docusaurus:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("div\\[class\\*=\"theme-doc-markdown\"\\]"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "docusaurus:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("div\\[class\\*=\"docs-wrapper\"\\]"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "docusaurus:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("class=\"navbar__brand\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "docusaurus:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("class=\"docusaurus-highlight-code-line\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "docusaurus:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("__DOCUSAURUS_INITIAL_STATE__"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "docusaurus:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("__DOCUSAURUS_CLIENT_CONTEXT__"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "docusaurus:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("window\\.__DOCUSAURUS\\.routeDidUpdate"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "docusaurus:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("window\\.__DOCUSAURUS\\.prefetch"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "docusaurus:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("window\\.__DOCUSAURUS_SSR_CONTEXT__"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "docusaurus:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("data-docusaurus-ssr=\"true\""),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
