import type { TechnologyDefinition } from '../../types';

export const gatsbyTechnologyDefinition = {
	id: "gatsby",
	name: "Gatsby",
	website: "https://www.gatsbyjs.org/",
	description: "Gatsby is a React-based open-source framework with performance, scalability and security built-in.",
	icon: "Gatsby.svg",
	categories: [
		"framework",
		"ui-library",
	],
	rules: [
		{
			id: "gatsby:dom:0",
			kind: "dom",
			selector: "div#___gatsby, style#gatsby-inlined-css",
			description: "DOM selector matches a known technology marker.",
		},
		{
			id: "gatsby:meta:1",
			kind: "meta",
			key: "generator",
			valuePattern: new RegExp("^Gatsby(?: ([0-9.]+))?$", "i"),
			version: {
				source: "match",
				group: 1,
			},
			description: "Meta tag matches a known technology marker.",
		},
		{
			id: "gatsby:meta:2",
			kind: "meta",
			key: "generator",
			valuePattern: new RegExp("^gatsby(?: ([0-9.]+))?$", "i"),
			version: {
				source: "match",
				group: 1,
			},
			description: "Meta tag matches a known technology marker.",
		},
		{
			id: "gatsby:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("__GATSBY"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "gatsby:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("__GATSBY_RESOLVED_PAGES"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "gatsby:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("__GATSBY_DEFERRED_CODEGEN"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "gatsby:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("__GATSBY_CHUNK_MAP"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "gatsby:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("window\\.___GATSBY"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "gatsby:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("__GATSBY_REGISTER_COMPONENT"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "gatsby:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("__GATSBY_DYNAMIC_CHUNK_MAP"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "gatsby:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("__GATSBY_ERROR_OVERLAY_HANDLER"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "gatsby:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("___loader"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "gatsby:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("___emitter"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "gatsby:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("window\\.___navigate"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "gatsby:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("window\\.___replacePath"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "gatsby:resourceUrl:modern:12",
			kind: "resourceUrl",
			pattern: new RegExp("gatsby-config\\.[jt]s$"),
			confidence: 55,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "gatsby:resourceUrl:modern:13",
			kind: "resourceUrl",
			pattern: new RegExp("gatsby-node\\.[jt]s$"),
			confidence: 55,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "gatsby:resourceUrl:modern:14",
			kind: "resourceUrl",
			pattern: new RegExp("gatsby-ssr\\.[jt]s$"),
			confidence: 55,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "gatsby:resourceUrl:modern:15",
			kind: "resourceUrl",
			pattern: new RegExp("gatsby-browser\\.[jt]s$"),
			confidence: 55,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
	],
	metadata: {
		cpe: "cpe:2.3:a:gatsbyjs:gatsby:*:*:*:*:*:node.js:*:*",
	},
	implies: [
		"react",
		"webpack",
	],
} as const satisfies TechnologyDefinition;
