import type { TechnologyDefinition } from '../../types';

export const nextJsTechnologyDefinition = {
	id: "next-js",
	name: "Next.js",
	website: "https://nextjs.org/",
	description: "Free and open-source React front-end web development framework that enables functionality such as server-side rendering and generating static websites for React based web applications.",
	categories: [
		"framework",
	],
	rules: [
		{
			id: "next-js:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("window\\.__NEXT_P\\s*="),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "next-js:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("__NEXT_CROSS_ORIGIN"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "next-js:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("data-nextjs-page"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "next-js:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("__NEXT_HYDRATED_STATE__"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "next-js:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("__NEXT_HYDRATE_MARKER__"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "next-js:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("__NEXT_DROP_CLIENT_FILE__"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "next-js:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("getServerSideProps"),
			confidence: 85,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "next-js:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("getInitialProps"),
			confidence: 85,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "next-js:header:modern:8",
			kind: "header",
			key: "server",
			valuePattern: new RegExp("Vercel"),
			confidence: 75,
			description: "HTTP response header matches a modern tooling marker.",
		},
		{
			id: "next-js:header:modern:9",
			kind: "header",
			key: "x-vercel-cache",
			valuePattern: new RegExp("HIT"),
			confidence: 75,
			description: "HTTP response header matches a modern tooling marker.",
		},
		{
			id: "next-js:header:modern:10",
			kind: "header",
			key: "x-vercel-id",
			valuePattern: new RegExp("."),
			confidence: 75,
			description: "HTTP response header matches a modern tooling marker.",
		},
		{
			id: "next-js:header:modern:11",
			kind: "header",
			key: "x-powered-by",
			valuePattern: new RegExp("nextjs"),
			confidence: 75,
			description: "HTTP response header matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
