import type { TechnologyDefinition } from '../../types';

export const remixTechnologyDefinition = {
	id: "remix",
	name: "Remix",
	website: "https://remix.run/",
	description: "Remix is a React framework used for server-side rendering (SSR).",
	icon: "Remix.svg",
	categories: [
		"framework",
		"server-runtime-infra",
	],
	rules: [
		{
			id: "remix:jsGlobal:0",
			kind: "jsGlobal",
			property: "__remixContext",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "remix:jsGlobal:1",
			kind: "jsGlobal",
			property: "__remixRouteModules",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "remix:jsGlobal:2",
			kind: "jsGlobal",
			property: "__remixRouter",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "remix:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("__remixContext"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("__remixManifest"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("__remixRouteModules"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("__remix_entry__"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("isOutsideRemixApp:"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("💿 Hey developer 👋.*remix\\.run\\/guides\\/errors"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("remix\\.run\\/route\\/meta"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("Unknown @remix-run\\/router error"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("[\"']remix-router-transitions[\"']"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("You are trying to use a blocker on a POP navigation.*@remix-run\\/router"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("All route meta functions must return an array of meta objects"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("data-remix-run"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("data-remix-"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("remix-pending"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("remix-state"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("when your app is loading JS modules.*clientLoader.*remix\\.run\\/route\\/hydrate-fallback"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("dangerouslySetInnerHTML:.*💿 Hey developer"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix:header:modern:17",
			kind: "header",
			key: "X-Remix-Reload-Document",
			valuePattern: new RegExp(".+", "i"),
			confidence: 75,
			description: "HTTP response header matches a modern tooling marker.",
		},
		{
			id: "remix:header:modern:18",
			kind: "header",
			key: "X-Remix-Replace",
			valuePattern: new RegExp(".+", "i"),
			confidence: 75,
			description: "HTTP response header matches a modern tooling marker.",
		},
		{
			id: "remix:header:modern:19",
			kind: "header",
			key: "X-Remix-Revalidate",
			valuePattern: new RegExp(".+", "i"),
			confidence: 75,
			description: "HTTP response header matches a modern tooling marker.",
		},
		{
			id: "remix:header:modern:20",
			kind: "header",
			key: "X-Remix-Response",
			valuePattern: new RegExp(".+", "i"),
			confidence: 75,
			description: "HTTP response header matches a modern tooling marker.",
		},
	],
	metadata: {
		oss: true,
	},
	implies: [
		"react",
		"react-router",
	],
} as const satisfies TechnologyDefinition;
