import type { TechnologyDefinition } from '../../types';

export const storybookTechnologyDefinition = {
	id: "storybook",
	name: "Storybook",
	website: "https://storybook.js.org",
	description: "Storybook is a frontend workshop for building UI components and pages in isolation.",
	icon: "storybook.svg",
	categories: [
		"framework",
		"developer-tooling",
		"component-library",
	],
	rules: [
		{
			id: "storybook:jsGlobal:0",
			kind: "jsGlobal",
			property: "__STORYBOOK_ADDONS",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "storybook:jsGlobal:1",
			kind: "jsGlobal",
			property: "STORYBOOK_ADDON_STATE",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "storybook:jsGlobal:2",
			kind: "jsGlobal",
			property: "STORYBOOK_BUILDER",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "storybook:jsGlobal:3",
			kind: "jsGlobal",
			property: "__STORYBOOKADDONS__",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "storybook:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("__STORYBOOK_PREVIEW__"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "storybook:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("data-storybook(-.*)?"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "storybook:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("storybook-wrapper"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "storybook:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("sb-previewBlock"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "storybook:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("__STORYBOOK_STATE__"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "storybook:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("window\\.__STORYBOOK_MANAGER__"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "storybook:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("window\\.__STORYBOOK_COMPOSECONFIGS"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "storybook:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("STORYBOOK_HOOKS_CONTEXT"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "storybook:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("STORYBOOK_ADDON_STATE"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "storybook:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("STORYBOOK_ADDON_ACTIONS"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "storybook:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("STORYBOOK_ADDON_BACKGROUNDS"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "storybook:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("STORYBOOK_ADDON_DOCS"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
	metadata: {
		oss: true,
	},
} as const satisfies TechnologyDefinition;
