import type { TechnologyDefinition } from '../../types';

export const sveltekitTechnologyDefinition = {
	id: "sveltekit",
	name: "SvelteKit",
	website: "https://kit.svelte.dev",
	description: "SvelteKit is the official Svelte framework for building web applications with a flexible filesystem-based routing.",
	icon: "Svelte.svg",
	categories: [
		"framework",
		"component-library",
	],
	rules: [
		{
			id: "sveltekit:dom:0",
			kind: "dom",
			selector: "#svelte-announcer",
			description: "DOM selector matches a known technology marker.",
		},
		{
			id: "sveltekit:html:1",
			kind: "html",
			pattern: new RegExp("\\b__sveltekit[_\\w]*\\b"),
			confidence: 90,
			description: "Document HTML contains a SvelteKit runtime marker.",
		},
		{
			id: "sveltekit:html:2",
			kind: "html",
			pattern: new RegExp("\\bdata-sveltekit-(?:preload|reload|noscroll|keepfocus)[-=]", "i"),
			confidence: 85,
			description: "Document HTML contains SvelteKit navigation attributes.",
		},
		{
			id: "sveltekit:meta:3",
			kind: "meta",
			key: "generator",
			valuePattern: new RegExp("SvelteKit", "i"),
			description: "Meta tag matches a known technology marker.",
		},
		{
			id: "sveltekit:meta:4",
			kind: "meta",
			key: "generator",
			valuePattern: new RegExp("sveltekit", "i"),
			description: "Meta tag matches a known technology marker.",
		},
		{
			id: "sveltekit:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("__sveltekit"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "sveltekit:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("\\$app\\/navigation"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "sveltekit:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("\\$app\\/stores"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "sveltekit:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("\\$app\\/forms"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "sveltekit:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("\\$app\\/environment"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "sveltekit:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("data-sveltekit-"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "sveltekit:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("data-sveltekit-prefetch"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "sveltekit:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("data-sveltekit-hydrate"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "sveltekit:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("data-sveltekit-enhanced"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "sveltekit:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("__sveltekit_hydrate"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "sveltekit:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("__sveltekit_data"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "sveltekit:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("sveltekit\\.start"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "sveltekit:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("__sveltekit_ssr"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
	metadata: {
		oss: true,
		cpe: "cpe:2.3:a:svelte:sveltekit:*:*:*:*:*:*:*:*",
	},
	implies: [
		"node-js",
		"svelte",
		"vite",
	],
} as const satisfies TechnologyDefinition;
