import type { TechnologyDefinition } from '../../types';

export const vitepressTechnologyDefinition = {
	id: "vitepress",
	name: "VitePress",
	website: "https://vitepress.vuejs.org/",
	description: "VitePress is a Vite & Vue Powered Static Site Generator.",
	icon: "vite.svg",
	categories: [
		"framework",
	],
	rules: [
		{
			id: "vitepress:jsGlobal:0",
			kind: "jsGlobal",
			property: "__VP_HASH_MAP__",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "vitepress:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("__VITEPRESS_"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vitepress:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("window\\.__VP_"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vitepress:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("__VP_HASH_MAP"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vitepress:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("__VP_SITE_DATA"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vitepress:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("__VP_SITE_DATA__"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vitepress:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("window\\.__VITEPRESS_DEV__"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vitepress:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("window\\.__VITEPRESS_SSR__"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vitepress:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("div\\[class\\*=\"VPDoc\"\\]"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vitepress:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("div\\[class\\*=\"VPNav\"\\]"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vitepress:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("div\\[class\\*=\"VPSidebar\"\\]"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vitepress:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("div\\[class\\*=\"VPContent\"\\]"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vitepress:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("div\\[class\\*=\"VPFooter\"\\]"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vitepress:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("class=\"vp-doc\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vitepress:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("class=\"VPHomeHero\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vitepress:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("__VITEPRESS_DATA__"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vitepress:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("window\\.__VITEPRESS_INITIAL_STATE__"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vitepress:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("__VP_STATIC_DATA__"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vitepress:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("__vitepress_runtime_data__"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
	metadata: {
		oss: true,
	},
	implies: [
		"vite",
		"vue-js",
	],
} as const satisfies TechnologyDefinition;
