import type { TechnologyDefinition } from '../../types';

export const antDesignTechnologyDefinition = {
	id: "ant-design",
	name: "Ant Design",
	website: "https://ant.design/",
	description: "An enterprise-class UI design language and React UI library",
	categories: [
		"component-library",
		"styling-library",
	],
	rules: [
		{
			id: "ant-design:stylesheetContent:modern:0",
			kind: "stylesheetContent",
			pattern: new RegExp("antd"),
			confidence: 75,
			description: "Stylesheet content matches a modern styling marker.",
		},
		{
			id: "ant-design:resourceUrl:modern:1",
			kind: "resourceUrl",
			pattern: new RegExp("antd[.\\-@/]"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "ant-design:resourceUrl:modern:2",
			kind: "resourceUrl",
			pattern: new RegExp("ant-design[.\\-@/]"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "ant-design:html:modern:3",
			kind: "html",
			pattern: new RegExp("class=\"[^\"]*ant-btn"),
			confidence: 65,
			description: "Document HTML matches a modern tooling marker.",
		},
		{
			id: "ant-design:html:modern:4",
			kind: "html",
			pattern: new RegExp("class=\"[^\"]*ant-layout"),
			confidence: 65,
			description: "Document HTML matches a modern tooling marker.",
		},
		{
			id: "ant-design:html:modern:5",
			kind: "html",
			pattern: new RegExp("class=\"[^\"]*ant-table"),
			confidence: 65,
			description: "Document HTML matches a modern tooling marker.",
		},
		{
			id: "ant-design:html:modern:6",
			kind: "html",
			pattern: new RegExp("class=\"[^\"]*ant-modal"),
			confidence: 65,
			description: "Document HTML matches a modern tooling marker.",
		},
		{
			id: "ant-design:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("\"ant-design-icons\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ant-design:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("\\[Ant Design CSS-in-JS\\] Theme should have at least one derivative function"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ant-design:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("[\"']data-ant-cssinjs-cache-path[\"']"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ant-design:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("@ant-design\\/fast-color: unsupported input"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ant-design:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("@ant-design-icons"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ant-design:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("[\"']anticon[\"']"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ant-design:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("\\.displayName\\s*=\\s*[\"']AntdIcon[\"']"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ant-design:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("name:\\s*[\"']antd[\"']"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ant-design:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("antCls:\\s*[\"']\\.[\"']\\.concat\\("),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ant-design:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("[\"']data-rc-order[\"']:\\s*[\"']prependQueue[\"']"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ant-design:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("icon should be icon definiton, but got"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ant-design:scriptContent:modern:18",
			kind: "scriptContent",
			pattern: new RegExp("ant-message-(?:notice|loading|success|error|warning|info)(?:-content)?"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ant-design:scriptContent:modern:19",
			kind: "scriptContent",
			pattern: new RegExp("ant-notification-(?:notice|info|success|error|warning|close|btn)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ant-design:scriptContent:modern:20",
			kind: "scriptContent",
			pattern: new RegExp("ant-modal-(?:confirm|confirm-body|confirm-btns|confirm-title|wrap)\\b"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ant-design:scriptContent:modern:21",
			kind: "scriptContent",
			pattern: new RegExp("ant-drawer-(?:wrapper-body|header-title|content-wrapper|mask)\\b"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ant-design:scriptContent:modern:22",
			kind: "scriptContent",
			pattern: new RegExp("ant-form-item-(?:control-input|explain-(?:connected|error)|required-mark|margin|with-help|feedback-icon|extra)\\b"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ant-design:scriptContent:modern:23",
			kind: "scriptContent",
			pattern: new RegExp("ant-select-(?:selection-(?:overflow|placeholder|search)|dropdown)\\b"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ant-design:scriptContent:modern:24",
			kind: "scriptContent",
			pattern: new RegExp("ant-dropdown-menu-(?:submenu-(?:title|expand-icon)|title-content)\\b"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ant-design:scriptContent:modern:25",
			kind: "scriptContent",
			pattern: new RegExp("ant-picker-(?:super-(?:prev|next)-icon|header-super-prev-btn|datetime-panel)\\b"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ant-design:scriptContent:modern:26",
			kind: "scriptContent",
			pattern: new RegExp("ant-calendar-picker-(?:clear|separator|input|icon|container)\\b"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ant-design:scriptContent:modern:27",
			kind: "scriptContent",
			pattern: new RegExp("ant-table-(?:filter-trigger-container|column-sorter-(?:up|down)|selection-extra|fixed-(?:right|left)|placeholder|measure-row)\\b"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ant-design:scriptContent:modern:28",
			kind: "scriptContent",
			pattern: new RegExp("anticon-(?:spin-dot-spin|loading-3-quarters|step-(?:forward|backward))\\b"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ant-design:scriptContent:modern:29",
			kind: "scriptContent",
			pattern: new RegExp("antd\\/(?:es|lib)\\/locale\\/[a-z]{2}_[A-Z]{2}\\b"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ant-design:scriptContent:modern:30",
			kind: "scriptContent",
			pattern: new RegExp("ConfigProvider\\.config\\(\\{\\s*theme:\\s*\\{[^}]{0,500}token:"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ant-design:scriptContent:modern:31",
			kind: "scriptContent",
			pattern: new RegExp("data-row-key=\"ant-table-row-[0-9]{1,10}\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ant-design:scriptContent:modern:32",
			kind: "scriptContent",
			pattern: new RegExp("data-node-key=\"ant-tree-treenode-[0-9]{1,10}\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ant-design:scriptContent:modern:33",
			kind: "scriptContent",
			pattern: new RegExp("import\\s+(?:\\{[^}]*\\}|[^{}\\s]+)\\s+from\\s+['\"]antd(?:\\/[^'\"]*)?['\"]"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ant-design:stylesheetContent:modern:34",
			kind: "stylesheetContent",
			pattern: new RegExp("--ant-primary-color:\\s*[^;]*"),
			confidence: 65,
			description: "Stylesheet content matches a modern styling marker.",
		},
		{
			id: "ant-design:stylesheetContent:modern:35",
			kind: "stylesheetContent",
			pattern: new RegExp("--ant-font-size-base:\\s*[^;]*"),
			confidence: 65,
			description: "Stylesheet content matches a modern styling marker.",
		},
		{
			id: "ant-design:resourceUrl:modern:36",
			kind: "resourceUrl",
			pattern: new RegExp("antd\\/(?:es|lib)\\/[^/]{1,50}\\/style\\/index\\.[jt]s$"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "ant-design:resourceUrl:modern:37",
			kind: "resourceUrl",
			pattern: new RegExp("antd\\/dist\\/(?:antd|reset)\\.(?:css|less)$"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "ant-design:resourceUrl:modern:38",
			kind: "resourceUrl",
			pattern: new RegExp("antd\\/(?:es|lib)\\/(?:message|notification|modal|table|form|select)\\/[^/]{1,50}\\.js$"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "ant-design:resourceUrl:modern:39",
			kind: "resourceUrl",
			pattern: new RegExp("antd\\/(?:es|lib)\\/locale\\/[a-z]{2}_[A-Z]{2}\\.js$"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "ant-design:resourceUrl:modern:40",
			kind: "resourceUrl",
			pattern: new RegExp("antd\\/(?:es|lib)\\/style\\/themes\\/(?:default|dark|compact)\\.less$"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "ant-design:resourceUrl:modern:41",
			kind: "resourceUrl",
			pattern: new RegExp("@ant-design\\/icons\\/lib\\/icons\\/[A-Z][^/]{1,50}\\.js$"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "ant-design:resourceUrl:modern:42",
			kind: "resourceUrl",
			pattern: new RegExp("@ant-design\\/icons-svg\\/inline-namespaced\\/$"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
