import type { TechnologyDefinition } from '../../types';

export const radixUiTechnologyDefinition = {
	id: "radix-ui",
	name: "Radix UI",
	website: "https://www.radix-ui.com/",
	description: "Unstyled, accessible components for building high‑quality design systems",
	categories: [
		"component-library",
		"styling-library",
	],
	rules: [
		{
			id: "radix-ui:resourceUrl:modern:0",
			kind: "resourceUrl",
			pattern: new RegExp("@radix-ui\\/"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "radix-ui:resourceUrl:modern:1",
			kind: "resourceUrl",
			pattern: new RegExp("radix-ui"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "radix-ui:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("\"DialogContent\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "radix-ui:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("\"DialogTrigger\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "radix-ui:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("\"DialogOverlay\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "radix-ui:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("\"PopoverContent\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "radix-ui:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("\"PopoverTrigger\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "radix-ui:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("\"DropdownMenuContent\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "radix-ui:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("\"DropdownMenuTrigger\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "radix-ui:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("\"SelectContent\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "radix-ui:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("\"SelectTrigger\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "radix-ui:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("\"TooltipContent\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "radix-ui:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("\"TooltipTrigger\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "radix-ui:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("--radix-popover-"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "radix-ui:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("--radix-dropdown-"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "radix-ui:stylesheetContent:modern:15",
			kind: "stylesheetContent",
			pattern: new RegExp("--radix-popover-"),
			confidence: 65,
			description: "Stylesheet content matches a modern styling marker.",
		},
		{
			id: "radix-ui:stylesheetContent:modern:16",
			kind: "stylesheetContent",
			pattern: new RegExp("--radix-dropdown-"),
			confidence: 65,
			description: "Stylesheet content matches a modern styling marker.",
		},
		{
			id: "radix-ui:stylesheetContent:modern:17",
			kind: "stylesheetContent",
			pattern: new RegExp("--radix-tooltip-"),
			confidence: 65,
			description: "Stylesheet content matches a modern styling marker.",
		},
		{
			id: "radix-ui:scriptContent:modern:18",
			kind: "scriptContent",
			pattern: new RegExp("\\[data-radix-[^\\]]*\\]"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "radix-ui:scriptContent:modern:19",
			kind: "scriptContent",
			pattern: new RegExp("(?:\"var\\(--radix-[^)]*\\)\"|'var\\(--radix-[^)]*\\)'|var\\(--radix-[^)]*\\))"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "radix-ui:scriptContent:modern:20",
			kind: "scriptContent",
			pattern: new RegExp("setAttribute\\([\"']data-radix-focus-guard[\"'],\\s*[\"'][^\"']*[\"']\\)"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "radix-ui:scriptContent:modern:21",
			kind: "scriptContent",
			pattern: new RegExp("[\"']@radix-ui\\/(?:react|vue|svelte)-[a-z0-9-]+[\"']"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "radix-ui:stylesheetContent:modern:22",
			kind: "stylesheetContent",
			pattern: new RegExp("--radix-(?:accordion|alert-dialog|avatar|checkbox|collapsible|context-menu|dialog|dropdown-menu|hover-card|menu|navigation-menu|popover|radio-group|scroll-area|select|slider|tabs|toast|toggle-group|tooltip)-[a-z0-9-]+"),
			confidence: 75,
			description: "Stylesheet content matches a modern styling marker.",
		},
		{
			id: "radix-ui:stylesheetContent:modern:23",
			kind: "stylesheetContent",
			pattern: new RegExp("\\[data-radix-(?:accordion|alert-dialog|avatar|checkbox|collapsible|context-menu|dialog|dropdown-menu|hover-card|menu|navigation-menu|popover|radio-group|scroll-area|select|slider|tabs|toast|toggle-group|tooltip)(?:-[a-z0-9-]+)?\\]"),
			confidence: 75,
			description: "Stylesheet content matches a modern styling marker.",
		},
		{
			id: "radix-ui:scriptContent:modern:24",
			kind: "scriptContent",
			pattern: new RegExp("you can wrap it with our VisuallyHidden component\\.\\n\\nFor more information, see https:\\/\\/radix-ui\\.com\\/primitives\\/docs\\/components\\/"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
