import type { TechnologyDefinition } from '../../types';

export const dateFnsTechnologyDefinition = {
	id: "date-fns",
	name: "date-fns",
	website: "https://date-fns.org/",
	description: "Modern JavaScript date utility library",
	categories: [
		"dates",
	],
	rules: [
		{
			id: "date-fns:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("\"weekStartsOn must be between 0 and 6 inclusively\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "date-fns:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("firstWeekContainsDate must be between 1 and 7 inclusively"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "date-fns:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("\"startDate or endDate for interval cannot be Invalid Date\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "date-fns:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("\"The step must be a number between 0 and 7 inclusively\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "date-fns:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("\"useAdditionalDayPeriodTokens must be used with isProtectedDayPeriodToken\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "date-fns:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("firstWeekContainsDate"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "date-fns:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("[\"']abbreviated[\"'].*[\"']narrow[\"'].*[\"']short[\"'].*[\"']wide[\"']"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "date-fns:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("eachWeekendOfInterval\\([^)]+\\)|eachWeekendOfMonth\\([^)]+\\)|eachWeekendOfYear\\([^)]+\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "date-fns:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("differenceInBusinessDays\\([^)]+\\)|addBusinessDays\\([^)]+\\)|subBusinessDays\\([^)]+\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "date-fns:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("differenceInCalendarISOWeeks\\([^)]+\\)|startOfISOWeek\\([^)]+\\)|lastDayOfISOWeek\\([^)]+\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "date-fns:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("getQuarter\\([^)]+\\)|setQuarter\\([^)]+\\)|startOfQuarter\\([^)]+\\)|lastDayOfQuarter\\([^)]+\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "date-fns:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("getISOWeekYear\\([^)]+\\)|startOfISOWeekYear\\([^)]+\\)|endOfISOWeekYear\\([^)]+\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "date-fns:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("format\\([^,]+,\\s*[\"']PPPPp[\"']\\)"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "date-fns:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("format\\([^,]+,\\s*[\"']RRRR[\"']\\)"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "date-fns:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("formatISO9075\\([^)]+\\)"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "date-fns:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("format\\([^,]+,\\s*[\"'][^\"']+[\"'],\\s*\\{locale:\\s*[^}]+\\}\\)"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "date-fns:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("\"Wrong first weekday of week\""),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "date-fns:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("\"ordinalNumber function is required\""),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "date-fns:scriptContent:modern:18",
			kind: "scriptContent",
			pattern: new RegExp("\"localizer function is required\""),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "date-fns:scriptContent:modern:19",
			kind: "scriptContent",
			pattern: new RegExp("eachDayOfInterval\\([^)]+\\)|eachHourOfInterval\\([^)]+\\)|eachMinuteOfInterval\\([^)]+\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "date-fns:scriptContent:modern:20",
			kind: "scriptContent",
			pattern: new RegExp("isWithinInterval\\([^,]+,\\s*\\{start:[^,]+,\\s*end:[^}]+\\}\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "date-fns:scriptContent:modern:21",
			kind: "scriptContent",
			pattern: new RegExp("areIntervalsOverlapping\\([^,]+,\\s*[^,]+(?:,\\s*\\{inclusive:\\s*(?:true|false)\\}\\s*)?\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "date-fns:scriptContent:modern:22",
			kind: "scriptContent",
			pattern: new RegExp("import\\s*\\{[^}]*\\}\\s*from\\s*[\"']date-fns\\/fp[\"']"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "date-fns:scriptContent:modern:23",
			kind: "scriptContent",
			pattern: new RegExp("pipe\\(\\s*(?:addDays|addMonths|addYears)\\s*\\(\\d+\\)\\s*,\\s*(?:format|formatDistance|formatRelative)"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
