import type { TechnologyDefinition } from '../../types';

export const jsJodaTechnologyDefinition = {
	id: "js-joda",
	name: "JS-Joda",
	website: "https://js-joda.github.io/js-joda/",
	description: "Immutable date and time library for JavaScript",
	categories: [
		"dates",
	],
	rules: [
		{
			id: "js-joda:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("\"DateTimeException: TemporalField must not be null\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "js-joda:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("\"DateTimeException: ChronoField must not be null\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "js-joda:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("\"DateTimeException: ChronoUnit must not be null\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "js-joda:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("\"DateTimeException: Invalid value for YearOfEra\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "js-joda:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("\"DateTimeException: Invalid value for MonthOfYear\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "js-joda:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("\"UnsupportedTemporalTypeException: Unsupported field: FieldUnsupported\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "js-joda:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("@copyright.*js-joda.*contributors"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "js-joda:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("DateTimeFormatter.*ISO_LOCAL_DATE.*ISO_LOCAL_TIME"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "js-joda:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("MIN_SAFE_INTEGER.*MAX_SAFE_INTEGER.*safeToInt"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "js-joda:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("Pattern using \\(localized\\) text not implemented, use @js-joda\\/locale plugin!"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "js-joda:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("time must be an instance of LocalTime or OffsetTime"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "js-joda:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("Pattern using (localized) text not implemented yet"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "js-joda:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("t === v\\.MONTHS \\|\\| t === v\\.YEARS \\|\\| t === v\\.DECADES \\|\\| t === v\\.CENTURIES \\|\\| t === v\\.MILLENNIA \\|\\| t === v\\.ERAS "),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "js-joda:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("ChronoField\\.ALIGNED_WEEK_OF_MONTH|ChronoField\\.ALIGNED_DAY_OF_WEEK_IN_MONTH"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "js-joda:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("ChronoUnit\\.HALF_DAYS|ChronoUnit\\.FOREVER"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "js-joda:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("IsoChronology\\.INSTANCE"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "js-joda:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("Period\\.parse\\(\"P\\d+Y\\d+M\\d+D\"\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "js-joda:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("ZoneRegion\\.of\\(\"[^\"]+\"\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "js-joda:scriptContent:modern:18",
			kind: "scriptContent",
			pattern: new RegExp("Clock\\.system\\(ZoneId\\.of\\([^)]+\\)\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "js-joda:scriptContent:modern:19",
			kind: "scriptContent",
			pattern: new RegExp("ALIGNED_DAY_OF_WEEK_IN_MONTH"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "js-joda:scriptContent:modern:20",
			kind: "scriptContent",
			pattern: new RegExp("ALIGNED_DAY_OF_WEEK_IN_YEAR"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
