import type { TechnologyDefinition } from '../../types';

export const luxonTechnologyDefinition = {
	id: "luxon",
	name: "Luxon",
	website: "https://moment.github.io/luxon/",
	description: "Modern JavaScript date utility library",
	categories: [
		"dates",
	],
	rules: [
		{
			id: "luxon:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("\"Zone required with IANA name\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "luxon:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("\"Unique zone required\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "luxon:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("\"Can't subtract an invalid DateTime\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "luxon:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("\"Missing locale data for \""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "luxon:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("\"Could not create DateTime from invalid JSON\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "luxon:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("\"Numbers in toRelative\\(\\) are required to be Integers\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "luxon:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("isLuxonDateTime:\\s*true"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "luxon:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("\"Zone is an abstract class\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "luxon:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("formatToParts\\([^)]*\\).*?timeZoneName.*?offsetName"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "luxon:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("type\\s*===\\s*\"timeZoneName\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "luxon:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("LuxonError\\s*=.*?function.*?_Error\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "luxon:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("inheritsLoose\\([^,]+,\\s*_Error\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "luxon:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("Info\\.features\\(\\)\\.zones"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "luxon:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("Info\\.features\\(\\)\\.intl"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "luxon:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("Info\\.features\\(\\)\\.relative"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "luxon:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("Info\\.meridiems\\("),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "luxon:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("\\{numberingSystem:\\s*[\"'][^\"']+[\"'],\\s*outputCalendar:\\s*[\"'][^\"']+[\"']\\}"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "luxon:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("\\{conversionAccuracy:\\s*[\"']casual[\"']\\}"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "luxon:scriptContent:modern:18",
			kind: "scriptContent",
			pattern: new RegExp("Settings\\.throwOnInvalid\\s*=\\s*true"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "luxon:scriptContent:modern:19",
			kind: "scriptContent",
			pattern: new RegExp("Settings\\.defaultZone\\s*="),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
