import type { TechnologyDefinition } from '../../types';

export const momentJsTechnologyDefinition = {
	id: "moment-js",
	name: "Moment.js",
	website: "https://momentjs.com",
	description: "Moment.js is a free and open-source JavaScript library that removes the need to use the native JavaScript Date object directly.",
	icon: "Moment.js.svg",
	categories: [
		"dates",
		"widgets-misc",
	],
	rules: [
		{
			id: "moment-js:scriptSrc:0",
			kind: "scriptSrc",
			pattern: new RegExp("moment(?:\\.min)?\\.js"),
			description: "Script source URL matches a known technology marker.",
		},
		{
			id: "moment-js:jsGlobal:1",
			kind: "jsGlobal",
			property: "moment",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "moment-js:jsGlobal:2",
			kind: "jsGlobal",
			property: "moment.version",
			valuePattern: new RegExp("^(.+)$"),
			version: {
				source: "match",
				group: 1,
			},
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "moment-js:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("\\._isAMomentObject\\s*=\\s*source\\._isAMomentObject"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "moment-js:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("\\._isAMomentObject\\s*=\\s*true"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "moment-js:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("moment\\.updateOffset\\s*=\\s*function"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "moment-js:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("\\._pf\\.(?:empty|unusedTokens|unusedInput|overflow|charsLeftOver|nullInput|invalidEra|invalidMonth|invalidFormat|userInvalidated|iso|parsedDateParts|meridiem)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "moment-js:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("use moment\\.updateLocale\\(localeName, config\\) to change an existing locale\\. moment\\.defineLocale\\(localeName, config\\) should only be used for creating a new locale"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "moment-js:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("moment\\(\\)\\.lang\\(\\) is deprecated\\. Instead, use moment\\(\\)\\.localeData\\(\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "moment-js:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("moment construction falls back to js Date\\(\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "moment-js:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("\"Moment Timezone setDefault\\(\\) requires Moment\\.js >= [0-9.]+"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "moment-js:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("'Moment Timezone requires Moment\\.js\\. See https:\\/\\/momentjs\\.com\\/timezone\\/docs\\/#\\/use-it\\/browser\\/'"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "moment-js:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("http:\\/\\/momentjs\\.com\\/guides\\/#\\/warnings\\/js-date\\/"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "moment-js:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("http:\\/\\/momentjs\\.com\\/guides\\/#\\/warnings\\/define-locale\\/"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "moment-js:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("http:\\/\\/momentjs\\.com\\/guides\\/#\\/warnings\\/min-max\\/"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "moment-js:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("DATETIME_LOCAL:\"YYYY-MM-DDTHH:mm\",DATETIME_LOCAL_SECONDS:\"YYYY-MM-DDTHH:mm:ss\",DATETIME_LOCAL_MS:\"YYYY-MM-DDTHH:mm:ss\\.SSS\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "moment-js:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("\\._invalidDate\\s*=\\s*['\"]Invalid date['\"]"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "moment-js:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("\\._week\\s*=\\s*{\\s*dow:\\s*\\d+,\\s*doy:\\s*\\d+\\s*}"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "moment-js:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("\\._locale\\._(?:abbr|config|ordinal|calendar|monthsParseExact)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "moment-js:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("\\._isUTC\\s*=\\s*(?:true|false)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "moment-js:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("\\._offset\\s*=\\s*(?:0|-?\\d+)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
	metadata: {
		cpe: "cpe:2.3:a:momentjs:moment:*:*:*:*:*:*:*:*",
	},
} as const satisfies TechnologyDefinition;
