import type { TechnologyDefinition } from '../../types';

export const amdTechnologyDefinition = {
	id: "amd",
	name: "AMD",
	website: "https://en.wikipedia.org/wiki/Asynchronous_module_definition",
	description: "Asynchronous Module Definition (AMD) is a JavaScript API for defining modules such that the module and its dependencies can be asynchronously loaded.",
	categories: [
		"module-format",
	],
	rules: [
		{
			id: "amd:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("define\\s*\\(\\s*[\"'][^\"']+[\"']\\s*,\\s*\\["),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "amd:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("define\\s*\\(\\s*\\[[^\\]]*\\]\\s*,\\s*function"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "amd:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("define\\s*\\(\\s*function\\s*\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "amd:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("define\\s*\\(\\s*\\[\\s*[\"']require[\"']\\s*,\\s*[\"']exports[\"']\\s*,\\s*[\"']module[\"']\\s*\\]"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "amd:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("define\\s*\\(\\s*\\[\\s*[\"']exports[\"']\\s*\\]"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "amd:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("define\\([\"'][^\"']+[\"'],\\["),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "amd:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("define\\(\\[[^\\]]*\\],function"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "amd:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("define\\(function\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "amd:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("return\\s*\\{\\s*[^}]*\\}"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "amd:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("return\\s*\\(\\s*\\{\\s*[^}]*\\}\\s*\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "amd:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("exports\\.\\w+\\s*="),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "amd:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("exports\\[[\"']\\w+[\"']\\]\\s*="),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "amd:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("return\\s+function\\s*\\w*\\s*\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "amd:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("return\\s+class\\s*\\w*\\s*\\{"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "amd:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("module\\.exports\\s*="),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "amd:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("exports\\s*=\\s*[^;]+"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "amd:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("return{"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "amd:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("exports\\.\\w+="),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "amd:scriptContent:modern:18",
			kind: "scriptContent",
			pattern: new RegExp("return function\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "amd:scriptContent:modern:19",
			kind: "scriptContent",
			pattern: new RegExp("return class\\{"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "amd:scriptContent:modern:20",
			kind: "scriptContent",
			pattern: new RegExp("Object\\.defineProperty\\s*\\(\\s*exports\\s*,"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "amd:scriptContent:modern:21",
			kind: "scriptContent",
			pattern: new RegExp("Object\\.defineProperties\\s*\\(\\s*exports\\s*,"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "amd:scriptContent:modern:22",
			kind: "scriptContent",
			pattern: new RegExp("factory\\s*\\(\\s*(?:require\\s*,\\s*)?exports\\s*,\\s*module\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "amd:scriptContent:modern:23",
			kind: "scriptContent",
			pattern: new RegExp("factory\\.call\\s*\\(\\s*this\\s*,\\s*(?:require\\s*,\\s*)?exports\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "amd:scriptContent:modern:24",
			kind: "scriptContent",
			pattern: new RegExp("typeof\\s+exports\\s*===?\\s*[\"']object[\"']"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "amd:scriptContent:modern:25",
			kind: "scriptContent",
			pattern: new RegExp("typeof\\s+define\\s*===?\\s*[\"']function[\"']"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "amd:scriptContent:modern:26",
			kind: "scriptContent",
			pattern: new RegExp("\\w+\\.define\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "amd:scriptContent:modern:27",
			kind: "scriptContent",
			pattern: new RegExp("\\w+\\.exports\\."),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
