import type { TechnologyDefinition } from '../../types';

export const commonjsTechnologyDefinition = {
	id: "commonjs",
	name: "CommonJS",
	website: "https://en.wikipedia.org/wiki/CommonJS#:~:text=CommonJS%20is%20a%20project%20to,js.",
	description: "Project to standardize the module ecosystem for JavaScript outside of web browsers.",
	categories: [
		"module-format",
	],
	rules: [
		{
			id: "commonjs:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("require\\s*\\(\\s*[\"'][^\"']+[\"']\\s*\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "commonjs:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("require\\s*\\(\\s*`[^`]+`\\s*\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "commonjs:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("(?:const|let|var)\\s*\\{[^}]+\\}\\s*=\\s*require\\s*\\([^)]+\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "commonjs:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("(?:const|let|var)\\s+\\w+\\s*=\\s*require\\s*\\([^)]+\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "commonjs:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("=require\\([\"'][^\"']+[\"']\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "commonjs:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("=require\\([^)]+\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "commonjs:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("require\\([\"'][^\"']+[\"']\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "commonjs:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("require\\s*\\(\\s*\\w+\\s*\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "commonjs:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("require\\s*\\(\\s*\\w+\\s*\\+\\s*[\"'][^\"']*[\"']\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "commonjs:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("require\\s*\\(\\s*`[^`]*\\$\\{[^}]+\\}[^`]*`\\s*\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "commonjs:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("require\\.resolve\\s*\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "commonjs:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("require\\.cache\\b"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "commonjs:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("require\\.main\\b"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "commonjs:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("module\\.exports\\s*=\\s*[^;]+"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "commonjs:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("module\\s*\\[\\s*[\"']exports[\"']\\s*\\]\\s*="),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "commonjs:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("module\\.exports\\s*=\\s*\\{"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "commonjs:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("exports\\.\\w+\\s*="),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "commonjs:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("exports\\[[\"']\\w+[\"']\\]\\s*="),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "commonjs:scriptContent:modern:18",
			kind: "scriptContent",
			pattern: new RegExp("Object\\.defineProperty\\s*\\(\\s*exports\\s*,\\s*[\"']\\w+[\"']\\s*,"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "commonjs:scriptContent:modern:19",
			kind: "scriptContent",
			pattern: new RegExp("Object\\.defineProperties\\s*\\(\\s*exports\\s*,"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "commonjs:scriptContent:modern:20",
			kind: "scriptContent",
			pattern: new RegExp("exports\\s*=\\s*module\\.exports\\s*="),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "commonjs:scriptContent:modern:21",
			kind: "scriptContent",
			pattern: new RegExp("module\\.exports\\s*=\\s*exports\\s*="),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "commonjs:scriptContent:modern:22",
			kind: "scriptContent",
			pattern: new RegExp("exports\\.\\w+="),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "commonjs:scriptContent:modern:23",
			kind: "scriptContent",
			pattern: new RegExp("exports=module\\.exports="),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "commonjs:scriptContent:modern:24",
			kind: "scriptContent",
			pattern: new RegExp("module\\.exports=\\{"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "commonjs:scriptContent:modern:25",
			kind: "scriptContent",
			pattern: new RegExp("exports\\s*\\[\\s*[\"']default[\"']\\s*\\]\\s*="),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "commonjs:scriptContent:modern:26",
			kind: "scriptContent",
			pattern: new RegExp("module\\.exports\\s*\\[\\s*[\"']default[\"']\\s*\\]\\s*="),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
