import type { TechnologyDefinition } from '../../types';

export const esModulesTechnologyDefinition = {
	id: "es-modules",
	name: "ES Modules",
	website: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules",
	description: "A way to structure your JavaScript code in separate files that can be imported where needed.",
	categories: [
		"module-format",
	],
	rules: [
		{
			id: "es-modules:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("import\\s+\\{[^}]+\\}\\s*from"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "es-modules:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("import\\s+\\w+\\s*,\\s*\\{[^}]+\\}\\s*from"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "es-modules:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("import\\s+\\*\\s+as\\s+\\w+\\s+from"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "es-modules:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("import\\s+\\w+\\s+from"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "es-modules:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("import\\s+[\"'][^\"']+[\"']"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "es-modules:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("import{[^}]+}from"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "es-modules:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("import\\{"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "es-modules:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("import\\*"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "es-modules:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("from[\"'][^\"']+[\"']"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "es-modules:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("import\\s*\\([^)]+\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "es-modules:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("import\\s*\\([\"'][^\"']+[\"']\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "es-modules:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("\\(\\s*\\)\\s*=>\\s*import\\s*\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "es-modules:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("await\\s+import\\s*\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "es-modules:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("Promise\\s*\\.\\s*all\\s*\\(\\s*\\[?\\s*import\\s*\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "es-modules:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("import\\([\"'][^\"']+[\"']\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "es-modules:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("\\(\\)?=>import\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "es-modules:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("await import\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "es-modules:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("export\\s+(?:const|let|var|class|function|interface|type)\\s+\\w+"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "es-modules:scriptContent:modern:18",
			kind: "scriptContent",
			pattern: new RegExp("export\\s+\\{[^}]+\\}"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "es-modules:scriptContent:modern:19",
			kind: "scriptContent",
			pattern: new RegExp("export\\s+\\{[^}]+\\}\\s+from"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "es-modules:scriptContent:modern:20",
			kind: "scriptContent",
			pattern: new RegExp("export\\s+default\\s+"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "es-modules:scriptContent:modern:21",
			kind: "scriptContent",
			pattern: new RegExp("export\\s+default\\s+function\\s*\\w*\\s*\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "es-modules:scriptContent:modern:22",
			kind: "scriptContent",
			pattern: new RegExp("export\\s+default\\s+class\\s*\\w*\\s*\\{"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "es-modules:scriptContent:modern:23",
			kind: "scriptContent",
			pattern: new RegExp("export\\s+\\*\\s+from"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "es-modules:scriptContent:modern:24",
			kind: "scriptContent",
			pattern: new RegExp("export\\s+\\*\\s+as\\s+\\w+\\s+from"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "es-modules:scriptContent:modern:25",
			kind: "scriptContent",
			pattern: new RegExp("export{[^}]+}"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "es-modules:scriptContent:modern:26",
			kind: "scriptContent",
			pattern: new RegExp("export{[^}]+}from"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "es-modules:scriptContent:modern:27",
			kind: "scriptContent",
			pattern: new RegExp("export default"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "es-modules:scriptContent:modern:28",
			kind: "scriptContent",
			pattern: new RegExp("export\\*"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "es-modules:scriptContent:modern:29",
			kind: "scriptContent",
			pattern: new RegExp("Object\\.defineProperty\\s*\\(\\s*exports\\s*,\\s*['\"]__esModule['\"]\\s*,\\s*\\{\\s*value:\\s*true\\s*\\}\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
