import type { TechnologyDefinition } from '../../types';

export const umdTechnologyDefinition = {
	id: "umd",
	name: "UMD",
	website: "https://github.com/umdjs/umd",
	description: "Universal Module Definition (UMD) is a way to define modules that work in both CommonJS and AMD environments.",
	categories: [
		"module-format",
	],
	rules: [
		{
			id: "umd:scriptContent:wrapper:0",
			kind: "scriptContent",
			pattern: new RegExp("(?:typeof\\s+exports|typeof exports)[\\s\\S]{0,240}module\\.exports[\\s\\S]{0,240}(?:typeof\\s+define|typeof define)[\\s\\S]{0,120}define\\.amd"),
			confidence: 90,
			description: "Bundled script content contains a complete UMD wrapper.",
		},
		{
			id: "umd:scriptContent:wrapper:1",
			kind: "scriptContent",
			pattern: new RegExp("(?:typeof\\s+define|typeof define)[\\s\\S]{0,120}define\\.amd[\\s\\S]{0,240}(?:typeof\\s+exports|typeof exports)[\\s\\S]{0,240}module\\.exports"),
			confidence: 90,
			description: "Bundled script content contains a complete UMD wrapper.",
		},
		{
			id: "umd:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("typeof\\s+define\\s*===?\\s*[\"']function[\"']\\s*&&\\s*define\\.amd"),
			confidence: 5,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "umd:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("typeof\\s+exports\\s*===?\\s*[\"']object[\"']"),
			confidence: 5,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "umd:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("typeof\\s+module\\s*!==?\\s*[\"']undefined[\"']"),
			confidence: 5,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "umd:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("typeof\\s+root\\s*!==?\\s*[\"']undefined[\"']"),
			confidence: 5,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "umd:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("\\(\\s*function\\s*\\(\\s*(?:root,\\s*)?factory\\s*\\)"),
			confidence: 5,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "umd:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("\\(\\s*function\\s*\\(\\s*global\\s*,\\s*factory\\s*\\)"),
			confidence: 5,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "umd:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("function\\(\\w+,\\w+\\){"),
			confidence: 5,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "umd:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("\\btypeof exports\\b.*\\btypeof module\\b"),
			confidence: 5,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "umd:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("\\btypeof define\\b.*\\bdefine\\.amd\\b"),
			confidence: 5,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "umd:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("define\\s*\\(\\s*[\"'][^\"']+[\"']\\s*,\\s*\\["),
			confidence: 5,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "umd:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("define\\s*\\(\\s*\\[[^\\]]*\\]\\s*,\\s*function"),
			confidence: 5,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "umd:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("define\\s*\\(\\s*function\\s*\\("),
			confidence: 5,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "umd:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("root\\[\\s*[\"'][^\"']+[\"']\\s*\\]\\s*="),
			confidence: 5,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "umd:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("this\\[\\s*[\"'][^\"']+[\"']\\s*\\]\\s*="),
			confidence: 5,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "umd:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("global\\[\\s*[\"'][^\"']+[\"']\\s*\\]\\s*="),
			confidence: 5,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "umd:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("module\\.exports\\s*=\\s*factory"),
			confidence: 5,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "umd:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("exports\\s*=\\s*factory"),
			confidence: 5,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "umd:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("define\\.amd\\s*="),
			confidence: 5,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "umd:scriptContent:modern:18",
			kind: "scriptContent",
			pattern: new RegExp("factory\\s*\\(\\s*(?:root|global|this|window)\\s*\\)"),
			confidence: 5,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "umd:scriptContent:modern:19",
			kind: "scriptContent",
			pattern: new RegExp("factory\\s*\\(\\s*(?:exports|module)?\\s*,\\s*(?:exports|module)?\\s*\\)"),
			confidence: 5,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "umd:scriptContent:modern:20",
			kind: "scriptContent",
			pattern: new RegExp("\\[\\s*[\"']require[\"']\\s*,\\s*[\"']exports[\"']\\s*,\\s*[\"']module[\"']\\s*\\]"),
			confidence: 5,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "umd:scriptContent:modern:21",
			kind: "scriptContent",
			pattern: new RegExp("\\[\\s*[\"']exports[\"']\\s*,\\s*[\"']module[\"']\\s*\\]"),
			confidence: 5,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "umd:scriptContent:modern:22",
			kind: "scriptContent",
			pattern: new RegExp("factory\\(\\w+(?:,\\w+)*\\)"),
			confidence: 5,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "umd:scriptContent:modern:23",
			kind: "scriptContent",
			pattern: new RegExp("\\[[\"']require[\"'],[\"']exports[\"']\\]"),
			confidence: 5,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
