import type { TechnologyDefinition } from '../../types';

export const chakraUiTechnologyDefinition = {
	id: "chakra-ui",
	name: "Chakra UI",
	website: "https://chakra-ui.com",
	description: "Chakra UI is a simple, modular and accessible component library that gives you the building blocks you need to build your React applications.",
	icon: "Chakra UI.svg",
	categories: [
		"styling-library",
		"component-library",
	],
	rules: [
		{
			id: "chakra-ui:scriptSrc:0",
			kind: "scriptSrc",
			pattern: new RegExp("\\.chakra-ui\\."),
			description: "Script source URL matches a known technology marker.",
		},
		{
			id: "chakra-ui:dom:1",
			kind: "dom",
			selector: "html[style*='chakra-ui-color-mode'], body.chakra-ui-dark, body.chakra-ui-light, div.chakra-portal",
			description: "DOM selector matches a known technology marker.",
		},
		{
			id: "chakra-ui:dom:2",
			kind: "dom",
			selector: "html[style*='chakra-ui-color-mode'], body.chakra-ui-dark, body.chakra-ui-light, div.chakra-portal, div.chakra-container",
			description: "DOM selector matches a known technology marker.",
		},
		{
			id: "chakra-ui:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("data-chakra-component=\"(?:Button|Modal|Tooltip|Popover|Menu|Drawer|Alert|Toast)\""),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "chakra-ui:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("data-popper-(?:reference-hidden|escaped|placement)=\"chakra-[^\"]{1,50}\""),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "chakra-ui:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("data-theme-color=\"chakra-[^\"]{1,30}\""),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "chakra-ui:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("data-theme=\"chakra-ui-(?:light|dark)\""),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "chakra-ui:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("chakra-(?:button|modal|menu|popover|toast|drawer|alert|form)__[a-zA-Z-]{1,30}\\b"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "chakra-ui:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("chakra-(?:stack|wrap|container|box|text|heading|link)(?:-[a-zA-Z]{1,20})?\\b"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "chakra-ui:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("chakra-(?:fade|scale|slide)-(?:bottom|top|left|right)(?:-(?:enter|exit)(?:-active)?)?\\b"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "chakra-ui:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("chakra-(?:portal-(?:zIndex|overlay|content)|modal-(?:overlay|content-wrapper|body|header|footer))\\b"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "chakra-ui:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("chakra-(?:error-boundary|strict-mode-warning)\\b"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "chakra-ui:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("var\\(--chakra-(?:colors|sizes|fonts|space|radii|shadows)-[^)]{1,50}\\)"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "chakra-ui:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("useChakra(?:Context|ColorMode|Theme|Toast|Disclosure|Modal|Menu|Tabs)\\b"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "chakra-ui:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("_(?:hover|active|focus|disabled|invalid|checked|expanded|selected)=\"chakra-[^\"]{1,50}\""),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "chakra-ui:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("sx=\\{[^}]{0,500}?_(?:hover|focus|active):"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "chakra-ui:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("import\\s+\\{[^}]{1,200}\\}\\s+from\\s+[\"']@chakra-ui\\/(?:react|core|icons|system|theme|hooks)[\"']"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "chakra-ui:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("ChakraProvider\\s+theme=\\{[^}]{1,500}\\}"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "chakra-ui:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("extendTheme\\(\\{[^}]{1,500}\\}\\)"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "chakra-ui:resourceUrl:modern:16",
			kind: "resourceUrl",
			pattern: new RegExp("@chakra-ui\\/(?:react|core|icons|system|theme|hooks)\\b"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "chakra-ui:resourceUrl:modern:17",
			kind: "resourceUrl",
			pattern: new RegExp("chakra-ui-core(?:@[\\d.]{1,10})?(?:\\.min)?\\.js$"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "chakra-ui:resourceUrl:modern:18",
			kind: "resourceUrl",
			pattern: new RegExp("chakra-(?:components|theme|utils)\\.[a-f0-9]{8}\\.js$"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "chakra-ui:resourceUrl:modern:19",
			kind: "resourceUrl",
			pattern: new RegExp("(?:chakra-theme|theme\\.chakra)\\.(?:js|ts)$"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "chakra-ui:resourceUrl:modern:20",
			kind: "resourceUrl",
			pattern: new RegExp("chunk-chakra-[a-z-]{1,30}\\.[a-f0-9]{8}\\.js$"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "chakra-ui:resourceUrl:modern:21",
			kind: "resourceUrl",
			pattern: new RegExp("chakra-[a-z-]{1,30}-[a-f0-9]{8}\\.js$"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "chakra-ui:resourceUrl:modern:22",
			kind: "resourceUrl",
			pattern: new RegExp("@chakra-ui\\/icons(?:-[a-z]+)?(?:@[\\d.]{1,10})?\\b\\.js$"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "chakra-ui:resourceUrl:modern:23",
			kind: "resourceUrl",
			pattern: new RegExp("emotion-(?:cache|element)-chakra\\b"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
	],
	metadata: {
		oss: true,
	},
	implies: [
		"react",
	],
} as const satisfies TechnologyDefinition;
