import type { TechnologyDefinition } from '../../types';

export const foundationTechnologyDefinition = {
	id: "foundation",
	name: "Foundation",
	website: "https://foundation.zurb.com/",
	description: "The most advanced responsive front-end framework in the world.",
	categories: [
		"styling-library",
	],
	rules: [
		{
			id: "foundation:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("grid-(?:margin|padding)-[xy](?:\\s|$)"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "foundation:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("cell-(?:block(?:-container|-y)?)\\b"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "foundation:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("xy-grid-(?:container|frame|cell)\\b"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "foundation:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("(?:^|\\s)(?:medium|large|xlarge|xxlarge)-(?:expand|unstack|offset|push|pull)-\\d{1,2}(?:\\s|$)"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "foundation:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("(?:^|\\s)responsive-embed-(?:widescreen|panorama|square|portrait)\\b"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "foundation:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("data-(?:whatinput|whatintent|interchange|equalizer-watch|magellan|abide|accordion|dropdown|drilldown|responsive-(?:accordion-tabs|tabs))(?:=|$)"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "foundation:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("Foundation\\.(?:Abide|Accordion|Dropdown(?:Menu)?|Equalizer|Interchange|Magellan|OffCanvas|Orbit|ResponsiveMenu|ResponsiveToggle|Reveal|Slider|SmoothScroll|Sticky|Tabs|Toggler|Tooltip|ResponsiveAccordionTabs)\\b\\("),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "foundation:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("off-canvas-(?:content|absolute|fixed|reveal|overlap-(?:left|right|top|bottom))\\b"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "foundation:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("drilldown-(?:submenu(?:-cover)?|subitem|current|parent)\\b"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "foundation:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("orbit-(?:container|wrapper|slides|slide|bullets|previous|next|figure)\\b"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "foundation:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("(?:^|\\s)(?:show|hide)-for-(?:sr|landscape|portrait)(?:-only)?\\b"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "foundation:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("(?:form-error\\s+is-visible|is-invalid-(?:input|label|container))-(?:abide|equalizer|magellan)\\b"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "foundation:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("'(?:closeme|resizeme|scrollme|mutate|toggled|sticky\\.zf|magellan)\\.zf'"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "foundation:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("'(?:down|up|left|right)\\.zf\\.(?:drilldown|accordion|dropdown)'"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "foundation:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("mui-(?:enter|leave|slide|fade|hinge|spin|scale)(?:-(?:active|from|to))?\\b"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "foundation:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("(?:^|\\s)is-(?:animating|entering|leaving|active|complete)-mui\\b"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "foundation:resourceUrl:modern:16",
			kind: "resourceUrl",
			pattern: new RegExp("foundation-sites@[0-9.]{1,10}\\/dist\\/(?:js|css)\\/foundation(?:\\.min)?\\.(?:js|css)$"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "foundation:resourceUrl:modern:17",
			kind: "resourceUrl",
			pattern: new RegExp("foundation-sites\\/dist\\/(?:js|css)\\/plugins\\/foundation\\.[a-z]{1,20}\\.(?:js|css)$"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "foundation:resourceUrl:modern:18",
			kind: "resourceUrl",
			pattern: new RegExp("foundation\\.(?:core|grid|typography|forms|controls|float|prototype|rtl)(?:\\.min)?\\.(?:js|css)$"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "foundation:resourceUrl:modern:19",
			kind: "resourceUrl",
			pattern: new RegExp("foundation\\.(?:abide|accordion|drilldown|dropdown|equalizer|interchange|magellan|offcanvas|orbit|responsivemenu|reveal|slider|smoothscroll|sticky|tabs|toggler|tooltip)\\.js$"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "foundation:resourceUrl:modern:20",
			kind: "resourceUrl",
			pattern: new RegExp("(?:motion-ui\\/dist\\/motion-ui|foundation-motion-ui)(?:\\.min)?\\.(?:js|css)$"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "foundation:resourceUrl:modern:21",
			kind: "resourceUrl",
			pattern: new RegExp("_foundation-settings\\.scss$"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "foundation:resourceUrl:modern:22",
			kind: "resourceUrl",
			pattern: new RegExp("foundation-custom\\.scss$"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
