import type { TechnologyDefinition } from '../../types';

export const muiTechnologyDefinition = {
	id: "mui",
	name: "MUI",
	website: "https://mui.com",
	description: "MUI(formerly Material UI) is a simple and customisable component library to build faster, beautiful, and more accessible React applications.",
	icon: "MUI.svg",
	categories: [
		"styling-library",
		"component-library",
	],
	rules: [
		{
			id: "mui:stylesheetContent:0",
			kind: "stylesheetContent",
			pattern: new RegExp("\\.MuiPaper-root"),
			description: "Stylesheet content contains a bounded technology signature.",
		},
		{
			id: "mui:dom:1",
			kind: "dom",
			selector: "style[data-meta='MuiPaper'], div.MuiBox-root, div.MuiPaper-root, style[data-meta='MuiButton']",
			description: "DOM selector matches a known technology marker.",
		},
		{
			id: "mui:dom:2",
			kind: "dom",
			selector: "style[data-meta='MuiPaper'], div.MuiBox-root, div.MuiPaper-root, style[data-meta='MuiButton'], input.MuiInputBase-input, div.MuiContainer-root",
			description: "DOM selector matches a known technology marker.",
		},
		{
			id: "mui:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("https:\\/\\/mui\\.com\\/production-error\\/\\?code="),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mui:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("Symbol\\.for\\([\"']mui\\.nested[\"']\\)"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mui:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("\\.muiName\\s*=\\s*[\"'](Button|Slider|TextField|Checkbox|Radio|Switch|Select|Autocomplete|Tooltip|Modal|Dialog|Drawer|AppBar|IconButton)[\"']"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mui:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("name:\\s*[\"'](Mui[A-Z][a-zA-Z0-9]*)[\"']"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mui:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("\\.\\s*__mui_systemSx\\b"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mui:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("from\\s+[\"']@mui\\/material(?:\\/styles)?[\"']\\s*;"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mui:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("import\\s+\\{\\s*(?:[^{}]*,\\s*)?(?:styled|alpha|createTheme|ThemeProvider)(?:\\s*,\\s*[^{}]*)?\\s*\\}\\s+from\\s+[\"']@mui\\/material(?:\\/styles)?[\"']"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mui:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("import\\s+\\{\\s*(?:[^{}]*,\\s*)?(?:Button|TextField|Checkbox|Radio|Select|Switch|Slider|Dialog|Drawer|AppBar|Toolbar|IconButton|Typography|Box|Grid|Paper|Card|Divider|List|Avatar)(?:\\s*,\\s*[^{}]*)?\\s*\\}\\s+from\\s+[\"']@mui\\/material(?:\\/[a-zA-Z0-9]+)?[\"']"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mui:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("from\\s+[\"']@mui\\/icons-material(?:\\/[a-zA-Z0-9]+)?[\"']"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mui:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("MuiButtonBase-(?:root|focusVisible|disabled|color(?:Primary|Secondary))\\b"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mui:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("MuiButton-(?:contained(?:Primary)|outlined(?:Secondary)|text(?:Success)|size(?:Large)|fullWidth)\\b"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mui:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("data-mui-(?:color-scheme=\"(?:light|dark)\"|internal-clone-element=\"true\")"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mui:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("(?:private-mui-(?:x-id|focusVisible|hidden|root|colorAction)|StyledEngineProvider\\s+injectFirst)\\b"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mui:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("var\\(--mui-(?:palette|typography|spacing|shadows|shape|zIndex|transitions)-[^)]{1,50}\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mui:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("import\\s+\\{[^}]{1,200}\\}\\s+from\\s+[\"']@mui\\/(?:material|system|base|joy-ui|icons-material)[\"']"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mui:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("components:\\s*\\{\\s*MuiButton:\\s*\\{[^}]{1,500}\\}\\s*\\}"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mui:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("data-mui-base-(?:button|select|slider|switch|tabs|input)\\b"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mui:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("aria-(?:owns|controls|haspopup|expanded)=\"mui-[^\"]{1,50}\""),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mui:scriptContent:modern:18",
			kind: "scriptContent",
			pattern: new RegExp("id=\"(?:modal|menu)-[^\"]{1,30}\"\\s+role=\"(?:presentation|menu)\"\\s+class=\"Mui(?:Modal-root|Menu-list)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mui:scriptContent:modern:19",
			kind: "scriptContent",
			pattern: new RegExp("createTheme\\(\\{\\s*palette:\\s*\\{\\s*primary:\\s*\\{[^}]{1,500}\\}\\s*\\}\\s*\\}"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mui:scriptContent:modern:20",
			kind: "scriptContent",
			pattern: new RegExp("(?:Material-UI|MUI):\\s"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mui:scriptContent:modern:21",
			kind: "scriptContent",
			pattern: new RegExp("data-(?:mui-inject-first=\"true\"|emotion=\"mui(?:-[a-z]+)?\")\\b"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
	metadata: {
		saas: true,
		oss: true,
		pricing: [
			"freemium",
			"payg",
		],
	},
	implies: [
		"react",
	],
} as const satisfies TechnologyDefinition;
