import type { TechnologyDefinition } from '../../types';

export const shadcnUiTechnologyDefinition = {
	id: "shadcn-ui",
	name: "shadcn/ui",
	website: "https://ui.shadcn.com",
	description: "A set of high-quality React components out of the box. It is written in TypeScript with predictable static types.",
	categories: [
		"styling-library",
	],
	rules: [
		{
			id: "shadcn-ui:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("\\w+\\.displayName\\s*=\\s*[\"'](Button|Dialog|DropdownMenu)[\"'];\\s*(?:.*\\s*)*\\w+\\s*=\\s*\\w+\\.forwardRef"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "shadcn-ui:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("className:\\s*\\w+\\(\\s*\\w+\\(\\{\\s*variant:\\s*\\w+,\\s*size:\\s*\\w+,\\s*className:\\s*\\w+\\s*\\}\\)\\)"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "shadcn-ui:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("let\\s+\\w+\\s*=\\s*\\(\\s*0\\s*,\\s*\\w+\\s*\\.\\s*F\\s*\\)\\s*\\(\\s*[\"'](?:[^\"']*whitespace-nowrap[^\"']*rounded-md[^\"']*ring-offset-background[^\"']*)"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "shadcn-ui:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("variants:\\s*\\{\\s*variant:\\s*\\{\\s*default:[^}]*text-primary-foreground[^}]*,\\s*destructive:[^}]*text-destructive-foreground[^}]*,\\s*outline:[^}]*border-input\\s*bg-background[^}]*,\\s*secondary:[^}]*bg-secondary\\s*text-secondary-foreground[^}]*,\\s*ghost:[^}]*hover:bg-accent[^}]*,\\s*link:[^}]*text-primary\\s*underline-offset-4[^}]*\\s*\\}"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "shadcn-ui:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("data-\\[state=open\\]:animate-in\\s+data-\\[state=closed\\]:animate-out\\s+data-\\[state=closed\\]:fade-out-0\\s+data-\\[state=open\\]:fade-in-0\\s+data-\\[state=closed\\]:zoom-out-95\\s+data-\\[state=open\\]:zoom-in-95\\s+data-\\[state=closed\\]:slide-out-to-left-1\\/2"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "shadcn-ui:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("className:\\s*[\"'][^\"']*absolute\\s+right-4\\s+top-4\\s+rounded-sm\\s+opacity-70\\s+ring-offset-background[^\"']*[\"'][^>]*>\\s*\\([^)]*\\.jsx\\)\\([^)]*\\{\\s*className:\\s*[\"']h-4\\s+w-4[\"']\\s*\\}\\),\\s*\\([^)]*\\.jsx\\)\\([^)]*\\{\\s*className:\\s*[\"']sr-only[\"'][^}]*\\},\\s*[\"']Close[\"']"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "shadcn-ui:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("\\(\\s*0\\s*,\\s*\\w+\\.jsxs?\\s*\\)\\(\\s*\\w+\\s*,\\s*\\{\\s*(?:[^}]*,)?\\s*children:\\s*\\[\\s*\\(\\s*0\\s*,\\s*\\w+\\.jsx\\s*\\)\\(\\s*\\w+\\s*\\.\\s*\\w+\\s*,\\s*\\{\\s*className:[^}]*\\}\\s*\\)\\s*,\\s*\\(\\s*0\\s*,\\s*\\w+\\.jsx\\s*\\)\\(\\s*[\"']input[\"']\\s*,\\s*\\{\\s*(?:[^}]*,)?\\s*placeholder:\\s*[\"']Search\\.\\.\\.[\"']"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "shadcn-ui:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("class=[\"'](?:[^\"']{0,100}?\\s)?(?:destructive|outline|secondary|ghost|link)(?:\\s[^\"']{0,100})?[\"']"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "shadcn-ui:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("from\\s+[\"']@\\/components\\/ui\\/(?:accordion|alert-dialog|aspect-ratio|avatar|badge|calendar|card|carousel|checkbox|collapsible|command|context-menu|dialog|dropdown-menu|hover-card|input|label|menubar|navigation-menu|popover|progress|radio-group|scroll-area|select|separator|sheet|skeleton|slider|switch|table|tabs|textarea|toggle|tooltip)[\"']"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "shadcn-ui:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("\\(\\s*0\\s*,\\s*\\w+\\.jsxs?\\s*\\)\\(\\s*\\w+\\s*\\.\\s*\\w+\\s*,\\s*\\{\\s*(?:[^}]*,)?\\s*children:\\s*\\[\\s*\\(\\s*0\\s*,\\s*\\w+\\.jsx\\s*\\)\\(\\s*\\w+\\s*\\.\\s*\\w+\\s*,\\s*\\{[^}]*\\}\\s*\\)\\s*,\\s*\\(\\s*0\\s*,\\s*\\w+\\.jsx\\s*\\)\\(\\s*\\w+\\s*,\\s*\\{\\s*className:[^}]*\\}\\s*\\)\\s*\\]\\s*\\}\\s*\\)"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "shadcn-ui:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("toast:[^{]*\\{\\s*(?:[^}]*,)?\\s*title:\\s*[\"'][^\"']*[\"']\\s*,\\s*description:\\s*[\"'][^\"']*[\"']\\s*,\\s*(?:action\\s*:\\s*\\{[^}]*\\}\\s*,\\s*)?(?:variant\\s*:\\s*[\"'](?:default|destructive)[\"']\\s*,\\s*)?\\s*(?:duration\\s*:\\s*\\d+\\s*,\\s*)?\\s*\\}"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "shadcn-ui:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("\\(\\s*0\\s*,\\s*\\w+\\.jsxs?\\s*\\)\\(\\s*\\w+\\s*\\.\\s*\\w+\\s*,\\s*\\{\\s*(?:[^}]*,)?\\s*children:\\s*\\[\\s*[^,]*,\\s*\\(\\s*0\\s*,\\s*\\w+\\.jsx\\s*\\)\\(\\s*\\w+\\s*,\\s*\\{\\s*className:\\s*[\"']h-4\\s+w-4\\s+(?:shrink|transition)-0[^\"']*data-\\[state=open\\]:rotate-180[^\"']*[\"']"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "shadcn-ui:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("cn\\(\\s*buttonVariants\\(\\{[^}]*variant:"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "shadcn-ui:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("cn\\(\\s*alertVariants\\(\\{[^}]*variant:"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "shadcn-ui:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("cn\\(\\s*cardVariants\\(\\{[^}]*variant:"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "shadcn-ui:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("cn\\(\\s*[\"'](?:fixed|absolute)\\s+(?:inset-0|inset-x-0|inset-y-0)\\s+z-50\\s+flex\\s+items-center\\s+justify-center[\"']"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
