import type { TechnologyDefinition } from '../../types';

export const tailwindCssTechnologyDefinition = {
	id: "tailwind-css",
	name: "Tailwind CSS",
	website: "https://tailwindcss.com/",
	description: "Tailwind is a utility-first CSS framework for rapidly building custom user interfaces.",
	icon: "tailwindcss.svg",
	categories: [
		"styling-library",
		"component-library",
	],
	rules: [
		{
			id: "tailwind-css:scriptSrc:0",
			kind: "scriptSrc",
			pattern: new RegExp("\\.tailwindcss(?:tailwind-config-cdn)?\\.(?:com|js)"),
			description: "Script source URL matches a known technology marker.",
		},
		{
			id: "tailwind-css:stylesheetContent:1",
			kind: "stylesheetContent",
			pattern: new RegExp("--tw-(?:rotate|translate|space-x|text-opacity|border-opacity)"),
			description: "Stylesheet content contains a bounded technology signature.",
		},
		{
			id: "tailwind-css:dom:2",
			kind: "dom",
			selector: "link[rel='stylesheet'][href*='tailwind']",
			description: "DOM selector matches a known technology marker.",
		},
		{
			id: "tailwind-css:jsGlobal:3",
			kind: "jsGlobal",
			property: "tailwind",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "tailwind-css:scriptSrc:4",
			kind: "scriptSrc",
			pattern: new RegExp("\\.tailwindcss(?:tailwind-config-cdn)?\\.(?:com|js)|\\/npm\\/@tailwindcss\\/browser"),
			description: "Script source URL matches a known technology marker.",
		},
		{
			id: "tailwind-css:stylesheetContent:5",
			kind: "stylesheetContent",
			pattern: new RegExp("--tw-(?:rotate|translate|space-x|text-opacity|border-opacity|bg-opacity|scale|ring|blur|shadow|brightness|contrast|grayscale|invert|sepia)"),
			description: "Stylesheet content contains a bounded technology signature.",
		},
		{
			id: "tailwind-css:text:8",
			kind: "text",
			pattern: new RegExp("\\/\\/\\*! tailwindcss v([\\d.]+) \\| MIT License \\| https:\\/\\/tailwindcss\\.com\\*\\/"),
			version: {
				source: "match",
				group: 1,
			},
			description: "Page text contains a known technology marker.",
		},
		{
			id: "tailwind-css:jsGlobal:9",
			kind: "jsGlobal",
			property: "hexToTailwindColorVar",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "tailwind-css:meta:10",
			kind: "meta",
			key: "application-name",
			valuePattern: new RegExp("^Tailwind CSS$", "i"),
			description: "Meta tag matches a known technology marker.",
		},
		{
			id: "tailwind-css:html:11",
			kind: "html",
			pattern: new RegExp("/\\*!\\s*tailwindcss\\s+v[\\d.]+\\s*\\|\\s*MIT\\s*License\\s*\\|\\s*https://tailwindcss\\.com", "i"),
			confidence: 95,
			description: "Document HTML contains the Tailwind CSS generated stylesheet banner.",
		},
		{
			id: "tailwind-css:html:12",
			kind: "html",
			pattern: new RegExp("--tw-(?:ring|shadow|translate|rotate|skew|scale|space-[xy]|divide-[xy]|border-opacity|text-opacity|bg-opacity)[a-z-]*\\s*:", "i"),
			confidence: 85,
			description: "Document HTML contains Tailwind-generated CSS custom properties.",
		},
		{
			id: "tailwind-css:html:modern:0",
			kind: "html",
			pattern: new RegExp("<[^>]+class=\"[^\"]*\\[[^\\]]+\\][^\"]*\"", "i"),
			confidence: 20,
			description: "Document HTML contains arbitrary-value utility-looking classes. This is weak without Tailwind-generated CSS or a Tailwind script/package marker.",
		},
		{
			id: "tailwind-css:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("@tailwind\\s+(?:base|components|utilities|variants)\\b"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "tailwind-css:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("@layer\\s+(?:base|components|utilities)\\b"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "tailwind-css:stylesheetContent:modern:3",
			kind: "stylesheetContent",
			pattern: new RegExp("\\/\\*\\s*!\\s*tailwindcss\\s+v\\d+\\.\\d+\\.\\d+\\s*\\|\\s*MIT\\s*License\\s*\\|\\s*https:\\/\\/tailwindcss\\.com\\s*\\*\\/"),
			confidence: 75,
			description: "Stylesheet content matches a modern styling marker.",
		},
		{
			id: "tailwind-css:stylesheetContent:modern:4",
			kind: "stylesheetContent",
			pattern: new RegExp("--tw-(?:ring-inset|ring-offset-width|ring-offset-color|ring-color|ring-offset-shadow|ring-shadow|shadow|shadow-colored)"),
			confidence: 75,
			description: "Stylesheet content matches a modern styling marker.",
		},
		{
			id: "tailwind-css:stylesheetContent:modern:5",
			kind: "stylesheetContent",
			pattern: new RegExp("\\.space-[xy]-\\d+\\s*>\\s*:not\\(\\[hidden\\]\\)\\s*~\\s*:not\\(\\[hidden\\]\\)"),
			confidence: 75,
			description: "Stylesheet content matches a modern styling marker.",
		},
		{
			id: "tailwind-css:stylesheetContent:modern:6",
			kind: "stylesheetContent",
			pattern: new RegExp("\\[-?-tw-[^\\]]*\\]"),
			confidence: 75,
			description: "Stylesheet content matches a modern styling marker.",
		},
		{
			id: "tailwind-css:stylesheetContent:modern:7",
			kind: "stylesheetContent",
			pattern: new RegExp("--tw-[a-z-]+:\\s*[^;]*;"),
			confidence: 75,
			description: "Stylesheet content matches a modern styling marker.",
		},
		{
			id: "tailwind-css:stylesheetContent:modern:8",
			kind: "stylesheetContent",
			pattern: new RegExp("(?:\\*|:before|:after|:first|:last|:only|:even:before|::after|::backdrop)\\s*\\{[^}]*(?:--tw-[a-z-]+:[^;]*;.*){5,}", "s"),
			confidence: 75,
			description: "Stylesheet content matches a modern styling marker.",
		},
		{
			id: "tailwind-css:stylesheetContent:modern:9",
			kind: "stylesheetContent",
			pattern: new RegExp("\\*\\s*,\\s*:after\\s*,\\s*:before\\s*\\{[^}]*--tw-[a-z-]+:"),
			confidence: 75,
			description: "Stylesheet content matches a modern styling marker.",
		},
		{
			id: "tailwind-css:stylesheetContent:modern:10",
			kind: "stylesheetContent",
			pattern: new RegExp("::backdrop\\s*\\{[^}]*--tw-[a-z-]+:"),
			confidence: 75,
			description: "Stylesheet content matches a modern styling marker.",
		},
		{
			id: "tailwind-css:html:modern:11",
			kind: "html",
			pattern: new RegExp("<[^>]+class=\"[^\"]*(?:group|peer)\\/(?:[\\w-]+)[^\"]*\"", "i"),
			confidence: 20,
			description: "Document HTML contains grouped utility-looking classes. This is weak without Tailwind-generated CSS or a Tailwind script/package marker.",
		},
		{
			id: "tailwind-css:html:modern:12",
			kind: "html",
			pattern: new RegExp("<[^>]+class=\"[^\"]*(?:hover|focus|active|group-hover|dark):[\\w-]+[^\"]*\"", "i"),
			confidence: 20,
			description: "Document HTML contains variant-prefixed utility-looking classes. This is weak without Tailwind-generated CSS or a Tailwind script/package marker.",
		},
		{
			id: "tailwind-css:html:modern:13",
			kind: "html",
			pattern: new RegExp("<[^>]+class=\"(?:[^\"]*\\s)?(?:flex|grid)\\s+(?:items|justify)-(?:center|start|end|between)[^\"]*\"", "i"),
			confidence: 15,
			description: "Document HTML contains common utility class names. This is too generic to display as Tailwind evidence by itself.",
		},
		{
			id: "tailwind-css:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("@apply\\s+(?:[\\w-]+(?:\\/[0-9]+)?(?:\\s+)?){1,15};"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "tailwind-css:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("@variants\\s+(?:[\\w-]+(?:,\\s*[\\w-]+)*)\\s*\\{"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "tailwind-css:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("@screen\\s+(?:sm|md|lg|xl|2xl)\\b"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "tailwind-css:stylesheetContent:modern:17",
			kind: "stylesheetContent",
			pattern: new RegExp("\\.(?:bg|text|border)-(?:[\\w-]+)(?:-\\d+)?\\/\\d+"),
			confidence: 65,
			description: "Stylesheet content matches a modern styling marker.",
		},
		{
			id: "tailwind-css:stylesheetContent:modern:18",
			kind: "stylesheetContent",
			pattern: new RegExp("--tw-(?:translate-[xy]|rotate|skew-[xy]|scale-[xy]):"),
			confidence: 65,
			description: "Stylesheet content matches a modern styling marker.",
		},
		{
			id: "tailwind-css:stylesheetContent:modern:19",
			kind: "stylesheetContent",
			pattern: new RegExp("--tw-ring-(?:inset|offset-width|offset-color|color|offset-shadow|shadow):"),
			confidence: 65,
			description: "Stylesheet content matches a modern styling marker.",
		},
		{
			id: "tailwind-css:stylesheetContent:modern:20",
			kind: "stylesheetContent",
			pattern: new RegExp("\\.(?:sm|md|lg|xl|2xl)\\\\:[\\w-]+"),
			confidence: 65,
			description: "Stylesheet content matches a modern styling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
