import type { TechnologyDefinition } from '../../types';

export const angularTechnologyDefinition = {
	id: "angular",
	name: "Angular",
	website: "https://angular.io",
	description: "Angular is a TypeScript-based open-source web application framework led by the Angular Team at Google.",
	icon: "Angular.svg",
	categories: [
		"ui-library",
	],
	rules: [
		{
			id: "angular:dom:0",
			kind: "dom",
			selector: "[ng-version]",
			description: "DOM selector matches a known technology marker.",
		},
		{
			id: "angular:jsGlobal:1",
			kind: "jsGlobal",
			property: "ng.coreTokens",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "angular:jsGlobal:2",
			kind: "jsGlobal",
			property: "ng.probe",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "angular:jsGlobal:3",
			kind: "jsGlobal",
			property: "getAllAngularRootElements",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "angular:jsGlobal:4",
			kind: "jsGlobal",
			property: "getAngularTestability",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "angular:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("platformBrowser\\w*\\s*\\(\\s*\\[\\s*\\{\\s*ngZone\\s*:\\s*[\"']zone\\.js[\"']"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("ɵcmp|ɵmod|ɵfac|ɵinj|ɵprov|ɵdef"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("assert(Not)?InAngularZone()"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("isInAngularZone()"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("runOutsideAngular\\s*\\(\\s*\\(\\)\\s*=>"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("NgZoneEvent"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("createPolicy\\([\"']angular#[^\"']+[\"']\\)"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("Zone\\.__load_patch\\(['\"]angular['\"],\\s*function"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("__Zone_enable_cross_context_check"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("__zone_symbol__BLACK_LISTED_EVENTS"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("\\[\\s*\"ngInjectableDef\"\\s*,\\s*ɵɵdefine"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("ɵɵdefineInjectable\\s*\\(\\s*\\{\\s*factory:"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("defineNgModule\\s*\\(\\s*\\{\\s*type:\\s*\\w+,\\s*bootstrap:"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("data-ng-version=[\"']\\d+\\.\\d+\\.\\d+[\"']"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("__ignore_ng_zone__"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("angularZoneInstanceIdProperty"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("ngDevMode\\s*=\\s*false"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("\\b[a-zA-Z_$][\\w$]*\\.angular\\.callbacks\\b"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:18",
			kind: "scriptContent",
			pattern: new RegExp("Standard Angular field decorators are not supported in JIT mode"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:19",
			kind: "scriptContent",
			pattern: new RegExp("Expected to be in Angular Zone, but it is not!"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:20",
			kind: "scriptContent",
			pattern: new RegExp("Tried to load angular more than once"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:21",
			kind: "scriptContent",
			pattern: new RegExp("http:\\/\\/errors\\.angularjs\\.org"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:22",
			kind: "scriptContent",
			pattern: new RegExp("ɵɵdefineComponent\\s*\\(\\s*\\{\\s*type:\\s*\\w+,\\s*selectors:\\s*\\[\\s*\\["),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:23",
			kind: "scriptContent",
			pattern: new RegExp("ɵɵfactoryDef\\s*\\(\\s*type,\\s*view"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:24",
			kind: "scriptContent",
			pattern: new RegExp("prototype\\.ngOnInit\\s*=\\s*function\\s*\\(\\s*\\)\\s*\\{"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:25",
			kind: "scriptContent",
			pattern: new RegExp("prototype\\.ngOnDestroy\\s*=\\s*function\\s*\\(\\s*\\)\\s*\\{"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:26",
			kind: "scriptContent",
			pattern: new RegExp("ɵɵdetectChanges\\s*\\(\\s*\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:27",
			kind: "scriptContent",
			pattern: new RegExp("ChangeDetectorRef\\.prototype\\.markForCheck"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:28",
			kind: "scriptContent",
			pattern: new RegExp("ɵɵviewQuery\\s*\\(\\s*\\w+\\s*,\\s*\\d+"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:29",
			kind: "scriptContent",
			pattern: new RegExp("ɵɵcontentQuery\\s*\\(\\s*\\w+\\s*,\\s*\\d+"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:30",
			kind: "scriptContent",
			pattern: new RegExp("ɵɵtemplate\\s*\\(\\s*\\d+\\s*,\\s*[A-Za-z]\\w*\\s*,\\s*\\d+\\s*,\\s*\\d+"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:31",
			kind: "scriptContent",
			pattern: new RegExp("ɵɵtemplateRefExtractor"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:32",
			kind: "scriptContent",
			pattern: new RegExp("ɵɵelementContainerStart\\s*\\(\\s*\\d+\\s*,\\s*\\[\\s*[\"']\\*ngIf[\"']"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:33",
			kind: "scriptContent",
			pattern: new RegExp("ɵɵelementContainerStart\\s*\\(\\s*\\d+\\s*,\\s*\\[\\s*[\"']\\*ngFor[\"']"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:34",
			kind: "scriptContent",
			pattern: new RegExp("ɵɵlistener\\s*\\(\\s*[\"'][^\"']+[\"']\\s*,\\s*function"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:35",
			kind: "scriptContent",
			pattern: new RegExp("ɵɵproperty\\s*\\(\\s*[\"'][^\"']+[\"']\\s*,\\s*"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:36",
			kind: "scriptContent",
			pattern: new RegExp("ɵɵattribute\\s*\\(\\s*[\"'][^\"']+[\"']\\s*,\\s*"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:37",
			kind: "scriptContent",
			pattern: new RegExp("RouterModule\\.forRoot\\s*\\(\\s*\\[\\s*\\{\\s*path\\s*:"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:38",
			kind: "scriptContent",
			pattern: new RegExp("ɵɵRouterModule\\s*\\(\\s*\\[\\s*\\{\\s*path\\s*:"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:39",
			kind: "scriptContent",
			pattern: new RegExp("router-outlet"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:40",
			kind: "scriptContent",
			pattern: new RegExp("RouterOutlet\\.prototype\\.ngOnDestroy"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:41",
			kind: "scriptContent",
			pattern: new RegExp("CanActivate\\s*:\\s*\\["),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:42",
			kind: "scriptContent",
			pattern: new RegExp("CanDeactivate\\s*:\\s*\\["),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:43",
			kind: "scriptContent",
			pattern: new RegExp("NavigationStart\\s*\\.\\s*prototype\\s*\\.\\s*toString"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:44",
			kind: "scriptContent",
			pattern: new RegExp("NavigationEnd\\s*\\.\\s*prototype\\s*\\.\\s*toString"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:45",
			kind: "scriptContent",
			pattern: new RegExp("FormGroup\\.prototype\\.registerControl"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:46",
			kind: "scriptContent",
			pattern: new RegExp("FormBuilder\\.prototype\\.group"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:47",
			kind: "scriptContent",
			pattern: new RegExp("Validators\\.required"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:48",
			kind: "scriptContent",
			pattern: new RegExp("Validators\\.minLength\\s*\\(\\s*\\d+\\s*\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:49",
			kind: "scriptContent",
			pattern: new RegExp("NgModel\\.prototype\\.ngOnChanges"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:50",
			kind: "scriptContent",
			pattern: new RegExp("FormControlDirective\\.prototype\\.ngOnChanges"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:51",
			kind: "scriptContent",
			pattern: new RegExp("ControlContainer\\.prototype\\.registerOnChange"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular:scriptContent:modern:52",
			kind: "scriptContent",
			pattern: new RegExp("AbstractControl\\.prototype\\.statusChanges"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
	metadata: {
		oss: true,
		cpe: "cpe:2.3:a:angularjs:angular:*:*:*:*:*:*:*:*",
	},
	implies: [
		"typescript",
	],
	excludes: [
		"angulardart",
		"angularjs",
	],
} as const satisfies TechnologyDefinition;
