import type { TechnologyDefinition } from '../../types';

export const infernoTechnologyDefinition = {
	id: "inferno",
	name: "Inferno",
	website: "https://infernojs.org/",
	description: "A JavaScript library for building user interfaces",
	categories: [
		"ui-library",
	],
	rules: [
		{
			id: "inferno:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("createVNode\\(\\d+,(?:[\"'][^\"']+[\"']|\\w+),(?:null|\\{[^}]*\\}|\\w+),"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "inferno:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("\\$V=\\d+,\\$C=\\d+,\\$M=\\d+"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "inferno:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("\\$F=\\d+,\\$T=\\d+"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "inferno:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("normalizeProps\\(\\{[^}]+\\}\\)|normalizeChildren\\([^)]+\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "inferno:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("__render\\(\\w+,\\w+,(?:!0|!1)\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "inferno:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("__patch\\(\\w+,\\w+,\\w+,(?:!0|!1)\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "inferno:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("class\\s+[$_a-zA-Z][\\w$]*\\s+extends\\s+Component\\s*\\{\\s*render\\s*\\(\\s*\\)\\s*\\{"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "inferno:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("function\\s+[$_a-zA-Z][\\w$]*\\(\\{[^}]*\\}\\)\\{return createVNode\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "inferno:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("function\\s+useState\\s*\\(\\s*\\w+\\s*\\)\\s*\\{\\s*return\\s+\\$HS\\s*\\(\\s*\\d+"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "inferno:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("function\\s+useEffect\\s*\\(\\s*\\w+\\s*,\\s*\\w+\\s*\\)\\s*\\{\\s*\\$HE\\s*\\(\\s*\\d+"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "inferno:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("\\$HI=new WeakMap,\\$HS=function"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "inferno:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("\\$HR=function\\(\\w+,\\w+\\)\\{"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "inferno:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("\\[\\w+,function\\(\\w+\\)\\{return \\$HS\\(\\d+,\\w+,\\w+\\)\\}\\]"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "inferno:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("\\$HC\\(\\d+,function\\(\\)\\{"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "inferno:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("createElement=createVNode"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "inferno:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("Component=InfernoComponent"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "inferno:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("checkPropTypes\\(\\w+,\\w+,[\"']\\w+[\"']\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "inferno:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("findDOMfromVNode\\(\\w+\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "inferno:scriptContent:modern:18",
			kind: "scriptContent",
			pattern: new RegExp("hydrate\\(\\w+,\\w+,\\w+\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
