import type { TechnologyDefinition } from '../../types';

export const jqueryTechnologyDefinition = {
	id: "jquery",
	name: "jQuery",
	website: "https://jquery.com",
	description: "jQuery is a JavaScript library which is a free, open-source software designed to simplify HTML DOM tree traversal and manipulation, as well as event handling, CSS animation, and Ajax.",
	icon: "jQuery.svg",
	categories: [
		"ui-library",
		"widgets-misc",
	],
	rules: [
		{
			id: "jquery:scriptSrc:0",
			kind: "scriptSrc",
			pattern: new RegExp("jquery"),
			description: "Script source URL matches a known technology marker.",
		},
		{
			id: "jquery:scriptSrc:1",
			kind: "scriptSrc",
			pattern: new RegExp("\\/jquery(?:-(\\d+\\.\\d+\\.\\d+))[/.-]"),
			version: {
				source: "match",
				group: 1,
			},
			description: "Script source URL matches a known technology marker.",
		},
		{
			id: "jquery:scriptSrc:2",
			kind: "scriptSrc",
			pattern: new RegExp("\\/(\\d+\\.\\d+\\.\\d+)\\/jquery[/.-][^u]"),
			version: {
				source: "match",
				group: 1,
			},
			description: "Script source URL matches a known technology marker.",
		},
		{
			id: "jquery:jsGlobal:3",
			kind: "jsGlobal",
			property: "$.fn.jquery",
			valuePattern: new RegExp("([\\d.]+)"),
			version: {
				source: "match",
				group: 1,
			},
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "jquery:jsGlobal:4",
			kind: "jsGlobal",
			property: "jQuery.fn.jquery",
			valuePattern: new RegExp("([\\d.]+)"),
			version: {
				source: "match",
				group: 1,
			},
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "jquery:scriptSrc:5",
			kind: "scriptSrc",
			pattern: new RegExp("\\/(\\d+\\.\\d+\\.\\d+)\\/jquery(?!\\.popupoverlay\\.js|(?:\\.[\\w-]*)*fancybox)[/.-][^u]"),
			version: {
				source: "match",
				group: 1,
			},
			description: "Script source URL matches a known technology marker.",
		},
		{
			id: "jquery:jsGlobal:6",
			kind: "jsGlobal",
			property: "jQuery.prototype.jquery",
			valuePattern: new RegExp("([\\d.]+)"),
			version: {
				source: "match",
				group: 1,
			},
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "jquery:scriptSrc:7",
			kind: "scriptSrc",
			pattern: new RegExp("\\/(\\d+\\.\\d+\\.\\d+)\\/jquery(?!\\.popupoverlay\\.js)[/.-][^u]"),
			version: {
				source: "match",
				group: 1,
			},
			description: "Script source URL matches a known technology marker.",
		},
		{
			id: "jquery:scriptSrc:8",
			kind: "scriptSrc",
			pattern: new RegExp("\\/(\\d+\\.\\d+\\.\\d+)\\/jquery(?:\\.min)\\.js"),
			version: {
				source: "match",
				group: 1,
			},
			description: "Script source URL matches a known technology marker.",
		},
		{
			id: "jquery:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("typeof\\s+jQuery\\s*===?\\s*[\"']function[\"']"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "jquery:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("jQuery\\.fn\\s*=\\s*jQuery\\.prototype\\s*=\\s*\\{"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "jquery:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("jQuery\\.extend\\(\\s*\\{\\s*(?:[^{}]|\\{[^{}]*\\})*\\}\\s*\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "jquery:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("jQuery\\.Deferred exception:"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "jquery:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("!\\ Bundled\\ license\\ information:[\\s\\S]*?jquery\\/dist\\/jquery\\.js[\\s\\S]*?\\*"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "jquery:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("define\\(\"jquery\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "jquery:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("var\\s+[a-zA-Z_$][0-9a-zA-Z_$]*\\s*=\\s*[a-zA-Z_$][0-9a-zA-Z_$]*\\.jQuery\\s*,\\s*[a-zA-Z_$][0-9a-zA-Z_$]*\\s*=\\s*[a-zA-Z_$][0-9a-zA-Z_$]*\\.\\$"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "jquery:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("jQuery\\.event\\s*=\\s*\\{(?:[^{}]|\\{[^{}]*\\})*\\}"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "jquery:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("jQuery\\.Event\\s*=\\s*function\\s*\\(\\s*src\\s*\\)\\s*\\{"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "jquery:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("jQuery\\.removeEvent\\s*=\\s*function\\s*\\(\\s*elem\\s*,\\s*type\\s*,\\s*handle\\s*\\)\\s*\\{"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "jquery:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("jQuery\\.event\\.(?:special|fix|props)\\s*="),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "jquery:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("jQuery\\.(?:Animation|Tween)\\s*=\\s*function\\s*\\(\\s*elem\\s*,\\s*options\\s*,\\s*prop\\s*,\\s*end\\s*\\)\\s*\\{"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "jquery:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("jQuery\\.fx\\.(?:tick|timer|interval|start|stop)\\s*="),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "jquery:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("jQuery\\.easing\\s*=\\s*\\{\\s*(?:[^{}]|\\{[^{}]*\\})*\\}"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "jquery:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("jQuery\\.(?:ajax|get|post|getJSON|getScript)\\s*=\\s*function\\s*\\("),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "jquery:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("jQuery\\.ajaxTransport\\s*=\\s*function\\s*\\("),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "jquery:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("jQuery\\.(?:ajaxPrefilter|ajaxSetup|ajaxSettings)\\s*="),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
	metadata: {
		cpe: "cpe:2.3:a:jquery:jquery:*:*:*:*:*:*:*:*",
	},
} as const satisfies TechnologyDefinition;
