import type { TechnologyDefinition } from '../../types';

export const preactTechnologyDefinition = {
	id: "preact",
	name: "Preact",
	website: "https://preactjs.com",
	description: "Preact is a JavaScript library that describes itself as a fast 3kB alternative to React with the same ES6 API.",
	icon: "Preact.svg",
	categories: [
		"ui-library",
		"widgets-misc",
	],
	rules: [
		{
			id: "preact:scriptSrc:0",
			kind: "scriptSrc",
			pattern: new RegExp("(?:^|[\\/_-])preact(?:[.@/_-]|\\.min\\.js|\\.module\\.js)", "i"),
			description: "Script source URL contains a Preact package marker.",
		},
		{
			id: "preact:html:1",
			kind: "html",
			pattern: new RegExp("\\b(?:preact|preact-render-to-string|preact\\/compat|preact\\/jsx-runtime)\\b", "i"),
			confidence: 80,
			description: "Document HTML contains a Preact package/runtime marker.",
		},
		{
			id: "preact:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("(?:window\\.)?preact=\\{(?:[^}]+)\\}"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "preact:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("from\\s+[\"']preact\\/(?:jsx-runtime|dist\\/preact\\.module)[\"']"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "preact:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("__preactattr_[$_a-zA-Z0-9]+"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "preact:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("\\/(?:acit|ex(?:s|g|n|p|\\\\$)|rph|grid|ows|mnc|ntw|ine\\[ch\\]|zoo|\\\\^ord|itera)\\/i"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "preact:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("\\.replace\\(\\/xlink\\(H\\|:h\\)\\/,\\s*[\"']h[\"']\\)\\.replace\\(\\/sName\\$\\/,\\s*[\"']s[\"']\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "preact:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("['\"]\\/\\(PointerCapture\\)\\$\\|Capture\\$\\/i['\"]"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "preact:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("(?:\\.|\\[[\"']|\\[)__(?:v|k|e|b|u|i|d|h|P|m|s|f)\\b"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "preact:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("(?:\\.|\\[[\"']|\\[)__(?:H|h|N|P|u|f)\\b"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "preact:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("__component[$_a-zA-Z0-9]+"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "preact:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("(?:^|[^a-zA-Z0-9_$])render\\s*\\(\\s*h\\s*\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "preact:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("hydrate\\s*\\(\\s*h\\s*\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "preact:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("data-preact(?:-client|-ssr)[\"']"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "preact:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("preactroot[$_a-zA-Z0-9]+"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "preact:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("\\[\\$?\\$(?:ref|key)\\$"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "preact:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("__self\\$\\s*:\\s*true|__source\\$\\s*:\\s*\\{"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "preact:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("\\bdiff\\s*\\(\\s*dom\\s*,\\s*vnode\\s*,\\s*context\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "preact:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("options\\.__h\\s*&&\\s*options\\.__h\\s*\\([^)]+\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "preact:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("__c\\s*=\\s*!__c"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "preact:scriptContent:modern:18",
			kind: "scriptContent",
			pattern: new RegExp("function\\s+(?:useState|useReducer)\\s*\\([^)]*\\)\\s*\\{\\s*return\\s+__h\\s*\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "preact:scriptContent:modern:19",
			kind: "scriptContent",
			pattern: new RegExp("function\\s+useEffect\\s*\\([^)]*\\)\\s*\\{\\s*__h\\s*\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "preact:scriptContent:modern:20",
			kind: "scriptContent",
			pattern: new RegExp("class\\s+[A-Za-z_$][\\w$]*\\s+extends\\s+(?:preact\\.)?Component\\s*\\{"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "preact:scriptContent:modern:21",
			kind: "scriptContent",
			pattern: new RegExp("(?:prototype\\.|\\.prototype\\.)(?:componentDidMount|componentWillUnmount)\\s*=\\s*function\\s*\\(\\)\\s*\\{"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "preact:scriptContent:modern:22",
			kind: "scriptContent",
			pattern: new RegExp("(?:prototype\\.|\\.prototype\\.)(?:componentDidUpdate|shouldComponentUpdate)\\s*=\\s*function\\s*\\([^)]*\\)\\s*\\{"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "preact:scriptContent:modern:23",
			kind: "scriptContent",
			pattern: new RegExp("Fragment\\s*:\\s*\\{\\s*\\[\\$?\\$type\\]\\s*:\\s*[\"']fragment[\"']\\s*\\}"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "preact:scriptContent:modern:24",
			kind: "scriptContent",
			pattern: new RegExp("__c\\s*=\\s*null\\s*;\\s*__v\\s*=\\s*null"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "preact:scriptContent:modern:25",
			kind: "scriptContent",
			pattern: new RegExp("from\\s+[\"']preact\\/compat[\"']"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "preact:scriptContent:modern:26",
			kind: "scriptContent",
			pattern: new RegExp("alias:\\s*\\{\\s*[\"']react[\"']\\s*:\\s*[\"']preact\\/compat[\"']"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "preact:scriptContent:modern:27",
			kind: "scriptContent",
			pattern: new RegExp("alias:\\s*\\{\\s*[\"']react-dom[\"']\\s*:\\s*[\"']preact\\/compat[\"']"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "preact:scriptContent:modern:28",
			kind: "scriptContent",
			pattern: new RegExp("createPortal\\s*:\\s*function\\s*\\(\\s*vnode,\\s*parent\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "preact:scriptContent:modern:29",
			kind: "scriptContent",
			pattern: new RegExp("Suspense\\s*:\\s*function\\s*\\(\\s*\\{\\s*children"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "preact:scriptContent:modern:30",
			kind: "scriptContent",
			pattern: new RegExp("lazy\\s*:\\s*function\\s*\\(\\s*loader\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "preact:scriptContent:modern:31",
			kind: "scriptContent",
			pattern: new RegExp("from\\s+[\"']@preact\\/signals(?:-core)?[\"']"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "preact:scriptContent:modern:32",
			kind: "scriptContent",
			pattern: new RegExp("__value\\s*=\\s*value"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "preact:scriptContent:modern:33",
			kind: "scriptContent",
			pattern: new RegExp("__subscribers\\s*=\\s*new\\s+Set"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
	metadata: {
		oss: true,
	},
} as const satisfies TechnologyDefinition;
