import type { TechnologyDefinition } from '../../types';

export const qwikTechnologyDefinition = {
	id: "qwik",
	name: "Qwik",
	website: "https://qwik.dev",
	description: "A JavaScript framework for building web applications",
	categories: [
		"ui-library",
	],
	rules: [
		{
			id: "qwik:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("\\(QWIK\\s*=\\s*\\{\\s*_:\\s*\\[\\],\\s*r:\\s*\\[\\]\\}\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("\\$renderComponent\\s*=\\s*\\(\\s*\\w+\\s*,\\s*\\w+\\s*\\)\\s*=>"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("\\[\\s*\"q:container\"\\s*\\]"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("\\[\\s*\"q:slot\"\\s*\\]"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("\\[\\s*\"q:template\"\\s*\\]"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("\\$qrl\\s*=\\s*symbol\\$\\(\\s*[\"']qrl[\"']\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("qrlDEV\\s*=\\s*\\((?:[^()]*|\\([^()]*\\))*\\)\\s*=>"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("resolveResource\\$\\(\\s*resource\\s*,\\s*el\\s*,\\s*url\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("createContextId\\(\\s*[\"']qc-n[\"']\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("jsx\\s*=\\s*\\(\\s*type\\s*,\\s*props\\s*,\\s*key\\s*\\)\\s*=>"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("jsxs\\s*=\\s*\\(\\s*type\\s*,\\s*props\\s*,\\s*key\\s*\\)\\s*=>"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("\\$renderComponent\\(\\s*\\w+\\s*,\\s*\\{\\s*[\"']\\$type[\"']\\s*:"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("Slot\\s*=\\s*\\{\\s*\\$keyProps:\\s*\\[[\"']name[\"']\\]\\s*\\}"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("q:load=[\"']\\w+\\.js[\"']"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("on:qvisible\\$=[\"']\\w+[\"']"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("component\\$\\s*\\(\\s*\\(\\s*\\{\\s*[\"']\\$props[\"']\\s*\\}"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("useSignal\\(\\s*\\w+\\s*\\)\\s*\\{\\s*return\\s+useStore\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("useStore\\(\\s*\\{\\}\\s*\\)\\s*\\{\\s*return\\s+\\$"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik:scriptContent:modern:18",
			kind: "scriptContent",
			pattern: new RegExp("useTask\\$\\s*\\(\\s*\\{\\s*track\\s*:\\s*\\(\\s*\\)\\s*=>"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik:scriptContent:modern:19",
			kind: "scriptContent",
			pattern: new RegExp("useResource\\$\\s*\\(\\s*\\{\\s*track\\s*:\\s*\\(\\s*\\)\\s*=>"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik:scriptContent:modern:20",
			kind: "scriptContent",
			pattern: new RegExp("lazy\\$\\s*\\(\\s*\\(\\s*\\)\\s*=>\\s*import\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik:scriptContent:modern:21",
			kind: "scriptContent",
			pattern: new RegExp("noSerialize\\s*\\(\\s*value\\s*\\)\\s*\\{\\s*return"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik:scriptContent:modern:22",
			kind: "scriptContent",
			pattern: new RegExp("\\$\\$clickEvent\\s*=\\s*\\(\\s*\\w+\\s*\\)\\s*=>"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik:scriptContent:modern:23",
			kind: "scriptContent",
			pattern: new RegExp("\\$\\$inputEvent\\s*=\\s*\\(\\s*\\w+\\s*\\)\\s*=>"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik:scriptContent:modern:24",
			kind: "scriptContent",
			pattern: new RegExp("prefetch\\(\\s*url\\s*,\\s*\\{\\s*signal\\s*\\}\\s*\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik:scriptContent:modern:25",
			kind: "scriptContent",
			pattern: new RegExp("server\\$\\s*\\(\\s*async\\s*\\(\\s*\\{\\s*request\\s*\\}\\s*\\)\\s*=>"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik:scriptContent:modern:26",
			kind: "scriptContent",
			pattern: new RegExp("routeLoader\\$\\s*\\(\\s*\\(\\s*\\{\\s*params\\s*,\\s*url\\s*\\}\\s*\\)\\s*=>"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik:scriptContent:modern:27",
			kind: "scriptContent",
			pattern: new RegExp("routeAction\\$\\s*\\(\\s*async\\s*\\(\\s*\\{\\s*request\\s*\\}\\s*\\)\\s*=>"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik:scriptContent:modern:28",
			kind: "scriptContent",
			pattern: new RegExp("validator\\$\\s*\\(\\s*\\[\\s*\\w+\\s*\\]\\s*\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
