import type { TechnologyDefinition } from '../../types';

export const reactTechnologyDefinition = {
	id: "react",
	name: "React",
	website: "https://reactjs.org",
	description: "React is an open-source JavaScript library for building user interfaces with reusable components.",
	icon: "React.svg",
	categories: [
		"ui-library",
	],
	rules: [
		{
			id: "react:scriptSrc:0",
			kind: "scriptSrc",
			pattern: new RegExp("react(?:-with-addons)?[.-](\\d+(?:\\.\\d+)+)[^/]*\\.js"),
			version: {
				source: "match",
				group: 1,
			},
			description: "Script source URL matches a known technology marker.",
		},
		{
			id: "react:scriptSrc:1",
			kind: "scriptSrc",
			pattern: new RegExp("\\/([\\d\\.]+)\\/react(?:\\-dom)?(?:\\.production)?(?:\\.min)?\\.js"),
			version: {
				source: "match",
				group: 1,
			},
			description: "Script source URL matches a known technology marker.",
		},
		{
			id: "react:scriptSrc:2",
			kind: "scriptSrc",
			pattern: new RegExp("react(?:\\-dom)?(?:\\.production)?(?:\\.min)?\\.js"),
			description: "Script source URL matches a known technology marker.",
		},
		{
			id: "react:scriptSrc:3",
			kind: "scriptSrc",
			pattern: new RegExp("^react\\b.*\\.js"),
			description: "Script source URL matches a known technology marker.",
		},
		{
			id: "react:html:4",
			kind: "html",
			pattern: new RegExp("<[^>]+data-react"),
			description: "HTML contains a known technology signature.",
		},
		{
			id: "react:dom:5",
			kind: "dom",
			selector: "[data-reactroot], [data-reactid], [data-react-helmet], [data-react-checksum]",
			description: "DOM contains React-specific hydration or metadata attributes.",
		},
		{
			id: "react:dom:6",
			kind: "dom",
			selector: "div[id='react-root'], div[id^='react-root-']",
			description: "DOM contains a conventional React root element id.",
		},
		{
			id: "react:jsGlobal:7",
			kind: "jsGlobal",
			property: "React.version",
			valuePattern: new RegExp("^([\\d\\.]+)$"),
			version: {
				source: "match",
				group: 1,
			},
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "react:jsGlobal:8",
			kind: "jsGlobal",
			property: "ReactOnRails",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "react:jsGlobal:9",
			kind: "jsGlobal",
			property: "__REACT_ON_RAILS_EVENT_HANDLERS_RAN_ONCE__",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "react:meta:10",
			kind: "meta",
			key: "description",
			valuePattern: new RegExp("^Web site created using create-react-app$", "i"),
			description: "Meta tag matches a known technology marker.",
		},
		{
			id: "react:dom:12",
			kind: "dom",
			selector: "div[id*='appReactRoot']",
			description: "DOM selector matches a known technology marker.",
		},
		{
			id: "react:dom:13",
			kind: "dom",
			selector: "div[id='react-root'], div[id^='react-root-']",
			description: "DOM contains a conventional React root element id.",
		},
		{
			id: "react:dom:15",
			kind: "dom",
			selector: "style[id*='react-tooltip-core-styles']",
			description: "DOM selector matches a known technology marker.",
		},
		{
			id: "react:jsGlobal:16",
			kind: "jsGlobal",
			property: "__isReactFizzContext",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "react:meta:17",
			kind: "meta",
			key: "og:image",
			valuePattern: new RegExp("%REACT_APP_SEO_IMAGE_URL%", "i"),
			description: "Meta tag matches a known technology marker.",
		},
		{
			id: "react:meta:18",
			kind: "meta",
			key: "description",
			valuePattern: new RegExp("^web site created using create-react-app$", "i"),
			description: "Meta tag matches a known technology marker.",
		},
		{
			id: "react:dom:19",
			kind: "dom",
			selector: "div[id='react-root'], div[id^='react-root-'], div[id*='appReactRoot'], style[id*='react-tooltip-core-styles']",
			description: "DOM contains React-specific root or library style markers.",
		},
		{
			id: "react:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("__reactFiber[$\\w]+"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("__reactContainer[$\\w]+"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("Symbol\\.for\\(['\"]react\\.[\\w.]+['\"]\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("\\b(?:__reactEventHandlers|__reactProps)[$\\w]+"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("\\.createRoot\\([\\s\\S]{1,50}?\\.render\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("hydrateRoot\\([\\s\\S]{1,50}?\\.render\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("\\breturn\\s+ReactDOM\\."),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("(?:document|container|root|element)\\.querySelector\\(['\"]\\[data-reactroot\\]['\"]\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("startTransition\\s*\\(\\s*\\(\\s*\\)\\s*=>\\s*\\{"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("\\.createBlockingRoot\\s*\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("import\\s*\\{\\s*jsx\\s*(?:as\\s*_jsx)?\\s*\\}\\s*from\\s*[\"']react\\/jsx-runtime[\"']"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("import\\s*\\{[^}]*jsxDEV[^}]*\\}\\s*from\\s*[\"']react\\/jsx-dev-runtime[\"']"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("_jsxFileName\\s*:\\s*[\"'][^\"']+[\"']"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("import\\s*\\{[^}]*jsxs?[^}]*\\}\\s*from\\s*[\"']react\\/jsx-runtime[\"']"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("\\[data-reactroot\\]"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("data-react-hydrated"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("__reactError[$\\w]+"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react:scriptContent:modern:18",
			kind: "scriptContent",
			pattern: new RegExp("__reactEventHandlers[$\\w]+"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react:scriptContent:modern:19",
			kind: "scriptContent",
			pattern: new RegExp("__scheduleUpdate"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react:scriptContent:modern:20",
			kind: "scriptContent",
			pattern: new RegExp("__reactFiber[$_a-zA-Z0-9]+"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react:scriptContent:modern:21",
			kind: "scriptContent",
			pattern: new RegExp("ReactCurrentBatchConfig\\s*=\\s*\\{"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react:scriptContent:modern:22",
			kind: "scriptContent",
			pattern: new RegExp("Scheduler\\.unstable_scheduleCallback"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react:scriptContent:modern:23",
			kind: "scriptContent",
			pattern: new RegExp("__reactEvents[$_a-zA-Z0-9]+"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react:scriptContent:modern:24",
			kind: "scriptContent",
			pattern: new RegExp("reactEventHandlers[$_a-zA-Z0-9]+"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
	metadata: {
		cpe: "cpe:2.3:a:facebook:react:*:*:*:*:*:*:*:*",
	},
} as const satisfies TechnologyDefinition;
