import type { TechnologyDefinition } from '../../types';

export const solidTechnologyDefinition = {
	id: "solid",
	name: "Solid",
	website: "https://www.solidjs.com/",
	description: "A declarative JavaScript library for building user interfaces",
	categories: [
		"ui-library",
	],
	rules: [
		{
			id: "solid:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("\\$PROXY\\s*=\\s*Symbol\\(\\s*[\"']solid-proxy[\"']\\s*\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("_\\$HY\\s*=\\s*\\{\\s*events:\\s*\\["),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("\\[\\s*\\$\\$\\s*=\\s*\\w+\\s*,\\s*\\$\\$_\\s*=\\s*\\w+\\s*\\]\\s*=\\s*createSignal\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("createEffect\\(\\s*\\(\\s*\\)\\s*=>\\s*\\{\\s*untrack\\(\\s*\\(\\s*\\)\\s*=>"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("createMemo\\(\\s*\\(\\s*\\)\\s*=>\\s*\\w+\\(\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("\\$\\$root\\s*=\\s*\\{\\s*disposables:\\s*new Set\\s*\\}"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("\\$\\$PROXY\\s*=\\s*Symbol\\(\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("insert\\s*\\(\\s*\\w+\\s*,\\s*\\(\\s*\\)\\s*=>\\s*\\w+\\.assign\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("_tmpl\\$\\s*=\\s*\\[\\s*\\w+\\(\\s*[\"'][^\"']+[\"']\\s*\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("createComponent\\(\\s*\\w+\\s*,\\s*\\{\\s*get"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("\\[\\s*\"data-hk\"\\s*\\]\\s*=\\s*\\_\\$HY"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("\\[\\s*\"data-dk\"\\s*\\]\\s*=\\s*\\_\\$HY"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("function\\s+createSignal\\s*\\(\\s*value\\s*,\\s*options\\s*\\)\\s*\\{\\s*const\\s+[a-zA-Z_$][0-9a-zA-Z_$]*\\s*=\\s*\\{\\s*value\\s*\\}"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("function\\s+createEffect\\s*\\(\\s*fn\\s*,\\s*value\\s*\\)\\s*\\{\\s*runEffect"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("createResource\\(\\s*source\\s*,\\s*fetcher\\s*,\\s*options\\s*\\)\\s*\\{"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("onMount\\(\\s*\\(\\s*\\)\\s*=>\\s*\\{"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("onCleanup\\(\\s*\\(\\s*\\)\\s*=>\\s*\\{"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("For\\s*=\\s*\\{\\s*each:\\s*\\w+\\s*,\\s*fallback:\\s*\\w+\\s*\\}"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid:scriptContent:modern:18",
			kind: "scriptContent",
			pattern: new RegExp("Show\\s*=\\s*\\{\\s*when:\\s*\\w+\\s*,\\s*fallback:\\s*\\w+\\s*\\}"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid:scriptContent:modern:19",
			kind: "scriptContent",
			pattern: new RegExp("function\\s+\\w+\\s*\\(\\s*props\\s*\\)\\s*\\{\\s*return\\s+createComponent\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid:scriptContent:modern:20",
			kind: "scriptContent",
			pattern: new RegExp("splitProps\\(\\s*props\\s*,\\s*\\[[^\\]]+\\]\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid:scriptContent:modern:21",
			kind: "scriptContent",
			pattern: new RegExp("mergeProps\\(\\s*defaults\\s*,\\s*props\\s*\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid:scriptContent:modern:22",
			kind: "scriptContent",
			pattern: new RegExp("\\$template\\$\\s*=\\s*\\w+\\(\\s*[\"'][^\"']+[\"']\\s*\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid:scriptContent:modern:23",
			kind: "scriptContent",
			pattern: new RegExp("lazy\\(\\s*\\(\\s*\\)\\s*=>\\s*import\\([^)]+\\)\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid:scriptContent:modern:24",
			kind: "scriptContent",
			pattern: new RegExp("_\\$template\\s*=\\s*\\[\\s*[\"'][^\"']+[\"']"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid:scriptContent:modern:25",
			kind: "scriptContent",
			pattern: new RegExp("loadResource\\(\\s*key\\s*,\\s*fetcher\\s*\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid:scriptContent:modern:26",
			kind: "scriptContent",
			pattern: new RegExp("createStore\\(\\s*\\{\\s*\\w+:\\s*[^}]+\\}\\s*\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid:scriptContent:modern:27",
			kind: "scriptContent",
			pattern: new RegExp("produce\\(\\s*\\w+\\s*,\\s*draft\\s*=>"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid:scriptContent:modern:28",
			kind: "scriptContent",
			pattern: new RegExp("reconcile\\(\\s*\\w+\\s*,\\s*\\{\\s*key:\\s*\\w+\\s*\\}\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid:scriptContent:modern:29",
			kind: "scriptContent",
			pattern: new RegExp("unwrap\\(\\s*\\w+\\s*,\\s*\\{\\s*proxy:\\s*true\\s*\\}\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
