import type { TechnologyDefinition } from '../../types';

export const vueJsTechnologyDefinition = {
	id: "vue-js",
	name: "Vue.js",
	website: "https://vuejs.org",
	description: "Vue.js is an open-source model–view–viewmodel JavaScript framework for building user interfaces and single-page applications.",
	icon: "vue.svg",
	categories: [
		"ui-library",
	],
	rules: [
		{
			id: "vue-js:scriptSrc:0",
			kind: "scriptSrc",
			pattern: new RegExp("vue[.-]([\\d.]*\\d)[^/]*\\.js"),
			version: {
				source: "match",
				group: 1,
			},
			description: "Script source URL matches a known technology marker.",
		},
		{
			id: "vue-js:scriptSrc:1",
			kind: "scriptSrc",
			pattern: new RegExp("(?:\\/([\\d.]+))?\\/vue(?:\\.min)?\\.js"),
			version: {
				source: "match",
				group: 1,
			},
			description: "Script source URL matches a known technology marker.",
		},
		{
			id: "vue-js:stylesheetContent:2",
			kind: "stylesheetContent",
			pattern: new RegExp("\\.vue-notification-group"),
			description: "Stylesheet content contains a bounded technology signature.",
		},
		{
			id: "vue-js:html:3",
			kind: "html",
			pattern: new RegExp("<[^>]+\\sdata-v(?:ue)?-"),
			description: "HTML contains a known technology signature.",
		},
		{
			id: "vue-js:dom:4",
			kind: "dom",
			selector: ".vue-app",
			description: "DOM selector matches a known technology marker.",
		},
		{
			id: "vue-js:jsGlobal:5",
			kind: "jsGlobal",
			property: "Vue",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "vue-js:jsGlobal:6",
			kind: "jsGlobal",
			property: "Vue.version",
			valuePattern: new RegExp("^(.+)$"),
			version: {
				source: "match",
				group: 1,
			},
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "vue-js:jsGlobal:7",
			kind: "jsGlobal",
			property: "VueRoot",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "vue-js:jsGlobal:8",
			kind: "jsGlobal",
			property: "__VUE_HOT_MAP__",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "vue-js:jsGlobal:9",
			kind: "jsGlobal",
			property: "__VUE__",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "vue-js:jsGlobal:10",
			kind: "jsGlobal",
			property: "vueDLL",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "vue-js:html:11",
			kind: "html",
			pattern: new RegExp("<(?!svg)[^>]+\\sdata-v(?:ue)?-"),
			description: "HTML contains a known technology signature.",
		},
		{
			id: "vue-js:dom:12",
			kind: "dom",
			selector: "link[href*='docsify/themes/vue.css']",
			description: "DOM selector matches a known technology marker.",
		},
		{
			id: "vue-js:dom:13",
			kind: "dom",
			selector: "meta[data-vue-meta]",
			description: "DOM selector matches a known technology marker.",
		},
		{
			id: "vue-js:dom:14",
			kind: "dom",
			selector: "div[class*='vue-scroll-picker-group'] > div[class*='vue-scroll-picker']",
			description: "DOM selector matches a known technology marker.",
		},
		{
			id: "vue-js:dom:15",
			kind: "dom",
			selector: "div[class*='Vue-Toastification__container']",
			description: "DOM selector matches a known technology marker.",
		},
		{
			id: "vue-js:dom:16",
			kind: "dom",
			selector: ".vue-app, link[href*='docsify/themes/vue.css'], meta[data-vue-meta], div[class*='vue-scroll-picker-group'] > div[class*='vue-scroll-picker'], div[class*='Vue-Toastification__container']",
			description: "DOM selector matches a known technology marker.",
		},
		{
			id: "vue-js:jsGlobal:17",
			kind: "jsGlobal",
			property: "webpackChunkweb_tool_vue",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "vue-js:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("__v_isRef=!0"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-js:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("__v_isReactive=!0"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-js:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("__v_raw"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-js:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("\\.__ob__\\b"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-js:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("__VUE_SSR_CONTEXT__"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-js:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("\\$el\\.__vue__\\s*=\\s*\\w+"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-js:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("getVueComponent\\s*:"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-js:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("\\$vnode(?:\\.ssrContext)?"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-js:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("\\[\\$\\$\\]"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-js:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("new Vue\\(\\{(?:[^{}]|{[^{}]*})*el:[\"'][^\"']+[\"']"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-js:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("const\\s+[_$a-zA-Z][\\w$]*\\s*=\\s*createApp\\s*\\(\\s*\\{[^}]*\\}\\s*\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-js:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("_createVNode\\(\\s*(?:[\"'][^\"']+[\"']|\\w+)\\s*,\\s*(?:null|\\{[^}]*\\}|\\[[^\\]]*\\])"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-js:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("createBlock\\(\\s*[\\w$]+\\s*,\\s*(?:null|\\{[^}]*\\}|\\[[^\\]]*\\])"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-js:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("openBlock\\(\\),createElementBlock\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-js:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("createBaseVNode\\(\\s*[\"'][^\"']+[\"']"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-js:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("withDirectives\\(\\s*createVNode\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-js:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("vShow,\\[\\[\\$props\\.show\\]\\]"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-js:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("\\$slots\\s*\\.\\s*default\\s*\\?\\s*renderList\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-js:scriptContent:modern:18",
			kind: "scriptContent",
			pattern: new RegExp("renderSlot\\(\\s*_ctx\\.\\$slots\\s*,\\s*[\"']default[\"']"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-js:scriptContent:modern:19",
			kind: "scriptContent",
			pattern: new RegExp("defineComponent\\(\\s*\\{(?:[^{}]|{[^{}]*})*setup\\s*\\(\\s*\\{\\s*props\\s*\\}"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-js:scriptContent:modern:20",
			kind: "scriptContent",
			pattern: new RegExp("props:\\s*\\{(?:[^{}]|{[^{}]*})*type:\\s*(?:String|Number|Boolean|Array|Object|Function)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-js:scriptContent:modern:21",
			kind: "scriptContent",
			pattern: new RegExp("emits:\\s*\\{(?:[^{}]|{[^{}]*})*\\}|emits:\\s*\\[(?:[^\\[\\]]*)\\]"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
