import type {
	ObservationStopReason as ContentObservationStopReason,
	PageSignalPollingState as ObservationSessionState,
} from '../content/observed-page-signals';
import type { DetectionSessionKey } from './detection-session';
import type { AnalysisStatus, SiteAnalysis } from '../detection/types';
import type { DetectionReplayTrace } from '../pipeline';
import type { ObservationBatch, ObservationBatchControllerStats } from '../observations';
import type { AppResult } from '../shared/result';

/**
 * Analysis modes accepted by the popup-to-background request.
 *
 * `cache-first` lets the background return a stored `SiteAnalysis` for the
 * active origin. `refresh` skips that lookup and collects the page again.
 */
export const ANALYSIS_MODES = ['cache-first', 'refresh'] as const;

/** Request mode for active-tab analysis. */
export type AnalyzeActiveTabMode = typeof ANALYSIS_MODES[number];

/**
 * Observation choices accepted by the background API.
 *
 * Every value except `none` asks the content script to keep watching the page
 * after event analysis. The same bounded observation policy is used today for
 * `while-popup-open` and `bounded`; callers use the names to describe intent,
 * while the lifecycle policy owns the actual duration and event-storm limits.
 */
export const OBSERVATION_MODES = ['none', 'while-popup-open', 'bounded'] as const;

/** Request value that controls whether live page watching starts. */
export type ActiveTabObservationMode = typeof OBSERVATION_MODES[number];


/** Progressive enrichment states returned with an analysis response. */
export const ANALYSIS_ENRICHMENT_STATUSES = ['not-needed', 'pending', 'complete', 'failed', 'timed-out', 'skipped'] as const;

/** Whether deeper evidence collection is pending, complete, failed, timed out, unnecessary, or skipped. */
export type AnalysisEnrichmentStatus = typeof ANALYSIS_ENRICHMENT_STATUSES[number];

/** User-visible enrichment state for progressive active-tab detection. */
export type AnalysisEnrichmentState = {
	/** Current enrichment lifecycle state for this analysis response. */
	status: AnalysisEnrichmentStatus;
	/** Millisecond timestamp when enrichment completed, when known. */
	completedAt?: number;
	/** Short machine-readable reason for skipped, terminal, or unnecessary enrichment. */
	reason?: string;
};

/** Cache states returned to the popup after active-tab analysis. */
export const ANALYSIS_CACHE_STATUSES = ['hit', 'miss', 'bypassed'] as const;

/** Cache state returned with an active-tab analysis response. */
export type AnalysisCacheStatus = typeof ANALYSIS_CACHE_STATUSES[number];

/**
 * Request sent by the popup when it asks the background to analyze the active tab.
 */
export type AnalyzeActiveTabInput = {
	/** Whether the background may reuse stored analysis for the active origin. */
	mode: AnalyzeActiveTabMode;
	/** Whether the content script should watch the page after a fresh analysis. */
	observe: ActiveTabObservationMode;
};

/**
 * Minimal active-tab identity needed before popup analysis starts.
 *
 * The popup uses this record to choose a storage snapshot first, then asks the
 * background to synchronize the page. Keeping identity separate from analysis
 * avoids loading the detector registry just to decide which cached result can be
 * painted during popup startup.
 */
export type ActiveTabIdentity = {
	/** Browser tab id that owns the active top-frame page. */
	readonly tabId: number;
	/** Frame id used by current detection sessions; top frame is always `0`. */
	readonly frameId: number;
	/** Full active URL used only for the legacy analysis-cache fallback. */
	readonly url: string;
	/** Hostname shown in the popup before a stored analysis is rendered. */
	readonly hostname: string;
	/** Stable storage partition for origin-level snapshot lookup. */
	readonly originHash: string;
	/** Stable storage partition for exact active URL comparisons. */
	readonly urlHash: string;
	/** Whether persistent reads and writes should be skipped for this popup. */
	readonly incognito: boolean;
};

/**
 * Stable handle for the observation session created by one popup analysis.
 *
 * The popup keeps this handle so refresh and stop actions target the same tab
 * and document that started observation, even if the user activates another tab
 * before cleanup or a manual stop.
 */
export type ObservationSessionTarget = {
	/** Tab that owns the content-script observation session. */
	tabId: number;
	/** Session id generated by the background and accepted by the content script. */
	sessionId: string;
	/** Document URL that the session was created to observe. */
	expectedUrl: string;
	/** Whether persistent analysis and replay storage must be skipped. */
	incognito?: boolean;
};

/** Request that targets a specific existing observation session. */
export type ObservationSessionTargetInput = ObservationSessionTarget;

/**
 * Request for reading the newest persisted analysis for a known session target.
 *
 * Background enrichment can finish after the content observer expires or after the
 * Manifest V3 service worker restarts. The popup sends its rendered timestamp so
 * the background can answer only when storage contains a newer snapshot for the
 * same document target.
 */
export type ObservationSessionAnalysisSnapshotInput = ObservationSessionTarget & {
	/** Millisecond timestamp of the newest analysis already rendered by the popup. */
	afterAnalyzedAt: number;
};

/** Request for replay history tied to the analysis currently visible in the popup. */
export type ReplayTraceHistoryInput = {
	/** Analysis URL that owns the replay history record. */
	readonly url: string;
};

/**
 * Response returned to the popup after active-tab analysis.
 *
 * `analysis` remains the stable rendering and cache shape. `replayTrace` and
 * `replayHistory` carry redacted pipeline details that let the popup explain
 * detections without widening `SiteAnalysis` itself.
 */
export type AnalyzeActiveTabOutput = {
	/** Normalized detector output safe for popup rendering and cache storage. */
	analysis: SiteAnalysis;
	/** Cache metadata that explains whether stored output was reused. */
	cache: {
		/** Whether the analysis came from cache, missed cache, or bypassed cache. */
		status: AnalysisCacheStatus;
		/** Storage key used for the origin-level cache record. */
		key: string;
		/** Millisecond timestamp when the cache record should be treated as stale. */
		expiresAt?: number;
	};
	/** Live observation state when the fresh analysis started page watching. */
	session?: ObservationSessionState;
	/** Stable session handle the popup should use for refresh, stop, and cleanup. */
	sessionTarget?: ObservationSessionTarget;
	/**
	 * Redacted pipeline trace for fresh or cached analysis runs.
	 *
	 * Older cache entries can omit this field when they predate replay trace
	 * retention. Callers should treat it as optional explanation data rather than
	 * part of the stable `SiteAnalysis` envelope.
	 */
	replayTrace?: DetectionReplayTrace;
	/** Bounded newest-first replay traces saved for the active origin. */
	replayHistory?: readonly DetectionReplayTrace[];
	/** Whether deeper evidence collection is still running or already reflected. */
	enrichment?: AnalysisEnrichmentState;
};

/** Reason a content-script observation session stopped. */
export type ObservationStopReason = ContentObservationStopReason;

/**
 * Storage target a content script can use after the background identifies the tab.
 *
 * Content scripts cannot ask Chrome for their own `tabId`, so the background
 * sends the durable storage identity when it starts observation. Once the target
 * is known, content can publish status revisions without depending on service
 * worker memory.
 */
export type ContentPageSessionSnapshotTarget = {
	/** Exact session key shared by content and background snapshot writers. */
	readonly key: DetectionSessionKey;
	/** Full document URL used by the public analysis envelope. */
	readonly url: string;
	/** Stable hash of the exact document URL for popup snapshot filtering. */
	readonly urlHash: string;
	/** Hostname shown by the popup before richer analysis is available. */
	readonly hostname: string;
	/** Private browsing sessions skip durable snapshot writes. */
	readonly incognito?: boolean;
};

/**
 * Request sent from the background to the content script to start page watching.
 */
export type BeginObservationSessionInput = {
	/** Unique id generated by the background for this observation session. */
	sessionId: string;
	/** URL the background expects the content script to still be observing. */
	expectedUrl: string;
	/** Durable snapshot target used by content-owned observation status writes. */
	snapshotTarget?: ContentPageSessionSnapshotTarget;
	/** Limits that keep content-script observation bounded. */
	policy: {
		/** How long the content script should keep watching the page. */
		durationMs: number;
		/** How often pending DOM changes may be scanned. */
		throttleMs: number;
		/** Maximum queued nodes before falling back to a full document scan. */
		maxPendingNodes: number;
		/** Maximum observed mutations before the session stops itself. */
		maxMutations: number;
	};
};

/** Content-script response for collecting the active document as observations. */
export type CollectObservationBatchOutput = {
	/** Bounded normalized observations emitted from the current document scan. */
	batch: ObservationBatch;
};

/** Content-script response for flushing queued late observation events. */
export type FlushObservationBatchOutput = {
	/** Next bounded batch when late evidence-bearing facts are queued. */
	batch?: ObservationBatch;
	/** Queue and drop counters from the content-side batch controller. */
	stats: ObservationBatchControllerStats;
	/** Observation session state after pending DOM mutation scans are flushed. */
	session: ObservationSessionState;
};

/** Serializable HTML pattern probe sent to the content script. */
export type HtmlProbe = {
	/** Technology that owns the original HTML rule. */
	technologyId: string;
	/** Index of the rule inside that technology's rule list. */
	ruleIndex: number;
	/** Regular expression source without slashes. */
	source: string;
	/** Regular expression flags, such as `i`. */
	flags: string;
};

/**
 * Request sent from the background to the content script for event observation capture.
 *
 * The content collector still uses the older DOM snapshot reader internally
 * because that is the safest way to read document facts in one synchronous pass.
 * The RPC response is early normalized observations.
 */
export type CollectPageSignalsInput = {
	/** Collection tier represented by this request. */
	tier?: 'initial' | 'enrichment';
	/** Whether the content script should include bounded page HTML text. */
	includeHtml?: boolean;
	/** Whether visible text should be collected for text rules. */
	includeText?: boolean;
	/** Whether inline script text should be collected for script-content rules. */
	includeScriptContent?: boolean;
	/** Whether inline and accessible stylesheet text should be collected for stylesheet-content rules. */
	includeStylesheetContent?: boolean;
	/** Whether localStorage and sessionStorage keys should be collected. */
	includeStorageKeys?: boolean;
	/** DOM selectors the content script should check for detector rules. */
	selectorProbeList: string[];
	/** HTML regex probes serialized for the content script. */
	htmlProbeList?: HtmlProbe[];
	/** Optional debug id used only to correlate summary timing logs. */
	timingTraceId?: string;
};

/** Popup-to-background API exposed through the messaging adapter. */
export interface BackgroundApi {
	/** Return aggregate cache status for the extension. */
	getAnalysisStatus(): Promise<AppResult<AnalysisStatus>>;
	/** Return active-tab identity without collecting or analyzing page data. */
	getActiveTabIdentity(): Promise<AppResult<ActiveTabIdentity>>;
	/** Analyze the active tab and optionally start a content-script observation session. */
	analyzeActiveTab(input: AnalyzeActiveTabInput): Promise<AppResult<AnalyzeActiveTabOutput>>;
	/** Re-analyze a known observation session when its queued page facts are dirty. */
	refreshObservationSession(input: ObservationSessionTargetInput): Promise<AppResult<AnalyzeActiveTabOutput>>;
	/** Return the newest persisted analysis for a known session when storage has advanced. */
	getObservationSessionLatestAnalysis(input: ObservationSessionAnalysisSnapshotInput): Promise<AppResult<AnalyzeActiveTabOutput>>;
	/** Stop a known content-script observation session. */
	stopObservationSession(input: ObservationSessionTargetInput): Promise<AppResult<ObservationSessionState>>;
	/** Read a known content-script observation session state. */
	getObservationSessionState(input: ObservationSessionTargetInput): Promise<AppResult<ObservationSessionState>>;
	/** Return bounded replay history for the analysis URL already visible in the popup. */
	getReplayTraceHistory(input: ReplayTraceHistoryInput): Promise<AppResult<readonly DetectionReplayTrace[]>>;
}

/** Background-to-content API exposed through the content-script messaging adapter. */
export interface ContentApi {
	/** Collect the current content script document as normalized observations. */
	collectObservationBatch(input: CollectPageSignalsInput): Promise<AppResult<CollectObservationBatchOutput>>;
	/** Start watching late-added scripts, links, styles, and metadata. */
	beginObservationSession(input: BeginObservationSessionInput): Promise<AppResult<ObservationSessionState>>;
	/** Stop the current observation session manually. */
	stopObservationSession(): Promise<AppResult<ObservationSessionState>>;
	/** Flush late normalized observations queued by DOM and resource observers. */
	flushObservationBatch(): Promise<AppResult<FlushObservationBatchOutput>>;
	/** Return the current observation session state. */
	getObservationSessionState(): Promise<AppResult<ObservationSessionState>>;
}
