import type {
	ObservationStopReason as ContentObservationStopReason,
	PageSignalPollingState as ObservationSessionState,
} from '../content/observed-page-signals';
import type { AnalysisStatus, PageSignals, SiteAnalysis } from '../detection/types';
import type { AppResult } from '../shared/result';

/**
 * Analysis modes accepted by the popup-to-background request.
 *
 * `cache-first` lets the background return a stored `SiteAnalysis` for the
 * active origin. `refresh` skips that lookup and collects the page again.
 */
export const ANALYSIS_MODES = ['cache-first', 'refresh'] as const;

/** Request mode for active-tab analysis. */
export type AnalyzeActiveTabMode = typeof ANALYSIS_MODES[number];

/**
 * Observation choices accepted by the background API.
 *
 * Phase 2 keeps the current behavior: every value except `none` asks the
 * content script to watch the page after fresh analysis. A later lifecycle phase
 * can give `bounded` separate behavior without changing the request field.
 */
export const OBSERVATION_MODES = ['none', 'while-popup-open', 'bounded'] as const;

/** Request value that controls whether live page watching starts. */
export type ActiveTabObservationMode = typeof OBSERVATION_MODES[number];

/** Cache states returned to the popup after active-tab analysis. */
export const ANALYSIS_CACHE_STATUSES = ['hit', 'miss', 'bypassed'] as const;

/** Cache state returned with an active-tab analysis response. */
export type AnalysisCacheStatus = typeof ANALYSIS_CACHE_STATUSES[number];

/**
 * Request sent by the popup when it asks the background to analyze the active tab.
 */
export type AnalyzeActiveTabInput = {
	/** Whether the background may reuse stored analysis for the active origin. */
	mode: AnalyzeActiveTabMode;
	/** Whether the content script should watch the page after a fresh analysis. */
	observe: ActiveTabObservationMode;
};

/**
 * Response returned to the popup after active-tab analysis.
 *
 * This is the UI-facing result shape. Future evidence or replay data can be
 * added behind storage or detector seams, but the popup still receives this
 * normalized `SiteAnalysis` until a deliberate UI migration changes it.
 */
export type AnalyzeActiveTabOutput = {
	/** Normalized detector output safe for popup rendering and cache storage. */
	analysis: SiteAnalysis;
	/** Cache metadata that explains whether stored output was reused. */
	cache: {
		/** Whether the analysis came from cache, missed cache, or bypassed cache. */
		status: AnalysisCacheStatus;
		/** Storage key used for the origin-level cache record. */
		key: string;
		/** Millisecond timestamp when the cache record should be treated as stale. */
		expiresAt?: number;
	};
	/** Live observation state when the fresh analysis started page watching. */
	session?: ObservationSessionState;
};

/** Reason a content-script observation session stopped. */
export type ObservationStopReason = ContentObservationStopReason;

/**
 * Request sent from the background to the content script to start page watching.
 */
export type BeginObservationSessionInput = {
	/** Unique id generated by the background for this observation session. */
	sessionId: string;
	/** URL the background expects the content script to still be observing. */
	expectedUrl: string;
	/** Limits that keep content-script observation bounded. */
	policy: {
		/** How long the content script should keep watching the page. */
		durationMs: number;
		/** How often pending DOM changes may be scanned. */
		throttleMs: number;
		/** Maximum queued nodes before falling back to a full document scan. */
		maxPendingNodes: number;
		/** Maximum observed mutations before the session stops itself. */
		maxMutations: number;
	};
};

/** Serializable HTML pattern probe sent to the content script. */
export type HtmlProbe = {
	/** Technology that owns the original HTML rule. */
	technologyId: string;
	/** Index of the rule inside that technology's rule list. */
	ruleIndex: number;
	/** Regular expression source without slashes. */
	source: string;
	/** Regular expression flags, such as `i`. */
	flags: string;
};

/**
 * Request sent from the background to the content script for page signal capture.
 */
export type CollectPageSignalsInput = {
	/** Whether the content script should include bounded page HTML text. */
	includeHtml?: boolean;
	/** DOM selectors the content script should check for detector rules. */
	selectorProbeList: string[];
	/** HTML regex probes serialized for the content script. */
	htmlProbeList?: HtmlProbe[];
};

/** Popup-to-background API exposed through the messaging adapter. */
export interface BackgroundApi {
	/** Return aggregate cache status for the extension. */
	getAnalysisStatus(): Promise<AppResult<AnalysisStatus>>;
	/** Analyze the active tab and optionally start a content-script observation session. */
	analyzeActiveTab(input: AnalyzeActiveTabInput): Promise<AppResult<AnalyzeActiveTabOutput>>;
	/** Re-analyze the active tab when its content-script observation session is dirty. */
	refreshActiveObservationSession(): Promise<AppResult<AnalyzeActiveTabOutput>>;
	/** Stop the active tab's content-script observation session. */
	stopActiveObservationSession(): Promise<AppResult<ObservationSessionState>>;
	/** Read the active tab's current content-script observation state. */
	getActiveObservationSessionState(): Promise<AppResult<ObservationSessionState>>;
}

/** Background-to-content API exposed through the content-script messaging adapter. */
export interface ContentApi {
	/** Collect bounded page signals from the current content script document. */
	collectPageSignals(input: CollectPageSignalsInput): Promise<AppResult<PageSignals>>;
	/** Start watching late-added scripts, links, styles, and metadata. */
	beginObservationSession(input: BeginObservationSessionInput): Promise<AppResult<ObservationSessionState>>;
	/** Stop the current observation session manually. */
	stopObservationSession(): Promise<AppResult<ObservationSessionState>>;
	/** Return the current observation session state. */
	getObservationSessionState(): Promise<AppResult<ObservationSessionState>>;
}
