import type { TechnologyDefinition } from '../../types';

export const agGridTechnologyDefinition = {
	id: "ag-grid",
	name: "AG Grid",
	website: "https://www.ag-grid.com/",
	description: "The best JavaScript Data Table for building Enterprise Applications",
	categories: [
		"table-library",
	],
	rules: [
		{
			id: "ag-grid:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("ag-grid-community"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ag-grid:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("ag-grid-enterprise"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ag-grid:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("ag-grid-react"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ag-grid:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("ag-grid-angular"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ag-grid:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("ag-grid-vue"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ag-grid:resourceUrl:modern:5",
			kind: "resourceUrl",
			pattern: new RegExp("ag-grid"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "ag-grid:html:modern:6",
			kind: "html",
			pattern: new RegExp("class=\"ag-root-wrapper\""),
			confidence: 65,
			description: "Document HTML matches a modern tooling marker.",
		},
		{
			id: "ag-grid:html:modern:7",
			kind: "html",
			pattern: new RegExp("class=\"ag-theme-"),
			confidence: 65,
			description: "Document HTML matches a modern tooling marker.",
		},
		{
			id: "ag-grid:html:modern:8",
			kind: "html",
			pattern: new RegExp("ag-header-cell"),
			confidence: 65,
			description: "Document HTML matches a modern tooling marker.",
		},
		{
			id: "ag-grid:html:modern:9",
			kind: "html",
			pattern: new RegExp("ag-body-viewport"),
			confidence: 65,
			description: "Document HTML matches a modern tooling marker.",
		},
		{
			id: "ag-grid:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("AgGridReact"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ag-grid:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("AgGridVue"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ag-grid:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("AgGridAngular"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ag-grid:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("gridOptions\\s*="),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ag-grid:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("columnDefs\\s*:"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
