import type { TechnologyDefinition } from '../../types';

export const tanstackVirtualTechnologyDefinition = {
	id: "tanstack-virtual",
	name: "TanStack Virtual",
	website: "https://tanstack.com/virtual",
	description: "Headless UI for virtualizing scrollable elements",
	categories: [
		"table-library",
	],
	rules: [
		{
			id: "tanstack-virtual:resourceUrl:modern:0",
			kind: "resourceUrl",
			pattern: new RegExp("@tanstack\\/virtual-core[.\\-@/]"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "tanstack-virtual:resourceUrl:modern:1",
			kind: "resourceUrl",
			pattern: new RegExp("@tanstack\\/react-virtual[.\\-@/]"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "tanstack-virtual:resourceUrl:modern:2",
			kind: "resourceUrl",
			pattern: new RegExp("@tanstack\\/vue-virtual[.\\-@/]"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "tanstack-virtual:resourceUrl:modern:3",
			kind: "resourceUrl",
			pattern: new RegExp("@tanstack\\/solid-virtual[.\\-@/]"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "tanstack-virtual:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("exports\\.Virtualizer\\b"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "tanstack-virtual:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("exports\\.useVirtualizer\\b"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "tanstack-virtual:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("exports\\.useWindowVirtualizer\\b"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "tanstack-virtual:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("exports\\.observeElementRect\\b"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "tanstack-virtual:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("exports\\.observeElementOffset\\b"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "tanstack-virtual:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("exports\\.elementScroll\\b"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "tanstack-virtual:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("exports\\.windowScroll\\b"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "tanstack-virtual:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("exports\\.measureElement\\b"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "tanstack-virtual:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("exports\\.defaultRangeExtractor\\b"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "tanstack-virtual:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("\"getVirtualItems\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "tanstack-virtual:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("\"getMeasurements\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "tanstack-virtual:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("\"calculateRange\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "tanstack-virtual:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("\"maybeNotify\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "tanstack-virtual:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("\"getIndexes\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
