import type { TechnologyDefinition } from '../../types';

export const tanstackTableTechnologyDefinition = {
	id: "tanstack-table",
	name: "TanStack Table",
	website: "https://tanstack.com/table",
	description: "Headless UI for building powerful tables & datagrids",
	categories: [
		"table-library",
	],
	rules: [
		{
			id: "tanstack-table:resourceUrl:modern:0",
			kind: "resourceUrl",
			pattern: new RegExp("@tanstack\\/table-core[.\\-@/]"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "tanstack-table:resourceUrl:modern:1",
			kind: "resourceUrl",
			pattern: new RegExp("@tanstack\\/react-table[.\\-@/]"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "tanstack-table:resourceUrl:modern:2",
			kind: "resourceUrl",
			pattern: new RegExp("@tanstack\\/vue-table[.\\-@/]"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "tanstack-table:resourceUrl:modern:3",
			kind: "resourceUrl",
			pattern: new RegExp("@tanstack\\/solid-table[.\\-@/]"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "tanstack-table:resourceUrl:modern:4",
			kind: "resourceUrl",
			pattern: new RegExp("@tanstack\\/svelte-table[.\\-@/]"),
			confidence: 75,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "tanstack-table:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("\"getCoreRowModel\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "tanstack-table:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("\"getSortedRowModel\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "tanstack-table:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("\"getFilteredRowModel\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "tanstack-table:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("\"getPaginationRowModel\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "tanstack-table:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("\"getExpandedRowModel\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "tanstack-table:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("\"getGroupedRowModel\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "tanstack-table:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("\"columnSizingInfo\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "tanstack-table:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("\"columnPinning\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "tanstack-table:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("\"debugTable\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "tanstack-table:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("\"debugHeaders\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "tanstack-table:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("\"debugColumns\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "tanstack-table:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("\\bflexRender\\b"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "tanstack-table:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("\\buseReactTable\\b"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
