import type { TechnologyDefinition } from '../../types';

export const ebayPartnerNetworkTechnologyDefinition = {
	id: "ebay-partner-network",
	name: "eBay Partner Network",
	website: "https://partnernetwork.ebay.com",
	description: "eBay Partner Network is an online referral program where eBay pays commissions to referrers on sales generated by customers they’ve referred.",
	icon: "eBay.svg",
	categories: [
		"advertising-paid-media",
		"marketing-automation",
	],
	rules: [
		{
			id: "ebay-partner-network:scriptSrc:0",
			kind: "scriptSrc",
			pattern: new RegExp("epnt\\.ebay\\.com\\/"),
			description: "Script source URL matches a known technology marker.",
		},
	],
} as const satisfies TechnologyDefinition;
