import type { TechnologyDefinition } from '../../types';

export const axiosTechnologyDefinition = {
	id: "axios",
	name: "Axios",
	website: "https://github.com/axios/axios",
	description: "Promise based HTTP client for the browser and node.js.",
	icon: "Axios.svg",
	categories: [
		"http-client",
		"widgets-misc",
	],
	rules: [
		{
			id: "axios:scriptSrc:0",
			kind: "scriptSrc",
			pattern: new RegExp("\\/axios(@|\\/)([\\d.]+)(?:\\/[a-z]+)?\\/axios(?:.min)?\\.js"),
			version: {
				source: "match",
				group: 2,
			},
			description: "Script source URL matches a known technology marker.",
		},
		{
			id: "axios:jsGlobal:1",
			kind: "jsGlobal",
			property: "axios.get",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "axios:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("\"transitional option built-in validator\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "axios:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("\"Don't know how to serialize '[^']+'\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "axios:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("\"maxBodyLength size of -1 is not supported\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "axios:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("\\.isAxiosError\\("),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "axios:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("instanceof\\s+AxiosError"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "axios:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("CancelToken\\.source\\(\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "axios:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("\\.CancelToken\\s*\\.\\s*source\\s*\\(\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "axios:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("\\.interceptors\\.(request|response)\\.(use|eject)\\([^)]*\\)"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "axios:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("\\.interceptors\\.(request|response)\\.handlers"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "axios:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("AxiosRequestConfig(?![a-zA-Z])"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "axios:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("AxiosResponse(?![a-zA-Z])"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "axios:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("AxiosInstance(?![a-zA-Z])"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "axios:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("AxiosError(?![a-zA-Z])"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "axios:header:modern:13",
			kind: "header",
			key: "x-requested-with",
			valuePattern: new RegExp("XMLHttpRequest", "i"),
			confidence: 55,
			description: "HTTP response header matches a modern tooling marker.",
		},
	],
	metadata: {
		cpe: "cpe:2.3:a:axios:axios:*:*:*:*:*:node.js:*:*",
	},
} as const satisfies TechnologyDefinition;
