import type { TechnologyDefinition } from '../../types';

export const kyTechnologyDefinition = {
	id: "ky",
	name: "ky",
	website: "https://github.com/sindresorhus/ky?tab=readme-ov-file",
	description: "Tiny and elegant HTTP client based on the Fetch API",
	categories: [
		"http-client",
	],
	rules: [
		{
			id: "ky:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("\"Failed to parse URL from "),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ky:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("\"The `prefixUrl` option must start with"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ky:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("new\\s+\\w+\\.Request\\([\"']https:\\/\\/empty\\.invalid[\"']"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ky:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("\"Response code [0-9]+ \\([^)]+\\)\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ky:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("\"Failed to execute request hook\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ky:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("throw\\s+new\\s+Error\\([\"']retry\\.methods\\s+must\\s+be\\s+an\\s+array[\"']\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ky:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("throw\\s+new\\s+Error\\([\"']retry\\.statusCodes\\s+must\\s+be\\s+an\\s+array[\"']\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ky:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("throw\\s+new\\s+Error\\s*\\(\\s*[\"']Streams are not supported in your environment\\.\\s+`ReadableStream`\\s+is\\s+missing\\.[\"']\\s*\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ky:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("throw\\s+new\\s+Error\\s*\\(\\s*[\"']`input`\\s+must\\s+not\\s+begin\\s+with\\s+a\\s+slash\\s+when\\s+using\\s+`prefixUrl`[\"']\\s*\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ky:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("throw\\s+new\\s+TypeError\\s*\\(\\s*[\"']The\\s+`onDownloadProgress`\\s+option\\s+must\\s+be\\s+a\\s+function[\"']\\s*\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ky:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("\"The `onDownloadProgress` option must be a function\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ky:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("\\b\\w+\\._options\\.retry\\.backoffLimit\\b"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ky:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("\\w+\\._options\\.throwHttpErrors"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ky:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("\\{(?:[^}]*retry:[^}]+prefixUrl:[^}]+throwHttpErrors:[^}]*|[^}]*prefixUrl:[^}]+throwHttpErrors:[^}]+retry:[^}]*)\\}"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ky:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("retry:\\s*\\{\\s*limit:\\s*\\d+,\\s*statusCodes:\\s*\\[\\d+(?:,\\s*\\d+)*\\],\\s*methods:\\s*\\[[\"'](?:GET|POST|PUT|DELETE)[\"']"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ky:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("\\{\\s*status,\\s*statusText,\\s*response\\s*\\}\\s*=\\s*error"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
