import type { TechnologyDefinition } from '../../types';

export const relayGraphqlTechnologyDefinition = {
	id: "relay-graphql",
	name: "Relay GraphQL",
	website: "https://relay.dev/",
	description: "A JavaScript framework for building data-driven React applications",
	categories: [
		"http-client",
	],
	rules: [
		{
			id: "relay-graphql:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("\"RelayRequiredFields\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "relay-graphql:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("\"RelayLiveResolvers\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "relay-graphql:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("\"RelayDefaultMask\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "relay-graphql:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("\"RelayConnectionHandler\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "relay-graphql:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("\"getRootField: Expected id"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "relay-graphql:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("\"getLinkedRecords: Expected array of records\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "relay-graphql:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("\"Expected id for record .* missing field"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "relay-graphql:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("\"Expected record .* to have a .* selection"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "relay-graphql:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("\"Relay: Expected .* to be registered before cleaning up\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "relay-graphql:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("\"RelayModernStore: Mutation\",\\s*\"RetainQuery\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "relay-graphql:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("\"RelayModernStore: Operation\",\\s*\"CommitPayload\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "relay-graphql:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("\"__id\",\\s*\"__typename\",\\s*\"__isNode\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "relay-graphql:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("\"RelayReader: Expected .* to be a scalar\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "relay-graphql:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("\"connection:.*\\$.*\\$.*connections\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "relay-graphql:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("\"__connection_next_edge_index\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "relay-graphql:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("\"Connection handler .* cannot handle undefined\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "relay-graphql:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("\"RelayConcreteNode\\.(?:LinkedField|ScalarField|Fragment)\""),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "relay-graphql:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("\"RelayModernEnvironment: Operation\",\\s*\".*\"\\s*already exists\""),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "relay-graphql:scriptContent:modern:18",
			kind: "scriptContent",
			pattern: new RegExp("\"RelayValidator: Fragment spread .* unused\""),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
