import type { TechnologyDefinition } from '../../types';

export const serverActionsTechnologyDefinition = {
	id: "server-actions",
	name: "Server Actions",
	website: "https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations",
	description: "Asynchronous functions that are executed on the server. They can be called in Server and Client Components to handle form submissions and data mutations in Next.js applications.",
	categories: [
		"http-client",
	],
	rules: [
		{
			id: "server-actions:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("headers:\\s*\\{[^}]*(?:\"Accept\":\\s*[^,}]*RSC_CONTENT_TYPE_HEADER|\\[ACTION\\]:|\\[NEXT_ROUTER_STATE_TREE\\]:)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "server-actions:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("\"x-action-redirect\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "server-actions:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("\"x-action-revalidated\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "server-actions:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("JSON\\.parse\\([^)]*\\.get\\(\"x-action-revalidated\"\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "server-actions:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("\"__next_form_action__\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "server-actions:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("\"Server Actions must be bound to a server component\""),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "server-actions:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("\"Cannot pass a Server Action to a Client Component\""),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "server-actions:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("\"Server Action failed with\""),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "server-actions:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("\"Server Action application state update failed\""),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "server-actions:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("\\{paths:\\s*(?:\\[\\]|e\\[0\\]),\\s*tag:\\s*!!e\\[1\\],\\s*cookie:\\s*(?:e\\[2\\]|false)\\}"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "server-actions:header:modern:10",
			kind: "header",
			key: "x-action-redirect",
			valuePattern: new RegExp(".*"),
			confidence: 65,
			description: "HTTP response header matches a modern tooling marker.",
		},
		{
			id: "server-actions:header:modern:11",
			kind: "header",
			key: "x-action-revalidated",
			valuePattern: new RegExp("\\[\\[.*\\],\\d+,\\d+\\]"),
			confidence: 65,
			description: "HTTP response header matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
