import type { TechnologyDefinition } from '../../types';

export const superagentTechnologyDefinition = {
	id: "superagent",
	name: "Superagent",
	website: "https://ladjs.github.io/superagent",
	description: "Ajax with less suck - (and node.js HTTP client to match)",
	categories: [
		"http-client",
	],
	rules: [
		{
			id: "superagent:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("\"no appendQueryString\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "superagent:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("\"no Request#pipe\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "superagent:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("Warning: superagent request was sent twice, because both \\.end\\(\\) and \\.then\\(\\) were called\\. Never call \\.end\\(\\) if you use promises"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "superagent:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("Using browser-only version of superagent in non-browser environment"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "superagent:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("superagent can't mix \\.send\\(\\) and \\.attach\\(\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "superagent:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("This is not supported in browser version of superagent"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "superagent:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("Warning: \\.end\\(\\) was called twice\\. This is not supported in superagent"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "superagent:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("Request has been terminated\\nPossible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc\\."),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "superagent:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("\"superagent first\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "superagent:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("\"no superagent serializer\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "superagent:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("\"multiple content-types\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "superagent:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("\"please use Buffer\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "superagent:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("\"should be a blob\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "superagent:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("\"unexpected form field\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "superagent:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("\"retries exceeded\""),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "superagent:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("\"retry: gave up\""),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "superagent:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("\"retry: too many redirects\""),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "superagent:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("\"retry count exceeds\""),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "superagent:header:modern:18",
			kind: "header",
			key: "x-superagent-retry-count",
			valuePattern: new RegExp("^\\d+$"),
			confidence: 55,
			description: "HTTP response header matches a modern tooling marker.",
		},
		{
			id: "superagent:scriptContent:modern:19",
			kind: "scriptContent",
			pattern: new RegExp("\\.(?:accept|query|field|attach|set)\\([^)]*\\)\\.(?:accept|query|field|attach|set)\\([^)]*\\)\\.retry\\("),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "superagent:scriptContent:modern:20",
			kind: "scriptContent",
			pattern: new RegExp("\\.accept\\(['\"]application\\/json['\"]\\)\\.type\\(['\"]application\\/json['\"]\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "superagent:scriptContent:modern:21",
			kind: "scriptContent",
			pattern: new RegExp("\\.field\\([^)]+\\)\\.attach\\([^)]+\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "superagent:scriptContent:modern:22",
			kind: "scriptContent",
			pattern: new RegExp("\\.attach\\(['\"]file['\"],[^,]+,\\{filename:"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "superagent:scriptContent:modern:23",
			kind: "scriptContent",
			pattern: new RegExp("\\.attach\\(['\"]file['\"],[^,]+,\\{contentType:"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "superagent:scriptContent:modern:24",
			kind: "scriptContent",
			pattern: new RegExp("\\.field\\(['\"]name['\"],[^)]+\\)\\.field\\(['\"]key['\"],[^)]+\\)\\.attach\\("),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
