import type { TechnologyDefinition } from '../../types';

export const mobxTechnologyDefinition = {
	id: "mobx",
	name: "MobX",
	website: "https://mobx.js.org",
	description: "Simple, scalable state management.",
	icon: "MobX.svg",
	categories: [
		"state-management",
		"widgets-misc",
	],
	rules: [
		{
			id: "mobx:scriptSrc:0",
			kind: "scriptSrc",
			pattern: new RegExp("(?:\\/([\\d\\.]+))?\\/mobx(?:\\.[a-z]+){0,2}\\.js(?:$|\\?)"),
			version: {
				source: "match",
				group: 1,
			},
			description: "Script source URL matches a known technology marker.",
		},
		{
			id: "mobx:jsGlobal:1",
			kind: "jsGlobal",
			property: "__mobxGlobal",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "mobx:jsGlobal:2",
			kind: "jsGlobal",
			property: "__mobxGlobals",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "mobx:jsGlobal:3",
			kind: "jsGlobal",
			property: "__mobxInstanceCount",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "mobx:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("Symbol\\.for\\([\"']mobx-stored-annotations[\"']\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mobx:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("\"Since strict-mode is enabled, changing observed observable values outside actions is not allowed\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mobx:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("\"[ComputedValue] It is not allowed to create or access other observables or computeds while computing a computed value\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mobx:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("Symbol\\([\"']mobx administration[\"']\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mobx:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("mobx stored-annotations"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mobx:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("\\.__mobxInstanceCount"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mobx:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("\\.__mobxGlobals"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mobx:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("mobxGuid"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mobx:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("\\[MobX\\] minified error nr:"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mobx:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("https:\\/\\/github\\.com\\/mobxjs\\/mobx\\/blob\\/main\\/packages\\/mobx\\/src\\/errors\\.ts"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mobx:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("\\.isMobxAction\\s*=\\s*true"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mobx:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("\\.isMobXFlow\\s*=\\s*true"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mobx:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("\\{allowStateChanges:\\s*false,\\s*allowStateReads:\\s*true\\}"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mobx:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("enforceActions:\\s*true"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mobx:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("\\[\"?__mobxDecorators\"?\\]"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mobx:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("\\[\"?__mobxInstanceAdmin\"?\\]"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mobx:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("\\[\"?__mobxDidRunLazyInitializers\"?\\]"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mobx:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("\"Since strict-mode is enabled, changing (observed )?observable values outside actions is not allowed\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "mobx:scriptContent:modern:18",
			kind: "scriptContent",
			pattern: new RegExp("\"[mobx] Since strict-mode is enabled, changing observed observable values outside actions is not allowed\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
