import type { TechnologyDefinition } from '../../types';

export const ngrxTechnologyDefinition = {
	id: "ngrx",
	name: "NgRx",
	website: "https://ngrx.io/",
	description: "A set of reactive libraries for Angular.",
	categories: [
		"state-management",
	],
	rules: [
		{
			id: "ngrx:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("@ngrx\\/store\\/init"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ngrx:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("new\\s+[a-zA-Z.]*nKC\\(\\s*[\"']@ngrx\\/[^\"']+[\"']\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ngrx:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("\"@ngrx\\/store\\s+Internal[^\"]+\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ngrx:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("https:\\/\\/ngrx\\.io\\/guide\\/store\\/configuration\\/runtime-checks"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ngrx:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("\"@ngrx\\/store Internal Root Guard\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ngrx:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("\"@ngrx\\/store Internal Initial State\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ngrx:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("\"@ngrx\\/store Initial State\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ngrx:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("\"@ngrx\\/store\\/update-reducers\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ngrx:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("\\[\"\\$\\$isNgrxMockEnvironment\"\\]"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ngrx:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("\\[\"\\$ngrxMockState\"\\]"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ngrx:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("\"The root Store has been provided more than once. Feature modules should provide feature states instead.\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ngrx:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("\"@ngrx\\/store Store Features\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ngrx:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("\"@ngrx\\/store Internal Store Features\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ngrx:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("\"@ngrx\\/store Feature Reducers\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ngrx:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("\"@ngrx\\/store\\/metaReducers\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ngrx:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("\"@ngrx\\/store\\/reducers\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ngrx:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("[\"']\\@ngrx\\/store[\"']"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ngrx:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("[\"']\\@ngrx\\/effects[\"']"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ngrx:scriptContent:modern:18",
			kind: "scriptContent",
			pattern: new RegExp("[\"']\\@ngrx\\/entity[\"']"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "ngrx:scriptContent:modern:19",
			kind: "scriptContent",
			pattern: new RegExp("[\"']\\@ngrx\\/store-devtools[\"']"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
