import type { TechnologyDefinition } from '../../types';

export const piniaTechnologyDefinition = {
	id: "pinia",
	name: "Pinia",
	website: "https://pinia.vuejs.org",
	description: "Pinia is a state management library for Vue.js.",
	icon: "Pinia.svg",
	categories: [
		"state-management",
		"widgets-misc",
	],
	rules: [
		{
			id: "pinia:scriptSrc:0",
			kind: "scriptSrc",
			pattern: new RegExp("\\/pinia\\/.+\\.js"),
			description: "Script source URL matches a known technology marker.",
		},
		{
			id: "pinia:html:1",
			kind: "html",
			pattern: new RegExp("\\bpinia\\b", "i"),
			confidence: 80,
			description: "Document HTML contains a Pinia package/runtime marker.",
		},
		{
			id: "pinia:text:2",
			kind: "text",
			pattern: new RegExp("\"pinia\""),
			description: "Page text contains a known technology marker.",
		},
		{
			id: "pinia:jsGlobal:3",
			kind: "jsGlobal",
			property: "Pinia.createPinia",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "pinia:jsGlobal:4",
			kind: "jsGlobal",
			property: "__NUXT__.pinia",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "pinia:jsGlobal:5",
			kind: "jsGlobal",
			property: "mount_pinia",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "pinia:jsGlobal:6",
			kind: "jsGlobal",
			property: "pinia.state",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "pinia:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("Symbol\\([\"']pinia[\"']\\)"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "pinia:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("\"🍍 Pinia \\(root\\)\""),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "pinia:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("\"🍍 \""),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "pinia:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("const\\s+\\w+\\s*=\\s*Symbol\\(\\s*(?:'pinia'|\"pinia\")\\s*\\)"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "pinia:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("\\w+\\.config\\.globalProperties\\.\\$pinia\\s*=\\s*\\w+"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "pinia:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("\\/\\*!\\s*\\n\\s*\\*\\s*pinia\\s+v\\d+\\.\\d+\\.\\d+"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "pinia:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("\"\\[Pinia\\]: skipping hmr because store doesn't exist yet\""),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "pinia:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("\"pinia:mutations\""),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "pinia:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("MutationType\\.direct"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "pinia:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("MutationType\\.patchFunction"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "pinia:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("MutationType\\.patchObject"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "pinia:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("\"https:\\/\\/pinia\\.vuejs\\.org\\/logo\\.svg\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "pinia:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("\"__PINIA__\""),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "pinia:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("\"__PINIA_DEVTOOLS_GLOBAL_HOOK__\""),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
	metadata: {
		oss: true,
	},
	requires: [
		"vue-js",
	],
} as const satisfies TechnologyDefinition;
