import type { TechnologyDefinition } from '../../types';

export const reduxTechnologyDefinition = {
	id: "redux",
	name: "Redux",
	website: "https://redux.js.org",
	description: "Redux is a predictable state container for JavaScript applications.",
	icon: "Redux.svg",
	categories: [
		"state-management",
		"ui-library",
	],
	rules: [
		{
			id: "redux:scriptSrc:0",
			kind: "scriptSrc",
			pattern: new RegExp("\\/redux(@|\\/)([\\d.]+)(?:\\/[a-z]+)?\\/redux(?:.min)?\\.js"),
			version: {
				source: "match",
				group: 2,
			},
			description: "Script source URL matches a known technology marker.",
		},
		{
			id: "redux:dom:1",
			kind: "dom",
			selector: "link[href*='//redux.js.org']",
			description: "DOM selector matches a known technology marker.",
		},
		{
			id: "redux:jsGlobal:2",
			kind: "jsGlobal",
			property: "ReactRedux",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "redux:jsGlobal:3",
			kind: "jsGlobal",
			property: "Redux.applyMiddleware",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "redux:jsGlobal:4",
			kind: "jsGlobal",
			property: "__REDUX_DEVTOOLS_EXTENSION__",
			description: "Page-owned global matches a known technology marker.",
		},
		{
			id: "redux:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("\"@@redux\\/INIT[^\"]+\""),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "redux:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("\"@@redux\\/REPLACE[^\"]+\""),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "redux:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("\"@@redux\\/PROBE_UNKNOWN_ACTION[^\"]+\""),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "redux:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("redux-toolkit\\.js\\.org\\/Errors\\?code="),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "redux:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("Symbol\\.for\\([\"']rtk-state-proxy-original[\"']\\)"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "redux:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("Symbol\\.for\\([\"']react-redux-context[\"']\\)"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "redux:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("throw Error\\(['\"]You may not call store\\.getState\\(\\) while the reducer is executing\\. The reducer has already received the state as an argument\\. Pass it down from the top reducer instead of reading it from the store\\.['\"][\\)];"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "redux:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("See https:\\/\\/redux\\.js\\.org\\/api\\/store#subscribelistener"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "redux:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("throw Error\\(['\"]It looks like you are passing several store enhancers to createStore\\(\\)\\. This is not supported\\. Instead, compose them together to a single function\\. See https:\\/\\/redux\\.js\\.org\\/tutorials\\/fundamentals\\/part-4-store#creating-a-store-with-enhancers for an example\\.['\"][\\)];"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "redux:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("throw Error\\(['\"]Actions may not have an undefined \"type\" property\\. You may have misspelled an action type string constant\\.['\"][\\)];"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "redux:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("throw Error\\(['\"]Reducers may not dispatch actions\\.['\"][\\)];"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "redux:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("visit https:\\/\\/redux\\.js\\.org\\/Errors\\?code="),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "redux:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("You may need to add middleware to your store setup to handle dispatching other values, such as ['\"]redux-thunk['\"] to handle dispatching functions"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "redux:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("function\\s+createStore\\s*\\([^)]*\\)\\s*\\{\\s*(?:var|let|const)\\s+currentReducer\\s*=\\s*reducer(?:\\s*;)?\\s*(?:var|let|const)\\s+currentState\\s*=\\s*preloadedState"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "redux:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("function\\s+isPlainObject\\s*\\(obj\\)\\s*\\{\\s*if\\s*\\(typeof\\s+obj\\s*!==\\s*['\"]object['\"]\\s*\\|\\|\\s*obj\\s*===\\s*null\\)\\s*return\\s*false"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "redux:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("if\\s*\\(typeof\\s+enhancer\\s*!==\\s*['\"]undefined['\"]\\)\\s*\\{\\s*if\\s*\\(typeof\\s+enhancer\\s*!==\\s*['\"]function['\"]\\)\\s*\\{\\s*throw"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "redux:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("\"Actions must be plain objects\\. Instead, the actual type was: '[^']+'\\. You may need to add middleware\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "redux:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("'Actions may not have an undefined \"type\" property'"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "redux:scriptContent:modern:18",
			kind: "scriptContent",
			pattern: new RegExp("\"Action \\\\\"type\\\\\" property must be a string\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "redux:scriptContent:modern:19",
			kind: "scriptContent",
			pattern: new RegExp("\"You may not call store\\.subscribe\\(\\) while the reducer is executing\""),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "redux:scriptContent:modern:20",
			kind: "scriptContent",
			pattern: new RegExp("\"Reducers may not dispatch actions\""),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "redux:scriptContent:modern:21",
			kind: "scriptContent",
			pattern: new RegExp("\"The slice reducer for key [^\"]+ returned undefined during initialization\""),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "redux:scriptContent:modern:22",
			kind: "scriptContent",
			pattern: new RegExp("\"Invalid value of type .* for mapDispatchToProps argument when connecting component"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "redux:scriptContent:modern:23",
			kind: "scriptContent",
			pattern: new RegExp("Connect\\([^)]+\\).*reactReduxForwardedRef"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "redux:scriptContent:modern:24",
			kind: "scriptContent",
			pattern: new RegExp("\\[\"__reactRedux\"\\]"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "redux:scriptContent:modern:25",
			kind: "scriptContent",
			pattern: new RegExp("notifyNestedSubs"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "redux:scriptContent:modern:26",
			kind: "scriptContent",
			pattern: new RegExp("\\{reactReduxForwardedRef:.*getServerState:.*\\}"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
	metadata: {
		oss: true,
	},
} as const satisfies TechnologyDefinition;
