import type { TechnologyDefinition } from '../../types';

export const valtioTechnologyDefinition = {
	id: "valtio",
	name: "valtio",
	website: "https://valtio.dev/",
	description: "Reactive global state for React.",
	categories: [
		"state-management",
	],
	rules: [
		{
			id: "valtio:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("unstable_getDeriveSubscriptions"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "valtio:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("proxyCompare\\.markToTrack"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "valtio:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("'Please use proxy object'"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "valtio:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("\\[\\$valtioRef\\]"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "valtio:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("\\[valtio_listeners\\]"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "valtio:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("\\[valtio_source\\]"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "valtio:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("markToTrack\\(snapshot,\\s*true\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "valtio:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("snapshot\\[PROMISE_SYMBOL\\]"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "valtio:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("addPromiseListener"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "valtio:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("import\\s+.*from\\s+[\"']valtio\\/vanilla[\"']"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "valtio:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("import\\s+.*from\\s+[\"']valtio\\/utils[\"']"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "valtio:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("require\\([\"']valtio\\/vanilla[\"']\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "valtio:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("require\\([\"']valtio\\/utils[\"']\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "valtio:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("import\\([\"']valtio\\/vanilla[\"']\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "valtio:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("import\\([\"']valtio\\/utils[\"']\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "valtio:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("\"__valtio_devtools_value__\""),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "valtio:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("\"__valtio_devtools_undefined__\""),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "valtio:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("\"__valtio_devtools_pending__\""),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
