import type { TechnologyDefinition } from '../../types';

export const xstateTechnologyDefinition = {
	id: "xstate",
	name: "XState",
	website: "https://xstate.js.org/",
	description: "XState is a state management and orchestration solution for JavaScript and TypeScript apps.",
	categories: [
		"state-management",
	],
	rules: [
		{
			id: "xstate:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("\"@xstate\\.snapshot\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "xstate:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("\"@xstate\\.event\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "xstate:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("\"@xstate\\.microstep\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "xstate:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("\"xstate\\.init\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "xstate:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("\"xstate\\.stop\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "xstate:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("\"xstate\\.spawnChild\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "xstate:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("xstate\\$\\$type:\\s*1"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "xstate:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("xstate\\.done\\.actor\\.\\${[^}]+}"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "xstate:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("xstate\\.done\\.state\\.\\${[^}]+}"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "xstate:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("xstate\\.error\\.actor"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "xstate:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("xstate\\.invoke\\.\\${[^}]+}"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "xstate:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("\"xstate\\.observable\\.next\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "xstate:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("\"xstate\\.observable\\.error\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "xstate:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("\"xstate\\.observable\\.complete\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "xstate:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("\"xstate\\.promise\\.resolve\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "xstate:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("\"xstate\\.promise\\.reject\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "xstate:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("\"xstate\\.enqueueActions\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "xstate:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("\\.type=\"xstate\\.log\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
