import type { TechnologyDefinition } from '../../types';

export const zustandTechnologyDefinition = {
	id: "zustand",
	name: "Zustand",
	website: "https://zustand-demo.pmnd.rs",
	description: "A small, fast and scalable bearbones state-management solution using simplified flux principles.",
	categories: [
		"state-management",
	],
	rules: [
		{
			id: "zustand:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("zustandVanilla"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "zustand:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("zustandShallow"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "zustand:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("zustandContext"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "zustand:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("\\{\\s*getInitialState\\s*:[^,}]*,\\s*getState\\s*:[^,}]*,\\s*setState\\s*:[^,}]*,\\s*subscribe\\s*:[^,}]*\\s*\\}", "m"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "zustand:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("\\[zustand devtools middleware\\] Unsupported action format"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "zustand:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("\\[DEPRECATED\\] Passing a vanilla store will be unsupported in a future version\\. Instead use import \\{ useStore \\} from 'zustand'\\."),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "zustand:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("\\[zustand devtools middleware\\] Unsupported __setState action format"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "zustand:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("When using 'store' option in devtools\\(\\), the 'state' should have only one key"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "zustand:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("\\[DEPRECATED\\].*['\"]zustand\\/traditional['\"]"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "zustand:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("github\\.com\\/pmndrs\\/zustand\\/discussions\\/1937"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "zustand:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("\"Seems like you have not used zustand provider as an ancestor\\.\""),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "zustand:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("createWithEqualityFn.*instead of.*create.*useStoreWithEqualityFn.*instead of.*useStore"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "zustand:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("import\\s+.*from\\s+[\"']zustand\\/vanilla[\"']"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "zustand:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("import\\s+.*from\\s+[\"']zustand\\/react[\"']"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "zustand:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("import\\s+.*from\\s+[\"']zustand\\/shallow[\"']"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "zustand:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("require\\([\"']zustand\\/vanilla[\"']\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "zustand:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("require\\([\"']zustand\\/react[\"']\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "zustand:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("require\\([\"']zustand\\/shallow[\"']\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "zustand:scriptContent:modern:18",
			kind: "scriptContent",
			pattern: new RegExp("import\\([\"']zustand\\/vanilla[\"']\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "zustand:scriptContent:modern:19",
			kind: "scriptContent",
			pattern: new RegExp("import\\([\"']zustand\\/react[\"']\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "zustand:scriptContent:modern:20",
			kind: "scriptContent",
			pattern: new RegExp("import\\([\"']zustand\\/shallow[\"']\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "zustand:scriptContent:modern:21",
			kind: "scriptContent",
			pattern: new RegExp("define\\(\\[[\"']zustand\\/vanilla[\"']\\]|define\\(\\[[\"']zustand\\/react[\"']\\]|define\\(\\[[\"']zustand\\/shallow[\"']\\]"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
