import type { TechnologyDefinition } from '../../types';

export const angularRouterTechnologyDefinition = {
	id: "angular-router",
	name: "Angular Router",
	website: "https://angular.io/guide/router",
	description: "Powerful JavaScript router built and maintained by the Angular team that allows developers to build single-page applications with multiple views and share data between views.",
	categories: [
		"router",
	],
	rules: [
		{
			id: "angular-router:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("InjectionToken\\([\"'](?:ROUTER_CONFIG|ROUTER_INITIALIZER|ROUTER_FORROOT_GUARD)[\"']\\)"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular-router:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("\\[Symbol\\.for\\([\"'](?:NgRouter|RouterState|RouteParams)[\"']\\)\\]"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular-router:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("__NG_ROUTER_[A-Z_]+__"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular-router:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("\\w+\\.ɵfac\\s*=\\s*function\\s*\\(t\\)\\s*\\{\\s*return\\s*new\\s*\\(t\\s*\\|\\|\\s*\\w+Router\\)"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular-router:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("\\w+\\.ɵprov\\s*=\\s*\\/\\*@__PURE__\\*\\/\\s*[ɵ\\w]+\\([\"']Router[\"']\\)"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular-router:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("ɵɵdefineInjectable\\(\\{factory:\\s*function\\s*\\w+Router_Factory"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular-router:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("ɵɵdefineNgModule\\(\\{.*?declarations:\\s*\\[RouterOutlet\\]"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular-router:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("routerNgProbeToken"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular-router:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("emptyRouterOutlet"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular-router:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("router-outlet"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular-router:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("registerNonRouterCurrentEntryChangeListener"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular-router:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("\\.generateNgRouterState"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular-router:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("\\.nonRouterCurrentEntryChangeSubscription"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular-router:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("\\b[a-zA-Z_$][\\w$]*\\.\\$broadcast\\(\\s*[\"']\\$routeChangeStart[\"']\\s*,\\s*[a-zA-Z_$][\\w$]*\\s*,\\s*[a-zA-Z_$][\\w$]*\\s*\\)"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular-router:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("\\b[a-zA-Z_$][\\w$]*\\.\\$broadcast\\(\\s*[\"']\\$routeChangeSuccess[\"']\\s*,\\s*[a-zA-Z_$][\\w$]*\\s*,\\s*[a-zA-Z_$][\\w$]*\\s*\\)"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular-router:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("\\b[a-zA-Z_$][\\w$]*\\.\\$broadcast\\(\\s*[\"']\\$routeChangeError[\"']\\s*,\\s*[a-zA-Z_$][\\w$]*\\s*,\\s*[a-zA-Z_$][\\w$]*\\s*,\\s*[a-zA-Z_$][\\w$]*\\s*\\)"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular-router:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("RouterModule\\.(?:forRoot|forChild)\\(\\s*(?:\\[|routes)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular-router:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("provideRouter\\(\\s*withRouterConfig\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular-router:scriptContent:modern:18",
			kind: "scriptContent",
			pattern: new RegExp("withPreloading\\(\\s*(?:NoPreloading|PreloadAllModules)\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular-router:scriptContent:modern:19",
			kind: "scriptContent",
			pattern: new RegExp("withRouterConfig\\(\\{malformedUriErrorHandler:"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular-router:scriptContent:modern:20",
			kind: "scriptContent",
			pattern: new RegExp("NG_ROUTER_PROVIDERS"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular-router:scriptContent:modern:21",
			kind: "scriptContent",
			pattern: new RegExp("ROUTER_CONFIGURATION"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular-router:scriptContent:modern:22",
			kind: "scriptContent",
			pattern: new RegExp("ROUTER_FORROOT_GUARD"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular-router:scriptContent:modern:23",
			kind: "scriptContent",
			pattern: new RegExp("RouterOutlet\\.ngComponentOutlet"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular-router:scriptContent:modern:24",
			kind: "scriptContent",
			pattern: new RegExp("new\\s+NavigationCancelingError\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "angular-router:scriptContent:modern:25",
			kind: "scriptContent",
			pattern: new RegExp("EmptyOutletComponent"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
