import type { TechnologyDefinition } from '../../types';

export const nextJsRouterTechnologyDefinition = {
	id: "next-js-router",
	name: "Next.js Router",
	website: "https://nextjs.org/docs/routing/introduction",
	description: "Next.js has a file-system based router built on the concept of pages.",
	categories: [
		"router",
	],
	rules: [
		{
			id: "next-js-router:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("\\.isNextRouterError\\)\\("),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "next-js-router:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("\\[[\\w.]*NEXT_ROUTER_STATE_TREE_HEADER"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "next-js-router:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("GlobalLayoutRouterContext"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "next-js-router:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("extractPathFromFlightRouterState"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "next-js-router:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("useDynamicRouteParams\\)\\([\"']useParams\\(\\)[\"']"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "next-js-router:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("Object\\.defineProperty\\(Error\\([\"']invariant global layout router not mounted[\"']\\),\\s*[\"']__NEXT_ERROR_CODE[\"']"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "next-js-router:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("Object\\.defineProperty\\([^,]+,\\s*[\"']createInitialRouterState[\"']"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "next-js-router:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("[\"'](?:next\\/(?:navigation|router|link|dist\\/client\\/router)|n\\/r)[\"']"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "next-js-router:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("__NEXT_(?:DATA|P|C|HAS_REWRITE|ROUTER|HISTORY|OPTIMISTIC)__"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "next-js-router:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("AppRouterContext"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "next-js-router:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("[A-Za-z]\\.__N(?:=|ext)|__N_SSG|__N_SSP"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "next-js-router:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("window\\.__N(?:_STATE|EXT_P|_CROSS)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "next-js-router:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("err\\.digest.*NEXT_NOT_FOUND"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "next-js-router:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("NEXT_REDIRECT.*permanent"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
