import type { TechnologyDefinition } from '../../types';

export const qwikRouterTechnologyDefinition = {
	id: "qwik-router",
	name: "Qwik Router",
	website: "https://qwik.dev/docs/routing/",
	description: "Qwik has a file-system based router built on the concept of pages.",
	categories: [
		"router",
	],
	rules: [
		{
			id: "qwik-router:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("q:container=\"[\\w-]+\""),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik-router:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("q:version=\"[\\w.-]+\""),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik-router:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("q:base=\"[\\w-]+\""),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik-router:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("q:slot=\"[\\w-]+\""),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik-router:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("on:qvisible="),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik-router:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("preventdefault:submit"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik-router:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("q:key=\"[\\w-]+\""),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik-router:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("bindge:click="),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik-router:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("\\[Symbol\\.for\\(\"qk-city\"\\)\\]"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik-router:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("QwikCityMockProvider\\$_"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik-router:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("QwikCityProvider\\$_"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik-router:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("RouterOutlet\\$_"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik-router:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("\\$\\w+\\$_use[A-Z]\\w+__\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik-router:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("_\\$use[A-Z]\\w+\\$_\\([^)]*\\)\\[Q-\\w+\\]"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik-router:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("\\$\\w+\\$_use\\w+\\$_\\[Symbol\\.for\\(\"qHook\"\\)\\]"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik-router:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("qrl\\((?:[\"']\\w+_\\w+[\"'],\\s*)?[\"']\\$\\w+\\$_use\\w+\\$_[\"']\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik-router:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("endQwikCity\\$"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik-router:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("qwikCity\\.json"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik-router:scriptContent:modern:18",
			kind: "scriptContent",
			pattern: new RegExp("qwikSerializer\\$"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik-router:scriptContent:modern:19",
			kind: "scriptContent",
			pattern: new RegExp("qwikBrowser\\$"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik-router:scriptContent:modern:20",
			kind: "scriptContent",
			pattern: new RegExp("new QwikCityPageError\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik-router:scriptContent:modern:21",
			kind: "scriptContent",
			pattern: new RegExp("new QwikError\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik-router:scriptContent:modern:22",
			kind: "scriptContent",
			pattern: new RegExp("getErrorHtml\\$"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik-router:scriptContent:modern:23",
			kind: "scriptContent",
			pattern: new RegExp("qwikLoadPage\\$"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik-router:scriptContent:modern:24",
			kind: "scriptContent",
			pattern: new RegExp("QWIK_VERSION"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik-router:scriptContent:modern:25",
			kind: "scriptContent",
			pattern: new RegExp("QWIK_BUILD"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik-router:scriptContent:modern:26",
			kind: "scriptContent",
			pattern: new RegExp("QWIK_DEVTOOLS"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik-router:scriptContent:modern:27",
			kind: "scriptContent",
			pattern: new RegExp("QWIK_MODULES"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "qwik-router:resourceUrl:modern:28",
			kind: "resourceUrl",
			pattern: new RegExp("qwik-city-plan\\.js$", "i"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "qwik-router:resourceUrl:modern:29",
			kind: "resourceUrl",
			pattern: new RegExp("qwik-city-middleware\\.js$", "i"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "qwik-router:resourceUrl:modern:30",
			kind: "resourceUrl",
			pattern: new RegExp("qwik-city-static\\.js$", "i"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "qwik-router:resourceUrl:modern:31",
			kind: "resourceUrl",
			pattern: new RegExp("qwik-city-not-found\\.js$", "i"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "qwik-router:resourceUrl:modern:32",
			kind: "resourceUrl",
			pattern: new RegExp("entry\\.qwik\\.[a-f0-9]+\\.js$", "i"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "qwik-router:resourceUrl:modern:33",
			kind: "resourceUrl",
			pattern: new RegExp("q-[\\w-]+\\.qwik\\.js$", "i"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "qwik-router:resourceUrl:modern:34",
			kind: "resourceUrl",
			pattern: new RegExp("qwik\\.[\\w-]+\\.js$", "i"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "qwik-router:resourceUrl:modern:35",
			kind: "resourceUrl",
			pattern: new RegExp("qkc\\.[\\w-]+\\.js$", "i"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
