import type { TechnologyDefinition } from '../../types';

export const reactRouterTechnologyDefinition = {
	id: "react-router",
	name: "React Router",
	website: "https://reactrouter.com/",
	description: "Declarative routing for React applications that allows developers to build single-page applications with multiple views and share data between views.",
	categories: [
		"router",
	],
	rules: [
		{
			id: "react-router:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("\"remix-router-transitions\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react-router:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("\"react-router-scroll-positions\""),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react-router:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("@remix-run\\/router error"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react-router:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("createHashRouter.*manually changes the URL"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react-router:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("blocker on a POP navigation"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react-router:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("router only supports one blocker at a time"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react-router:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("💿 Hey developer 👋.*Check out https:\\/\\/remix\\.run\\/guides\\/errors"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react-router:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("(?:from\\s+[\"']|\\b)react-router(?:\\/dom)?[\"']"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react-router:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("\\.hasOwnProperty\\(\"remix-router-transitions\"\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react-router:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("\\[\"react-router-scroll-positions\"\\]"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react-router:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("@remix-run\\/router.*silently in production"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react-router:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("([a-zA-Z0-9_$]+)\\._pendingLocation\\s*&&\\s*\\1\\.setState\\(\\s*\\{\\s*location:\\s*\\1\\._pendingLocation"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react-router:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("([a-zA-Z0-9_$]+)\\.props\\.(?:staticContext|[a-zA-Z0-9_$]+)\\s*\\|\\|\\s*\\(\\1\\.(?:unlisten|[a-zA-Z0-9_$]+)\\s*=\\s*\\1\\.props\\.history\\.listen\\(function\\(([a-zA-Z0-9_$]+)\\)\\s*\\{\\s*([a-zA-Z0-9_$]+)\\._isMounted\\s*&&\\s*\\3\\.setState\\(\\s*\\{\\s*location:\\s*\\2"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react-router:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("match:\\s*([a-zA-Z0-9_$]+)\\.computeRootMatch\\(([a-zA-Z0-9_$]+)\\.state\\.location\\.pathname\\)"),
			confidence: 55,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react-router:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("(?:create|use)[BHM]?\\w*Router\\s*\\(\\s*\\["),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react-router:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("RouterProvider\\s*\\{\\s*router:"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react-router:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("\\[UNSAFE_NavigationContext\\]"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react-router:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("\\[DataRouterContext\\]"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "react-router:scriptContent:modern:18",
			kind: "scriptContent",
			pattern: new RegExp("\\[DataRouterStateContext\\]"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
