import type { TechnologyDefinition } from '../../types';

export const remixRouterTechnologyDefinition = {
	id: "remix-router",
	name: "Remix Router",
	website: "https://remix.run/docs/en/main/guides/accessibility#routing",
	description: "Remix has a file-system based router built on the concept of pages.",
	categories: [
		"router",
	],
	rules: [
		{
			id: "remix-router:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("[\"']@remix-run\\/router[\"']"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix-router:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("[\"']@remix-run\\/router\\/history[\"']"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix-router:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("[\"']@remix-run\\/router\\/data[\"']"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix-router:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("__remixRouter"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix-router:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("__remixManifest"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix-router:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("__remixContext"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix-router:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("__remixRouteModules"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix-router:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("\\[Symbol\\.for\\([\"']remix-router-state[\"']\\)\\]"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix-router:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("createPath\\(\\{pathname:"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix-router:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("getStateKeyForLocation\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix-router:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("createClientSideRemixRouter\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix-router:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("createRemixStub\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix-router:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("createActionData\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix-router:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("createLoaderData\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix-router:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("createRouteData\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix-router:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("createTransitionManager\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix-router:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("createClientRoute\\(\\{id:"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix-router:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("createClientResolver\\(\\{routes:"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix-router:scriptContent:modern:18",
			kind: "scriptContent",
			pattern: new RegExp("UNSAFE_DEFERRED_SYMBOL"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix-router:scriptContent:modern:19",
			kind: "scriptContent",
			pattern: new RegExp("UNSAFE_ERROR_BOUNDARY_SYMBOL"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix-router:scriptContent:modern:20",
			kind: "scriptContent",
			pattern: new RegExp("getLoadingNavigation\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix-router:scriptContent:modern:21",
			kind: "scriptContent",
			pattern: new RegExp("getSubmissionNavigation\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix-router:scriptContent:modern:22",
			kind: "scriptContent",
			pattern: new RegExp("getRedirectNavigation\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix-router:scriptContent:modern:23",
			kind: "scriptContent",
			pattern: new RegExp("createTransitionRedirect\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix-router:scriptContent:modern:24",
			kind: "scriptContent",
			pattern: new RegExp("ErrorResponseImpl\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix-router:scriptContent:modern:25",
			kind: "scriptContent",
			pattern: new RegExp("isRouteErrorResponse\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix-router:scriptContent:modern:26",
			kind: "scriptContent",
			pattern: new RegExp("createClientError\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix-router:scriptContent:modern:27",
			kind: "scriptContent",
			pattern: new RegExp("getInternalRouterError\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix-router:scriptContent:modern:28",
			kind: "scriptContent",
			pattern: new RegExp("createClientSideRoute\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix-router:scriptContent:modern:29",
			kind: "scriptContent",
			pattern: new RegExp("createClientRouteLoader\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix-router:scriptContent:modern:30",
			kind: "scriptContent",
			pattern: new RegExp("createClientLoaderFunction\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix-router:scriptContent:modern:31",
			kind: "scriptContent",
			pattern: new RegExp("createDeferredReadable\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "remix-router:resourceUrl:modern:32",
			kind: "resourceUrl",
			pattern: new RegExp("@remix-run[\\\\/]router[\\\\/]dist[\\\\/]router\\.js$"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "remix-router:resourceUrl:modern:33",
			kind: "resourceUrl",
			pattern: new RegExp("@remix-run[\\\\/]router[\\\\/]dist[\\\\/]data\\.js$"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "remix-router:resourceUrl:modern:34",
			kind: "resourceUrl",
			pattern: new RegExp("@remix-run[\\\\/]router[\\\\/]dist[\\\\/]history\\.js$"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "remix-router:resourceUrl:modern:35",
			kind: "resourceUrl",
			pattern: new RegExp("remix-router-[a-f0-9]+\\.js$", "i"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "remix-router:resourceUrl:modern:36",
			kind: "resourceUrl",
			pattern: new RegExp("remix-client-[a-f0-9]+\\.js$", "i"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "remix-router:resourceUrl:modern:37",
			kind: "resourceUrl",
			pattern: new RegExp("remix-routes-[a-f0-9]+\\.js$", "i"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "remix-router:resourceUrl:modern:38",
			kind: "resourceUrl",
			pattern: new RegExp("remix-route-loader\\.[a-f0-9]+\\.js$", "i"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "remix-router:resourceUrl:modern:39",
			kind: "resourceUrl",
			pattern: new RegExp("remix-action-handler\\.[a-f0-9]+\\.js$", "i"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "remix-router:resourceUrl:modern:40",
			kind: "resourceUrl",
			pattern: new RegExp("remix-transition-manager\\.[a-f0-9]+\\.js$", "i"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
