import type { TechnologyDefinition } from '../../types';

export const solidRouterTechnologyDefinition = {
	id: "solid-router",
	name: "Solid Router",
	website: "https://solidjs.com/docs/latest/concepts/router",
	description: "Solid has a file-system based router built on the concept of pages.",
	categories: [
		"router",
	],
	rules: [
		{
			id: "solid-router:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("[\"']@solidjs\\/router(?:\\/dist\\/|\\/)?[^\"']*[\"']"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid-router:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("\\$?\\w+\\.__propertyCheck"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid-router:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("\\$?\\w+\\.__intercepted"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid-router:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("\\$?\\w+\\.__propertyCache"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid-router:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("\\[Symbol\\.for\\([\"']solid-router-context[\"']\\)\\]"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid-router:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("\\[Symbol\\.for\\([\"']solid-root[\"']\\)\\]"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid-router:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("\\[Symbol\\.for\\([\"']solid-track[\"']\\)\\]"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid-router:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("\\[Symbol\\.for\\([\"']solid-dev[\"']\\)\\]"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid-router:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("\"undefined\"!=typeof window&&window\\.\\$PROXY"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid-router:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("DEV_EXPRESSION"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid-router:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("DEVCOMP"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid-router:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("\\w+\\.__propertyCheck&&\\w+\\.__propertyCheck\\([^)]+\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid-router:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("WeakMap\\.prototype\\.get\\.call\\(\\w+\\.__propertyCache"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid-router:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("\\w+\\.__interceptor\\(\\w+,\\w+\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid-router:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("createResource\\(\\{source:"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid-router:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("createMemo\\(\\{equals:!1\\}"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid-router:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("getOwner\\(\\)\\.owner"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid-router:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("throw new Error\\(\"@solidjs\\/router: "),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid-router:scriptContent:modern:18",
			kind: "scriptContent",
			pattern: new RegExp("SolidRouteError\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid-router:scriptContent:modern:19",
			kind: "scriptContent",
			pattern: new RegExp("handleRouterError\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "solid-router:resourceUrl:modern:20",
			kind: "resourceUrl",
			pattern: new RegExp("@solidjs[\\\\/]router[\\\\/]dist[\\\\/][^/]+\\.(?:cjs|mjs|js)$"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "solid-router:resourceUrl:modern:21",
			kind: "resourceUrl",
			pattern: new RegExp("solid-router\\.[\\w-]+\\.js$", "i"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "solid-router:resourceUrl:modern:22",
			kind: "resourceUrl",
			pattern: new RegExp("router\\.[\\w-]+\\.solidjs\\.js$", "i"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "solid-router:resourceUrl:modern:23",
			kind: "resourceUrl",
			pattern: new RegExp("solid\\.[\\w-]+\\.proxy\\.js$", "i"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "solid-router:resourceUrl:modern:24",
			kind: "resourceUrl",
			pattern: new RegExp("proxy\\.[\\w-]+\\.solid\\.js$", "i"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
		{
			id: "solid-router:resourceUrl:modern:25",
			kind: "resourceUrl",
			pattern: new RegExp("router\\.[\\w-]+\\.solid\\.js$", "i"),
			confidence: 45,
			description: "Resource filename or URL matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
