import type { TechnologyDefinition } from '../../types';

export const svelteRouterTechnologyDefinition = {
	id: "svelte-router",
	name: "Svelte Router",
	website: "https://svelte.dev/docs#svelte_router",
	description: "A declarative Svelte router with a small footprint.",
	categories: [
		"router",
	],
	rules: [
		{
			id: "svelte-router:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("[a-zA-Z0-9_$]+\\s*=\\s*[\"']sveltekit:navigation[\"']"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "svelte-router:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("a\\s+load\\s+function\\s+related\\s+to\\s+route\\s+['\"`]\\$\\{[\\w.]+\\}['\"`]\\s+returned"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "svelte-router:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("history\\.(?:pushState|replaceState).*?conflict with SvelteKit['\"]s router"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "svelte-router:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("__SVELTEKIT_CLIENT_ROUTING__"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "svelte-router:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("throw\\s+new\\s+Error\\([^)]*Page\\s+options\\s+are\\s+ignored\\s+when[^)]*router\\.type\\s+===\\s+['\"]hash['\"][^)]*\\)"),
			confidence: 65,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "svelte-router:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("\\.reject\\(new Error\\(\"navigation cancelled\"\\)\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "svelte-router:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("\\.reject\\(new Error\\(\"navigation aborted\"\\)\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "svelte-router:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("[\"']@sveltejs\\/kit(?:\\/navigation|\\/routing|\\/runtime\\/client)[\"']"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "svelte-router:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("[\"']sveltejs\\/kit(?:\\/package\\.json|\\/client\\.js)[\"']"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "svelte-router:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("\\[Symbol\\.for\\([\"']sveltekit-routing[\"']\\)\\]"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "svelte-router:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("load\\s*\\(\\s*\\{\\s*(?:params|url|route|depends)\\s*\\}"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "svelte-router:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("handle\\s*\\(\\s*\\{\\s*event\\s*,\\s*resolve\\s*\\}\\s*\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "svelte-router:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("handleError\\s*\\(\\s*\\{\\s*error\\s*,\\s*event\\s*\\}\\s*\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "svelte-router:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("setupLoadContext\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "svelte-router:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("goto\\(\\s*(?:url|delta):"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "svelte-router:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("pushState\\(\\s*\\{\\s*[^}]*sveltekit:"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "svelte-router:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("invalidateAll\\(\\s*\\{\\s*soft:\\s*true\\s*\\}\\)"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "svelte-router:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("preloadData\\(\\s*\\{\\s*type:\\s*[\"']link[\"']"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "svelte-router:scriptContent:modern:18",
			kind: "scriptContent",
			pattern: new RegExp("handleMissingId\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "svelte-router:scriptContent:modern:19",
			kind: "scriptContent",
			pattern: new RegExp("handleDataError\\("),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "svelte-router:scriptContent:modern:20",
			kind: "scriptContent",
			pattern: new RegExp("redirect\\((?:\\d{3}|\\w+\\.status)\\s*,\\s*(?:url|location):"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
