import type { TechnologyDefinition } from '../../types';

export const vueRouterTechnologyDefinition = {
	id: "vue-router",
	name: "Vue Router",
	website: "https://router.vuejs.org/",
	description: "The official router for Vue.js. It deeply integrates with Vue.js core.",
	categories: [
		"router",
	],
	rules: [
		{
			id: "vue-router:scriptContent:modern:0",
			kind: "scriptContent",
			pattern: new RegExp("\\{name:[\"']RouterLink[\"']"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-router:scriptContent:modern:1",
			kind: "scriptContent",
			pattern: new RegExp("\\{name:[\"']RouterView[\"']"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-router:scriptContent:modern:2",
			kind: "scriptContent",
			pattern: new RegExp("component\\([\"']RouterLink[\"'],[^)]+\\).*component\\([\"']RouterView[\"']"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-router:scriptContent:modern:3",
			kind: "scriptContent",
			pattern: new RegExp("\\{path:[^}]+component:[^}]+name:"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-router:scriptContent:modern:4",
			kind: "scriptContent",
			pattern: new RegExp("\\{currentRoute:[^}]+resolve:[^}]+beforeEach:"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-router:scriptContent:modern:5",
			kind: "scriptContent",
			pattern: new RegExp("beforeRouteLeave[^}]+beforeRouteEnter"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-router:scriptContent:modern:6",
			kind: "scriptContent",
			pattern: new RegExp("createWebHistory|createWebHashHistory|createMemoryHistory"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-router:scriptContent:modern:7",
			kind: "scriptContent",
			pattern: new RegExp("[\"']vue-router[\"']"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-router:scriptContent:modern:8",
			kind: "scriptContent",
			pattern: new RegExp("[\"']@vue\\/router[\"']"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-router:scriptContent:modern:9",
			kind: "scriptContent",
			pattern: new RegExp("__VUE_ROUTER__"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-router:scriptContent:modern:10",
			kind: "scriptContent",
			pattern: new RegExp("__VUE_ROUTER_BASE__"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-router:scriptContent:modern:11",
			kind: "scriptContent",
			pattern: new RegExp("defineComponent\\(\\{name:[\"']RouterView[\"']"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-router:scriptContent:modern:12",
			kind: "scriptContent",
			pattern: new RegExp("defineComponent\\(\\{name:[\"']RouterLink[\"']"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-router:scriptContent:modern:13",
			kind: "scriptContent",
			pattern: new RegExp("\\{name:[\"']router-link[\"']"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-router:scriptContent:modern:14",
			kind: "scriptContent",
			pattern: new RegExp("\\{name:[\"']router-view[\"']"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-router:scriptContent:modern:15",
			kind: "scriptContent",
			pattern: new RegExp("\\[routerViewLocationKey\\]"),
			confidence: 75,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-router:scriptContent:modern:16",
			kind: "scriptContent",
			pattern: new RegExp("\\{beforeEnter:[^}]+meta:"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-router:scriptContent:modern:17",
			kind: "scriptContent",
			pattern: new RegExp("\\{path:[^}]+component:[^}]+children:"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-router:scriptContent:modern:18",
			kind: "scriptContent",
			pattern: new RegExp("\\{name:[^}]+path:[^}]+component:"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-router:scriptContent:modern:19",
			kind: "scriptContent",
			pattern: new RegExp("globalProperties\\.\\$router"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-router:scriptContent:modern:20",
			kind: "scriptContent",
			pattern: new RegExp("globalProperties\\.\\$route"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
		{
			id: "vue-router:scriptContent:modern:21",
			kind: "scriptContent",
			pattern: new RegExp("matched\\.length[^}]+params[^}]+query[^}]+hash"),
			confidence: 45,
			description: "Bundled script content matches a modern tooling marker.",
		},
	],
} as const satisfies TechnologyDefinition;
